; Joomla! Project
; (C) 2013 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_CONFIG="Adeegyada Maamulaha"
COM_CONFIG_CONFIGURATION="Qaabeynta Adeegyada Maamulaha"
COM_CONFIG_ERROR_CONTROLLER_NOT_FOUND="Controller lama helin!"
COM_CONFIG_FIELD_DEFAULT_ACCESS_LEVEL_DESC="Deji Heerka Helitaanka ee caadiga ah ee waxyaabaha cusub ee la abuuray."
COM_CONFIG_FIELD_DEFAULT_ACCESS_LEVEL_LABEL="Heerka Helitaanka ee Asalka ah"
COM_CONFIG_FIELD_DEFAULT_LIST_LIMIT_LABEL="Xadka Liiska ee Caadiga ah"
COM_CONFIG_FIELD_METADESC_LABEL="Sharaxa Meta ee Goobta"
COM_CONFIG_FIELD_SEF_URL_DESC="Haddii xulashadan la naafo, URL-yada Joomla ma yeelan doonaan wax erayo muhiim ah oo waxay ku eg tahay <code>index.php?option=com_example&task=item.display&id=1</code> taas oo aan si fudud af laga sheegay ahayn ama sisi qordi ah ah. URL-yada Ku habboon Raadinta (SEF) waa kuwo si adag loo fahmi karo, tusaale ahaan <code>index.php/example/display/something</code>. Iyada oo la ilaalinayo magaca goobta, in doorkiisa taariikhiga awgeed, qaabka URL-ka ma saameeyo sida mashiinnada raadinta u qiimeeyaan bogagga goobtaada."
COM_CONFIG_FIELD_SEF_URL_LABEL="URL-yada Ku habboon Raadinta"
COM_CONFIG_FIELD_SITE_NAME_LABEL="Magaca Goobta"
COM_CONFIG_FIELD_SITE_OFFLINE_LABEL="Goobta oo offline ah"
COM_CONFIG_FIELD_SITENAME_PAGETITLES_LABEL="Magaca Goobta ee Ciwaannada Bogga"
COM_CONFIG_FIELD_VALUE_AFTER="Kadib"
COM_CONFIG_FIELD_VALUE_BEFORE="Kahor"
COM_CONFIG_METADATA_SETTINGS="Dejinta Metadata"
COM_CONFIG_MODULES_MODULE_NAME="Magaca Module-ka"
COM_CONFIG_MODULES_MODULE_TYPE="Nooca Module-ka"
COM_CONFIG_MODULES_SAVE_SUCCESS="Module-ka waa la keydiyey."
COM_CONFIG_MODULES_SETTINGS_TITLE="Dejinta Module-ka"
COM_CONFIG_SAVE_SUCCESS="Qaabeyntu waa la keydiyey."
COM_CONFIG_SEO_SETTINGS="Dejinta SEO"
COM_CONFIG_SITE_SETTINGS="Dejinta Goobta"
COM_CONFIG_TEMPLATE_SETTINGS="Dejinta Template"
COM_CONFIG_XML_DESCRIPTION="Maareeyaha Qaabaynta adeegyada hore ee Maamulaha."

