; Joomla! Project
; (C) 2009 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_USERS_ACTIVATION_TOKEN_NOT_FOUND="Lambarka xaqiijinta lama helin. Fiiri haddii koontadaadu durba firfircoon tahay oo isku day inaad gasho."
COM_USERS_CAPTCHA_LABEL="Captcha"
COM_USERS_DATABASE_ERROR="Khalad ka imanaya isticmaalaha xagga xogta: %s"
COM_USERS_EDIT_PROFILE="Tafatir Profile"
COM_USERS_EMAIL_ACCOUNT_DETAILS="Faahfaahinta Koontada ee {NAME} ee {SITENAME}"
COM_USERS_EMAIL_ACTIVATED_BY_ADMIN_ACTIVATION_BODY="Salaan {NAME},\n\nKoontadaada waxaa firfircooniyey maamulaha. Hadda waad soo geli kartaa {SITEURL} adigoo isticmaalaya magaca isticmaalaha {USERNAME} iyo erayga sirta ah ee aad dooratay markaad isdiiwaangelinaysay."
COM_USERS_EMAIL_ACTIVATED_BY_ADMIN_ACTIVATION_SUBJECT="Koontada la hawl geliyey ee {NAME} at {SITENAME}"
COM_USERS_EMAIL_ACTIVATE_WITH_ADMIN_ACTIVATION_BODY="Salaan maamulow,\n\nIsticmaale cusub ayaa isdiiwaangeliyey {SITENAME}.\nIsticmaaluhu wuxuu xaqiijiyey cinwaankiisa emailka waxana uu codsaday in aad ansixiso akoonkiisa.\nEmailkan wuxuu leeyahay faahfaahintooda:\n\n  Magaca :  {NAME} \n  email:  {EMAIL} \n  Magaca isticmaalaha:  {USERNAME} \n\nWaxaad isticmaalehaaga ku xoojin kartaa adigoo xulanaya xiriirkan hoose:\n{ACTIVATE}"
COM_USERS_EMAIL_ACTIVATE_WITH_ADMIN_ACTIVATION_SUBJECT="Ansixinta diiwaangelinta loo baahan yahay ee koontada {NAME} ee {SITENAME}"
COM_USERS_EMAIL_PASSWORD_RESET_BODY="Salaan,\n\nCodsi ayaa la sameeyey si loo cusboonaysiiyo eraygaaga sirta ah {SITENAME}. Si aad u cusboonaysiiso eraygaaga sirta ah, waxaad u baahan doontaa inaad dhiibto lambarkan xaqiijinta si loo xaqiijiyo in codsigu saxan yahay.\n\nLambarka xaqiijinta waa {TOKEN}\n\nXullo URL-ka hoos ku qoran oo sii wad inaad cusboonaysiiso eraygaaga sirta ah.\n\n{LINK_TEXT} \n\nMahadsanid."
COM_USERS_EMAIL_PASSWORD_RESET_SUBJECT="Codsigaaga erayga sirta ah ee {SITENAME}"
COM_USERS_EMAIL_REGISTERED_BODY="Salaan {NAME},\n\nWaad ku mahadsan tahay isdiiwaangelinta {SITENAME}.\n\nHadda waxaad ku soo gali kartaa {SITEURL} adigoo isticmaalaya magaca isticmaalaha iyo erayga sirta ah ee soo socda:\n\nMagaca isticmaalaha: {USERNAME}\nErayga sirta ah: {PASSWORD_CLEAR}"
COM_USERS_EMAIL_REGISTERED_BODY_NOPW="Salaan {NAME},\n\nWaad ku mahadsan tahay isdiiwaangelinta {SITENAME}.\n\nHadda waxaad ku soo gali kartaa {SITEURL} adigoo isticmaalaya magaca isticmaalaha iyo erayga sirta ah ee aad isdiiwaangelinta ku qortay."
COM_USERS_EMAIL_REGISTERED_NOTIFICATION_TO_ADMIN_BODY="Salaan maamulow,\n\nIsticmaale cusub '{NAME}', magaca isticmaalaha '{USERNAME}', ayaa isdiiwaangeliyey {SITEURL}."
COM_USERS_EMAIL_REGISTERED_WITH_ACTIVATION_BODY="Salaan {NAME},\n\nWaad ku mahadsan tahay isdiiwaangelinta {SITENAME}. Koontadaada waa la sameeyey lana firfircoonayn ka hor intaadan isticmaalin.\nSi aad koontada u firfircoonaato dooro xiriirka hoose ama koobi-geli biraawsarkaaga:\n{ACTIVATE} \n\nKa dib markaad firfircoonaato waxaad ku soo gali kartaa {SITEURL} adigoo isticmaalaya magaca isticmaalaha iyo erayga sirta ah ee soo socda:\n\nMagaca isticmaalaha: {USERNAME}\nErayga sirta ah: {PASSWORD_CLEAR}"
COM_USERS_EMAIL_REGISTERED_WITH_ACTIVATION_BODY_NOPW="Salaan {NAME},\n\nWaad ku mahadsan tahay isdiiwaangelinta {SITENAME}. Koontadaada waa la sameeyey lana firfircoonayn ka hor intaadan isticmaalin.\nSi aad koontada u firfircoonaato dooro xiriirka hoose ama koobi-geli biraawsarkaaga:\n{ACTIVATE} \n\nKa dib markaad firfircoonaato waxaad ku soo gali kartaa {SITEURL} adigoo isticmaalaya magaca isticmaalaha iyo erayga sirta ah ee aad isdiiwaangelinta ku qortay:\n\nMagaca isticmaalaha: {USERNAME}"
COM_USERS_EMAIL_REGISTERED_WITH_ADMIN_ACTIVATION_BODY="Salaan {NAME},\n\nWaad ku mahadsan tahay isdiiwaangelinta {SITENAME}. Koontadaada waa la sameeyey lana xaqiijinayaa ka hor intaadan isticmaalin.\n\nSi aad koontada u xaqiijiso, dooro xiriirka hoose ama koobi-geli biraawsarkaaga:\n{ACTIVATE} \n\nKa dib markaad xaqiijiso waxaa la ogeysiin doonaa maamulaha si uu koontadaada u firfircoonaado. Waxaad heli doontaa xaqiijinta marka la sameeyo.\n\nMarka koontadani la firfircoonaado waxaad ku soo gali kartaa {SITEURL} adigoo isticmaalaya magaca isticmaalaha iyo erayga sirta ah ee soo socda:\n\nMagaca isticmaalaha: {USERNAME}\nErayga sirta ah: {PASSWORD_CLEAR}"
COM_USERS_EMAIL_REGISTERED_WITH_ADMIN_ACTIVATION_BODY_NOPW="Salaan {NAME},\n\nWaad ku mahadsan tahay isdiiwaangelinta {SITENAME}. Koontadaada waa la sameeyey lana xaqiijinayaa ka hor intaadan isticmaalin.\n\nSi aad koontada u xaqiijiso, dooro xiriirka hoose ama koobi-geli biraawsarkaaga:\n{ACTIVATE} \n\nKa dib markaad xaqiijiso waxaa la ogeysiin doonaa maamulaha si uu koontadaada u firfircoonaado. Waxaad heli doontaa xaqiijinta marka la sameeyo.\n\nMarka koontadani la firfircoonaado waxaad ku soo gali kartaa {SITEURL} adigoo isticmaalaya magaca isticmaalaha iyo erayga sirta ah ee aad isdiiwaangelinta ku qortay:\n\nMagaca isticmaalaha: {USERNAME}"
COM_USERS_EMAIL_USERNAME_REMINDER_BODY="Salaan,\n\nWaxaa lagu codsaday in la xasuusiyo magaca isticmaaluhu ee akoonkaaga {SITENAME}.\n\nMagacaaga isticmaalaha: {USERNAME}\n\nSi aad ugu soo gasho akoonkaaga, xullo xiriirka hoose.\n\n{LINK_TEXT} \n\nMahadsanid."
COM_USERS_EMAIL_USERNAME_REMINDER_SUBJECT="Magacaaga isticmaale ee {SITENAME}"
COM_USERS_FIELD_PASSWORD_RESET_LABEL="Cinwaanka Emailka"
COM_USERS_FIELD_REMIND_EMAIL_LABEL="Cinwaanka Emailka"
COM_USERS_FIELD_RESET_CONFIRM_TOKEN_LABEL="Lambarka Xaqiijinta"
COM_USERS_FIELD_RESET_CONFIRM_USERNAME_LABEL="Magaca Isticmaalaha"
COM_USERS_FIELD_RESET_PASSWORD1_LABEL="Erayga sirta ah"
COM_USERS_FIELD_RESET_PASSWORD1_MESSAGE="Furayaasha sirta ah ee aad gelisay ma jaanqaadaan. Fadlan geli erayga sirta ah ee aad rabto booska erayga sirta ah oo xaqiiji gelintaada adiga oo ku gelinaya booska xaqiijinta sirta ah."
COM_USERS_FIELD_RESET_PASSWORD2_LABEL="Xaqiiji ereyga sirta ah"
COM_USERS_FRONTEND_LOGOUT_SUCCESS="Waad ka baxday."
COM_USERS_INVALID_EMAIL="Cinwaanka iimaylka aan sax ahayn"
COM_USERS_LBL_SELECT_INSTRUCTIONS="Fadlan dooro sida aad jeclaan lahayd inaad ku xaqiijiso inaad galeyso goobtan."
COM_USERS_LOGIN_DEFAULT_LABEL="Isticmaalaha Gelitaanka"
COM_USERS_LOGIN_REGISTER="Ma haysataa xisaab?"
COM_USERS_LOGIN_REMEMBER_ME="I xasuuso"
COM_USERS_LOGIN_REMIND="Miyaa ilaaway magacaaga isticmaalaha?"
COM_USERS_LOGIN_RESET="Miyaa ilaaway ereygaaga sirta ah?"
COM_USERS_LOGIN_USERNAME_LABEL="Magaca isticmaalaha"
COM_USERS_MAIL_FAILED="Dirista iimaylka waa lagu guuldareystay."
COM_USERS_MAIL_SEND_FAILURE_BODY="Waxaa la kulmay qalad marka la dirayay iimaylka diiwaangelinta isticmaalaha. Isticmaalaha isku dayay inuu isdiiwaangeliyo waa: %s"
COM_USERS_MAIL_SEND_FAILURE_SUBJECT="Qalad dirista iimaylka"
COM_USERS_MFA_ADD_AUTHENTICATOR_OF_TYPE="Ku dar nooc cusub oo %s ah"
COM_USERS_MFA_ADD_PAGE_HEAD="Ku dar Habka Caddeynta Badbaado ee Badan"
COM_USERS_MFA_BACKUPCODES_PRINT_PROMPT="Koodhadhka kaydka waxay kuu oggolaanayaan inaad gasho goobta haddii habkaaga caddeynta badbaado ee joogtada ah uusan shaqayn ama haddii aadan heli karin. Koodh kasta waxaa loo isticmaali karaa <em>hal mar oo kaliya</em>."
COM_USERS_MFA_BACKUPCODES_PRINT_PROMPT_HEAD="<a href=\"%1s\" class=\"%2s\">Daabac koodhadhkan</a> oo ku hay jeebkaaga."
COM_USERS_MFA_BACKUPCODES_RESET="Dib-u-sameynta Koodhadhka Kaydka"
COM_USERS_MFA_BACKUPCODES_RESET_INFO="Isticmaal batoonka hoose si aad u abuurto set cusub oo koodhadh kayd ah. Waxaan kugula talineynaa inaad sidaas sameyso haddii aad u maleyneyso in koodhadhkaaga kaydka ay khatar ku jiraan, tusaale ahaan qof ayaa hela nuqulka daabacan, ama haddii aad helayso koodhadh kayd oo yaraaday."
COM_USERS_MFA_EDIT_FIELD_DEFAULT="Ka dhig habkan caddeynta badbaado habka asalka"
COM_USERS_MFA_EDIT_FIELD_TITLE="Cinwaan"
COM_USERS_MFA_EDIT_FIELD_TITLE_DESC="Adiga iyo maamulayaasha goobta waxaad arki doontaan magacaas in liiska hababka caddeynta badbaado ee akoonkaaga isticmaale. Fadlan ha ku darin wax macluumaad ah oo xasaasi ah ama aqoonsiyada shaqsiga ah."
COM_USERS_MFA_EDIT_PAGE_HEAD="Beddel habka caddeynta badbaado ee badan"
COM_USERS_MFA_FIRSTTIME_INSTRUCTIONS_HEAD="Isticmaal Caddeynta Badbaado ee Badan si aad u hesho ammaan dheeraad ah"
COM_USERS_MFA_FIRSTTIME_INSTRUCTIONS_WHATITDOES="Waa sida ay u shaqeyso. Ku dar habka Aqoonsiga Koofiyadista Multi-factor hoos. Laga bilaabo hadda, markaad gelaysid goobta mar kasta waxaa lagaa codsan doonaa inaad isticmaasho habkan si aad u dhamaystirto gelitaanka. Xitaa haddii qof xado magacaaga isticmaale iyo eraygaaga sirta ah, ma heli doonaan koontooyinkaaga goobtan."
COM_USERS_MFA_FIRSTTIME_NOTINTERESTED="Ha tusi mar kale"
COM_USERS_MFA_FIRSTTIME_PAGE_HEAD="Ku dejiso Kahortagista Multi-factor"
COM_USERS_MFA_INVALID_CODE="Aqoonsiga Koofiyadista Multi-factor wuu fashilmay. Fadlan isku day mar kale."
COM_USERS_MFA_INVALID_METHOD="Hab dagaal gelid aan sax ahayn."
COM_USERS_MFA_LBL_CREATEDON="La raaciyey: %s"
COM_USERS_MFA_LBL_DATE_FORMAT_PAST="F d, Y"
COM_USERS_MFA_LBL_DATE_FORMAT_TODAY="H:i"
COM_USERS_MFA_LBL_DATE_FORMAT_YESTERDAY="H:i"
COM_USERS_MFA_LBL_LASTUSED="La isticmaalay ugu dambayn: %s"
COM_USERS_MFA_LBL_PAST="%s"
COM_USERS_MFA_LBL_TODAY="Maanta, %s"
COM_USERS_MFA_LBL_YESTERDAY="Shalay, %s"
COM_USERS_MFA_LIST_DEFAULTTAG="Asalka"
COM_USERS_MFA_LIST_INSTRUCTIONS="Ku dar ugu yaraan hal hab oo Koofiyadista Multi-factor ah. Mar kasta oo aad ku gelaysid goobta waxaad tahay inaad bixiso."
COM_USERS_MFA_LIST_PAGE_HEAD="Xulashooyinkaada Koofiyadista Multi-factor"
COM_USERS_MFA_LIST_REMOVEALL="Deminta"
COM_USERS_MFA_LIST_STATUS_OFF="Koofiyadista Multi-factor <strong>lama iibin</strong>."
COM_USERS_MFA_LIST_STATUS_ON="Koofiyadista Multi-factor waa la hawlgaliyay."
COM_USERS_MFA_LOGOUT="Ka Bax"
COM_USERS_MFA_MANDATORY_NOTICE_BODY="Fadlan suurtogeli hab Koofiyadista Multi-factor oo loogu talagalay koontadaada isticmaale. Ma sii wadi doontid isticmaalka goobtan ilaa aad sidaa samayso."
COM_USERS_MFA_MANDATORY_NOTICE_HEAD="Koofiyadista Multi-factor waa lagama maarmaan koontadaada isticmaale"
COM_USERS_MFA_SELECT_PAGE_HEAD="Dooro hab Koofiyadista Multi-factor"
COM_USERS_MFA_USE_DIFFERENT_METHOD="Dooro hab kale"
COM_USERS_MFA_TRY_LIMIT_REACHED="Waad gaartay xadka isku day biiro ee habka Aqoonsiga hadda. Fadlan dooro hab kale ama sugo."
COM_USERS_MFA_VALIDATE="Hubi"
COM_USERS_OR="ama"
COM_USERS_PROFILE="Astaanta Adeegsanaha"
COM_USERS_PROFILE_CORE_LEGEND="Astaanta"
COM_USERS_PROFILE_DEFAULT_LABEL="Tafatir Astaantaada"
COM_USERS_PROFILE_EMAIL1_LABEL="Cinwaanka Emailka"
COM_USERS_PROFILE_LAST_VISITED_DATE_LABEL="Taariikhda Ugu Dambaysay Booqo"
COM_USERS_PROFILE_MULTIFACTOR_AUTH="Sax-xaqa-badan"
COM_USERS_PROFILE_NAME_LABEL="Magac"
COM_USERS_PROFILE_NEVER_VISITED="Waa markii ugu horeysay ee aad soo booqatay boggan."
COM_USERS_PROFILE_NOCHANGE_USERNAME_DESC="Haddii aad rabto inaad bedesho magaca adeegsiga, fadlan la xiriir maamulaha bogga."
COM_USERS_PROFILE_PASSWORD1_LABEL="Furaha"
COM_USERS_PROFILE_PASSWORD1_MESSAGE="Furayaasha aad gelisay ma wada sinna. Fadlan geli furaha aad rabtid ee qaybta furaha oo xaqiiji arjigaaga adigoo ku gelinaya qeybta xaqiijinta furaha."
COM_USERS_PROFILE_PASSWORD2_LABEL="Xaqiiji Furaha"
COM_USERS_PROFILE_REGISTERED_DATE_LABEL="Taariikhda Diiwaan-gashan"
COM_USERS_PROFILE_SAVE_FAILED="Astaanta laguma keydin karin: %s"
COM_USERS_PROFILE_SAVE_SUCCESS="Astaanta waa la keydiyey."
COM_USERS_PROFILE_USERNAME_LABEL="Magaca Adeegsiga"
COM_USERS_PROFILE_USERNAME_MESSAGE="Magaca adeegsiga aad gelisay ma heli karo. Fadlan dooro magaca adeegsiga kale."
COM_USERS_PROFILE_VALUE_NOT_FOUND="Defaultka Websiteka"
COM_USERS_REGISTER_EMAIL1_LABEL="Cinwaanka Emailka"
COM_USERS_REGISTER_NAME_LABEL="Magac"
COM_USERS_REGISTER_REQUIRED="<strong class=\"red\">*</strong> Goob Loo Baahan Yahay"
COM_USERS_REGISTER_USERNAME_LABEL="Magaca Adeegsiga"
COM_USERS_REGISTER_USERNAME_MESSAGE="Magaca adeegsiga aad gelisay ma heli karo. Fadlan dooro magaca adeegsiga kale."
COM_USERS_REGISTRATION="Diiwaangelinta Isticmaalaha"
COM_USERS_REGISTRATION_ACL_ADMIN_ACTIVATION="Fadlan gal si aad u xaqiijiso inaad xaq u leedahay inaad dhaqaajiso xisaabaad cusub."
COM_USERS_REGISTRATION_ACL_ADMIN_ACTIVATION_PERMISSIONS="Ma lihid ogolaansho aad ku dhaqaajiso xisaabaad cusub, fadlan gal akoon leh xuquuq ka wanaagsan."
COM_USERS_REGISTRATION_ACTIVATE_SUCCESS="Xisaabtaada waa la dhaqaajiyay. Hadda waad gali kartaa adoo isticmaalaya magaca isticmaalaha iyo furahaaga ee aad dooratay intii aad ku jirtay diiwaangelinta."
COM_USERS_REGISTRATION_ACTIVATION_NOTIFY_SEND_MAIL_FAILED="Khalad ayaa dhacay intii la dirayay emaylka ogeysiiska dhaqaajinta"
COM_USERS_REGISTRATION_ACTIVATION_SAVE_FAILED="Kama dhammaan in la badbaadiyo xogta dhaqaajinta: %s"
COM_USERS_REGISTRATION_ADMINACTIVATE_SUCCESS="Xisaabta isticmaalaha waa la dhaqaajiyay waxaana loo sheegay isticmaalaha."
COM_USERS_REGISTRATION_COMPLETE_ACTIVATE="Xisaabtaada waa la sameeyay oo xiriir dhaqaajin ah ayaa loo diray cinwaanka emaylka aad gelisay. Ogow inaad tahay inaad dhaqaajiso xisaabta adoo dooranaya xiriirka dhaqaajinta marka aad hesho emaylka ka hor intaadan gelin."
COM_USERS_REGISTRATION_COMPLETE_VERIFY="Xisaabtaada waa la sameeyay waxaana loo diray xiriir xaqiijin ah cinwaanka emaylka aad gelisay. Ogow inaad tahay inaad xaqiijiso xisaabta adoo dooranaya xiriirka xaqiijinta marka aad hesho emaylka ka dibna maamulaha ayaa dhaqaajin doona xisaabtaada intaadan galin."
COM_USERS_REGISTRATION_DEFAULT_LABEL="Diiwaangelinta Isticmaalaha"
COM_USERS_REGISTRATION_SAVE_FAILED="Diiwaangelintu wey fashilantay: %s"
COM_USERS_REGISTRATION_SAVE_SUCCESS="Waad ku mahadsan tahay diiwaangelinta. Hadda waad gali kartaa adoo isticmaalaya magaca isticmaalaha iyo furahaaga ee aad diiwaangelisay."
COM_USERS_REGISTRATION_SEND_MAIL_FAILED="Khalad ayaa dhacay intii la dirayay emaylka diiwaangelinta. Fariin ayaa loo diray maamulaha goobtan."
COM_USERS_REGISTRATION_VERIFY_SUCCESS="Cinwaankaaga emaylka waa la xaqiijiyay. Marka maamulaha uu oggolaado xisaabtaada waxaa lagu ogeysiin doonaa emayl kadibna waxaad gali kartaa goobta."
COM_USERS_REMIND="Xasuusin"
COM_USERS_REMIND_DEFAULT_LABEL="Fadlan geli cinwaanka emaylka la xiriira xisaabtaada Isticmaalaha. Magacaagu wuxuu laguugu soo diri doonaa emaylka ku jira diiwaanka."
COM_USERS_REMIND_LIMIT_ERROR_N_HOURS="Waxaad dhaaftay tirada ugu badan ee loo oggol yahay in la beddelo furaha sirta ah. Fadlan isku day mar kale %d saacadood gudahood."
COM_USERS_REMIND_LIMIT_ERROR_N_HOURS_1="Waxaad dhaaftay tirada ugu badan ee loo oggol yahay in la beddelo furaha sirta ah. Fadlan isku day mar kale hal saac gudahood."
COM_USERS_REMIND_REQUEST="Haddii cinwaanka emaylka aad gelisay uu ka diiwaan gashan yahay goobtan waxaad si dhakhso ah u heli doontaa emayl leh xasuusin."
COM_USERS_REMIND_REQUEST_ERROR="Khalad ka dhacay codsiga xasuusinta furaha sirta."
COM_USERS_REMIND_REQUEST_FAILED="Xasuusintu way fashilantay: %s"
COM_USERS_REMIND_REQUEST_SUCCESS="Xasuusin la diray. Fadlan hubi emaylkaaga."
COM_USERS_REMIND_SUPERADMIN_ERROR="Isticmaalaha Super ma codsan karo xasuusin furaha sirta. Fadlan la xiriir isticmaale kale oo Super ah ama isticmaal hab kale."
COM_USERS_RESET="Dib u habeynta Furaha sirta"
COM_USERS_RESET_COMPLETE_ERROR="Khalad ka dhacay dhammeystirka dib u habeynta furaha sirta."
COM_USERS_RESET_COMPLETE_FAILED="Dhameystirka dib u dajinta erayga sirta ah wuu fashilmay: %s"
COM_USERS_RESET_COMPLETE_LABEL="Si aad u dhamaystirto habka dib u cusbooneysiinta erayga sirta, fadlan geli eray sir cusub."
COM_USERS_RESET_COMPLETE_SUCCESS="Dib u dajinta erayga sirta ah waa lagu guuleystay. Waxaad hadda gali kartaa bogga."
COM_USERS_RESET_COMPLETE_TOKENS_MISSING="Caddaynta dib u cusboonaysiinta erayga sirta ah ayaa fashilantay sababtoo ah waxay la'aanteed koodhka xaqiijinta."
COM_USERS_RESET_CONFIRM_ERROR="Khalad inta lagu jiro xaqiijinta erayga sirta ah."
COM_USERS_RESET_CONFIRM_FAILED="Caddaynta dib u cusbooneysiinta erayga sirta ah ayaa fashilantay sababtoo ah koodhka xaqiijinta ma saxna. %s"
COM_USERS_RESET_CONFIRM_LABEL="E-mail ayaa loo diray ciwaankaaga emailka. Emailku wuxuu leeyahay koodh xaqiijin, fadlan ku dhaji koodhka xaqiijinta goobta hoose si aad u caddayso inaad tahay milkiilaha koontadan."
COM_USERS_RESET_REQUEST="Haddii ciwaanka e-mailka aad gelisay uu ka diiwaan gashan yahay mareegtan waxaad si dhow u heli doontaa email leh isku xirka dib u cusbooneysiinta erayga sirta koontadaada."
COM_USERS_RESET_REQUEST_ERROR="Khalad codsanaya dib u cusbooneysiinta erayga sirta ah."
COM_USERS_RESET_REQUEST_FAILED="Dib u dajinta erayga sirta ah waa lagu guuldareystay: %s"
COM_USERS_RESET_REQUEST_LABEL="Fadlan geli ciwaanka emailka ee koontadaada. Koodh xaqiijinta ayaa laguu soo diri doonaa. Marka aad heshid koodhka xaqiijinta, waxaad dooran doontaa eray sir cusub oo koontadaada."
COM_USERS_SETTINGS_FIELDSET_LABEL="Dejinta Aasaasiga ah"
COM_USERS_USER_ALLOWTOURAUTOSTART_LABEL="U oggolow Kormeerro Si otomaatig Ah Loo Biloow"
COM_USERS_USER_BACKUPCODE="Koodhka Kaydka ah"
COM_USERS_USER_BACKUPCODES="Koodhadhka Kaydka ah"
COM_USERS_USER_BACKUPCODES_CAPTIVE_PROMPT="Haddii aadan gelin karin habkaaga Caadiga ah ee Laba-factor Aqoonsi isticmaalo mid ka mid ah Koodhadhkayaga Kaydka ah ee ku xiga goobta hoose. Fadlan xusuusnow in Koodhkan Kaydka ah ee degdega ah aan dib loo isticmaali karin."
COM_USERS_USER_BACKUPCODES_DESC="Haddii aadan helin qalabkaaga Aqoonsiga Laba-factor waxaad isticmaali kartaa mid ka mid ah furaha soo socda halkii aad isticmaali lahayd koodhka amniga caadiga ah. Mid kasta oo ka mid ah koodhkan degdegga ah waxa si degdeg ah loo burburiyaa marka la isticmaalo. Waxaan ku talinaynaa in la daabaco koodhadan iyo in daabacaadda lagu hayo meel ammaan ah oo la heli karo, tusaale ahaan boorsadaada ama sanduuq ammaan ah."
COM_USERS_USER_BLOCKED="Isticmaalahan waa la xannibay. Haddii tani ay khalad tahay, fadlan la xiriir maamulaha."
COM_USERS_USER_COLORSCHEME_LABEL="Qaabka Madow"
COM_USERS_USER_COLORSCHEME_OPTION_DARK="Isticmaal Qaabka Midabka Madow"
COM_USERS_USER_COLORSCHEME_OPTION_FOLLOW_OS="Raac Dejinta OS"
COM_USERS_USER_COLORSCHEME_OPTION_LIGHT="Isticmaal Qaabka Midabka Fudud"
COM_USERS_USER_FIELD_BACKEND_LANGUAGE_LABEL="Luuqadda Backend"
COM_USERS_USER_FIELD_BACKEND_TEMPLATE_LABEL="Qaabka Template-ka Backend"
COM_USERS_USER_FIELD_EDITOR_LABEL="Tifaftiraha"
COM_USERS_USER_FIELD_FRONTEND_LANGUAGE_LABEL="Luuqadda Hore"
COM_USERS_USER_FIELD_TIMEZONE_LABEL="Aaga Waqtiga"
COM_USERS_USER_MULTIFACTOR_AUTH="Hubinta Badbaadada ee Inta Badan"
COM_USERS_USER_NOT_FOUND="Isticmaale lama helin."
COM_USERS_USER_SAVE_FAILED="Ku guul-dareystay in la keydiyo isticmaalaha: %s"

