; Joomla! Project
; (C) 2011 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_FINDER="Raadiiska Caqliga Leh"
COM_FINDER_ADVANCED_SEARCH_TOGGLE="Raadiiska Sare"
COM_FINDER_ADVANCED_TIPS_AND="<p>Gelinta <strong>tani iyo taas</strong> foomka raadinta waxay soo celin doontaa natiijooyin ay ku jiraan labada &quot;tani&quot; iyo &quot;taas&quot;.</p>"
COM_FINDER_ADVANCED_TIPS_INTRO="<p>Halkan waxaa ku yaal dhowr tusaale oo ku saabsan sida aad u isticmaali karto faa'iidada raadinta:</p>"
COM_FINDER_ADVANCED_TIPS_NOT="<p>Gelinta <strong>tani ma aha taas</strong> foomka raadinta waxay soo celin doontaa natiijooyin ay ku jiraan &quot;tani&quot; oo aan ku jirin &quot;taas&quot;.</p>"
COM_FINDER_ADVANCED_TIPS_OR="<p>Gelinta <strong>tani ama taas</strong> foomka raadinta waxay soo celin doontaa natiijooyin ay ku jiraan ama &quot;tani&quot; ama &quot;taas&quot;.</p>"
COM_FINDER_ADVANCED_TIPS_OUTRO="<p>Natiijooyinka raadinta waxaa sidoo kale lagu shaandheyn karaa iyadoo la adeegsanayo shuruudo kala duwan. Xulo mid ama in ka badan filters hoose si aad u bilowdo.</p>"
COM_FINDER_ADVANCED_TIPS_PHRASE="<p>Gelinta <strong>&quot;tani iyo taas&quot;</strong> (xumaadood) foomka raadinta waxay soo celin doontaa natiijooyin ay ku jiraan weedha dhabta ah &quot;tani iyo taas&quot;.</p>"
COM_FINDER_DEFAULT_PAGE_TITLE="Natiijooyinka Raadinta"
COM_FINDER_FILTER_BRANCH_LABEL="Raadi by %s"
COM_FINDER_FILTER_DATE1="Taariikhda Bilawga"
COM_FINDER_FILTER_DATE1_DESC="Gali taariikh qaabka YYYY-MM-DD."
COM_FINDER_FILTER_DATE1_OPERATOR="Hawlgalka Taariikhda Bilawga"
COM_FINDER_FILTER_DATE2="Taariikhda Dhamaadka"
COM_FINDER_FILTER_DATE2_DESC="Gali taariikh qaabka YYYY-MM-DD."
COM_FINDER_FILTER_DATE2_OPERATOR="Hawlgalka Taariikhda Dhamaadka"
COM_FINDER_FILTER_DATE_AFTER="Ka dib"
COM_FINDER_FILTER_DATE_BEFORE="Ka hor"
COM_FINDER_FILTER_DATE_EXACTLY="Sida saxda ah"
COM_FINDER_FILTER_SELECT_ALL_LABEL="Raadi Dhammaan"
COM_FINDER_FILTER_WHEN_AFTER="Ka dib"
COM_FINDER_FILTER_WHEN_BEFORE="Ka hor"
COM_FINDER_OPENSEARCH_NAME="Raadin"
COM_FINDER_QUERY_DATE_CONDITION_AFTER="ka dib"
COM_FINDER_QUERY_DATE_CONDITION_BEFORE="ka hor"
COM_FINDER_QUERY_DATE_CONDITION_EXACT="si sax ah"
COM_FINDER_QUERY_END_DATE="taariikhda dhamaadka <span class=\"when\">%s</span> <span class=\"date\">%s</span>"
COM_FINDER_QUERY_FILTER_BRANCH_VENUE="goobta"
COM_FINDER_QUERY_OPERATOR_AND="iyo"
COM_FINDER_QUERY_OPERATOR_NOT="maahan"
COM_FINDER_QUERY_OPERATOR_OR="ama"
COM_FINDER_QUERY_RESULTS="Iyadoo loo maleynayo %2$s, waxaa la helay <a href=\"#search-result-list\">%d natiijooyin.</a>"
COM_FINDER_QUERY_RESULTS_0="Iyadoo loo maleynayo %2$s, natiijooyin lama helin. <a href=\"#q\">Mar kale isku day.</a>"
COM_FINDER_QUERY_RESULTS_1="Iyadoo loo maleynayo %2$s, waxaa la helay natiijadan."
COM_FINDER_QUERY_START_DATE="taariikhda bilowga <span class=\"when\">%s</span> <span class=\"date\">%s</span>"
COM_FINDER_QUERY_TAXONOMY_NODE="leh <span class=\"node\">%s</span> sida <span class=\"branch\">%s</span> "
COM_FINDER_QUERY_TOKEN_EXCLUDED="<span class=\"term\">%s</span> waa in laga reebo"
COM_FINDER_QUERY_TOKEN_GLUE=", iyo "
COM_FINDER_QUERY_TOKEN_OPTIONAL="<span class=\"term\">%s</span> waa ikhtiyaari"
COM_FINDER_QUERY_TOKEN_REQUIRED="<span class=\"term\">%s</span> waa qasab"
COM_FINDER_SEARCH_ADVANCED_LEGEND="Raadin La Hormariyay"
COM_FINDER_SEARCH_FORM_LEGEND="Foomka Raadinta"
COM_FINDER_SEARCH_FORM_LIST_LABEL="Natiijooyinka Raadinta"
COM_FINDER_SEARCH_NO_RESULTS_BODY="Lama heli karin wax natiijooyin raadinta ah ee weydiinta: %s."
COM_FINDER_SEARCH_NO_RESULTS_BODY_MULTILANG="Lama heli karin wax natiijooyin raadinta ah oo ah Ingiriis (en-GB) ee weydiinta: %s."
COM_FINDER_SEARCH_NO_RESULTS_HEADING="Lama Helin Natiijooyin"
COM_FINDER_SEARCH_RESULTS_OF="Natiijooyinka <strong>%s</strong> - <strong>%s</strong> ee <strong>%s</strong>"
COM_FINDER_SEARCH_SIMILAR="Ma waxaad ula jeeddaa: %s?"
COM_FINDER_SEARCH_TERMS="Erayada Raadinta:"
COM_FINDER_SORT_BY="Kala Saar Sida:"
COM_FINDER_SORT_BY_PRICE_ASC="Qiimaha liiska koraya"
COM_FINDER_SORT_BY_PRICE_DESC="Qiimaha liiska hoos u dhacaya"
COM_FINDER_SORT_BY_RELEVANCE_ASC="Mudnaanta koraya"
COM_FINDER_SORT_BY_RELEVANCE_DESC="Mudnaanta hoos u dhacaya"
COM_FINDER_SORT_BY_SALES_PRICE_ASC="Qiimaha iibka koraya"
COM_FINDER_SORT_BY_SALES_PRICE_DESC="Qiimaha iibka hoos u dhacaya"

