; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_WRAPPER_NO_IFRAMES="Xulashadan si sax ah uma shaqayn doonto. Nasiib darro, daalacashadaadu kuma taageerto unugyada gudaha ku jira."

