; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_CONTACT_ADDRESS="Cinwaanka"
COM_CONTACT_CAPTCHA_LABEL="Captcha"
COM_CONTACT_CAT_NUM="Tirada Xiriirada:"
COM_CONTACT_CHECKED_OUT_BY="Waxaa hubiyay %s"
COM_CONTACT_CONTACT_DEFAULT_LABEL="Dir Email"
COM_CONTACT_CONTACT_DETAILS="Faahfaahinta"
COM_CONTACT_CONTACT_EMAIL_A_COPY_LABEL="Soo dir nooca naftaada"
COM_CONTACT_CONTACT_EMAIL_NAME_LABEL="Magaca"
COM_CONTACT_CONTACT_ENTER_MESSAGE_LABEL="Farriin"
COM_CONTACT_CONTACT_MESSAGE_SUBJECT_LABEL="Mawduuc"
COM_CONTACT_CONTACT_REQUIRED="<strong class=\"red\">*</strong> Goobta loo baahan yahay"
COM_CONTACT_CONTACT_SEND="Dir Email"
COM_CONTACT_COPYSUBJECT_OF="Nuqul ka mid ah: {SUBJECT}"
COM_CONTACT_COPYTEXT_OF="Tani waa nuqul ka mid ah farriinta aad dirtay {CONTACTNAME} iyada oo loo marayo {SITENAME}\n\n{BODY}"
COM_CONTACT_COUNT="Tirada Xiriirada:"
COM_CONTACT_COUNTRY="Waddanka"
COM_CONTACT_DEFAULT_PAGE_TITLE="Xiriirada"
COM_CONTACT_DETAILS="Xiriir"
COM_CONTACT_DOWNLOAD_INFORMATION_AS="Ku soo deji macluumaadka sida:"
COM_CONTACT_EDIT_CONTACT="Tafatir Xiriir"
COM_CONTACT_EDIT_PUBLISHED_CONTACT="Xiriir La Daabacay"
COM_CONTACT_EDIT_UNPUBLISHED_CONTACT="Xiriir Aan La Daabicin"
COM_CONTACT_EMAIL_FORM="Foomka Xiriirka"
COM_CONTACT_EMAIL_LABEL="Email"
COM_CONTACT_EMAIL_THANKS="Waad ku mahadsan tahay emailkaaga."
COM_CONTACT_ENQUIRY_SUBJECT="{SITENAME}: {SUBJECT}"
COM_CONTACT_ENQUIRY_TEXT="Tani waa email weydiineed oo loo marayo {URL} laga soo diray:\n{NAME} {EMAIL}\n\n{BODY}\n\n{CUSTOMFIELDS}"
COM_CONTACT_ERROR_CONTACT_NOT_FOUND="Xiriir lama helin"
COM_CONTACT_ERROR_UNIQUE_ALIAS="Xiriir kale oo ku jira qaybtan ayaa leh astaan isku mid ah."
COM_CONTACT_ERROR_UNIQUE_ALIAS_TRASHED="Xiriir la tuuray oo ku jira qaybtan ayaa leh astaan isku mid ah."
COM_CONTACT_FAX="Faakiska"
COM_CONTACT_FAX_NUMBER="Faakiska: %s"
COM_CONTACT_FIELD_CREATED_BY_ALIAS_LABEL="Waxaa abuuray Alias"
COM_CONTACT_FIELD_INFORMATION_ADDRESS_LABEL="Cinwaanka"
COM_CONTACT_FIELD_INFORMATION_COUNTRY_LABEL="Dalka"
COM_CONTACT_FIELD_INFORMATION_FAX_LABEL="Faakiska"
COM_CONTACT_FIELD_INFORMATION_MISC_LABEL="Macluumaad kale"
COM_CONTACT_FIELD_INFORMATION_MOBILE_LABEL="Mobiil"
COM_CONTACT_FIELD_INFORMATION_POSITION_LABEL="Jago"
COM_CONTACT_FIELD_INFORMATION_POSTCODE_LABEL="Lambarka Boostada/ZIP"
COM_CONTACT_FIELD_INFORMATION_STATE_LABEL="Gobolka ama Degmada"
COM_CONTACT_FIELD_INFORMATION_SUBURB_LABEL="Magaalada ama Xaafadda"
COM_CONTACT_FIELD_INFORMATION_TELEPHONE_LABEL="Telefoon"
COM_CONTACT_FIELD_INFORMATION_WEBPAGE_LABEL="Website"
COM_CONTACT_FIELD_LINKED_USER_LABEL="Isticmaale La Xiriiriyay"
COM_CONTACT_FIELD_NAME_LABEL="Magaca"
COM_CONTACT_FIELD_PARAMS_IMAGE_LABEL="Sawir"
COM_CONTACT_FIELD_PUBLISH_DOWN_LABEL="Dhammaadka Daabacaadda"
COM_CONTACT_FIELD_PUBLISH_UP_LABEL="Bilowga Daabacaadda"
COM_CONTACT_FIELD_SORTNAME1_LABEL="Meel Kowaad ee Kala Saarista"
COM_CONTACT_FIELD_SORTNAME2_LABEL="Goobta Kala-Saarista Labaad"
COM_CONTACT_FIELD_SORTNAME3_LABEL="Goobta Kala-Saarista Saddexaad"
COM_CONTACT_FIELDSET_METADATA="Macluumaadka Meta"
COM_CONTACT_FIELDSET_MISCELLANEOUS="Macluumaad Kala Duwan"
COM_CONTACT_FIELDSET_PUBLISHING="Daabacaadda"
COM_CONTACT_FILTER_LABEL="Goobta Kala-Saarista"
COM_CONTACT_FILTER_SEARCH_DESC="Kalafilaanshaha Cinwaanka"
COM_CONTACT_FORM_EDIT_CONTACT="Wax Ka Beddel Xidhiidhka"
COM_CONTACT_FORM_FILTER_LEGEND="Kalafilaansho"
COM_CONTACT_FORM_LABEL="U dir email. Dhammaan goobaha leh calaamada (*) waa lagama maarmaan."
COM_CONTACT_IMAGE_DETAILS="Sawirka xidhiidhka"
COM_CONTACT_LINKS="Xidhiidhyo"
COM_CONTACT_MOBILE="Moobil"
COM_CONTACT_MOBILE_NUMBER="Moobil: %s"
COM_CONTACT_NEW_CONTACT="Xidhiidh Cusub"
COM_CONTACT_NO_CONTACTS="Ma jiraan Xidhiidho la soo bandhigo"
COM_CONTACT_NOT_MORE_THAN_ONE_EMAIL_ADDRESS="Ma geli kartid in ka badan hal cinwaan email."
COM_CONTACT_NUM_ITEMS="Tirada Xidhiidhada:"
COM_CONTACT_OTHER_INFORMATION="Macluumaad Kala Duwan"
COM_CONTACT_POSITION="Booska"
COM_CONTACT_PROFILE="Astaanta"
COM_CONTACT_SELECT_CONTACT="Xulo xidhiidh:"
COM_CONTACT_SESSION_INVALID="Kukiyada fadhiga ayaa khalad ah. Fadlan hubi inaad cookies-ka ku hawlan tahay boggaga adeeggaaga."
COM_CONTACT_STATE="Gobolka"
COM_CONTACT_SUBURB="Xaafad"
COM_CONTACT_TABLE_CAPTION="Xiriirada"
COM_CONTACT_TELEPHONE="Telefon"
COM_CONTACT_TELEPHONE_NUMBER="Telefon: %s"
COM_CONTACT_USER_FIELDS="Meelo"
COM_CONTACT_VCARD="Kaarka v"
COM_CONTACT_WEBPAGE="Bogga Internetka"

