; Joomla! Project
; (C) 2013 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_TAGS_CREATED_DATE="Taariikhda La Abuuray"
COM_TAGS_DEFAULT_PAGE_TITLE="Calaamadaha"
COM_TAGS_MODIFIED_DATE="Taariikhda La Bedelay"
COM_TAGS_NO_ITEMS="Wax walax la mid ah lama helin."
COM_TAGS_NO_TAGS="Calaamad wax loo soo bandhigo ma jiraan."
COM_TAGS_PUBLISHED_DATE="Taariikhda La Daabacay"
COM_TAGS_TAG_NOT_FOUND="Calaamad lama helin."
COM_TAGS_TITLE_FILTER_LABEL="Qor Qayb Ka Mid Ah Cinwaanka"

