; Joomla! Project
; (C) 2007 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_MEDIA="Warbaahin"
COM_MEDIA_ACTIONS_TOOLBAR_LABEL="Shay: %s"
COM_MEDIA_ACTION_DELETE="Tirtir"
COM_MEDIA_ACTION_DOWNLOAD="Soo dejiso"
COM_MEDIA_ACTION_EDIT="Tafatir"
COM_MEDIA_ACTION_PREVIEW="Fiirso"
COM_MEDIA_ACTION_RENAME="Magaca Beddel"
COM_MEDIA_ACTION_SHARE="Hel Link"
COM_MEDIA_ALIGN="Sawirka Float"
COM_MEDIA_ALIGN_DESC="Tani waxay dabaqeysaa fasalada 'float-start', 'pull-center' ama 'float-end' qodobka '<figure>' ama '<img>'."
COM_MEDIA_BREADCRUMB_LABEL="Hagitaan"
COM_MEDIA_BROWSE_FILES="Baadh Faylasha"
COM_MEDIA_CAPTION="Qormo"
COM_MEDIA_CAPTION_CLASS_DESC="Tani waxay dabaqeysaa fasalada la geliyay qodobka '<figcaption>'. Tusaale ahaan: 'text-start', 'text-end', 'text-center'."
COM_MEDIA_CAPTION_CLASS_LABEL="Fasalka Qormada"
COM_MEDIA_CHANGE_ORDERING="Badal Habeynta"
COM_MEDIA_CLEAR_LIST="Liiska Nadiifi"
COM_MEDIA_CONFIGURATION="Warbaahin: Xulashooyinka"
COM_MEDIA_CONFIRM_DELETE_MODAL="Tirtir"
COM_MEDIA_CONFIRM_DELETE_MODAL_HEADING="Xaqiiji Tirtir"
COM_MEDIA_COPY_FILE_NOT_POSSIBLE_FILE_ALREADY_EXISTS="Nuqulka faylka suurtogal ma aha maadaama uu jiro faylka bartilmaameedka"
COM_MEDIA_COPY_FILE_NOT_POSSIBLE="Nuqulka faylka suurtogal ma aha"
COM_MEDIA_COPY_FOLDER_ALREADY_EXISTS="Nuqulka faylka suurtogal ma aha maadaama uu jiro faylka bartilmaameedka"
COM_MEDIA_COPY_FOLDER_DESTINATION_CAN_NOT_DELETE="Nuqulka faylka suurtogal ma aha maadaama uu yahay faylka bartilmaameedka oo aan la tirtiri karin"
COM_MEDIA_COPY_FOLDER_NOT_POSSIBLE="Nuqulka faylka suurtogal ma aha"
COM_MEDIA_CREATE_FOLDER="Abuur Fayl"
COM_MEDIA_CREATE_NEW_FOLDER="Abuur Fayl Cusub"
COM_MEDIA_CREATE_NEW_FOLDER_ERROR="Khalad ayaa ka dhacay abuurista faylka."
COM_MEDIA_CREATE_NEW_FOLDER_SUCCESS="Faylka waa la abuuray."
COM_MEDIA_CURRENT_PROGRESS="Horumarka Hadda"
COM_MEDIA_DECREASE_GRID="Yaree cabbirka shabakadda"
COM_MEDIA_DELETE="Ma hubtaa inaad rabto inaad tirtirto shayga (shyaasha) la xushay? Tallaabadan waa joogto oo ma la noqon karo. Haddii aad tirtirto fayl, dhammaan waxa ku jira faylkaas waa la tirtiri doonaa si joogto ah."
COM_MEDIA_DELETE_ERROR="Khalad ayaa ka dhacay tirista shayga."
COM_MEDIA_DELETE_NOT_POSSIBLE="Ma suurtogal maahan in la tirtiro!"
COM_MEDIA_DELETE_SUCCESS="Shayga waa la tirtiray."
COM_MEDIA_DETAIL_VIEW="Muuqaal Faahfaahsan"
COM_MEDIA_DIRECTORY="Fayl"
COM_MEDIA_DIRECTORY_UP="Faylka Kor"
COM_MEDIA_DROP_FILE="Kudar fayl(asha) si aad u dirto"
COM_MEDIA_ERROR="Khalad baa dhacay."
COM_MEDIA_ERROR_BAD_REQUEST="Codsi Qalad"
COM_MEDIA_ERROR_FILE_EXISTS="Faylka hore ayuu u jiraa."
COM_MEDIA_ERROR_NOT_AUTHENTICATED="Kuma aad caddayn. Fadlan gal."
COM_MEDIA_ERROR_NOT_AUTHORIZED="Laguma ogola"
COM_MEDIA_ERROR_NOT_FOUND="Faylka ama Faylka lama helo"
COM_MEDIA_ERROR_UNABLE_TO_BROWSE_FOLDER_WARNDIRNAME="Lama booqan karo:&#160;%s. Magaca faylka waa in uu lahaado oo kaliya xuruufaha alfanumer ah oo aan lahayn meel bannaan."
COM_MEDIA_ERROR_UNABLE_TO_CREATE_FOLDER_WARNDIRNAME="Looma abuuri karo fayl. Magaca faylka waa in uu lahaado oo kaliya xuruufaha alfanumer ah oo aan lahayn meel bannaan."
COM_MEDIA_ERROR_UNABLE_TO_DELETE="Ma tirtiri karo:&#160;"
COM_MEDIA_ERROR_UNABLE_TO_DELETE_FILE_WARNFILENAME="Ma tirtiri karo:&#160;%s. Magaca faylka waa in uu lahaado oo kaliya xuruufaha alfanumer ah oo aan lahayn meel bannaan."
COM_MEDIA_ERROR_UNABLE_TO_DELETE_FOLDER_NOT_EMPTY="Ma tirtiri karo:&#160;%s. Faylku kuma jiro madhan!"
COM_MEDIA_ERROR_UNABLE_TO_DELETE_FOLDER_WARNDIRNAME="Ma awoodin in la tirtiro:&#160;%s. Magaca galka waa inuu ka koobnaadaa jilayaal alfanameerik ah oo aan lahayn meel bannaan."
COM_MEDIA_ERROR_WARNFILETOOLARGE="Faylkani aad buu u weyn yahay si loo galiyo."
COM_MEDIA_ERROR_WARNUPLOADTOOLARGE="Wadarta cabbirka kor u qaaduhu waxay ka sarreeyaa xadiga."
COM_MEDIA_FIELD_CHECK_MIME_DESC="Isticmaal MIME Magic ama Fileinfo si aad isku daydo inaad xaqiijiso faylasha. Isku day inaad naafo ka dhigto haddii aad hesho khaladaad nooca MIME ah oo aan sax ahayn."
COM_MEDIA_FIELD_CHECK_MIME_LABEL="Hubi Noocyada MIME"
COM_MEDIA_FIELD_IGNORED_EXTENSIONS_DESC="Kordhinta faylka la iska indhatirayo ee noocyada MIME iyo kor u qaadisyo xaddidan."
COM_MEDIA_FIELD_IGNORED_EXTENSIONS_LABEL="Korodhsiya La Iska Indhotiray"
COM_MEDIA_FIELD_LEGAL_EXTENSIONS_DESC="Kordhinsiya (noocyada faylasha) aad ogtahay inaad geliso (oo ku kala fogan jaafad)."
COM_MEDIA_FIELD_LEGAL_EXTENSIONS_LABEL="Korodhsiya Sharciga ah (Noocyada Faylasha)"
COM_MEDIA_FIELD_LEGAL_IMAGE_EXTENSIONS_DESC="Kordhinta sawirka (noocyada faylasha) aad ogtahay inaad geliso (oo ku kala fogan jaafad). Kuwani waxaa loo isticmaalaa si loo hubiyo madaxyada sawirka saxda ah."
COM_MEDIA_FIELD_LEGAL_IMAGE_EXTENSIONS_LABEL="Korodhsiya Sawirka Sharciga ah (Noocyada Faylasha)"
COM_MEDIA_FIELD_LEGAL_MIME_TYPES_DESC="Liiska kala qoddobi ee noocyada MIME ee sharciya oo la geyn karo."
COM_MEDIA_FIELD_LEGAL_MIME_TYPES_LABEL="Noocyada MIME Sharciga ah"
COM_MEDIA_FIELD_MAXIMUM_SIZE_DESC="Isticmaal eber si aan xad lahayn. Ogow: serverkaaga wuxuu leeyahay xadigu ugu sarreeya."
COM_MEDIA_FIELD_MAXIMUM_SIZE_LABEL="Cabbirka Ugu Badan (MB)"
COM_MEDIA_FIELD_PATH_FILE_FOLDER_DESC="Geli jidka galka faylasha ee ku xiga xididka."
COM_MEDIA_FIELD_PATH_FILE_FOLDER_LABEL="Jidka ilaa Galka Faylka"
COM_MEDIA_FIELD_PATH_IMAGE_FOLDER_DESC="Geli jidka galka sawirka ee ku xiga xididka."
COM_MEDIA_FIELD_PATH_IMAGE_FOLDER_LABEL="Jidka ilaa Galka Sawirka"
COM_MEDIA_FIELD_RESTRICT_UPLOADS_DESC="Xaddid gelinta isticmaalayaasha ka hooseeya maareeyaha illaa sawirada haddii Fileinfo ama MIME Magic aan la rakibin."
COM_MEDIA_FIELD_RESTRICT_UPLOADS_LABEL="Xaddid Gelinta"
COM_MEDIA_FILE_EXISTS_AND_OVERRIDE="%s durbadiiba wuu jiraa. Ma rabtaa inaad bedesho?"
COM_MEDIA_FILES="Faylal"
COM_MEDIA_FILESIZE="Cabbirka Faylka"
COM_MEDIA_FOLDER="Galka"
COM_MEDIA_FOLDER_NAME="Magaca Kaydka"
COM_MEDIA_FOLDERS="Kaydadka"
COM_MEDIA_IMAGE_DESCRIPTION="Sharaxa Sawirka"
COM_MEDIA_IMAGE_URL="URL-ka Sawirka"
COM_MEDIA_INCREASE_GRID="Kordhi cabbirka shabakadda"
COM_MEDIA_INSERT="Gali"
COM_MEDIA_INSERT_IMAGE="Gali Sawirka"
COM_MEDIA_MANAGE_ITEM="Maamul sheyga: %s"
COM_MEDIA_MAXIMUM_SIZE="Cabbirka Ugu Badan"
COM_MEDIA_MEDIA="Warbaahinta"
COM_MEDIA_MEDIA_DATE_CREATED="Taariikhda la sameeyay"
COM_MEDIA_MEDIA_DATE_MODIFIED="Taariikhda la bedelay"
COM_MEDIA_MEDIA_DIMENSION="Cabbirrada"
COM_MEDIA_MEDIA_EXTENSION="Kordhinta"
COM_MEDIA_MEDIA_MIME_TYPE="Nooca MIME"
COM_MEDIA_MEDIA_NAME="Magac"
COM_MEDIA_MEDIA_SIZE="Cabbirka"
COM_MEDIA_MEDIA_TYPE="Nooca"
COM_MEDIA_MOVE_FILE_ALREADY_EXISTS="Ma suurtagal ahan in faylka la dhaqaajiyo maxaa yeelay faylka bartilmaameedka horay ayuu u jiray"
COM_MEDIA_MOVE_FILE_EXTENSION_INVALID="Ma suurtagal ahan in faylka la dhaqaajiyo maxaa yeelay kordhinta waa mid aan shaqayn"
COM_MEDIA_MOVE_FILE_NOT_POSSIBLE="Ma suurtagal ahan in faylka la dhaqaajiyo"
COM_MEDIA_MOVE_FOLDER_ALREADY_EXISTS="Ma suurtagal ahan in kaydka la dhaqaajiyo maxaa yeelay kaydka bartilmaameedka horay ayuu u jiray"
COM_MEDIA_MOVE_FOLDER_EXISTING_DESTINATION_FAILED="Wejiga kaydka u guuryo bartilmaameedka jira waa la guul darraystay"
COM_MEDIA_MOVE_FOLDER_NOT_POSSIBLE="Ma suurtagal ahan in kaydka la dhaqaajiyo maxaa yeelay kaydka bartilmaameedka waa fayl mana la tirtiri karo"
COM_MEDIA_NAME="Magaca Sawirka"
COM_MEDIA_NO_IMAGES_FOUND="Sawirro lama helin"
COM_MEDIA_NOT_SET="Lama dejin"
COM_MEDIA_ORDER_ASC="Kor u kac"
COM_MEDIA_ORDER_BY="Kala saar"
COM_MEDIA_ORDER_DESC="Hoos u dhac"
COM_MEDIA_ORDER_DIRECTION="Jiho kala-saar"
COM_MEDIA_OVERALL_PROGRESS="Horumarka Guud"
COM_MEDIA_PIXEL_DIMENSIONS="Qiyaasta Pixel (b x d)"
COM_MEDIA_PLEASE_SELECT_ITEM="Fadlan xulo shayga."
COM_MEDIA_RENAME="Magaca beddel"
COM_MEDIA_RENAME_ERROR="Khalad magaca beddelida shayga."
COM_MEDIA_RENAME_SUCCESS="Shayga magac cusub."
COM_MEDIA_SEARCH="Raadi..."
COM_MEDIA_SELECT_ALL="Dhammaan xulo beddel"
COM_MEDIA_SERVER_ERROR="Khalad gudaha server-ka"
COM_MEDIA_SHARE="Wadaag faylka"
COM_MEDIA_SHARE_COPY="Nuqul ka samee golaha shaqada"
COM_MEDIA_SHARE_COPY_FAILED_ERROR="Khalad nuqul ka qaadida golaha shaqada"
COM_MEDIA_SHARE_DESC="Qof kasta oo link-ga haysta wuxuu arki karaa faylka."
COM_MEDIA_START_UPLOAD="Bilaabida Soo rarida"
COM_MEDIA_THUMBNAIL_VIEW="Fiiro Thumbnail ah"
COM_MEDIA_TITLE="Cinwaanka Sawirka"
COM_MEDIA_TOGGLE_INFO="Macluumaadka shayga beddel"
COM_MEDIA_TOGGLE_LIST_VIEW="Beddel ka muuqashada grid iyo miiska"
COM_MEDIA_TOGGLE_SELECT_ITEM="Beddel xulashada shayga"
COM_MEDIA_TOOLBAR_LABEL="Maareeyaha Warbaahinta"
COM_MEDIA_UP="Kor"
COM_MEDIA_UPLOAD="Soo rar"
COM_MEDIA_UPLOAD_COMPLETE="Soo rarid Dhameystiran"
COM_MEDIA_UPLOAD_FILE="Faylka Soo rar"
COM_MEDIA_UPLOAD_SUCCESS="Waxyaabaha waa la soo raray."

