; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_CONTENT_ARTICLE_CONTENT="Waxyaabaha ku jira"
COM_CONTENT_ARTICLE_HITS="Xidhmooyinka: %d"
COM_CONTENT_ARTICLE_INFO="Faahfaahin"
COM_CONTENT_ARTICLE_VOTE_FAILURE="Waxaad maanta qiimeeysay maqaalka!"
COM_CONTENT_ARTICLE_VOTE_SUCCESS="Waad ku mahadsan tahay inaad qiimeysay maqaalka."
COM_CONTENT_ARTICLES_TABLE_CAPTION="Maqaallo"
COM_CONTENT_AUTHOR_FILTER_LABEL="Shaandhaynta Qoraaga"
COM_CONTENT_CAPTCHA_DESC="Fadlan dhameystir hubinta amniga."
COM_CONTENT_CAPTCHA_LABEL="Captcha"
COM_CONTENT_CATEGORY="Qeybta: %s"
COM_CONTENT_CATEGORY_LIST_TABLE_CAPTION="Maqaallada ku jira qeybta %s"
COM_CONTENT_CHECKED_OUT_BY="Xiriiriyey %s"
COM_CONTENT_CONTENT_TYPE_ARTICLE="Maqaal"
COM_CONTENT_CONTENT_TYPE_CATEGORY="Qeybta Maqaallada"
COM_CONTENT_CREATED_DATE="Taariikhda la abuuray"
COM_CONTENT_CREATED_DATE_ON="Waxaa la abuuray: %s"
COM_CONTENT_EDIT_ITEM="Tafatir Maqaal"
COM_CONTENT_EDIT_PUBLISHED_ARTICLE="Maqaal la daabacay"
COM_CONTENT_EDIT_UNPUBLISHED_ARTICLE="Maqaal aan la daabicin"
COM_CONTENT_ERROR_ARTICLE_NOT_FOUND="Maqaalka lama helin"
COM_CONTENT_ERROR_LOGIN_TO_VIEW_ARTICLE="Fadlan soo gal si aad u aragto maqaalka"
COM_CONTENT_ERROR_PARENT_CATEGORY_NOT_FOUND="Qeybtuwaha lama helin"
COM_CONTENT_ERROR_PRINT_POPUP="Waan ka xunnahay, Joomla mar dambe ma taageeri donaan print_popup"
COM_CONTENT_ERROR_UNIQUE_ALIAS="Maqaal kale oo ku yaal qeybtaan ayaa leh magac la mid ah."
COM_CONTENT_ERROR_UNIQUE_ALIAS_TRASHED="Maqaal qashin ah oo qeybtaan ku jira ayaa leh magac la mid ah."
COM_CONTENT_FEED_READMORE="Akhri wax dheeraad ah &hellip;"
COM_CONTENT_FIELD_ARTICLETEXT_LABEL="Qoraalka Maqaallada"
COM_CONTENT_FIELD_FEATURED_DOWN_LABEL="Dhamee Muujinta"
COM_CONTENT_FIELD_FEATURED_UP_LABEL="Bilow Muujinta"
COM_CONTENT_FIELD_FULL_LABEL="Sawirka Qoraalka oo Dhan"
COM_CONTENT_FIELD_IMAGE_ALT_EMPTY_DESC="Sawir Qurxin - sharaxaad looma baahna"
COM_CONTENT_FIELD_IMAGE_ALT_EMPTY_LABEL="Sharaxaad La'aan"
COM_CONTENT_FIELD_IMAGE_ALT_LABEL="Sharaxaada Sawirka (Alt Text)"
COM_CONTENT_FIELD_IMAGE_CAPTION_LABEL="Qoraalka Sawirka"
COM_CONTENT_FIELD_IMAGE_CLASS_LABEL="Fasal Sawir"
COM_CONTENT_FIELD_INTRO_LABEL="Sawirka Hordhaca"
COM_CONTENT_FIELD_NOTE_LABEL="Ogeysiis"
COM_CONTENT_FIELD_URL_LINK_TEXT_LABEL="Qoraalka Xidhiidhka"
COM_CONTENT_FIELD_URLA_LABEL="Xidhiidh A"
COM_CONTENT_FIELD_URLA_LINK_TEXT_LABEL="Xidhiidhka A Qoraalka"
COM_CONTENT_FIELD_URLB_LABEL="Xidhiidh B"
COM_CONTENT_FIELD_URLB_LINK_TEXT_LABEL="Xidhiidhka B Qoraalka"
COM_CONTENT_FIELD_URLC_LABEL="Xidhiidh C"
COM_CONTENT_FIELD_URLC_LINK_TEXT_LABEL="Xidhiidhka C Qoraalka"
COM_CONTENT_FILTER_AUTHORS_BY_ME="- Waxaa abuuray aniga -"
COM_CONTENT_FILTER_SEARCH_DESC="Raadinta Sifeeyaha Mawduuca"
COM_CONTENT_FLOAT_LABEL="Sawirka Guurguura"
COM_CONTENT_FORM_EDIT_ARTICLE="Tafatir maqaal"
COM_CONTENT_FORM_FILTER_LEGEND="Sifeeyayaal"
COM_CONTENT_FORM_FILTER_SUBMIT="Sifee"
COM_CONTENT_HEADING_TITLE="Cinwaanka"
COM_CONTENT_HITS_FILTER_LABEL="Shaandhaynta Garaac"
COM_CONTENT_IMAGES_AND_URLS="Sawirro iyo Xiriiriyo"
COM_CONTENT_INTROTEXT="Qodobku waa inuu lahaadaa waxyaabo."
COM_CONTENT_INVALID_RATING="Qiimaynta Qodobka: Qiimayn aan Sax ahayn: %s"
COM_CONTENT_LAST_UPDATED="Waxa Ugu Dambeeyey La Cusbooneysiiyey: %s"
COM_CONTENT_METADATA="Xogta Metada"
COM_CONTENT_MODAL_FILTER_SEARCH_DESC="Raadin cinwaanka iyo magaca kale. Ku bilow ID: ama QORAA: si aad u raadsato aqoonsiga maqaalka ama qoraaga maqaalka."
COM_CONTENT_MODAL_FILTER_SEARCH_LABEL="Raadi Maqaallada"
COM_CONTENT_MODIFIED_DATE="Taariikhda wax-ka-beddelka"
COM_CONTENT_MONTH="Bisha"
COM_CONTENT_MORE_ARTICLES="Maqaallo Dheeraad &hellip;"
COM_CONTENT_NEW_ARTICLE="Maqaal Cusub"
COM_CONTENT_NO_ARTICLES="Waxaa jira maqaallo la'aan qaybtan. Haddii qaanada hoosaadka ay ku soo bandhigto boggan, waxaa suuragal ah inay leeyihiin maqaallo."
COM_CONTENT_NUM_ITEMS="Tirada Maqaallada:"
COM_CONTENT_ON_NEW_CONTENT="Maqaal cusub ayaa ay soo gudbisay '%1$s' oo cinwaankiisu yahay '%2$s'."
COM_CONTENT_ORDERING="Dalbashada:<br>Maqaallada cusub guud ahaanba waxaa lagu daraa booska ugu horreeya ee qaybta. Dalbashada waxaa lagu beddeli karaa dhinaca dambe."
COM_CONTENT_PAGEBREAK_DOC_TITLE="Jebinta Bogga"
COM_CONTENT_PAGEBREAK_INSERT_BUTTON="Geli Jebinta Bogga"
COM_CONTENT_PAGEBREAK_TITLE="Cinwaanka Bogga:"
COM_CONTENT_PAGEBREAK_TOC="Cinwaanka Tusmada:"
COM_CONTENT_PARENT="Qaybta Waalidka: %s"
COM_CONTENT_PUBLISHED_DATE="Taariikhda Daabaca"
COM_CONTENT_PUBLISHED_DATE_ON="La Daabacay: %s"
COM_CONTENT_PUBLISHING="Daabicid"
COM_CONTENT_RATINGS="Qiimeynta"
COM_CONTENT_RATINGS_COUNT="Qiimeynta: %s"
COM_CONTENT_READ_MORE="Akhri wax dheeraad ah &hellip;"
COM_CONTENT_READ_MORE_TITLE="Akhri wax dheeraad ah: %s"
COM_CONTENT_REGISTER_TO_READ_MORE="Isdiiwaangeli si aad wax dheeraad ah u akhriso &hellip;"
COM_CONTENT_RUN_TRANSITION="Orod Kala-guurka"
COM_CONTENT_SAVE_SUCCESS="Maqaal siibmay."
COM_CONTENT_SAVE_WARNING="Magac isku mid ah ayaa jiray sidaa darteed lambar ayaa lagu daray dhamaadka. Haddii aad dooneyso inaad bedesho magac-u-dhigga, fadlan la xiriir maamule goobta"
COM_CONTENT_SELECT_AN_ARTICLE="Xulo Maqaal"
COM_CONTENT_STATE="Gobol"
COM_CONTENT_SUBMIT_SAVE_SUCCESS="Maqaal la gudbiyay."
COM_CONTENT_TITLE_FILTER_LABEL="Magac-u-dhigga Filter"
COM_CONTENT_TRANSITION="Kala-guur"
COM_CONTENT_VOTES="Codee"
COM_CONTENT_VOTES_COUNT="Codee: %s"
COM_CONTENT_WORKFLOW="Habka Socodka Shaqada"
COM_CONTENT_WORKFLOW_STAGE="Heerka Sicirada Shaqada"
COM_CONTENT_WRITTEN_BY="Qoray: %s"

