; Joomla! Project
; (C) 2013 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_AJAX="Wajiga Ajax"
COM_AJAX_FILE_NOT_EXISTS="Faylka ku yaal %s ma jiro."
COM_AJAX_METHOD_NOT_EXISTS="Habka %s ma jiro."
COM_AJAX_MODULE_NOT_ACCESSIBLE="Module %s lama daabacin, ma haysatid ogolaansho, ama looma qoondeyn in alaabadani hadda."
COM_AJAX_SPECIFY_FORMAT="Fadlan ku caddee qaab jawaab sax ah, oo aan ahayn mid HTML, sida json, raw, debug, iwm."
COM_AJAX_TEMPLATE_NOT_ACCESSIBLE="Template %s uma qoondeysan alaabadani hadda."
COM_AJAX_XML_DESCRIPTION="Wajiga Ajax oo la ballaadhin karo ee Joomla."

