; Joomla! Project
; (C) 2011 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

FINDER_CLI="Raadiyaha Casriga ah ee INDEXER"
FINDER_CLI_BATCH_COMPLETE=" * Hadal goos goos ah oo la shaqeeyay %d ah daqiiqoo %s ah."
FINDER_CLI_BATCH_CONTINUING=" * Sii wad socodka goos gooska ..."
FINDER_CLI_BATCH_PAUSING=" * Jooji socodka %d ilbiriqsi ..."
FINDER_CLI_FILTER_RESTORE_WARNING="Digniin: Ma helin waa dambiil %s/%s ee shaandheynta %s"
FINDER_CLI_INDEX_PURGE="Nadiifi tusmada"
FINDER_CLI_INDEX_PURGE_FAILED="- nadiifinta tusmada ma ay guulaysan."
FINDER_CLI_INDEX_PURGE_SUCCESS="- nadiifinta tusmada waa guuleysatay"
FINDER_CLI_PEAK_MEMORY_USAGE="Isticmaalka xusuusta ugu sarreeya: %s bytes"
FINDER_CLI_PROCESS_COMPLETE="Waqtiga Socodka Guud: %s ilbiriqsiyo."
FINDER_CLI_RESTORE_FILTER_COMPLETED="- tirada shaandhaynta la soo ceshay: %s"
FINDER_CLI_RESTORE_FILTERS="Soo celinta shaandheyn"
FINDER_CLI_SAVE_FILTER_COMPLETED="- tirada shaandheynteyda kaydsan: %s"
FINDER_CLI_SAVE_FILTERS="Kaydinta shaandheyn"
FINDER_CLI_SETTING_UP_PLUGINS="Abuurista kaabayaal Raadiyaha Casriga ah"
FINDER_CLI_SETUP_ITEMS="Abuuri %d shay ee %s daqiiqadood."
FINDER_CLI_SKIPPING_PAUSE_LOW_BATCH_PROCESSING_TIME=" * Joojinta joojinta, maadaama goor hore uu lahaa habsocod aad u hooseeya (%ss < %ds)"
FINDER_CLI_STARTING_INDEXER="Bilowga Indexer"

