; Joomla! Project
; (C) 2014 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

LIB_PHPASS="phpass"
LIB_PHPASS_XML_DESCRIPTION="phpass waa qaab barnaamijyada PHP ee loogu talagalay kaydinta furaha sirta ah ee la qaadi karo. Habka la doorbiday (ugu aaminka san) ee phpass uu taageero waa bcrypt oo ah qaabka OpenBSD (loo yaqaan PHP sida CRYPT_BLOWFISH), iyadoo dib loogu laabto furaha sirta ah ee BSDI ee ku saleysan DES (loo yaqaan PHP sida CRYPT_EXT_DES) iyo ugu dambeyntii dib ugu laabashada habka kaydinta furaha sirta ah ee ku saleysan MD5 oo leh tirada wareegga beddelka ah oo uu fuliyo phpass lafteeda."

