; Joomla! Project
; (C) 2010 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_STATS="Tirakoob"
MOD_STATS_LAYOUT_DEFAULT="Dhaqameed"
MOD_STATS_XML_DESCRIPTION="Qaabka Module-ka Tirakoobku wuxuu muujinayaa macluumaad ku saabsan rakibitaankaaga serverka oo ay weheliso tirakoobka isticmaalayaasha bogga iyo tirada Qoraallada ku jira xogtaada."

