; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_WRAPPER="Xidhmo"  
MOD_WRAPPER_FIELD_ADD_LABEL="Si otomaatig ah ku dar http://"  
MOD_WRAPPER_FIELD_AUTOHEIGHT_LABEL="Dhererka otomaatiga ah"  
MOD_WRAPPER_FIELD_HEIGHT_LABEL="Dherer"  
MOD_WRAPPER_FIELD_LAZYLOADING_LABEL="Shaqeynta daxalka"  
MOD_WRAPPER_FIELD_TARGET_LABEL="Magaca Bartilmaameedka"  
MOD_WRAPPER_FIELD_URL_LABEL="URL"  
MOD_WRAPPER_FIELD_WIDTH_LABEL="Ballac"  
MOD_WRAPPER_NO_IFRAMES="Ma jiro iframes"  
MOD_WRAPPER_XML_DESCRIPTION="Qaabkan wuxuu muujiyaa daaqad iframe ah oo goob la cayimay ku yaal."

