; Joomla! Project
; (C) 2006 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_BREADCRUMBS="Burambur"
MOD_BREADCRUMBS_FIELD_HOMETEXT_DESC="Qoraalkan waxaa lagu soo bandhigi doonaa sidii gelitaanka guriga. Haddii beerta banaan tahay, waxay isticmaalaysaa qiimaha caadiga ah ee ku jira feylka luqadda mod_breadcrumbs.ini."
MOD_BREADCRUMBS_FIELD_HOMETEXT_LABEL="Qoraalka Gelitaanka Guriga"
MOD_BREADCRUMBS_FIELD_SHOWHERE_LABEL="&quot;Waxaad joogtaa halkaan&quot;"
MOD_BREADCRUMBS_FIELD_SHOWHOME_LABEL="Guri"
MOD_BREADCRUMBS_FIELD_SHOWLAST_LABEL="Dambe"
MOD_BREADCRUMBS_HERE="Waxaad joogtaa halkan: "
MOD_BREADCRUMBS_HOME="Guri"
MOD_BREADCRUMBS_XML_DESCRIPTION="Qeybtaan waxay soo bandhigaysaa Buramburka."

