; Joomla! Project
; (C) 2010 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_ARTICLES_ARCHIVE="Maqaallada - Keydin"
MOD_ARTICLES_ARCHIVE_LAYOUT_DEFAULT="Caadi"
MOD_ARTICLES_ARCHIVE_XML_DESCRIPTION="Qaabkaani wuxuu soo bandhigayaa liis bisha kalandarka ee ay ku jiraan Maqaallada Keydin. Marka aad meesha kadhigtid maqaal xaaladda Keydin, liiskan si toos ah ayaa loo soo saari doonaa."

