; Joomla! Project
; (C) 2010 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_LANGUAGES="Beddelka Luqadda"
MOD_LANGUAGES_DESC="Dooro luqaddaada"
MOD_LANGUAGES_FIELD_ACTIVE_LABEL="Luqadda Firfircoon"
MOD_LANGUAGES_FIELD_DROPDOWN_IMAGE_LABEL="Isticmaal Calamo Si Aad Ugu Beddelato"
MOD_LANGUAGES_FIELD_DROPDOWN_LABEL="Isticmaal Beddelka"
MOD_LANGUAGES_FIELD_FOOTER_LABEL="Qoraalka Dabagalka"
MOD_LANGUAGES_FIELD_FULL_NAME_LABEL="Magacyada Dhamaystiran ee Luqadda"
MOD_LANGUAGES_FIELD_HEADER_LABEL="Qoraalka Hore"
MOD_LANGUAGES_FIELD_INLINE_LABEL="Muuqaal Toosan"
MOD_LANGUAGES_FIELD_USEIMAGE_LABEL="Isticmaal Calamo Sawir ah"
MOD_LANGUAGES_XML_DESCRIPTION="Qaybtani waxay ku soo bandhigaysaa beddelka luqadda ee websaydhkaaga luqadaha nuxurka ee la heli karo."

