; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_WHOSONLINE="Yaa ku jira khadka tooska ah"
MOD_WHOSONLINE_FIELD_FILTER_GROUPS_DESC="Dooro inaad ku hagaajiso kooxaha isticmaalaha adeegsanaya"
MOD_WHOSONLINE_FIELD_FILTER_GROUPS_LABEL="Sifee Kooxda"
MOD_WHOSONLINE_FIELD_VALUE_BOTH="Labadoodaba"
MOD_WHOSONLINE_FIELD_VALUE_NAMES="Magacyada isticmaalayaasha"
MOD_WHOSONLINE_FIELD_VALUE_NUMBER="# ee Martida / Isticmaalayaasha"
MOD_WHOSONLINE_GUESTS="%s&#160;marti"
MOD_WHOSONLINE_GUESTS_0="wax marti ah ma jiro"
MOD_WHOSONLINE_GUESTS_1="marti kaliya"
MOD_WHOSONLINE_MEMBERS="%s&#160;xubno"
MOD_WHOSONLINE_MEMBERS_0="wax xubno ah ma jiro"
MOD_WHOSONLINE_MEMBERS_1="xubin kaliya"
MOD_WHOSONLINE_NO_SESSION_METADATA="Ma suurtagal ahan in la soo bandhigo macluumaadka isticmaaleyaasha khadka tooska ah waqtigan."
MOD_WHOSONLINE_SAME_GROUP_MESSAGE="Liiska Isticmaalayaasha ku jira kooxahaaga isticmaalaha ama kooxaha hoosaadka kooxahaaga isticmaalaha"
MOD_WHOSONLINE_SHOWMODE_LABEL="Soo bandhig"
MOD_WHOSONLINE_XML_DESCRIPTION="Qeybta Yaa ku jira khadka tooska ah waxay soo bandhigtaa tirada Isticmaalayaasha Aan La Garneyn (sida Martida) iyo Isticmaalayaasha Diiwaangashan (kuwa gala ee hadda socda bogga internetka)."
MOD_WHOSONLINE_WE_HAVE="Waxaan haynaa %1$s iyo %2$s khadka tooska ah"

