; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_RANDOM_IMAGE="Sawir aan kala sooc lahayn"
MOD_RANDOM_IMAGE_FIELD_FOLDER_LABEL="Koofiyad Sawir"
MOD_RANDOM_IMAGE_FIELD_HEIGHT_LABEL="Dherer (px)"
MOD_RANDOM_IMAGE_FIELD_LINK_LABEL="Xidhiidh"
MOD_RANDOM_IMAGE_FIELD_TYPE_LABEL="Nooca Sawirka"
MOD_RANDOM_IMAGE_FIELD_WIDTH_LABEL="Balaadh (px)"
MOD_RANDOM_IMAGE_NO_IMAGES="Sawiro Ma jiraan"
MOD_RANDOM_IMAGE_XML_DESCRIPTION="Qaabkaani wuxuu soo bandhigayaa sawir aan kala sooc lahayn oo ka socda faylka aad dooratay."

