; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_LOGIN="Gelitaanka"
MOD_LOGIN_FIELD_GREETING_LABEL="Salaan"
MOD_LOGIN_FIELD_LOGIN_REDIRECTURL_DESC="Haddii wax menu ah aan la dooran, isticmaalayaashu waxay ku sii joogayaan isla bogga ka dib gelitaanka."
MOD_LOGIN_FIELD_LOGIN_REDIRECTURL_LABEL="Bogga Loo Celiyo Kadib Gelitaanka"
MOD_LOGIN_FIELD_LOGOUT_REDIRECTURL_DESC="Haddii wax menu ah aan la dooran, isticmaalayaashu waxay ku sii joogayaan isla bogga ka dib bixitaanka."
MOD_LOGIN_FIELD_LOGOUT_REDIRECTURL_LABEL="Bogga Loo Celiyo Kadib Bixitaanka"
MOD_LOGIN_FIELD_NAME_LABEL="Magaca/Magaca isticmaalaha"
MOD_LOGIN_FIELD_POST_TEXT_LABEL="Qoraal ka dambeeya"
MOD_LOGIN_FIELD_PRE_TEXT_LABEL="Qoraal ka hor"
MOD_LOGIN_FIELD_PROFILE_LABEL="Xidhiidhka Profileka"
MOD_LOGIN_FIELD_REGISTRATION_MENU_LABEL="Bogga Diiwangelinta"
MOD_LOGIN_FIELD_USETEXT_LABEL="Tus Calaamado"
MOD_LOGIN_FORGOT_YOUR_PASSWORD="Illowday furahaaga?"
MOD_LOGIN_FORGOT_YOUR_USERNAME="Illowday magacaaga?"
MOD_LOGIN_HINAME="Salaan %s,"
MOD_LOGIN_PROFILE="Eeg Profile"
MOD_LOGIN_REGISTER="Samee koonto"
MOD_LOGIN_REMEMBER_ME="Igu xasuuso"
MOD_LOGIN_VALUE_ICONS="Calaamado"
MOD_LOGIN_VALUE_NAME="Magaca"
MOD_LOGIN_VALUE_TEXT="Qoraal"
MOD_LOGIN_VALUE_USERNAME="Magaca isticmaalaha"
MOD_LOGIN_XML_DESCRIPTION="Moduulkan wuxuu soo bandhigayaa foom gelitaan magaca isticmaalaha iyo furaha sirta ah. Sidoo kale waxa uu soo bandhigayaa xiriir si loogu soo celiyo furaha sirta ah ee la illoobay. Haddii diiwaangelinta isticmaalaha la daaray (Users &rarr; Manage &rarr; Options), xiriir kale ayaa la soo bandhigi doonaa si loogu ogolaado isticmaalayaasha inay is-diiwaangeliyaan."

