; Joomla! Project
; (C) 2010 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_ARTICLES_CATEGORY="Maqaallo - Qeyb (Dhaxalgal)"
MOD_ARTICLES_CATEGORY_FIELD_ARTICLEGROUPING_LABEL="Kooxaynta Maqaallo"
MOD_ARTICLES_CATEGORY_FIELD_ARTICLEGROUPINGDIR_LABEL="Jiho Kooxaynta"
MOD_ARTICLES_CATEGORY_FIELD_ARTICLEORDERING_LABEL="Gees Maqaal oo la Dalbo"
MOD_ARTICLES_CATEGORY_FIELD_ARTICLEORDERINGDIR_LABEL="Jiho Dalbo"
MOD_ARTICLES_CATEGORY_FIELD_AUTHOR_LABEL="Qorayaasha"
MOD_ARTICLES_CATEGORY_FIELD_AUTHORALIAS_LABEL="Magacyada Magac-u-yaalka"
MOD_ARTICLES_CATEGORY_FIELD_AUTHORALIASFILTERING_LABEL="Nooca Sifeynta Magac-u-yaalka"
MOD_ARTICLES_CATEGORY_FIELD_AUTHORFILTERING_LABEL="Nooca Sifeynta Qoraaga"
MOD_ARTICLES_CATEGORY_FIELD_CATDEPTH_LABEL="Qoto Dheerida Qeybta"
MOD_ARTICLES_CATEGORY_FIELD_CATFILTERINGTYPE_LABEL="Nooca Sifeynta Qeybta"
MOD_ARTICLES_CATEGORY_FIELD_COUNT_DESC="Tirada shay-yada la soo bandhigayo. Qiimaha caadiga ah ee 0 wuxuu soo bandhigi doonaa dhammaan maqaallada."
MOD_ARTICLES_CATEGORY_FIELD_COUNT_LABEL="Tirada"
MOD_ARTICLES_CATEGORY_FIELD_DATEFIELD_LABEL="Gees Taariikhda"
MOD_ARTICLES_CATEGORY_FIELD_DATEFIELDFORMAT_DESC="Fadlan geli qaab taariikheed sax ah. Eeg: https://php.net/date macluumaadka qaabka."
MOD_ARTICLES_CATEGORY_FIELD_DATEFIELDFORMAT_LABEL="Qaabka Taariikhda"
MOD_ARTICLES_CATEGORY_FIELD_DATEFILTERING_LABEL="Sifeynta Taariikhda"
MOD_ARTICLES_CATEGORY_FIELD_DATEGROUPINGFIELD_DESC="Xulo geeska taariikhda ee ay tahay inaad u isticmaasho kooxaynta taariikhda."
MOD_ARTICLES_CATEGORY_FIELD_DATEGROUPINGFIELD_LABEL="Gees Kooxaynta Taariikhda"
MOD_ARTICLES_CATEGORY_FIELD_DATERANGEFIELD_LABEL="Geesa Kaalmo Taariikheed"
MOD_ARTICLES_CATEGORY_FIELD_ENDDATE_LABEL="Ilaa Taariikhda"
MOD_ARTICLES_CATEGORY_FIELD_EXCLUDEDARTICLES_LABEL="Aqoonsiga Maqaallada Laga Saarayo"
MOD_ARTICLES_CATEGORY_FIELD_GROUP_DISPLAY_LABEL="Xulashooyinka Muuqaalka"
MOD_ARTICLES_CATEGORY_FIELD_GROUP_FILTERING_LABEL="Xulashooyinka Sifeynta"
MOD_ARTICLES_CATEGORY_FIELD_GROUP_GROUPING_LABEL="Xulashooyinka Kooxaynta"
MOD_ARTICLES_CATEGORY_FIELD_GROUP_ORDERING_LABEL="Xulashada Dalabka"
MOD_ARTICLES_CATEGORY_FIELD_INTROTEXTLIMIT_LABEL="Xadka Qoraalka Hordhaca ah (xarfaha)"
MOD_ARTICLES_CATEGORY_FIELD_LINKTITLES_LABEL="Cinwaanada La Xiriiriyay"
MOD_ARTICLES_CATEGORY_FIELD_MODE_DESC="Fadlan dooro habka aad rabto inaad isticmaasho. Haddii Habka Caadiga ah la doorto, markaa u qaabee moduleka wuxuuna soo bandhigi doonaa liiska maqaalada joogtada ah ee ku yaala shayga menu ee aad u qorshaysay moduleka. Haddii Habka Firfircoon la doorto, waxaad weli u qaabayn kartaa moduleka si caadi ah, si kastaba ha ahaatee hadda fursada Qaybta lama isticmaali doono. Taas bedelkeeda, moduleka wuxuu si firfircoon u ogaan doonaa haddii aad ku jirto muuqalka Qaybta wuxuuna soo bandhigi doonaa liiska maqaalada ku jira Qaybtaas. Marka Habka Firfircoon la doorto, waxaa fiican inaad ka tagto moduleka in lagu dejiyo inuu soo bandhigo dhammaan bogagga, maadaama uu go'aansanayo inuu soo bandhigo wax walba oo firfircoon."
MOD_ARTICLES_CATEGORY_FIELD_MODE_LABEL="Habka"
MOD_ARTICLES_CATEGORY_FIELD_MONTHYEARFORMAT_DESC="Fadlan geli qaab taariikh sax ah. Fiiri: https://php.net/date si aad u hesho macluumaadka qaabaynta."
MOD_ARTICLES_CATEGORY_FIELD_MONTHYEARFORMAT_LABEL="Qaabka Muujinta Bisha iyo Sannadka"
MOD_ARTICLES_CATEGORY_FIELD_RELATIVEDATE_LABEL="Taariikhda Qaraabada"
MOD_ARTICLES_CATEGORY_FIELD_SHOWCHILDCATEGORYARTICLES_LABEL="Maqaalada Qaybta Hoosaadka"
MOD_ARTICLES_CATEGORY_FIELD_SHOWFEATURED_LABEL="Maqaalada Muuqata"
MOD_ARTICLES_CATEGORY_FIELD_SHOWHITS_LABEL="Tirakoobka"
MOD_ARTICLES_CATEGORY_FIELD_SHOWINTROTEXT_LABEL="Qoraalka Hordhaca ah"
MOD_ARTICLES_CATEGORY_FIELD_SHOWONARTICLEPAGE_DESC="Dooro inaad muujiso ama qariso Liiska Maqaalada ee Bogagga Maqaalada. Tani waxay la micno tahay in moduleka uu kaliya uu isu soo bandhigayo si firfircoon Bogagga Qaybaha."
MOD_ARTICLES_CATEGORY_FIELD_SHOWONARTICLEPAGE_LABEL="Muuji Bogga Maqaalka"
MOD_ARTICLES_CATEGORY_FIELD_STARTDATE_LABEL="Xadka Taariikhda Bilowga"
MOD_ARTICLES_CATEGORY_OPTION_ASCENDING_VALUE="Sare u Kac"
MOD_ARTICLES_CATEGORY_OPTION_CREATED_VALUE="Taariikhda La Abuuray"
MOD_ARTICLES_CATEGORY_OPTION_DATERANGE_VALUE="Xadka Taariikhda"
MOD_ARTICLES_CATEGORY_OPTION_DESCENDING_VALUE="Hoos u Dhac"
MOD_ARTICLES_CATEGORY_OPTION_DYNAMIC_VALUE="Firfircoon"
MOD_ARTICLES_CATEGORY_OPTION_EXCLUDE_VALUE="Ka Reeb"
MOD_ARTICLES_CATEGORY_OPTION_EXCLUSIVE_VALUE="Gooni ah"
MOD_ARTICLES_CATEGORY_OPTION_FINISHPUBLISHING_VALUE="Taariikhda Dhammaadka Daabacaadda"
MOD_ARTICLES_CATEGORY_OPTION_HITS_VALUE="Tirakoob"
MOD_ARTICLES_CATEGORY_OPTION_ID_VALUE="ID"
MOD_ARTICLES_CATEGORY_OPTION_INCLUDE_VALUE="Ku dar"
MOD_ARTICLES_CATEGORY_OPTION_INCLUSIVE_VALUE="Ku darid"
MOD_ARTICLES_CATEGORY_OPTION_MODIFIED_VALUE="Taariikhda La Bedelay"
MOD_ARTICLES_CATEGORY_OPTION_MONTHYEAR_VALUE="Bisha iyo Sannadka"
MOD_ARTICLES_CATEGORY_OPTION_NORMAL_VALUE="Caadi"
MOD_ARTICLES_CATEGORY_OPTION_OFF_VALUE="Off"
MOD_ARTICLES_CATEGORY_OPTION_ONLYFEATURED_VALUE="Kaliya"
MOD_ARTICLES_CATEGORY_OPTION_ORDERING_VALUE="Kala-saar Qormooyinka"
MOD_ARTICLES_CATEGORY_OPTION_ORDERINGFEATURED_VALUE="Kala-saar Maqaallada Muhiimka ah"
MOD_ARTICLES_CATEGORY_OPTION_RANDOM_VALUE="Si Aan Kala Sooc Lahayn"
MOD_ARTICLES_CATEGORY_OPTION_RATING_VALUE="Qiimeyn"
MOD_ARTICLES_CATEGORY_OPTION_RELATIVEDAY_VALUE="Taariikhda Isbarbardhiga"
MOD_ARTICLES_CATEGORY_OPTION_STARTPUBLISHING_VALUE="Bilow Waqtiga Daabacaadda"
MOD_ARTICLES_CATEGORY_OPTION_VOTE_VALUE="Cod"
MOD_ARTICLES_CATEGORY_OPTION_YEAR_VALUE="Sanad"
MOD_ARTICLES_CATEGORY_READ_MORE="Akhri: "
MOD_ARTICLES_CATEGORY_READ_MORE_TITLE="Akhri &hellip;"
MOD_ARTICLES_CATEGORY_REGISTER_TO_READ_MORE="Isdiiwaangeli si aad wax badan u akhriso"
MOD_ARTICLES_CATEGORY_UNTAGGED="Aan Summad Lahayn"
MOD_ARTICLES_CATEGORY_XML_DESCRIPTION="Qaabkan wuxuu soo bandhigayaa liiska maqaalado ku jira mid ama ka badan qeybaha. Qaabkan waxaa ka horreeya qaabka \"Maqaallada\"."

