; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_ARTICLES_ARCHIVE="Maqaallo - La Keydiyay"
MOD_ARTICLES_ARCHIVE_DATE="%1$s, %2$s"
MOD_ARTICLES_ARCHIVE_FIELD_COUNT_LABEL="# Bilood"
MOD_ARTICLES_ARCHIVE_XML_DESCRIPTION="Qaabkan wuxuu soo bandhigayaa liiska bilaha taariikhda ee leh maqaallo la keydiyay. Kadib markaad beddesho xaaladda maqaal si loo kaydiyo, liiskan si toos ah ayaa loo abuuri doonaa."

