; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_STATS="Tirakoob"
MOD_STATS_ARTICLES="Maqaallo"
MOD_STATS_ARTICLES_VIEW_HITS="Maqaallo Aragtida Hits"
MOD_STATS_CACHING="Kaydinta"
MOD_STATS_FIELD_COUNTER_LABEL="Tirinta Hit"
MOD_STATS_FIELD_INCREASECOUNTER_LABEL="Kordhi Tirinta"
MOD_STATS_FIELD_SERVERINFO_LABEL="Macluumaadka Serverka"
MOD_STATS_FIELD_SITEINFO_LABEL="Macluumaadka Goobta"
MOD_STATS_GZIP="Gzip"
MOD_STATS_OS="OS"
MOD_STATS_PHP="PHP"
MOD_STATS_TIME="Waqti"
MOD_STATS_USERS="Isticmaalayaasha"
MOD_STATS_WEBLINKS="Xiriirada Webka"
MOD_STATS_XML_DESCRIPTION="Qaybta Tirakoobku waxay soo bandhigeysaa macluumaadka ku saabsan rakibaadda serverkaaga oo ay la socoto tirakoobyada isticmaalayaasha bogga iyo tirada Maqaalada ee kaydkaaga."

