; Joomla! Project
; (C) 2010 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_ARTICLES_CATEGORY="Maqaallada - Qaybta (Dhaxaltooyo)"
MOD_ARTICLES_CATEGORY_LAYOUT_DEFAULT="Default"
MOD_ARTICLES_CATEGORY_XML_DESCRIPTION="Modulkan wuxuu soo bandhigayaa liis maqaal ah oo ka yimid hal ama in ka badan qaybaha. Modulkan waxaa ka talinaya module-ka \"Maqaallada\"."

