; Joomla! Project
; (C) 2010 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_ARTICLES_NEWS="Maqaallada - Warbixin (Qadiimi)"
MOD_ARTICLES_NEWS_FIELD_EXCLUDE_CURRENT_LABEL="Ka Reeb Maqaalka Hadda"
MOD_ARTICLES_NEWS_FIELD_FEATURED_LABEL="Maqaallada La Muujiyay"
MOD_ARTICLES_NEWS_FIELD_IMAGES_ARTICLE_LABEL="Tus Sawirka Hordhac/Fullan"
MOD_ARTICLES_NEWS_FIELD_IMAGES_DESC="Tus sawirada ku dhex jira qoraalka maqaalka."
MOD_ARTICLES_NEWS_FIELD_IMAGES_LABEL="Tus Sawirada Maqaalka"
MOD_ARTICLES_NEWS_FIELD_ITEMS_LABEL="Tirada Maqaallada"
MOD_ARTICLES_NEWS_FIELD_LINKTITLE_LABEL="Cinwaannada Xiranta"
MOD_ARTICLES_NEWS_FIELD_ORDERING_CREATED_DATE="Taariikhda Abuurka"
MOD_ARTICLES_NEWS_FIELD_ORDERING_LABEL="Kala Saar Natiijooyinka"
MOD_ARTICLES_NEWS_FIELD_ORDERING_MODIFIED_DATE="Taariikhda Wax Ka Bedelka"
MOD_ARTICLES_NEWS_FIELD_ORDERING_ORDERING="Kawararid"
MOD_ARTICLES_NEWS_FIELD_ORDERING_PUBLISHED_DATE="Taariikhda La Daabacay"
MOD_ARTICLES_NEWS_FIELD_ORDERING_RANDOM="Kale"
MOD_ARTICLES_NEWS_FIELD_READMORE_LABEL="'Sii Akhri &hellip;' Isku xirka"
MOD_ARTICLES_NEWS_FIELD_SEPARATOR_LABEL="Kala-sooca Ugu Dambeeya"
MOD_ARTICLES_NEWS_FIELD_SHOWINTROTEXT_LABEL="Qoraalka Hordhaca"
MOD_ARTICLES_NEWS_FIELD_TITLE_LABEL="Cinwaanka Maqaalka"
MOD_ARTICLES_NEWS_FIELD_TRIGGEREVENTS_LABEL="Kicin Dhacdoyinka Plugin"
MOD_ARTICLES_NEWS_OPTION_FULLIMAGE="Sawirka Dhammeystiran"
MOD_ARTICLES_NEWS_OPTION_INTROIMAGE="Sawirka Hordhaca"
MOD_ARTICLES_NEWS_READMORE="Sii Akhri &hellip;"
MOD_ARTICLES_NEWS_READMORE_REGISTER="Isdiiwaangeli si aad u Akhrido Faahfaahin Dheeraad ah"
MOD_ARTICLES_NEWS_TITLE_HEADING="Heerka Cinwaanka"
MOD_ARTICLES_NEWS_VALUE_ONLY_SHOW_FEATURED="Kaliya tus Maqaallada La Muujiyay"
MOD_ARTICLES_NEWS_XML_DESCRIPTION="Qaabka Maqaallada Wararka wuxuu soo bandhigi doonaa tiro go'an oo Maqaallo ah oo ka socda Qeyb cayiman ama dhexdhexaadyo Qeybo ah. Qaabkan waxaa ka sarreeya module-ka \"Maqaallada\"."

