; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_ARTICLES_LATEST="Qoraallada - Ugu Danbeeyay (Hore)"
MOD_LATEST_NEWS_FIELD_AUTHOR_LABEL="Waxaa Abuuray Qoraha/Qorayaasha"
MOD_LATEST_NEWS_FIELD_COUNT_LABEL="Qoraallo La Tusinayo"
MOD_LATEST_NEWS_FIELD_FEATURED_LABEL="Qoraallada Muhiimka ah"
MOD_LATEST_NEWS_FIELD_ORDERING_LABEL="Amar"
MOD_LATEST_NEWS_FIELD_USER_LABEL="Qorayaasha"
MOD_LATEST_NEWS_VALUE_ADDED_BY_ME="Waxaan ku daray ama wax ka beddelay aniga"
MOD_LATEST_NEWS_VALUE_ANYONE="Qof kasta"
MOD_LATEST_NEWS_VALUE_CREATED_BY="Waxaa Abuuray"
MOD_LATEST_NEWS_VALUE_NOTADDED_BY_ME="Ma aysan dhejin ama wax ka badalin aniga"
MOD_LATEST_NEWS_VALUE_ONLY_SHOW_FEATURED="Kaliya tus Qoraallada Muhiimka ah"
MOD_LATEST_NEWS_VALUE_RECENT_ADDED="Kuwa dhawaan la dhejiyay ugu horreeya"
MOD_LATEST_NEWS_VALUE_RECENT_MODIFIED="Kuwa dhawaan wax laga beddelay ugu horreeya"
MOD_LATEST_NEWS_VALUE_RECENT_PUBLISHED="Kuwa dhawaan la qoray ugu horreeya"
MOD_LATEST_NEWS_VALUE_RECENT_RAND="Qoraallo Random ah"
MOD_LATEST_NEWS_VALUE_RECENT_TOUCHED="Kuwa dhawaan la tacaalay ugu horreeya"
MOD_LATEST_NEWS_XML_DESCRIPTION="Habkani wuxuu soo bandhigayaa liiska Qoraallada ugu dhawaan la qoray iyo hadda jirta. Habkani waxaa ka sii sareeya \"Qoraallada\" moduleka."

