; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_RELATED_FIELD_MAX_DESC="Tirada ugu badnaan ee maqaalada la xiriira ah ee la soo bandhigi karo (caadi ahaan waa 5)."
MOD_RELATED_FIELD_MAX_LABEL="Maqaalada Ugu Badnaan"
MOD_RELATED_FIELD_SHOWDATE_LABEL="Taariikhda"
MOD_RELATED_ITEMS="Maqaalada - Kuwan La Xiriira"
MOD_RELATED_XML_DESCRIPTION="Mashiinkani wuxuu soo bandhigayaa Maqaallada kale ee la xiriira midka la daawanayo. Xiriirradan waxaa lagu aasaasa by Keyword-ka. <br> Dhammaan keyword-yada maqaalka hadda waxaa ka la baaraa dhammaan keyword-yada dhammaan maqaallada la daabaco. Tusaale ahaan, waad yeelan kartaa maqaal ku saabsan &quot;Tarminta Baqarada&quot; iyo mid kale oo ku saabsan &quot;Gacanta Sare Kabka Madaw&quot;. Haddii aad ku darto keyword &quot;baqaro&quot; labada maqaal, markaa qaybta Alaabada La Xiriira waxay liis garaysaa maqaalka &quot;Tarminta Baqarada&quot; markaad daawanayso &quot;Gacanta Sare Kabka Madaw&quot; iyo sida kale."

