; Joomla! Project
; (C) 2010 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_WHOSONLINE="Yaa Online"
MOD_WHOSONLINE_LAYOUT_DEFAULT="Caadi"
MOD_WHOSONLINE_LAYOUT_DISABLED="Aan Shaqayn"
MOD_WHOSONLINE_XML_DESCRIPTION="Qaybta Yaa Online waxay soo bandhigaysaa tirada Dadka Socda (Martida) iyo Dadka Diiwaangashan (isticmaalayaasha soo gala) ee hadda booqanaya shabakadda."

