; Joomla! Project
; (C) 2010 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_RELATED_ITEMS="Qodobbo - La Xiriira"
MOD_RELATED_ITEMS_LAYOUT_DEFAULT="Caadi"
MOD_RELATED_XML_DESCRIPTION="Waxaan madalkan soo bandhigayaa Qodobbo kale oo la xiriira midka shaqaaluhu eegayo. Xidhiidhadani waxa lagu aasaasay Erayada Furaha. <br>Dhammaan erayada furaha ee maqaalkan hadda waa la baadhaa iyadoo la eegayo dhammaan erayada furaha ee dhammaan Qodobbada kale ee la daabacay. Tusaale ahaan, waxaad yeelan kartaa maqaal ku saabsan &quot;Tarbiyeenta Baqshuul&quot; iyo mid kale oo ku saabsan &quot;Kobcinta Gacanta ee Cockatoos Madow&quot;. Haddii aad ku darto erayga furaha &quot;baqshuul&quot; labadaba Qodobbada, markaas Qaybta Qodobada la Xiriira waxay liiska gashan doontaa maqaalka &quot;Tarbiyeenta Baqshuul&quot; marka aad daawaneyso &quot;Kobcinta Gacanta ee Cockatoos Madow&quot; iyo dhinaca kale."

