; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_SYNDICATE="Feejinnada Syndication"
MOD_SYNDICATE_DEFAULT_FEED_ENTRIES="Galinka Feed"
MOD_SYNDICATE_FIELD_DISPLAYTEXT_LABEL="Calaamad Muujin"
MOD_SYNDICATE_FIELD_FORMAT_LABEL="Qaabka Feed"
MOD_SYNDICATE_FIELD_TEXT_DESC="Haddii ay bannaan tahay, qoraalka asalka ah ee faylka luqadda ayaa la isticmaali doonaa."
MOD_SYNDICATE_FIELD_TEXT_LABEL="Calaamad"
MOD_SYNDICATE_FIELD_VALUE_ATOM="Atom 1.0"
MOD_SYNDICATE_FIELD_VALUE_RSS="RSS 2.0"
MOD_SYNDICATE_XML_DESCRIPTION="Muuqaalka Caqliga leh ee Syndication-ka ee abuura Feejin lala wadaago bogga meesha Module-ku ku jiro."

