; Joomla! Project
; (C) 2006 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_CUSTOM="La habeeyey"
MOD_CUSTOM_FIELD_BACKGROUNDIMAGE_LABEL="Dooro Sawirka Asalka"
MOD_CUSTOM_FIELD_PREPARE_CONTENT_DESC="Ikhtiyaar ahaan u diyaari maadada Joomla Plugins-ka Mawduuca."
MOD_CUSTOM_FIELD_PREPARE_CONTENT_LABEL="Diyaari Mawduuca"
MOD_CUSTOM_XML_DESCRIPTION="Qaabkan wuxuu kuu oggolaanayaa inaad abuurto module adigoo isticmaalaya tifaftire WYSIWYG."

