; Joomla! Project
; (C) 2013 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_TAGS_SIMILAR="Tags - Kuwu dhaw"
MOD_TAGS_SIMILAR_LAYOUT_DEFAULT="Caadi"
MOD_TAGS_SIMILAR_XML_DESCRIPTION="Moduleka Tags-ka Kuwu dhaw wuxuu soo bandhigayaa isku xirnaanta walxaha kale ee leh tags la mid ah. Ilaalnaanta xiriirka lama ogaan karo."

