; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_MENU="Liiska"
MOD_MENU_FIELD_ACTIVE_LABEL="Shayga Aasaasiga ah"
MOD_MENU_FIELD_ALLCHILDREN_LABEL="Shayada Hoosaadka"
MOD_MENU_FIELD_CLASS_LABEL="Fasalka Liiska"
MOD_MENU_FIELD_ENDLEVEL_LABEL="Heerka Dhammaadka"
MOD_MENU_FIELD_MENUTYPE_LABEL="Dooro Liiska"
MOD_MENU_FIELD_STARTLEVEL_LABEL="Heerka Bilowga"
MOD_MENU_FIELD_TAG_ID_LABEL="Liiska Tag ID"
MOD_MENU_FIELD_TARGET_DESC="Qiimaha JavaScript si loo habeeyo daaqad pop-up ah, tusaale top=50, left=50, width=200, height=300."
MOD_MENU_FIELD_TARGET_LABEL="Meesha Bartilmaameedka"
MOD_MENU_TOGGLE="Beddel Socdaalinta"
MOD_MENU_XML_DESCRIPTION="Qaabkan wuxuu soo bandhigayaa liis hore ee loogu talagalay."

