; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_ARTICLES_POPULAR="Maqaallo - Kuwooda Ugu AKhrinta Badan (Dhaxal)"
MOD_POPULAR_FIELD_COUNT_LABEL="Maqaallada la Soo Bandhigayo"
MOD_POPULAR_FIELD_DATEFIELD_LABEL="Goobta Taariikhda"
MOD_POPULAR_FIELD_DATEFILTERING_LABEL="Shaandhaynta Taariikhda"
MOD_POPULAR_FIELD_ENDDATE_LABEL="Taariikhda Dhamaadka"
MOD_POPULAR_FIELD_FEATURED_LABEL="Maqaallada Lagu Soo Bandhigay"
MOD_POPULAR_FIELD_RELATIVEDATE_LABEL="Taariikh Qaraabo"
MOD_POPULAR_FIELD_STARTDATE_LABEL="Xadka Bilawga Taariikhda"
MOD_POPULAR_OPTION_CREATED_VALUE="Taariikhda La Abuuray"
MOD_POPULAR_OPTION_DATERANGE_VALUE="Xadka Taariikhda"
MOD_POPULAR_OPTION_MODIFIED_VALUE="Taariikhda La Beddelay"
MOD_POPULAR_OPTION_OFF_VALUE="Dami"
MOD_POPULAR_OPTION_RELATIVEDAY_VALUE="Taariikh Qaraabo"
MOD_POPULAR_OPTION_STARTPUBLISHING_VALUE="Taariikhda Bilawga Soo Bandhigista"
MOD_POPULAR_XML_DESCRIPTION="Qeybtaan waxay soo bandhigaysaa liis ka mid ah Maqaallada la daabacay kuwaas oo leh tirada ugu badan ee aragista bogga. Qeybtaan waxaa beddelay qeybta \"Maqaallada\"."

