; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_BANNERS_NO_CLIENT="- Ma jiro macmiil -"
MOD_BANNERS="Bannaat"
MOD_BANNERS_BANNER="Bannaan"
MOD_BANNERS_FIELD_BANNERCLIENT_DESC="Xulo bannaanada kaliya macmiil shakhsi ah."
MOD_BANNERS_FIELD_BANNERCLIENT_LABEL="Macmiil"
MOD_BANNERS_FIELD_COUNT_DESC="Tirada bannaanada la soo bandhigayo (default waa 5)."
MOD_BANNERS_FIELD_COUNT_LABEL="Tiro"
MOD_BANNERS_FIELD_FOOTER_LABEL="Qoraalka Hoosta"
MOD_BANNERS_FIELD_HEADER_LABEL="Qoraalka Xagga Sare"
MOD_BANNERS_FIELD_RANDOMISE_LABEL="Si waddo kala duwan"
MOD_BANNERS_FIELD_TAG_DESC="Bannaanka waxaa lagu doortaa iyadoo la isku beegsanayo ereyada furaha bannaanada iyo Dukumiintiga hadda ka socda."
MOD_BANNERS_FIELD_TAG_LABEL="Xulo ereyada furaha"
MOD_BANNERS_FIELD_TARGET_LABEL="Bartilmaameed"
MOD_BANNERS_VALUE_STICKYORDERING="Kaanadii, Kala darajo"
MOD_BANNERS_VALUE_STICKYRANDOMISE="Kaanadii, Si waddo kala duwan"
MOD_BANNERS_XML_DESCRIPTION="Module-ka Bannaanka wuxuu soo bandhigayaa Bannaanada firfircoon ee ka socda qayb kale."

