; Joomla! Project
; (C) 2010 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_SYNDICATE="Quudinta Wadaagga"  
MOD_SYNDICATE_LAYOUT_DEFAULT="Dhaqameed"  
MOD_SYNDICATE_XML_DESCRIPTION="Qaab Wadaag oo Caqli leh oo abuura Quudin Wadaag loogu talagalay bogga uu Module-ka ka muuqdo."

