; Joomla! Project
; (C) 2024 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_ARTICLES="Maqaallada"
MOD_ARTICLES_FIELD_ARTICLEGROUPINGDIR_LABEL="Jihaynta Isku-Keenidda"
MOD_ARTICLES_FIELD_ARTICLEGROUPING_LABEL="Isku-Keenidda Maqaallada"
MOD_ARTICLES_FIELD_ARTICLEORDERINGDIR_LABEL="Jihaynta Kala-Saaridda"
MOD_ARTICLES_FIELD_ARTICLEORDERING_LABEL="Aagga Maqaalka ee Lagu Kala Saarayo"
MOD_ARTICLES_FIELD_AUTHORALIASFILTERING_LABEL="Nooca Sifeynta Magacyada Qoraaga"
MOD_ARTICLES_FIELD_AUTHORALIAS_LABEL="Magacyada Bedelka ee Qoraaga"
MOD_ARTICLES_FIELD_AUTHORFILTERING_LABEL="Nooca Sifeynta Qoraaga"
MOD_ARTICLES_FIELD_AUTHOR_LABEL="Qoraayaasha"
MOD_ARTICLES_FIELD_CATDEPTH_LABEL="Qoto dheer ee Qaybta"
MOD_ARTICLES_FIELD_CATFILTERINGTYPE_DESC="Ku dar ama ka saar qeybaha la xushay."
MOD_ARTICLES_FIELD_CATFILTERINGTYPE_LABEL="Nooca Sifeynta Qaybta"
MOD_ARTICLES_FIELD_COUNT_DESC="Tirada waxyaabaha la soo bandhigayo. U deji 0 si aad u tusto dhammaan maqaallada."
MOD_ARTICLES_FIELD_COUNT_LABEL="Maqaallada la Soo Bandhigayo"
MOD_ARTICLES_FIELD_DATEFIELDFORMAT_DESC="Fadlan geli qaab taariikh sax ah. Fiiri: https://php.net/date si aad u hesho macluumaadka qaabeynta."
MOD_ARTICLES_FIELD_DATEFIELDFORMAT_LABEL="Qaabka Taariikhda"
MOD_ARTICLES_FIELD_DATEFIELD_LABEL="Aagga Taariikhda"
MOD_ARTICLES_FIELD_DATEFILTERING_LABEL="Sifeynta Taariikhda"
MOD_ARTICLES_FIELD_DATEGROUPINGFIELD_DESC="Dooro aagga taariikhda aad rabto in lagu dabaqo isku-keenidda taariikhda."
MOD_ARTICLES_FIELD_DATEGROUPINGFIELD_LABEL="Aagga Isku-Keenidda Taariikhda"
MOD_ARTICLES_FIELD_DATERANGEFIELD_LABEL="Aagga Kala-duwanaanta Taariikhda"
MOD_ARTICLES_FIELD_ENDDATE_LABEL="Ilaa Taariikh"
MOD_ARTICLES_FIELD_EX_OR_INCLUDE_LABEL="Ka Saar ama Ku Dar Maqaallada"
MOD_ARTICLES_FIELD_EXCLUDEDARTICLES_LABEL="Maqaallada laga Saarayo"
MOD_ARTICLES_FIELD_EXCLUDE_CURRENT_LABEL="Ka Saar Maqaalka Hadda jira"
MOD_ARTICLES_FIELD_GROUP_DISPLAY_LABEL="Ikhtiyaarada Muuqaalka"
MOD_ARTICLES_FIELD_GROUP_FILTERING_LABEL="Ikhtiyaarada Sifeynta"
MOD_ARTICLES_FIELD_GROUP_GROUPING_LABEL="Ikhtiyaarada Ururinta"
MOD_ARTICLES_FIELD_GROUP_ORDERING_LABEL="Ikhtiyaarada Kala-sarraynta"
MOD_ARTICLES_FIELD_IMAGES_ARTICLE_LABEL="Tuso Sawirka Hordhaca/Dhameystiran"
MOD_ARTICLES_FIELD_IMAGES_DESC="Muuji sawirada ku jira qoraalka maqaalka."
MOD_ARTICLES_FIELD_IMAGES_LABEL="Muuji Sawirada Maqaalka"
MOD_ARTICLES_FIELD_INCLUDEDARTICLES_LABEL="Maqaalada ku Jiro"
MOD_ARTICLES_FIELD_INFOLAYOUT_DESC="Qaabka Macluumaadka Maqaallada (Taariikhda, Dhufashada, Qaybta, Qoraaga)."
MOD_ARTICLES_FIELD_INFOLAYOUT_LABEL="Qaabka Macluumaadka Maqaallada"
MOD_ARTICLES_FIELD_INTROTEXTLIMIT_DESC="Xaddid Qoraalka Hordhaca ilaa tiro cayiman oo xarfo ah. U deji 0 si aad u joojiso jarista."
MOD_ARTICLES_FIELD_INTROTEXTLIMIT_LABEL="Xadka Qoraalka Hordhaca (xarfo)"
MOD_ARTICLES_FIELD_LAYOUT_COL_LABEL="Tirada Ugu Badan ee Tiirarka"
MOD_ARTICLES_FIELD_LAYOUT_DESC="Muujinta maqaalada toosan ama jiifta."
MOD_ARTICLES_FIELD_LAYOUT_HOR="Jiif"
MOD_ARTICLES_FIELD_LAYOUT_LABEL="Qaabka"
MOD_ARTICLES_FIELD_LAYOUT_MULTILINE="Khadad Badan"
MOD_ARTICLES_FIELD_LAYOUT_SINGLELINE="Khad Hal"
MOD_ARTICLES_FIELD_LAYOUT_VERT="Toosan"
MOD_ARTICLES_FIELD_LINKTITLES_LABEL="Xiriirka Cinwaanka"
MOD_ARTICLES_FIELD_MODE_DESC="<em><strong>Qaabka Caadiga ah</strong></em> wuxuu soo bandhigayaa liis maqaalada go'an.<br><em><strong>Qaabka Firfircoon</strong></em> si firfircoon ayuu u baarayaa haddii uu ku jiro aragtida Qaybaha wuxuuna soo bandhigayaa liiska maqaalada ku jira Qaybtaas. Waxaa ugu fiican in lagu soo bandhigo dhammaan bogagga maadaama uu go'aansanayo inuu si firfircoon u soo bandhigo wax kasta."
MOD_ARTICLES_FIELD_MODE_LABEL="Qaabka"
MOD_ARTICLES_FIELD_MONTHYEARFORMAT_DESC="Fadlan geli qaab taariikh sax ah. Eeg: https://php.net/date si aad u hesho macluumaad qaabeyntaan."
MOD_ARTICLES_FIELD_MONTHYEARFORMAT_LABEL="Qaabka Muuqaalka Bish iyo Sanadka"
MOD_ARTICLES_FIELD_ONLYARCHIVED_LABEL="Maqaalada La Keydiyay"
MOD_ARTICLES_FIELD_RELATIVEDATE_LABEL="Taariikh La Xiriirta"
MOD_ARTICLES_FIELD_SELECT_ARTICLE_LABEL="Xulo Maqaal"
MOD_ARTICLES_FIELD_SHOWCATEGORYLINK_LABEL="Isku Xirka Qaybta"
MOD_ARTICLES_FIELD_SHOWCHILDCATEGORYARTICLES_DESC="Ku dar ama ka saar maqaalada ku jira qaybaha waalidka maqaallada la doortay."
MOD_ARTICLES_FIELD_SHOWCHILDCATEGORYARTICLES_LABEL="Maqaalada Qaybta Carruurta"
MOD_ARTICLES_FIELD_SHOWFEATURED_LABEL="Maqaalada La Sifeeyay"
MOD_ARTICLES_FIELD_SHOWHITS_LABEL="Guji"
MOD_ARTICLES_FIELD_SHOWINTROTEXT_LABEL="Qoraal Hordhac"
MOD_ARTICLES_FIELD_SHOWONARTICLEPAGE_DESC="Ka xulo inaad tusto ama qariso Liiska Maqaallada Bogagga Maqaallada. Tani waxa ay ka dhigan tahay in cutubku oo kaliya is muuji doono si firfircoon Bogagga Qaybta."
MOD_ARTICLES_FIELD_SHOWONARTICLEPAGE_LABEL="Tus Bogga Maqaalka"
MOD_ARTICLES_FIELD_STARTDATE_LABEL="Xadka Taariikhda Bilowga"
MOD_ARTICLES_FIELD_TITLEONLY_LABEL="Kaliya Cinwaanada (liisaska)"
MOD_ARTICLES_FIELD_TITLE_HEADING="Heerka Cinwaanka"
MOD_ARTICLES_FIELD_TITLE_HEADING_NONE="Midna"
MOD_ARTICLES_FIELD_TITLE_LABEL="Cinwaanka Maqaalka"
MOD_ARTICLES_FIELD_TRIGGER_EVENTS_DESC="Daar ikhtiyaarka si aad ugu kiciso saddex dhacdo plugin (ka dib Marka Cinwaanka La daabaco, ka Hor Inta aan La Daabicin Mawduuca, Ka dib Marka Mawduuca La Daabaco) maqaal kasta oo ku jira liiska natiijooyinka."
MOD_ARTICLES_FIELD_TRIGGER_EVENTS_LABEL="Kac Dhacdooyin Plugin"
MOD_ARTICLES_INFO="Faahfaahin"
MOD_ARTICLES_OPTION_ASCENDING_VALUE="Sare U Socod"
MOD_ARTICLES_OPTION_CREATED_VALUE="Taariikhda La Abuuray"
MOD_ARTICLES_OPTION_DATERANGE_VALUE="Kala Duwaanshaha Taariikhda"
MOD_ARTICLES_OPTION_DESCENDING_VALUE="Hoos U Socod"
MOD_ARTICLES_OPTION_DYNAMIC_VALUE="Firfircoon"
MOD_ARTICLES_OPTION_EXCLUDE_VALUE="Ka Saar"
MOD_ARTICLES_OPTION_EXCLUSIVE_VALUE="Khaas Ah"
MOD_ARTICLES_OPTION_FINISHPUBLISHING_VALUE="Taariikhda Dhameynta Daabacaadda"
MOD_ARTICLES_OPTION_FULLIMAGE="Sawir Buuxa"
MOD_ARTICLES_OPTION_HITS_VALUE="Guji"
MOD_ARTICLES_OPTION_ID_VALUE="Aqoonsi"
MOD_ARTICLES_OPTION_INCLUDE_VALUE="Ku dar"
MOD_ARTICLES_OPTION_INCLUSIVE_VALUE="Koo dhan"
MOD_ARTICLES_OPTION_INTROIMAGE="Sawirka Hordhaca"
MOD_ARTICLES_OPTION_MODIFIED_VALUE="Taariikhda Wax ka Bedelka"
MOD_ARTICLES_OPTION_MONTHYEAR_VALUE="Bisha iyo Sannadka"
MOD_ARTICLES_OPTION_NORMAL_VALUE="Caadi"
MOD_ARTICLES_OPTION_OFF_VALUE="Dami"
MOD_ARTICLES_OPTION_ONLYARCHIVEDHIDE_VALUE="Midna"
MOD_ARTICLES_OPTION_ONLYARCHIVEDSHOW_VALUE="Kaliya"
MOD_ARTICLES_OPTION_ONLYCURRENTUSER_VALUE="Kaliya isticmaalaha hadda"
MOD_ARTICLES_OPTION_ONLYFEATURED_VALUE="Kaliya"
MOD_ARTICLES_OPTION_ORDERINGFEATURED_VALUE="Amarka Maqaallada la Sii Muujiyey"
MOD_ARTICLES_OPTION_ORDERING_VALUE="Amarka Maqaalka"
MOD_ARTICLES_OPTION_RANDOM_VALUE="Kala gadisan"
MOD_ARTICLES_OPTION_RATING_VALUE="Qiimeyn"
MOD_ARTICLES_OPTION_RELATIVEDAY_VALUE="Taariikhda Xiriirka"
MOD_ARTICLES_OPTION_STARTPUBLISHING_VALUE="Taariikhda Bilaabashada Daabacaadda"
MOD_ARTICLES_OPTION_VOTE_VALUE="Cod"
MOD_ARTICLES_OPTION_YEAR_VALUE="Sanad"
MOD_ARTICLES_UNTAGGED="Aan Calaamadnayn"
MOD_ARTICLES_XML_DESCRIPTION="Qaabkaani wuxuu soo bandhigayaa maqaallo siyaabo kala duwan."


