; Joomla! Project
; (C) 2013 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_TAGS_POPULAR="Tags - Ku Caansanaan"
MOD_TAGS_POPULAR_FIELD_ALL_TIME="Wakhti dhan"
MOD_TAGS_POPULAR_FIELD_DISPLAY_COUNT_LABEL="Tirinta Shayga Muuji"
MOD_TAGS_POPULAR_FIELD_LAST_DAY="Maalintii ugu dambaysay"
MOD_TAGS_POPULAR_FIELD_LAST_HOUR="Saacaddii ugu dambaysay"
MOD_TAGS_POPULAR_FIELD_LAST_MONTH="Bishii ugu dambaysay"
MOD_TAGS_POPULAR_FIELD_LAST_WEEK="Usbuucii ugu dambaysay"
MOD_TAGS_POPULAR_FIELD_LAST_YEAR="Sannadkii ugu dambeeyay"
MOD_TAGS_POPULAR_FIELD_MAXSIZE_DESC="Cabbirka ugu badan ee farta loo isticmaalo tags-ka, oo u dhiganta cabbirka caadiga ah ee shabakadda (tusaale ahaan &quot;2&quot; waxay u taagan tahay 200% cabbirka caadiga)."
MOD_TAGS_POPULAR_FIELD_MAXSIZE_LABEL="Cabbirka Farta Ugu Badan"
MOD_TAGS_POPULAR_FIELD_MINSIZE_DESC="Cabbirka ugu yar ee farta loo isticmaalo tags-ka, oo u dhiganta cabbirka caadiga ah ee shabakadda (tusaale ahaan &quot;2&quot; waxay u taagan tahay 200% cabbirka caadiga)."
MOD_TAGS_POPULAR_FIELD_MINSIZE_LABEL="Cabbirka Farta Ugu Yar"
MOD_TAGS_POPULAR_FIELD_NO_RESULTS_LABEL="Muuji qoraalka &quot;Natiijooyin La'aan&quot;"
MOD_TAGS_POPULAR_FIELD_ORDER_VALUE_COUNT="Tirinta Shayga"
MOD_TAGS_POPULAR_FIELD_ORDER_VALUE_LABEL="Amar"
MOD_TAGS_POPULAR_FIELD_ORDER_VALUE_RANDOM="Si kadais"
MOD_TAGS_POPULAR_FIELD_ORDER_VALUE_TITLE="Cinwaan"
MOD_TAGS_POPULAR_FIELD_TIMEFRAME_LABEL="Xilliga"
MOD_TAGS_POPULAR_FIELDSET_CLOUD_LABEL="Qaabka Daruur"
MOD_TAGS_POPULAR_MAX_LABEL="Tags Ugu Badan"
MOD_TAGS_POPULAR_NO_ITEMS_FOUND="Wax Tags ah lama helin."
MOD_TAGS_POPULAR_PARENT_TAG_DESC="Xaddid tags-ka la tusayo in ay ka mid yihiin carruurta Tagga Hooyada."
MOD_TAGS_POPULAR_PARENT_TAG_LABEL="Tagga Hooyada"
MOD_TAGS_POPULAR_XML_DESCRIPTION="Qaabkan wuxuu soo bandhigayaa tags-ka lagu isticmaalay goobta liist ama qaabka daruurta. Tags-ka waxa lagu habayn karaa cinwaan ama tirinta shayga oo lagu xaddiday wakhti gaar ah."

