; Joomla! Project
; (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

CASSIOPEIA="Qaab dhismeedka goobta Cassiopeia"
TPL_CASSIOPEIA_BACKTOTOP="Soo noqo xagga sare"
TPL_CASSIOPEIA_BACKTOTOP_LABEL="Xiriir dib ugu-noqoshada-xagga sare"
TPL_CASSIOPEIA_BRAND_LABEL="Astaanta"
TPL_CASSIOPEIA_COLOR_NAME_ALTERNATIVE="Kaladuwan"
TPL_CASSIOPEIA_COLOR_NAME_LABEL="Mawduuca Midabka"
TPL_CASSIOPEIA_COLOR_NAME_STANDARD="Heer"
TPL_CASSIOPEIA_FLUID="Dareere"
TPL_CASSIOPEIA_FLUID_LABEL="Qaabeynta"
TPL_CASSIOPEIA_FONT_GROUP_LOCAL="Farta laga keenay Faylka"
TPL_CASSIOPEIA_FONT_GROUP_WEB="Farta laga keenay Shabakadda"
TPL_CASSIOPEIA_FONT_LABEL="Nidaamka Farta"
TPL_CASSIOPEIA_FONT_NOTE_TEXT="Farta nidaamka ayaa ah kuwa ugu waxqabadka fiican in kasta oo ay jiri karaan kala duwanaansho yar oo ku saabsan nidaamyada hawl-gelinta.<br> Gelinta farta laga keena ilo dibadda waxaa laga yaabaa inay ka hor-imaan karto sharciyada gaarka ah ee wadamo qaar.<br> Gelinta farta laga keenay faylka maxaliga ah waxaa laga yaabaa inay saameyn ku yeelato waxqabadka goobtaada."
TPL_CASSIOPEIA_FONT_SYSTEM="Farta Nidaamka"
TPL_CASSIOPEIA_FONT_SYSTEM_BODY="Xirmada Farta Jirka"
TPL_CASSIOPEIA_FONT_SYSTEM_HEADING="Xirmada Farta Ciwaanka"
TPL_CASSIOPEIA_FONT_SYSTEM_SELECT="Xulo Farta Nidaamka"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_ANTIQUE="Qadiimi"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_CLASSICAL="Qadiimiga Insaanimada"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_CODE="Koodhka Monospace"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_DIDONE="Didone"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_GEOMETRIC="Isku-qaaska Insaanimada"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_GROTESQUE="Neo-Grotesque"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_HANDWRITTEN="Qoraal Gacmeed"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_HUMANIST="Insaaninimada"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_INDUSTRIAL="Warshadeed"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_MONOSPACE="Monospace Slab Serif"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_OLDSTYLE="Qaab Gabow"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_ROUNDED="Qaab Wareegsan"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_SLAB="Slab Serif"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_TRANSITIONAL="Transitional"
TPL_CASSIOPEIA_LOGO_LABEL="Astaanta"
TPL_CASSIOPEIA_STATIC="Joogto"
TPL_CASSIOPEIA_STICKY_LABEL="Madaxa Ku Dheggan"
TPL_CASSIOPEIA_TAGLINE_DESC="Qoraal ikhtiyaari ah oo lagu muujiyo sidii ciwaanka hoose"
TPL_CASSIOPEIA_TAGLINE_LABEL="Hawlaha"
TPL_CASSIOPEIA_TITLE="Cinwaan (ikhtiyaari u ah astaanta)"
TPL_CASSIOPEIA_XML_DESCRIPTION="Sii wadidda dulucda cirifka (Solarflare laga soo bilaabo 1.0, Milkyway laga soo bilaabo 1.5 iyo Protostar laga soo bilaabo 3.0), Cassiopeia waa qaabka bogga Joomla 4 iyo Joomla 5 oo ku saleysan Bootstrap 5."

