; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_TEMPLATES="Cajalada"
COM_TEMPLATES_ARE_YOU_SURE="Ma hubtaa?"
COM_TEMPLATES_ASSIGNED_1="Loo xilsaaray hal menu shay."
COM_TEMPLATES_ASSIGNED_MORE="Loo xilsaaray %d menu shay."
COM_TEMPLATES_BUTTON_CHECK="Kormeer Dareenka"
COM_TEMPLATES_BUTTON_CHECK_LIST_ENTRY="Calaamadee La hubiyay"
COM_TEMPLATES_BUTTON_CLOSE_FILE="Xir"
COM_TEMPLATES_BUTTON_COPY_FILE="Nuqul Faylka"
COM_TEMPLATES_BUTTON_COPY_TEMPLATE="Nuqul Cajalada"
COM_TEMPLATES_BUTTON_CREATE="Abuur"
COM_TEMPLATES_BUTTON_CROP="Goyn"
COM_TEMPLATES_BUTTON_DELETE="Tirtir"
COM_TEMPLATES_BUTTON_DELETE_FILE="Tirtir Faylka"
COM_TEMPLATES_BUTTON_DELETE_LIST_ENTRY="Ka saar Diiwaanka"
COM_TEMPLATES_BUTTON_EXTRACT_ARCHIVE="Ka bixi Halkan"
COM_TEMPLATES_BUTTON_FILE="Fayl Cusub"
COM_TEMPLATES_BUTTON_FOLDERS="Maamul Faylalka"
COM_TEMPLATES_BUTTON_PREVIEW="Hordhac Cajalada"
COM_TEMPLATES_BUTTON_RENAME="Magac Bixin"
COM_TEMPLATES_BUTTON_RENAME_FILE="Magac Bixin Faylka"
COM_TEMPLATES_BUTTON_RESIZE="Dib-u-Cabir"
COM_TEMPLATES_BUTTON_TEMPLATE_CHILD="Abuur Cajalada Carruur"
COM_TEMPLATES_BUTTON_UNCHECK_LIST_ENTRY="Calaamadee Aan La Hubinin"
COM_TEMPLATES_BUTTON_UPLOAD="Soo Upload Garee"
COM_TEMPLATES_CHECK_FILE_OWNERSHIP="Hubi lahaanshaha faylka"
COM_TEMPLATES_CHILD_SUCCESS="Qaab-dhismeedka carruurta waa la sameeyay."
COM_TEMPLATES_CLICK_TO_ENLARGE="Xulo si aad u weyneyso."
COM_TEMPLATES_COMPILE_ERROR="Qalad ayaa dhacay. Looma ku guuleysan isku-darka."
COM_TEMPLATES_COMPILE_LESS="Waa inaad isku darta %s si aad u abuurto faylka CSS."
COM_TEMPLATES_CONFIGURATION="Template: Xulashooyinka"
COM_TEMPLATES_CONFIG_FIELDSET_DESC="Qaab-dhismeedka guud ee shebekadaha."
COM_TEMPLATES_CONFIG_FONT_LABEL="Noocyada Farta ee Saxda ah"
COM_TEMPLATES_CONFIG_IMAGE_LABEL="Noocyada Sawirka ee Saxda ah"
COM_TEMPLATES_CONFIG_POSITIONS_LABEL="Billow Mowqifyada Moduulka"
COM_TEMPLATES_CONFIG_SOURCE_LABEL="Noocyada Isha ee Saxsan"
COM_TEMPLATES_CONFIG_UPLOAD_LABEL="Cabbirka Ugu Badan ee La Soo Gelin Karo (MB)"
COM_TEMPLATES_COPY_CHILD_TEMPLATE_STYLES="%s, nuqul ka mid ah %s"
COM_TEMPLATES_COPY_SUCCESS="Qaab cusub oo la yiraahdo %s waa la rakibay."
COM_TEMPLATES_CROP_AREA_ERROR="Aagga goynta lama dooran."
COM_TEMPLATES_DIFF_CORE="Asalka"
COM_TEMPLATES_DIFF_DIFFERENCES="Farqiyada"
COM_TEMPLATES_DIFF_IDENTICAL="Labada fayl waa isku mid."
COM_TEMPLATES_DIFF_OPTIONS="Muuqaalka Farqiga Faylka"
COM_TEMPLATES_DIFF_OPTIONS_INLINE="Inline"
COM_TEMPLATES_DIFF_OPTIONS_SIDE="Dhinac-by-Dhinac"
COM_TEMPLATES_DIFF_OVERRIDE="Baddelid"
COM_TEMPLATES_DIRECTORY_NOT_WRITABLE="Galka shebekaddu ma qorno. Qaar ka mid ah shaqooyinka ma shaqeyn karaan."
COM_TEMPLATES_ERROR_ASSET_FILE_DELETE="Faylka joomla.asset.json lama tirtiri karo. Isbedelo ku samee tifaftiraha haddii aad rabto inaad bedesho faylka."
COM_TEMPLATES_ERROR_ASSET_FILE_INVALID_JSON="Faylka joomla.asset.json ma laha JSON sax ah, waa la baajiyey kaydinta."
COM_TEMPLATES_ERROR_CANNOT_DELETE_LAST_STYLE="Ma tirtiri kartid qaabka ugu dambeeya ee shebekad. Ma waxaad damacsan tahay inaad <a href=\"index.php?option=com_installer&view=manage&filter[type]=template\" class=\"alert-link\">ka saarto</a> shebekadda?"
COM_TEMPLATES_ERROR_CANNOT_UNSET_DEFAULT_STYLE="Ma damin karo qaabka aasaasiga ah."
COM_TEMPLATES_ERROR_COULD_NOT_COPY="Lama awoodo in la nuqulo faylasha template-ka ee galka ku meel gaar ah."
COM_TEMPLATES_ERROR_COULD_NOT_INSTALL="Lama rakibi karo template cusub oo laga soo qaaday galka ku meel gaarka ah."
COM_TEMPLATES_ERROR_COULD_NOT_WRITE="Lama awoodo in la tirtiro galka ku meel gaar ah."
COM_TEMPLATES_ERROR_CREATE_NOT_PERMITTED="Lama awoodo abuurista galka ku meel gaarka ah."
COM_TEMPLATES_ERROR_DUPLICATE_TEMPLATE_NAME="Template leh magaca kan hore ayaa hore loogu rakibay."
COM_TEMPLATES_ERROR_EDITOR_DISABLED="Labada CodeMirror ama None editor plugin waa in la awoodaa si loo tafatiro faylasha template-ka."
COM_TEMPLATES_ERROR_EXECUTABLE="Ma soo geli karo faylal la fulin karo."
COM_TEMPLATES_ERROR_EXTENSION_RECORD_NOT_FOUND="Diiwaanka kicinta lama helin ee database-ka."
COM_TEMPLATES_ERROR_FAILED_TO_SAVE_FILENAME="Qalad ayaa dhacay. Lama keydin karo faylka %s."
COM_TEMPLATES_ERROR_FILE_CREATE="Ku guuldareystay abuurista fayl."
COM_TEMPLATES_ERROR_FILE_DELETE="Qalad ayaa dhacay. Ku guuldareystay tirtirista faylka."
COM_TEMPLATES_ERROR_FILE_FORMAT="Qaabka faylka lama taageerayo."
COM_TEMPLATES_ERROR_FILE_RENAME="Qalad ayaa dhacay. Ku guuldareystay in la magac bedelo faylka."
COM_TEMPLATES_ERROR_FILE_UPLOAD="Ku guuldareystay soo gelinta faylka."
COM_TEMPLATES_ERROR_FOLDER_CREATE="Ku guuldareystay abuurista galka."
COM_TEMPLATES_ERROR_FONT_FILE_NOT_FOUND="Faylka farta lama helin."
COM_TEMPLATES_ERROR_IMAGE_FILE_NOT_FOUND="Faylka sawirka lama helin."
COM_TEMPLATES_ERROR_INDEX_DELETE="Faylka index.php lama tirtiri karo. Isbedel ku samee tafatiraha haddii aad rabto inaad bedesho faylka."
COM_TEMPLATES_ERROR_INVALID_FROM_NAME="Template ka laga koobiyeynayo lama helin."
COM_TEMPLATES_ERROR_INVALID_TEMPLATE_NAME="Magaca template-ka ma ansaxsana. Fadlan isticmaal keliya xuruuf, nambar iyo hoosta jiid."
COM_TEMPLATES_ERROR_NO_FILE_SELECTED="Fayl lama xulan."
COM_TEMPLATES_ERROR_RENAME_ASSET_FILE="Faylka joomla.asset.json lama magac bedeli karo."
COM_TEMPLATES_ERROR_RENAME_INDEX="Faylka index.php lama magac bedeli karo."
COM_TEMPLATES_ERROR_ROOT_DELETE="Galka hoose ma tirtiri karo."
COM_TEMPLATES_ERROR_SAVE_DISABLED_TEMPLATE="Ma suurtogasho in la badbaadiyo qaab la xiriira sheygaan la'aanta ah."
COM_TEMPLATES_ERROR_SOURCE_FILE_NOT_FOUND="Faylka asalka ah lama helin."
COM_TEMPLATES_ERROR_SOURCE_FILE_NOT_UNWRITABLE="Faylka isha ah looma celin karo xaalad aan la qorin."
COM_TEMPLATES_ERROR_SOURCE_FILE_NOT_WRITABLE="Faylka isha lama qori karo."
COM_TEMPLATES_ERROR_SOURCE_ID_FILENAME_MISMATCH="Aqoonsiga keydsan ma waafaqsana midka la soo gudbiyay."
COM_TEMPLATES_ERROR_STYLE_NOT_FOUND="Qaabka lama helin."
COM_TEMPLATES_ERROR_STYLE_REQUIRES_TITLE="Qaabku waxa uu u baahan yahay ciwaanka."
COM_TEMPLATES_ERROR_TEMPLATE_FOLDER_NOT_FOUND="Folderka template lama helin."
COM_TEMPLATES_ERROR_UPLOAD_INPUT="Fayl lama helin."
COM_TEMPLATES_ERROR_WARNFILENAME="Magaca faylka ayaa khaldan. Fadlan sax magaca faylka oo dib u soo geli."
COM_TEMPLATES_ERROR_WARNFILETOOLARGE="Faylkan waa mid aad u weyn oo la khaldiyay."
COM_TEMPLATES_ERROR_WARNFILETYPE="Qaabka faylka lama taageero."
COM_TEMPLATES_ERROR_WARNIEXSS="Lama soo gelin karo. XSS ayaa ku jirta."
COM_TEMPLATES_ERR_XML="Macluumaadka XML ee habka lama heli karo."
COM_TEMPLATES_FIELD_CLIENT_LABEL="Goobta"
COM_TEMPLATES_FIELD_HOME_LABEL="Daanin"
COM_TEMPLATES_FIELD_SOURCE_LABEL="Koodhka Asalka ah"
COM_TEMPLATES_FIELD_TEMPLATE_LABEL="Qaabka"
COM_TEMPLATES_FIELD_TITLE_LABEL="Magaca Qaabka"
COM_TEMPLATES_FILE_ARCHIVE_EXISTS="Faylasha qaarkood oo leh magac isku mid ah horey ayay u jiraan."
COM_TEMPLATES_FILE_ARCHIVE_EXTRACT_FAIL="Fashilka in la soo saaro faylka kaydka."
COM_TEMPLATES_FILE_ARCHIVE_EXTRACT_SUCCESS="Faylka Kaydka waa la soo saaray."
COM_TEMPLATES_FILE_ARCHIVE_NOT_FOUND="Faylka kaydka lama helin."
COM_TEMPLATES_FILE_ARCHIVE_OPEN_FAIL="Fashilka in la furo faylka kaydka."
COM_TEMPLATES_FILE_COMPARE_PANE="Kaladuwanaasho u dhexeeya faylka asalka ah iyo kan dib loo qeexay."
COM_TEMPLATES_FILE_CONTENT_PREVIEW="Dulmar Qaabka Faylka"
COM_TEMPLATES_FILE_COPY_FAIL="Ku guuldareystay in nuqul laga sameeyo faylka."
COM_TEMPLATES_FILE_COPY_SUCCESS="Faylka hadda ayaa nuqul laga sameeyay sida %s."
COM_TEMPLATES_FILE_CORE_PANE="Faylkii asalka ahaa (akhri kaliya)"
COM_TEMPLATES_FILE_CREATE_ERROR="Cilad ayaa dhacday abuuritaanka faylka."
COM_TEMPLATES_FILE_CREATE_SUCCESS="Faylka waa la abuuray."
COM_TEMPLATES_FILE_CROP_ERROR="Ku guuldareystay in la jaro sawirka."
COM_TEMPLATES_FILE_CROP_SUCCESS="Sawir la jaray."
COM_TEMPLATES_FILE_DELETE_ERROR="Ma awoodo in tirtiro faylka."
COM_TEMPLATES_FILE_DELETE_SUCCESS="Faylka waa la tirtiray."
COM_TEMPLATES_FILE_EXISTS="Fayl isla magaca ah horey ayuu u jiraa."
COM_TEMPLATES_FILE_INFO="Macluumaadka Faylka"
COM_TEMPLATES_FILE_NAME="Magaca Faylka"
COM_TEMPLATES_FILE_NEW_NAME_LABEL="Magaca Faylka Nuqulka"
COM_TEMPLATES_FILE_OVERRIDE_PANE="Wax ka beddelidda faylka (la'edit gareyn karo)"
COM_TEMPLATES_FILE_PERMISSIONS="Ogolaanshaha Faylka waa %s"
COM_TEMPLATES_FILE_RENAME_ERROR="Cilad ayaa dhacday dib u magac bixinta faylka."
COM_TEMPLATES_FILE_RENAME_SUCCESS="Faylka waa la dib u magac bixiyay."
COM_TEMPLATES_FILE_RESIZE_ERROR="Ku guuldareystay in la beddelo cabbirka sawirka."
COM_TEMPLATES_FILE_RESIZE_SUCCESS="Sawir la beddelay cabbirka."
COM_TEMPLATES_FILE_SAVE_SUCCESS="Faylka waa la keydiyay."
COM_TEMPLATES_FILE_UNSUPPORTED_ARCHIVE="Faylasha aan la taageerin ayaa ku dhex jira faylka zip-ka."
COM_TEMPLATES_FILE_UPLOAD_ERROR="Cilad ayaa dhacday marka la soo gelinayo faylka."
COM_TEMPLATES_FILE_UPLOAD_SUCCESS="Faylka la soo geliyay: %s"
COM_TEMPLATES_FILTER_TEMPLATE="- Doorasho Template -"
COM_TEMPLATES_FOLDER_CREATE_ERROR="Waxaa jirtay khalad abuuritaanka galka."
COM_TEMPLATES_FOLDER_CREATE_SUCCESS="Galkii waa la abuuray."
COM_TEMPLATES_FOLDER_DELETE_ERROR="Khalad ayaa dhacay. Waxaa lagu guuldareystay in la tirtiro galka."
COM_TEMPLATES_FOLDER_DELETE_SUCCESS="Galkii waa la tirtiray."
COM_TEMPLATES_FOLDER_ERROR="Ma awoodo in la abuuro galka."
COM_TEMPLATES_FOLDER_EXISTS="Galka leh magacaas oo kale horay ayuu u jiray."
COM_TEMPLATES_FOLDER_NAME="Magaca Galka"
COM_TEMPLATES_FOLDER_NOT_EXISTS="Galkii ma jiro."
COM_TEMPLATES_GD_EXTENSION_NOT_AVAILABLE="Kordhinta GD ee PHP ma heli karo.<br>Si aad u maamusho sawirada waxaad u baahan tahay kordhinta dheeraad ah oo lagu soo rakibo server-kaaga. Eeg <a href='https://downloads.joomla.org/technical-requirements' target='_blank' rel='noopener noreferrer'>Shuruudaha Rasmi ah ee Farsamada</a> dukumintiyada si aad u ogaato faahfaahin dheeraad ah."
COM_TEMPLATES_GRID_UNSET_LANGUAGE="Daabici %s asal"
COM_TEMPLATES_HEADING_ASSIGNED="La sameeyay"
COM_TEMPLATES_HEADING_DEFAULT="Asal"
COM_TEMPLATES_HEADING_DEFAULT_ASC="Asal sii kordhaya"
COM_TEMPLATES_HEADING_DEFAULT_DESC="Asal sii dhacaya"
COM_TEMPLATES_HEADING_IMAGE="Sawir"
COM_TEMPLATES_HEADING_PAGES="Bogagga"
COM_TEMPLATES_HEADING_STYLE="Qaab"
COM_TEMPLATES_HEADING_STYLE_ASC="Qaab sii kordhaya"
COM_TEMPLATES_HEADING_STYLE_DESC="Qaab sii dhacaya"
COM_TEMPLATES_HEADING_TEMPLATE="Qaraar"
COM_TEMPLATES_HEADING_TEMPLATE_ASC="Qaraar sii kordhaya"
COM_TEMPLATES_HEADING_TEMPLATE_DESC="Qaraar sii dhacaya"
COM_TEMPLATES_HOME_BUTTON="Dukumentiga"
COM_TEMPLATES_HOME_HEADING="Dooro Fayl"
COM_TEMPLATES_HOME_TEXT="Waxaad dooran kartaa ikhtiyaarra kala duwan oo aad u habeyn karto muuqaalka qaraarradaada. Maareeyaha Template-ka waxa uu taageerayaa faylasha Isha, faylasha Sawirka, faylasha Font, faylasha Zip iyo inta badan hawlgallada lagu samayn karo faylashaas. Door faylka oo diyaar baad tahay. Hubi dukumintiyada haddii aad rabto inaad wax badan ogaato."
COM_TEMPLATES_IMAGE_HEIGHT="Dherer"
COM_TEMPLATES_IMAGE_WIDTH="Balaadh"
COM_TEMPLATES_INVALID_FILE_NAME="Magaca faylka waa khalad. Fadlan dooro magac fayl oo leh a-z, A-Z, 0-9, ., - iyo _."
COM_TEMPLATES_INVALID_FILE_TYPE="Nooca faylka lama dooran."
COM_TEMPLATES_INVALID_FOLDER_NAME="Magaca galka waa khalad. Fadlan dooro magac gal oo leh a-z, A-Z, 0-9, - iyo _."
COM_TEMPLATES_LAYOUTS_DIFFVIEW_CORE="Tus Faylka Asaliga ah"
COM_TEMPLATES_LAYOUTS_DIFFVIEW_DIFF="Tus Kala duwanaanshaha"
COM_TEMPLATES_MANAGER_ADD_STYLE="Dhuuro: Ku dar Qaab"
COM_TEMPLATES_MANAGER_EDIT_STYLE="Dhuuro: Wax Ka Beddel Qaab"
COM_TEMPLATES_MANAGER_STYLES="Dhuuro: Qaababka"
COM_TEMPLATES_MANAGER_STYLES_ADMIN="Dhuuro: Qaababka (Maamule)"
COM_TEMPLATES_MANAGER_STYLES_BUTTON="Qaababka"
COM_TEMPLATES_MANAGER_STYLES_SITE="Dhuuro: Qaababka (Boggan)"
COM_TEMPLATES_MANAGER_TEMPLATES="Dhuuro"
COM_TEMPLATES_MANAGER_TEMPLATES_ADMIN="Dhuuro: Dhuuro (Maamule)"
COM_TEMPLATES_MANAGER_TEMPLATES_SITE="Dhuuro: Dhuuro (Boggan)"
COM_TEMPLATES_MANAGER_VIEW_TEMPLATE="Dhuuro: Habee (%s)"
COM_TEMPLATES_MANAGE_FOLDERS="Maamul Galalka"
COM_TEMPLATES_MENUS_ASSIGNMENT="Hawlgelinta Menu"
COM_TEMPLATES_MENU_CHANGED_1="Hal menu item ayaa lagu hawlgaliyay ama laga joojiyay qaabkan."
COM_TEMPLATES_MENU_CHANGED_MORE="%d menu items ayaa lagu hawlgaliyay ama laga joojiyay qaabkan."
COM_TEMPLATES_MODAL_FILE_DELETE="Faylka %s waa la tirtiri doonaa."
COM_TEMPLATES_MSG_MANAGE_NO_STYLES="Qaabab aan iswaafaqsanayn baadhistaada lama rakibin."
COM_TEMPLATES_MSG_MANAGE_NO_TEMPLATES="Dhuuro aan iswaafaqsanayn baadhistaada lama rakibin."
COM_TEMPLATES_NEW_FILE_HEADER="Abuur ama Soo rar fayl cusub."
COM_TEMPLATES_NEW_FILE_NAME="Magaca Faylka Cusub"
COM_TEMPLATES_NEW_FILE_SELECT="Xullo nooca faylka"
COM_TEMPLATES_NEW_FILE_TYPE="Nooca Faylka"
COM_TEMPLATES_NO_TEMPLATE_SELECTED="Ma jiro template loo doortay."
COM_TEMPLATES_N_CONFLICT="%d Isbedelo ayaa la helay"
COM_TEMPLATES_N_CONFLICT_1="Isbedel ayaa la helay"
COM_TEMPLATES_N_ITEMS_DELETED="%d qaabab template ah ayaa la tirtiray."
COM_TEMPLATES_N_ITEMS_DELETED_1="Qaab template ah ayaa la tirtiray."
COM_TEMPLATES_N_OVERRIDE_CHECKED="%d diiwaan ayaa la hubiyay."
COM_TEMPLATES_N_OVERRIDE_CHECKED_1="Diiwaan ayaa la hubiyay."
COM_TEMPLATES_N_OVERRIDE_DELETED="%d diiwaan ayaa la saaray."
COM_TEMPLATES_N_OVERRIDE_DELETED_1="Diiwaan ayaa la saaray."
COM_TEMPLATES_N_OVERRIDE_UNCHECKED="%d diiwaan ayaa laga hubin."
COM_TEMPLATES_N_OVERRIDE_UNCHECKED_1="Diiwaan ayaa laga hubin."
COM_TEMPLATES_OPTION_NONE=":: Midna ::"
COM_TEMPLATES_OPTION_SELECT_MENU_ITEM="- Xullo Shay Menu -"
COM_TEMPLATES_OVERRIDES="Faylasha Ka Baddalida"
COM_TEMPLATES_OVERRIDES_COMPONENTS="Qaybaha"
COM_TEMPLATES_OVERRIDES_LAYOUTS="Qaabaynta"
COM_TEMPLATES_OVERRIDES_MODULES="Modules"
COM_TEMPLATES_OVERRIDES_PLUGINS="Plugins"
COM_TEMPLATES_OVERRIDE_CHECKED="Waxaa la hubiyay"
COM_TEMPLATES_OVERRIDE_CORE_REMOVED="Fayl asalka ayaa la saaray"
COM_TEMPLATES_OVERRIDE_CREATED="Beddel ayaa lagu abuuray "
COM_TEMPLATES_OVERRIDE_CREATED_DATE="Waxaa lagu daray liiska"
COM_TEMPLATES_OVERRIDE_FAILED="Ku guuldareystay in la abuuro mid ka baxsan."
COM_TEMPLATES_OVERRIDE_MODIFIED_DATE="Isbeddelkii ugu dambeeyay ee la sameeyay iyadoo la cusbooneysiiyay"
COM_TEMPLATES_OVERRIDE_NOT_UPTODATE="Asalka faylasha la beddelay ee hoos ku taxan waa la cusboonaysiiyay. Liiskan wuxuu kaa caawinayaa inaad dib u eegto isbeddeladaas oo aad calaamadiso sidii loo hubiyay markaad horey u sii socoto."
COM_TEMPLATES_OVERRIDE_SOURCE="Ilaha Cusbooneysiinta"
COM_TEMPLATES_OVERRIDE_TEMPLATE_FILE="Faylka Template"
COM_TEMPLATES_OVERRIDE_UPTODATE="Faylasha la beddelay waa upto date. Waxna isbadal kuma dhicin cusboonaysiinta hore ama tan Joomla."
COM_TEMPLATES_OVERRIDE_UPDATED_FILES_CAPTION="Faylasha la cusbooneysiiyay ee la hubinayo."
COM_TEMPLATES_PREVIEW="Hordhac"
COM_TEMPLATES_RENAME_FILE="Beddel magaca faylka %s"
COM_TEMPLATES_RESIZE_IMAGE="Dib u celi Sawirka"
COM_TEMPLATES_SCREENSHOT="Sawir la xaday %s"
COM_TEMPLATES_SOURCE_CODE="Isha"
COM_TEMPLATES_STYLES_FILTER_SEARCH_DESC="Raadi sharaxaadda qaabka."
COM_TEMPLATES_STYLES_PAGES_ALL="Asalka dhammaan bogagga"
COM_TEMPLATES_STYLES_PAGES_ALL_LANGUAGE="Asalka %s bogagga"
COM_TEMPLATES_STYLES_PAGES_NONE="Lama qoondeyn"
COM_TEMPLATES_STYLES_PAGES_SELECTED_1="Waxaa loo qoondeeyay hal bog %d"
COM_TEMPLATES_STYLES_PAGES_SELECTED="Waxaa loo qoondeeyay %d bogagga"
COM_TEMPLATES_STYLES_TABLE_CAPTION="Qaababka Template"
COM_TEMPLATES_STYLE_CANNOT_DELETE_DEFAULT_STYLE="Lama tirtiri karo qaabka asalka ah."
COM_TEMPLATES_STYLE_FORM_EDIT="Wax ka bedel Qaabka"
COM_TEMPLATES_STYLE_SAVE_SUCCESS="Qaabka waa la keydiyay."
COM_TEMPLATES_SUBMENU_TEMPLATES="Templates"
COM_TEMPLATES_SUCCESS_DUPLICATED="Qaabka waa la nuqulay."
COM_TEMPLATES_SUCCESS_HOME_SET="Qaabka asalka waa la dhigay."
COM_TEMPLATES_SUCCESS_HOME_UNSET="Qaabka caadiga ah waa la joojiyay."
COM_TEMPLATES_TAB_DESCRIPTION="Sharaxaad Template"
COM_TEMPLATES_TAB_EDITOR="Tafatiraha"
COM_TEMPLATES_TAB_OVERRIDES="Abuur Toban"
COM_TEMPLATES_TAB_UPDATED_FILES="Faylasha Cusboonaysiiyay"
COM_TEMPLATES_TEMPLATES_FILTER_SEARCH_DESC="Raadi magaca template-ka ama magaca galka."
COM_TEMPLATES_TEMPLATES_TABLE_CAPTION="Templates"
COM_TEMPLATES_TEMPLATE_CHILD="Template Ilmo"
COM_TEMPLATES_TEMPLATE_CHILD_NAME_LABEL="Magaca Template Ilmo"
COM_TEMPLATES_TEMPLATE_CHILD_STYLE_LABEL="Qaabab Template Dheeraad ah"
COM_TEMPLATES_TEMPLATE_CLOSE="Xir"
COM_TEMPLATES_TEMPLATE_COPY="Nuqul Template"
COM_TEMPLATES_TEMPLATE_CORE_FILENAME="Faylka asalka ah &quot;%s&quot;."
COM_TEMPLATES_TEMPLATE_DESCRIPTION="Sharaxaada Template."
COM_TEMPLATES_TEMPLATE_DETAILS="%s Faahfaahin iyo Faylal"
COM_TEMPLATES_TEMPLATE_FILENAME="Saxida faylka &quot;%s&quot; ee template &quot;%s&quot;."
COM_TEMPLATES_TEMPLATE_FILES="Faylasha Template"
COM_TEMPLATES_TEMPLATE_FOLDER="Galka Template"
COM_TEMPLATES_TEMPLATE_IS_CHILD_OF="Ilmo <strong class=\"text-capitalize text-light\">%s</strong>"
COM_TEMPLATES_TEMPLATE_IS_PARENT="Waalid"
COM_TEMPLATES_TEMPLATE_MEDIA_FILES="Faylasha Warbaahinta"
COM_TEMPLATES_TEMPLATE_MEDIA_FOLDER="Galka Warbaahinta"
COM_TEMPLATES_TEMPLATE_NEW_NAME_DESC="Xarfaha, lambarada iyo hoosta oo kaliya."
COM_TEMPLATES_TEMPLATE_NEW_NAME_LABEL="Magaca Template Cusub"
COM_TEMPLATES_TEMPLATE_NEW_PREVIEW="Muuqaalka %s daaqad cusub."
COM_TEMPLATES_TEMPLATE_NEW_STYLE_DESC="Ku dhufo hababka jira ee loogu talagalay template-ka cusub ee cunugga."
COM_TEMPLATES_TEMPLATE_NOT_SPECIFIED="Template lama cayimin."
COM_TEMPLATES_TEMPLATE_NO_PREVIEW="Ma jiro aragti hore oo la heli karo. Waxaad ku karti gelin kartaa aragtida doorashooyinka."
COM_TEMPLATES_TEMPLATE_PREVIEW="Aragti hore"
COM_TEMPLATES_TOOLBAR_SET_HOME="Saldhig"
COM_TEMPLATES_UPTODATE="Waa cusub yahay"
COM_TEMPLATES_WARNING_FORMAT_WILL_NOT_BE_VISIBLE="Waxaad abuurtey file cusub oo leh kordhin '%s'. Tani waa la taageeray laakiin maadaama aad file-kaas kordhinta aan ku jirin liiska hababka la taageeray tan lama soo bandhigi karo. Fadlan hubi siyaasadaha Templates-ka oo ku dar qaabka haddii loo baahdo."
COM_TEMPLATES_XML_DESCRIPTION="Qaybtani waxay maamulaa templates"
JLIB_HTML_PUBLISH_ITEM="Astaan ​​sida la hubiyey"
JLIB_HTML_UNPUBLISH_ITEM="Astaan ​​sida aan la hubin"
JLIB_RULES_SETTING_NOTES_COM_TEMPLATES="Isbedelada waxay khuseeyaan qaybtaan kaliya.<br><em><strong>Laga dhaxlay</strong></em> - habaynta Guud ama heer ka sareeya ayaa lagu dabaqay.<br><em><strong>Diidey</strong></em> had iyo jeer way guuleeysataa - wax kasta oo lagu dejiyo heerka Guud ama ka sarreeya waxayna khuseysaa dhammaan walxaha cunugga.<br><em><strong>La oggolaaday</strong></em> waxay awood u siineysaa ficilka qaybtaan ilaa laga baabi'iyo dejinta Qaab-dhismeedka Guud."

