; Joomla! Project
; (C) 2009 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_REDIRECT="Ku laabashada"
COM_REDIRECT_ADVANCED_OPTIONS="Sare"
COM_REDIRECT_BATCH_OPTIONS="Habka jaadka si loogu daro URL-yada cusub"
COM_REDIRECT_BATCH_TIP="Geli URL-ka dhacay (waa khasab) oo leh URL cusub (ikhtiyaari ah) oo u kala qaybsan %1$s (tusaale url-ka-hore%1$surl-ka-cusub). Kasta xariiq mid gelis ah!"
COM_REDIRECT_BATCH_UPDATE_WITH_NEW_URL="Cusboonaysiinta Jumlada URL-lasha la xushay"
COM_REDIRECT_BULK_SEPARATOR_DESC="Kala saaraha loo adeegsado soo dejinta jaadka, caadi ahaan waa '|' laakiin waxay noqon kartaa ',' haddii ay tahay nuqul / dhejin laga sameeyay faylka CSV tusaale ahaan."
COM_REDIRECT_BULK_SEPARATOR_LABEL="Kala Soocida Soo Dejinta Jumlada"
COM_REDIRECT_BUTTON_UPDATE_LINKS="Cusboonaysiinta Xiriirada"
COM_REDIRECT_CLEAR_FAIL="Ku guuldareystay in la tirtiro xiriirinta aan shaqeyn."
COM_REDIRECT_CLEAR_SUCCESS="Dhammaan xiriirinta aan shaqeyn ayaa la tirtiray."
COM_REDIRECT_COLLECT_MODAL_URLS_DISABLED="%1$s Ikhtiyaarka 'Ururi URLs' ee %2$s wuu naafo yahay. URL-yada bogga khaladka ah laguma ururin doono xidhiidhka."
COM_REDIRECT_COLLECT_URLS_ENABLED="%1$s Ikhtiyaarka 'Ururi URLs' waa la furay."
COM_REDIRECT_CONFIGURATION="Ku laabashada: Ikhtiyaarrada"
COM_REDIRECT_CONFIRM_PURGE="Ma hubtaa inaad rabto inaad tirtirto dhammaan xiriirinta aan shaqeyn?"
COM_REDIRECT_DEFAULT_IMPORT_STATE_DESC="Marka la soo dejinayo jaadka, si otomaatig ah u fur ama u demmi."
COM_REDIRECT_DEFAULT_IMPORT_STATE_LABEL="Xaaladda Soo Dejinta"
COM_REDIRECT_DISABLE_LINK="Naafo Xiriirka"
COM_REDIRECT_EDIT_LINK="Wax ka beddel Xiriirka #%d"
COM_REDIRECT_EDIT_PLUGIN_SETTINGS="Wax ka beddel Dejinta Plugin-ka"
COM_REDIRECT_EMPTYSTATE_BUTTON_ADD="Kudar xiriir cusub"
COM_REDIRECT_EMPTYSTATE_CONTENT="Ku hanuuni URLs bogagga webka ee aan ka jiri jirin degelkaaga bogagga webka ee shaqeynaya."
COM_REDIRECT_EMPTYSTATE_TITLE="Ku laabashada: Xiriirada"
COM_REDIRECT_ENABLE_LINK="Fur Xiriirka"
COM_REDIRECT_ERROR_DESTINATION_URL_REQUIRED="Ku hanuuninta waa inay lahaato URL-destination ah"
COM_REDIRECT_ERROR_DUPLICATE_OLD_URL="URL-ka isha waa inuu noqdaa mid gaar ah."

COM_REDIRECT_ERROR_DUPLICATE_URLS="Ilaha iyo meelaha isku socota URL-yadu ma noqon karaan kuwo isku mid ah."
COM_REDIRECT_ERROR_SOURCE_URL_REQUIRED="Redirect-kan waa inuu yeesho URL ilaha."
COM_REDIRECT_FIELD_COMMENT_LABEL="Faallo"
COM_REDIRECT_FIELD_CREATED_DATE_LABEL="Taariikhda la abuuray"
COM_REDIRECT_FIELD_NEW_URL_DESC="Geli URL-ka aad rabto in loo leexiyo."
COM_REDIRECT_FIELD_NEW_URL_LABEL="URL cusub"
COM_REDIRECT_FIELD_OLD_URL_DESC="Geli URL-ka la rabo in loo leexiyo."
COM_REDIRECT_FIELD_OLD_URL_LABEL="URL qadiim ah"
COM_REDIRECT_FIELD_REDIRECT_STATUS_CODE_DESC="Xulo koodka status-ka HTTP 1.1 ee lala xiriirinayo dib u celinta. Koodhadhka kaliya ee laga bilaabo 300-399 waxay la jaanqaadaan dib u celinta."
COM_REDIRECT_FIELD_REDIRECT_STATUS_CODE_LABEL="Koodka Status-ka Dib u Celinta"
COM_REDIRECT_FIELD_REFERRER_LABEL="Isku xiraha Tixraacaha"
COM_REDIRECT_FIELD_UPDATED_DATE_LABEL="Taariikhda Ugu Danbeysay ee La Cusbooneysiiyey"
COM_REDIRECT_FILTER_SEARCH_DESC="Raadi URL-ka qadiimka ah, URL cusub, bogga tixraacaya iyo faallada. Ku bixi ID: si aad ugu raadsato aqoonsiga isku xiraha."
COM_REDIRECT_FILTER_SEARCH_LABEL="Raadi Xidhiidhada"
COM_REDIRECT_FILTER_SELECT_OPTION_HTTP_HEADER="- Dooro Koodhka Status-ka HTTP -"
COM_REDIRECT_FORM_EDIT="Wax ka beddel Dib-u-celinta"
COM_REDIRECT_FORM_NEW="Dib-u-celin Cusub"
COM_REDIRECT_HEADING_CREATED_DATE="Taariikhda la abuuray"
COM_REDIRECT_HEADING_CREATED_DATE_ASC="Taariikhda la abuuray kor u kac"
COM_REDIRECT_HEADING_CREATED_DATE_DESC="Taariikhda la abuuray hoos u dhaca"
COM_REDIRECT_HEADING_HITS="404 Durbaan"
COM_REDIRECT_HEADING_HITS_ASC="404 Durbaan kor u kac"
COM_REDIRECT_HEADING_HITS_DESC="404 Durbaan hoos u dhaca"
COM_REDIRECT_HEADING_NEW_URL="URL cusub"
COM_REDIRECT_HEADING_NEW_URL_ASC="URL cusub oo kor u kac"
COM_REDIRECT_HEADING_NEW_URL_DESC="URL cusub hoos u sii socda"
COM_REDIRECT_HEADING_OLD_URL="URL-duqowday"
COM_REDIRECT_HEADING_OLD_URL_ASC="URL-duqowday kor u sii socda"
COM_REDIRECT_HEADING_OLD_URL_DESC="URL-duqowday hoos u sii socda"
COM_REDIRECT_HEADING_REFERRER="Bogga Tixraaca"
COM_REDIRECT_HEADING_REFERRER_ASC="Bogga Tixraaca kor u sii socda"
COM_REDIRECT_HEADING_REFERRER_DESC="Bogga Tixraaca hoos u sii socda"
COM_REDIRECT_HEADING_STATUS_CODE="Koodhka Xaaladda"
COM_REDIRECT_HEADING_STATUS_CODE_ASC="Koodhka Xaaladda kor u sii socda"
COM_REDIRECT_HEADING_STATUS_CODE_DESC="Koodhka Xaaladda hoos u sii socda"
COM_REDIRECT_MANAGER_LINK_EDIT="Dib-u-celinta: Wax-ka-beddelka"
COM_REDIRECT_MANAGER_LINK_NEW="Dib-u-celinta: Cusub"
COM_REDIRECT_MANAGER_LINKS="Dib-u-celinta: Xiriirada"
COM_REDIRECT_MODE_DESC="Habka Horumarsan wuxuu ogolaanayaa isticmaalka koodhadhka xaaladda HTTP 1.1 oo ka duwan caadiga '301 Si joogto ah loo raray'."
COM_REDIRECT_MODE_LABEL="Dhaqangeli Habka Horumarsan"
COM_REDIRECT_N_ITEMS_ARCHIVED="%d xiriir iyo galin."
COM_REDIRECT_N_ITEMS_ARCHIVED_1="Xiriirka la geliyay."
COM_REDIRECT_N_ITEMS_DELETED="%d xiriir la tirtiray."
COM_REDIRECT_N_ITEMS_DELETED_1="Xiriirka la tirtiray."
COM_REDIRECT_N_ITEMS_PUBLISHED="%d xiriir firfircoon."
COM_REDIRECT_N_ITEMS_PUBLISHED_1="Xiriirka firfircoon."
COM_REDIRECT_N_ITEMS_TRASHED="%d xiriir qashinka."
COM_REDIRECT_N_ITEMS_TRASHED_1="Xiriirka qashinka."
COM_REDIRECT_N_ITEMS_UNPUBLISHED="%d xiriir naafo ah."
COM_REDIRECT_N_ITEMS_UNPUBLISHED_1="Xiriirka naafo ah."
COM_REDIRECT_N_LINKS_ADDED="%d xiriiryo lagu daray."
COM_REDIRECT_N_LINKS_ADDED_1="Xiriiriye ayaa lagu daray."
COM_REDIRECT_N_LINKS_UPDATED="%d xiriiryo la cusbooneysiiyay."
COM_REDIRECT_N_LINKS_UPDATED_1="Xiriiriye la cusbooneysiiyay."
COM_REDIRECT_NEW_LINK="Xiriiriye Cusub"
COM_REDIRECT_NO_ITEM_ADDED="Xiriir lama darin."
COM_REDIRECT_NO_ITEM_SELECTED="Xiriir lama xulan."
COM_REDIRECT_NO_SEPARATOR_FOUND="Kala-soocidda %s lama helin marka aad wax soo dhoofsato."
COM_REDIRECT_PLUGIN_ENABLED="Qalabka Redirect Plugin waa la hawlgeliyay."
COM_REDIRECT_PLUGIN_MODAL_DISABLED="%s waa dansan yahay. Waa in la shaqeyn si qaybtaan ay u shaqeyso."
COM_REDIRECT_REDIRECTED_ON="Loo gudbiyay: %s."
COM_REDIRECT_SAVE_SUCCESS="Xiriiriyaha waa la badbaadiyay."
COM_REDIRECT_SEARCH_LINKS="Raadi goobaha xiriirka."
COM_REDIRECT_SYSTEM_PLUGIN="Nidaamka Redirect Plugin"
COM_REDIRECT_TOOLBAR_PURGE="Nadiifi Naafada"
COM_REDIRECT_XML_DESCRIPTION="Qaybtani waxay qabataa hagidda isku xirka."
COM_REDIRECTS_TABLE_CAPTION="Xiriirrada Hagidda"

JLIB_RULES_SETTING_NOTES_COM_REDIRECT="Isbeddeladu waxay khuseeyaan qaybtaan oo keliya.<br><em><strong>La dhaxlay</strong></em> - Dejinta Qaab Guud ama heer sarreysa ayaa la adeegsanayaa.<br><em><strong>La diiday</strong></em> mar walba ayaa guuleysta - wax kasta oo lagu dejiyo heerkul guud ama heer sare, waxayna ku khuseysaa dhammaan walxaha la dhaxlay.<br><em><strong>La ansixiyay</strong></em> waxay suurtogal ka dhigi doontaa tallaabada qaybtan ilaa ay ku baabi'iso Dejinta Qaab Guud."

