; Joomla! Project
; (C) 2016 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_FIELDS="Goobaha"
COM_FIELDS_BATCH_GROUP_LABEL="Si aad u dhaqaaqdid ama aad u koobiyaysatid doorashadaada fadlan dooro koox."
COM_FIELDS_BATCH_GROUP_OPTION_NONE="- Koox Ma Jirto -"
COM_FIELDS_CHOOSE_CONTEXT_LABEL="Xaalad"
COM_FIELDS_ERROR_UNIQUE_NAME="Goob kale ayaa isla magaca leh (xusuusnow waa wax la tuuray ama waxaa laga yaabaa inuu horey u jiro sida goob gaar ah oo ku saabsan kordhis kale)."
COM_FIELDS_FIELD_CLASS_DESC="Astaamaha fasalka ee goobta foomka wax-ka-beddelka. Haddii fasallo badan loo baahdo, ku sheeg meel bannaan."
COM_FIELDS_FIELD_CLASS_LABEL="Fasalka Goobta"
COM_FIELDS_FIELD_DEFAULT_VALUE_LABEL="Qiimaha Hore ee La Siiyo"
COM_FIELDS_FIELD_DISPLAY_AFTER_DISPLAY="Kadib Mawduuca Bandhigidda"
COM_FIELDS_FIELD_DISPLAY_AFTER_TITLE="Kadib Cinwaanka"
COM_FIELDS_FIELD_DISPLAY_BEFORE_DISPLAY="Ka hor Mawduuca Bandhigidda"
COM_FIELDS_FIELD_DISPLAY_LABEL="Bandhigga Tooska ah"
COM_FIELDS_FIELD_DISPLAY_NO_DISPLAY="Ha ishiinku si toos ah u soo bandhigin"
COM_FIELDS_FIELD_EDITABLE_IN_ADMIN="Maamulaha"
COM_FIELDS_FIELD_EDITABLE_IN_BOTH="Labada"
COM_FIELDS_FIELD_EDITABLE_IN_LABEL="Waxaa Lagu Beddeli Karaa"
COM_FIELDS_FIELD_EDITABLE_IN_SITE="Bogga"
COM_FIELDS_FIELD_FORM_EDIT="Goobta Wax Ka Beddel"
; The following string is deprecated and will be removed with 6.0
COM_FIELDS_FIELD_FORM_LAYOUT_LABEL="Qaabeynta"
COM_FIELDS_FIELD_FORM_NEW="Goob Cusub"
COM_FIELDS_FIELD_FORMOPTIONS_HEADING="Xulashooyinka Foomka"
COM_FIELDS_FIELD_GROUP_LABEL="Kooxda Goobaha"
COM_FIELDS_FIELD_IMAGE_ALT_DESC="Qoraal beddel ah oo loo adeegsado booqdayaasha aan heli karin sawirada."
COM_FIELDS_FIELD_IMAGE_ALT_LABEL="Qoraal Beddel"
COM_FIELDS_FIELD_IMAGE_DESC="Sumadda Sawirka."
COM_FIELDS_FIELD_IMAGE_LABEL="Sawir"
COM_FIELDS_FIELD_INVALID_DEFAULT_VALUE="Qiimaha caadiga ah waa mid aan sax ahayn."
COM_FIELDS_FIELD_LABEL_FORM_CLASS_LABEL="Fasalka Cinwaanka (Foomka)"
COM_FIELDS_FIELD_LABEL_LABEL="Cinwaan"
COM_FIELDS_FIELD_LABEL_RENDER_CLASS_LABEL="Fasalka Cinwaanka (Soo Bixitaanka)"
COM_FIELDS_FIELD_LAYOUT_LABEL="Qaab-dhismeed"
COM_FIELDS_FIELD_N_ITEMS_ARCHIVED="%d beeraha la dersay"
COM_FIELDS_FIELD_N_ITEMS_ARCHIVED_1="Beer la dersay"
COM_FIELDS_FIELD_N_ITEMS_CHECKED_IN="%d beeraha la hubiyay"
COM_FIELDS_FIELD_N_ITEMS_CHECKED_IN_1="Beer la hubiyay"
COM_FIELDS_FIELD_N_ITEMS_DELETED="%d beeraha la tirtiray"
COM_FIELDS_FIELD_N_ITEMS_DELETED_1="Beer la tirtiray"
COM_FIELDS_FIELD_N_ITEMS_PUBLISHED="%d beeraha la daabacay"
COM_FIELDS_FIELD_N_ITEMS_PUBLISHED_1="Beer la daabacay"
COM_FIELDS_FIELD_N_ITEMS_TRASHED="%d beeraha la qashinsaaray"
COM_FIELDS_FIELD_N_ITEMS_TRASHED_1="Beer la qashinsaaray"
COM_FIELDS_FIELD_N_ITEMS_UNPUBLISHED="%d beeraha aan la daabacin"
COM_FIELDS_FIELD_N_ITEMS_UNPUBLISHED_1="Beer aan la daabacin"
COM_FIELDS_FIELD_NOTE_LABEL="Qoraal"
COM_FIELDS_FIELD_ONLY_USE_IN_SUBFORM_BADGE="Subform Kaliya"
COM_FIELDS_FIELD_ONLY_USE_IN_SUBFORM_LABEL="Isticmaal Kaliya Subform"
COM_FIELDS_FIELD_PLACEHOLDER_DESC="Qoraalka wax ku meel gaarka ah kaasoo ka dhex muuqan doona beerka sida tilmaanta isticmaalaha ee wax galinta loo baahan yahay."
COM_FIELDS_FIELD_PLACEHOLDER_LABEL="Qoraalka wax ku meel gaarka ah"
COM_FIELDS_FIELD_PREFIX_LABEL="Hordhac"
COM_FIELDS_FIELD_RENDER_CLASS_DESC="Fasalka weelka beerka ee soo bixitaanka."
COM_FIELDS_FIELD_RENDER_CLASS_LABEL="Fasalka Muujinta"
COM_FIELDS_FIELD_RENDEROPTIONS_HEADING="Xulashooyinka Muujinta"
COM_FIELDS_FIELD_REQUIRED_LABEL="Waa loo baahanyahay"
COM_FIELDS_FIELD_SAVE_SUCCESS="Goobta waa la keydiyey"
COM_FIELDS_FIELD_SEARCHINDEX_BOTH="Ka dhig la raadin karo oo ku dar sida tixraac"
COM_FIELDS_FIELD_SEARCHINDEX_DESC="Digniin: Marka 'Ka dhig la raadin karo' la doorto, waxa ku jira goobta waxa lagu tixraacaa oo leh oggolaanshaha daawashada walxaha ku jira. Taas waxaa laga yaabaa inay horseeddo shaaca ka qaadista macluumaad aan la filayn."
COM_FIELDS_FIELD_SEARCHINDEX_DONT="Ha ka dhigin la raadin karo"
COM_FIELDS_FIELD_SEARCHINDEX_LABEL="Tusmada Raadinta"
COM_FIELDS_FIELD_SEARCHINDEX_SEARCHABLE="Ka dhig la raadin karo"
COM_FIELDS_FIELD_SEARCHINDEX_TAXONOMY="Ku dar sida tixraac"
COM_FIELDS_FIELD_SHOWLABEL_DESC="Muuji ama qari summada marka goobta la soo bandhigo."
COM_FIELDS_FIELD_SHOWLABEL_LABEL="Sumadda"
COM_FIELDS_FIELD_SHOWON_DESC="Sharci ku muujin ama qari goobta iyadoo ku xiran qiimaha goobo kale."
COM_FIELDS_FIELD_SHOWON_LABEL="Astaanta Muujinta"
COM_FIELDS_FIELD_SMARTSEARCHOPTIONS_HEADING="Raadinta Caqliga"
COM_FIELDS_FIELD_SUFFIX_LABEL="Dabayg"
COM_FIELDS_FIELD_TYPE_LABEL="Nooca"
COM_FIELDS_FIELD_USE_GLOBAL="Ka faa'iidayso dejimaha Plugin"
COM_FIELDS_FIELD_VALUE_RENDER_CLASS_DESC="Fasalka qiimaha goobta ee soo saarka."
COM_FIELDS_FIELD_VALUE_RENDER_CLASS_LABEL="Fasalka Qiimaha"
COM_FIELDS_FIELDS_FILTER_ONLY_USE_IN_SUBFORM_LABEL="Ku isticmaal Kaliya Foomka Hoosaadka"
COM_FIELDS_FIELDS_FILTER_SEARCH_DESC="Raadi magaca goobta, cinwaanka ama qoraalka. Ku bilow ID: si aad u raadiso aqoonsiga goobta. Ku bilow AUTHOR: si aad u raadiso qoraa goobta."
COM_FIELDS_FIELDS_FILTER_SEARCH_LABEL="Goobo Raadinta"
COM_FIELDS_FIELDS_TABLE_CAPTION="Goobaha"
COM_FIELDS_GROUP_FORM_EDIT="Tafatir Kooxda Goobta"
COM_FIELDS_GROUP_FORM_NEW="Koox Goob Cusub"
COM_FIELDS_GROUP_N_ITEMS_ARCHIVED="%d kooxo goobood kaydisan"
COM_FIELDS_GROUP_N_ITEMS_ARCHIVED_1="Koox goob kaydsan"
COM_FIELDS_GROUP_N_ITEMS_CHECKED_IN="%d kooxo goobood la hubiyey"
COM_FIELDS_GROUP_N_ITEMS_CHECKED_IN_1="Koox goob la hubiyey"
COM_FIELDS_GROUP_N_ITEMS_DELETED="%d kooxo goobood la masaxay"
COM_FIELDS_GROUP_N_ITEMS_DELETED_1="Koox goob la masaxay"
COM_FIELDS_GROUP_N_ITEMS_PUBLISHED="%d kooxo goobood la daabacay"
COM_FIELDS_GROUP_N_ITEMS_PUBLISHED_1="Koox goob la daabacay"
COM_FIELDS_GROUP_N_ITEMS_TRASHED="%d kooxo goobood la tuuray"
COM_FIELDS_GROUP_N_ITEMS_TRASHED_1="Koox goob la tuuray"
COM_FIELDS_GROUP_N_ITEMS_UNPUBLISHED="%d kooxo goobood aan la daabicin"
COM_FIELDS_GROUP_N_ITEMS_UNPUBLISHED_1="Koox goob aan la daabicin"
COM_FIELDS_GROUP_SAVE_SUCCESS="Koox Goob la keydiyey"
COM_FIELDS_GROUPS_FILTER_SEARCH_DESC="Raadi cinwaanka kooxda goobta. Hore ugu dar ID: si aad ugu raadsato aqoonsiga kooxda goobta."
COM_FIELDS_GROUPS_FILTER_SEARCH_LABEL="Raadi Kooxo Goobo"
COM_FIELDS_GROUPS_TABLE_CAPTION="Kooxo Goobo"
COM_FIELDS_MUSTCONTAIN_A_TITLE_FIELD="Goobtu waa inay lahaato cinwaan."
COM_FIELDS_MUSTCONTAIN_A_TITLE_GROUP="Kooxda Goob waxaa loo baahan yahay inay lahaato cinwaan."
COM_FIELDS_NO_FIELDS_TO_CREATE_SUBFORM_FIELD_WARNING="Waa inaad abuurtaa goobaha caadiga ah inta aanad abuurin goobka Isugeynta."
COM_FIELDS_ONLY_USE_IN_SUBFORM="- Isticmaal kaliya Isugeynta -"
COM_FIELDS_ONLY_USE_IN_SUBFORM_ANY="Qaab kasta"
COM_FIELDS_ONLY_USE_IN_SUBFORM_SUBFORM="Kaliya Isugeynta"
COM_FIELDS_SEARCHINDEX_MIGHT_REQUIRE_REINDEXING="Fadlan ogow, isbedelladaaga Maareeyaha Goobaha La Habeeyey waxay u baahan karaan inaad dib ugu dhisto tusaha Smart Search."
COM_FIELDS_SYSTEM_PLUGIN_NOT_ENABLED="<a href=\"%s\">Nidaamka - Goobo</a> taageeraha waa naafo. Goobaha la habeeyey kama muuqan doonaan ilaa aad taageeradan awood siiso."
COM_FIELDS_VIEW_FIELD_ADD_TITLE="%s: Garoon Cusub"
COM_FIELDS_VIEW_FIELD_EDIT_TITLE="%s: Wax ka Beddel Garoonka"
COM_FIELDS_VIEW_FIELD_FIELDSET_GENERAL="Guud"
COM_FIELDS_VIEW_FIELDS_BATCH_OPTIONS="Hawlgeli geedi socodka garoomada la doortay."
COM_FIELDS_VIEW_FIELDS_SELECT_CATEGORY="- Dooro Qaybta Loo Qaybiyey -"
COM_FIELDS_VIEW_FIELDS_SELECT_GROUP="- Dooro Kooxda Garoonka -"
COM_FIELDS_VIEW_FIELDS_SORT_GROUP_ASC="Kooxda Garoonka oo soo kordhaysa"
COM_FIELDS_VIEW_FIELDS_SORT_GROUP_DESC="Kooxda Garoonka oo hoos u dhacaysa"
COM_FIELDS_VIEW_FIELDS_SORT_TYPE_ASC="Nooca oo soo kordhaysa"
COM_FIELDS_VIEW_FIELDS_SORT_TYPE_DESC="Nooca oo hoos u dhacaysa"
COM_FIELDS_VIEW_FIELDS_TITLE="%s: Garoomada"
COM_FIELDS_VIEW_GROUP_ADD_TITLE="%s: Koox Garoon Cusub"
COM_FIELDS_VIEW_GROUP_EDIT_TITLE="%s: Wax ka Beddel Kooxda Garoonka"
COM_FIELDS_VIEW_GROUPS_BATCH_OPTIONS="Hawlgeli geedi socodka kooxaha garoomada ee la doortay."
COM_FIELDS_VIEW_GROUPS_TITLE="%s: Kooxaha Garoomada"
COM_FIELDS_XML_DESCRIPTION="Qayb loo adeegsado maareynta garoomada gaarka ah."

