; Joomla! Project
; (C) 2009 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_MENUS="Liiska"
COM_MENUS_ITEM_VIEW_EDIT_DESC="Waxay soo bandhigaysaa foom loogu talagalay in lagu abuuro waxyaabo cusub oo liis ah"
COM_MENUS_ITEM_VIEW_EDIT_TITLE="Waxyaabaha Cusub ee Liiska"
COM_MENUS_ITEMS_CHOOSE_MENU_DESC="Dooro Nooca Liiska bogga bartilmaameedka.<br><br>Kuma noqotid in lala midoobo <strong>Liiska</strong> hoostiisa kaas oo waxa liiskaan lagu meeleyn doono."
COM_MENUS_ITEMS_CHOOSE_MENU_LABEL="Dooro Nooca Liiska"
COM_MENUS_ITEMS_VIEW_DEFAULT_DESC="Waxay soo bandhigaysaa liiska waxyaabaha liiska"
COM_MENUS_ITEMS_VIEW_DEFAULT_TITLE="Waxyaabaha Liiska"
COM_MENUS_MENU_VIEW_EDIT_DESC="Waxay soo bandhigaysaa foom loogu talagalay in lagu abuuro liis cusub"
COM_MENUS_MENU_VIEW_EDIT_TITLE="Liis Cusub"
COM_MENUS_MENUS_PRESET_ALTERNATE="Preset - Liiska Mainka Guud ee Beddelka"
COM_MENUS_MENUS_PRESET_COMPONENTS="Preset - Dashboardka Qaybaha"
COM_MENUS_MENUS_PRESET_DEFAULT="Preset - Liiska Mainka Guud ee Joomla"
COM_MENUS_MENUS_PRESET_HELP="Preset - Dashboardka Caawinta"
COM_MENUS_MENUS_PRESET_MENUS="Preset - Dashboardka Liisaska"
COM_MENUS_MENUS_PRESET_SYSTEM="Preset - Dashboardka Nidaamka"
COM_MENUS_MENUS_VIEW_DEFAULT_DESC="Waxay soo bandhigaysaa liiska Noocyada Liiska"
COM_MENUS_MENUS_VIEW_DEFAULT_TITLE="Liiska"
COM_MENUS_XML_DESCRIPTION="Qaybta loogu talagalay in lagu abuuro liisaska."

