; Joomla! Project
; (C) 2007 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_INSTALLER="Rakibo"
COM_INSTALLER_DATABASE_VIEW_DEFAULT_DESC="Hubi oo cusbooneysii wixii dhibaato ah ee qaab-dhismeedka xogta ee ku saabsan boggaaga internetka."
COM_INSTALLER_DATABASE_VIEW_DEFAULT_TITLE="Hubi Xogta"
COM_INSTALLER_DATABASE_VIEW_DISPLAY_BADGE="Soo Bandhig Astaanta"
COM_INSTALLER_DISCOVER_VIEW_DEFAULT_DESC="Ogow kordhin aan soo marin habka rakibida caadiga ah."
COM_INSTALLER_DISCOVER_VIEW_DEFAULT_TITLE="Ogow Kordhin"
COM_INSTALLER_DISCOVER_VIEW_DISPLAY_BADGE="Soo Bandhig Astaanta"
COM_INSTALLER_INSTALL_VIEW_DEFAULT_DESC="Rakib kordhinta ku dhex rakibida Joomla! eeaga."
COM_INSTALLER_INSTALL_VIEW_DEFAULT_TITLE="Rakib Kordhin"
COM_INSTALLER_LANGUAGES_VIEW_DEFAULT_DESC="Ku rakib xidhmooyinka luqadda boggaaga Joomla!"
COM_INSTALLER_LANGUAGES_VIEW_DEFAULT_TITLE="Rakib Luqadaha"
COM_INSTALLER_MANAGE_VIEW_DEFAULT_DESC="Maamul kordhinta horey loogu rakibay boggaaga Joomla!"
COM_INSTALLER_MANAGE_VIEW_DEFAULT_TITLE="Maamul Kordhin"
COM_INSTALLER_UPDATE_VIEW_DEFAULT_DESC="Raadi oo Rakib cusbooneysiinta kordhinta la rakibay."
COM_INSTALLER_UPDATE_VIEW_DEFAULT_TITLE="Cusbooneysii Kordhin"
COM_INSTALLER_UPDATE_VIEW_DISPLAY_BADGE="Soo Bandhig Astaanta"
COM_INSTALLER_UPDATESITES_VIEW_DEFAULT_DESC="Soo bandhig liiska dhamaan goobaha cusbooneysiinta ee la hubin doono."
COM_INSTALLER_UPDATESITES_VIEW_DEFAULT_TITLE="Goobaha Cusbooneysiinta"
COM_INSTALLER_WARNINGS_VIEW_DEFAULT_DESC="Soo bandhig digniino la xiriira kordhinta lagu rakibay."
COM_INSTALLER_WARNINGS_VIEW_DEFAULT_TITLE="Digniino"
COM_INSTALLER_WARNINGS_VIEW_DISPLAY_BADGE="Soo Bandhig Astaanta"
COM_INSTALLER_XML_DESCRIPTION="Qaybta rakibida ee loogu talagalay ku darista, ka saariska iyo horumarinta kordhinta."

