; Joomla! Project
; (C) 2007 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_CONFIG="Qaabeynta"  
COM_CONFIG_COMPONENT_VIEW_DEFAULT_DESC="Soo bandhig ikhtiyaarada qaabeynta ee qaybta la xulay."  
COM_CONFIG_COMPONENT_VIEW_DEFAULT_TITLE="Ikhtiyaarada Qaabeynta Qaybta"  
COM_CONFIG_CONFIG_VIEW_DEFAULT_DESC="Waxay soo bandhigeysaa ikhtiyaarada qaabeynta guud ee goobta."  
COM_CONFIG_CONFIG_VIEW_DEFAULT_TITLE="Ikhtiyaarada Qaabeynta Goobta"  
COM_CONFIG_TEMPLATES_VIEW_DEFAULT_DESC="Waxay soo bandhigeysaa ikhtiyaarada heerka tusmada haddii tusmadu ogolaato tan."  
COM_CONFIG_TEMPLATES_VIEW_DEFAULT_TITLE="Soo Bandhig Ikhtiyaarada Tusaalaha"  
COM_CONFIG_XML_DESCRIPTION="Maareeyaha Qaabeynta"

