; Joomla! Project
; (C) 2016 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_FIELDS="Beeraha"  
COM_FIELDS_CHOOSE_COMPONENT_LABEL="Dooro Qayb"  
COM_FIELDS_FIELDS_VIEW_DEFAULT_DESC="Waxay muujinaysaa liis dhammaan beeraha."  
COM_FIELDS_FIELDS_VIEW_DEFAULT_TITLE="Liisaska Dhammaan Beeraha"  
COM_FIELDS_GROUPS_VIEW_DEFAULT_DESC="Waxay muujinaysaa liis dhammaan kooxaha beeralayda."  
COM_FIELDS_GROUPS_VIEW_DEFAULT_TITLE="Liisaska Dhammaan Kooxaha Beeralayda"  
COM_FIELDS_XML_DESCRIPTION="Qaybta maamula beeraha gaarka ah."

