; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_PLUGINS="Kudarrooyinka"
COM_PLUGINS_CONFIGURATION="Kudarro: Xulashoyinka"
COM_PLUGINS_ELEMENT_HEADING="Unsur"
COM_PLUGINS_ERROR_FILE_NOT_FOUND="Faylka %s lama heli karo."
COM_PLUGINS_FIELD_ELEMENT_LABEL="Faylka Kudarro"
COM_PLUGINS_FIELD_FOLDER_LABEL="Nooca Kudarro"
COM_PLUGINS_FIELD_NAME_LABEL="Magaca Kudarro"
COM_PLUGINS_FILTER_SEARCH_LABEL="Raadi Kudarrooyinka"
COM_PLUGINS_FOLDER_HEADING="Nooca"
COM_PLUGINS_FORM_EDIT="Foomka Wax-ka-beddel"
COM_PLUGINS_HEADING_ELEMENT_ASC="Unsurka kor kordhaya"
COM_PLUGINS_HEADING_ELEMENT_DESC="Unsurka hoos u dhacaya"
COM_PLUGINS_HEADING_FOLDER_ASC="Nooca kor kordhaya"
COM_PLUGINS_HEADING_FOLDER_DESC="Nooca hoos u dhacaya"
COM_PLUGINS_MANAGER_PLUGIN="Kudarrooyinka: %s"
COM_PLUGINS_MANAGER_PLUGINS="Kudarrooyinka"
COM_PLUGINS_N_ITEMS_CHECKED_IN_1="Kudarro la saxay."
COM_PLUGINS_N_ITEMS_CHECKED_IN_MORE="%d kudarro ayaa la saxay."
COM_PLUGINS_N_ITEMS_PUBLISHED="%d kudarro ayaa la oggolaaday."
COM_PLUGINS_N_ITEMS_PUBLISHED_1="Kudarro la oggolaaday."
COM_PLUGINS_N_ITEMS_UNPUBLISHED="%d kudarro ayaa la diiday."
COM_PLUGINS_N_ITEMS_UNPUBLISHED_1="Kudarro la diiday."
COM_PLUGINS_N_QUICKICON="Kudarrooyinka"
COM_PLUGINS_N_QUICKICON_1="Kudarro"
COM_PLUGINS_N_QUICKICON_SRONLY="Kudarrooyinka: %d kudarro ayaa la oggolaaday."
COM_PLUGINS_N_QUICKICON_SRONLY_1="Plugins: Hal plugin ayaa shaqaynaya."
COM_PLUGINS_NAME_HEADING="Magaca Plugin"
COM_PLUGINS_NO_ITEM_SELECTED="Wax plugins ah lama xulin."
COM_PLUGINS_OPTION_ELEMENT="- Xulo Qayb -"
COM_PLUGINS_OPTION_FOLDER="- Xulo Nooca -"
COM_PLUGINS_PLUGIN="Plugin"
COM_PLUGINS_SAVE_SUCCESS="Plugin waa la kaydshay."
COM_PLUGINS_SEARCH_IN_TITLE="Raadi magaca plugin-ka. Ku bilaab ID: si aad ugu raadsato ID plugin."
COM_PLUGINS_TABLE_CAPTION="Plugins"
COM_PLUGINS_XML_DESCRIPTION="Qeybtaan waxay maamushaa Joomla plugins."
COM_PLUGINS_XML_ERR="Macluumaadka XML plugins lama heli karo."
JLIB_HTML_PUBLISH_ITEM="Furi plugin"
JLIB_HTML_UNPUBLISH_ITEM="Xir plugin"

JLIB_RULES_SETTING_NOTES_COM_PLUGINS="Isbeddelladu waxay khuseeyaan qaybtaan oo kaliya.<br><em><strong>Dhaxalgal</strong></em> - goobta Dejin caalami ah ama heer sare ah ayaa la adeegsadaa.<br><em><strong>Diidday</strong></em> had iyo jeer guulaysato - wixii lagu dejiyey heerka Caalami ama heer sare ah waxayna khuseeyaan dhammaan qaybaha hoose.<br><em><strong>Ogolaaday</strong></em> waxay ogolaan doontaa ficilka qaybtaan ilaa laga hor istaago goobo kale oo Dejin caalami ah."

