; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_MEDIA="Warbaahinta"
COM_MEDIA_ACTIONS_TOOLBAR_LABEL="Qayb: %s"
COM_MEDIA_ACTION_DELETE="Tirtir"
COM_MEDIA_ACTION_DOWNLOAD="Soo dejiso"
COM_MEDIA_ACTION_EDIT="Tafatir"
COM_MEDIA_ACTION_PREVIEW="Muuqaalka hore"
COM_MEDIA_ACTION_RENAME="Magac bedel"
COM_MEDIA_ACTION_SHARE="Ka hel Xiriir"
COM_MEDIA_BREADCRUMB_LABEL="Raad-raac"
COM_MEDIA_BROWSER_TABLE_CAPTION="Nuxurka Faylka %s"
COM_MEDIA_CHANGE_ORDERING="Bedel Amar"
COM_MEDIA_CONFIGURATION="Warbaahinta: Xulashooyinka"
COM_MEDIA_CONFIRM_DELETE_MODAL="Tirtir"
COM_MEDIA_CONFIRM_DELETE_MODAL_HEADING="Xaqiiji Tirtirka"
COM_MEDIA_COPY_FILE_NOT_POSSIBLE_FILE_ALREADY_EXISTS="Nuqul faylka ma suurtagal ah maaddaama faylka meel ujeedadiisu mar hore uu jiro"
COM_MEDIA_COPY_FILE_NOT_POSSIBLE="Nuqul faylka ma suurtagal ah"
COM_MEDIA_COPY_FOLDER_ALREADY_EXISTS="Nuqul fayl ma suurtagal ah maaddaama faylka meel ujeedadiisu mar hore uu jiro"
COM_MEDIA_COPY_FOLDER_DESTINATION_CAN_NOT_DELETE="Nuqul fayl ma suurtagal ah maaddaama faylka meel ujeedadiisu uu yahay fayl oo aan la tirtiri karin"
COM_MEDIA_COPY_FOLDER_NOT_POSSIBLE="Nuqul fayl ma suurtagal ah"
COM_MEDIA_CREATE_NEW_FOLDER="Abuur Fayl Cusub"
COM_MEDIA_CREATE_NEW_FOLDER_ERROR="Cilad abuurista faylka."
COM_MEDIA_CREATE_NEW_FOLDER_EXISTING_FOLDER_ERROR="Fayl ama fayl magaciisu mar hore wuu jirtaa."
COM_MEDIA_CREATE_NEW_FOLDER_RELATIVE_PATH_ERROR="Isticmaalka waddooyinka qaraabo lama ogola."
COM_MEDIA_CREATE_NEW_FOLDER_SUCCESS="Faylka waa la abuuray."
COM_MEDIA_CREATE_NEW_FOLDER_UNEXPECTED_CHARACTER="Magaca faylka aan sax ahayn. Fadlan dooro magac faylal leh a-z, A-Z, 0-9, ., - iyo _."
COM_MEDIA_DECREASE_GRID="Yaree cabirka shabakadda"
COM_MEDIA_DELETE="Ma hubtaa inaad rabto inaad tirtirto shayga(yaashan) la xulay? Ficilkani waa joogto waxayna dib loo soo celin karin. Haddii aad tirtirto gal, dhammaan waxa ku jira waa la tirtiri doonaa."
COM_MEDIA_DELETE_ERROR="Khalad ayaa ka dhacay tirtirka shayga."
COM_MEDIA_DELETE_NOT_POSSIBLE="Tirtirista suurtagal maaha!"
COM_MEDIA_DELETE_SUCCESS="Shayga waa la tirtiray."
COM_MEDIA_DROP_FILE="Geli faylasha si aad u soo geliso"
COM_MEDIA_EDIT="Tafatirka Warbaahinta"
COM_MEDIA_ERROR="Khalad ayaa dhacay."
COM_MEDIA_ERROR_ACCOUNT_NOT_FOUND="Akoonka lama helin"
COM_MEDIA_ERROR_ACCOUNT_NOT_SET="Akoonka lama dhigin."
COM_MEDIA_ERROR_MAKESAFE="Faylka ma aysan noqon mid ammaan ah. Haddii uu ku jiro xarfo aan ASCII ahayn fadlan hubi inaad rakibtay Balaarinta INTL iyo ICONV ee PHP."
COM_MEDIA_ERROR_MEDIA_PROVIDER_NOT_FOUND="Bixiyaha Warbaahinta lama helin."
COM_MEDIA_ERROR_MISSING_DIR="Mid ama in ka badan oo ka mid ah dariiqooyinka lagu qeexay FileSystem - plugin Lokal ma jiraan."
COM_MEDIA_ERROR_NOT_AUTHENTICATED="Laguma xaqiijin. Fadlan gal gudaha."
COM_MEDIA_ERROR_NOT_AUTHORIZED="Laguma ogola"
COM_MEDIA_ERROR_NOT_FOUND="Fayl ama Gal ma helin"
COM_MEDIA_ERROR_NO_ADAPTER_FOUND="Nooca wax gelinta lama helin."
COM_MEDIA_ERROR_NO_CONTENT_AVAILABLE="Wax macluumaad ah lama heli karo!"
COM_MEDIA_ERROR_NO_PROVIDERS="Bixiyeyaasha nidaamka faylka lama helin. Fadlan daar ugu yaraan hal <a href=\"%s\">plugin nidaamka faylka</a>."
COM_MEDIA_ERROR_WARNFILETOOLARGE="Faylkani aad ayuu u weyn yahay si loo soo geliyo. Waxaad beddeli kartaa xaddidaadaha boggaaga qaybta Warbaahinta %s."
COM_MEDIA_FIELDSET_OPTIONS_LABEL="Warbaahinta"
COM_MEDIA_FIELD_CHECK_MIME_DESC="Isticmaal MIME Magic ama Fileinfo si aad isku daydo inaad xaqiijiso faylasha. Isku day inaad damiso haddii aad hesho khaladaadka nooca MIME ee aan sax ahayn."
COM_MEDIA_FIELD_CHECK_MIME_LABEL="Hubinta Garaafka MIME"
COM_MEDIA_FIELD_IGNORED_EXTENSIONS_DESC="Kordhinyo fayl ah oo la iska indhantay si loo hubiyo nooca MIME ama loo xaddido uploads."
COM_MEDIA_FIELD_IGNORED_EXTENSIONS_LABEL="Kordhiyo la iska indhantay"
COM_MEDIA_FIELD_LEGAL_AUDIO_EXTENSIONS_DESC="Kordhinta maqalka (noocyada faylasha) ee lagu oggolyahay inaad soo geliso (ku kala saar ,). Waxaa loo isticmaalayaa in lagu hubiyo madaxyada maqalka ee ansaxsan."
COM_MEDIA_FIELD_LEGAL_AUDIO_EXTENSIONS_LABEL="Kordhinta Maqalka Ee La Oggolan (Noocyada Faylka)"
COM_MEDIA_FIELD_LEGAL_DOCUMENT_EXTENSIONS_DESC="Kordhinta dukumentiyada (noocyada faylasha) ee lagu oggolyahay inaad soo geliso (ku kala saar ,). Waxaa loo isticmaalayaa in lagu hubiyo madaxyada dukumentiyada ee ansaxsan."
COM_MEDIA_FIELD_LEGAL_DOCUMENT_EXTENSIONS_LABEL="Kordhinta Dukumentiyada Ee La Oggolan (Noocyada Faylka)"
COM_MEDIA_FIELD_LEGAL_IMAGE_EXTENSIONS_DESC="Kordhinta sawirrada (noocyada faylasha) ee lagu oggolyahay inaad soo geliso (ku kala saar ,). Waxaa loo isticmaalayaa in lagu hubiyo madaxyada sawirrada ee ansaxsan."
COM_MEDIA_FIELD_LEGAL_IMAGE_EXTENSIONS_LABEL="Kordhinta Sawirrada Ee La Oggolan (Noocyada Faylka)"
COM_MEDIA_FIELD_LEGAL_MIME_TYPES_DESC="Liiska MIME ee ansaxsan ee lasoo gelin karo, oo ku kala duwan comma."
COM_MEDIA_FIELD_LEGAL_MIME_TYPES_LABEL="Noocyada MIME Ee La Oggolan"
COM_MEDIA_FIELD_LEGAL_VIDEO_EXTENSIONS_DESC="Kordhinta fiidiyowga (noocyada faylasha) ee lagu oggolyahay inaad soo geliso (ku kala saar ,). Waxaa loo isticmaalayaa in lagu hubiyo madaxyada fiidiyowga ee ansaxsan."
COM_MEDIA_FIELD_LEGAL_VIDEO_EXTENSIONS_LABEL="Kordhinta Fiidiyowga Ee La Oggolan (Noocyada Faylka)"
COM_MEDIA_FIELD_MAXIMUM_SIZE_DESC="Isticmaal eber wixii xaddid ah. Fiiro gaar ah: server-kaagu wuxuu hayaa xaddid ugu badan."
COM_MEDIA_FIELD_MAXIMUM_SIZE_LABEL="Cabbirka Ugu Badan (MB)"
COM_MEDIA_FIELD_PATH_FILE_FOLDER_DESC="Geli waddada faylasha ee ku xaddidan xididka webkaaga. Digniin! Inaad isku bedesho waddo aan ahayn tan caadiga ah ee 'images' waxay burburin kartaa xiriirkaaga. Fiiro gaar ah: Ha ku bilaabin waddada far slash!"
COM_MEDIA_FIELD_PATH_FILE_FOLDER_LABEL="Waddada Xidhmada Faylasha"
COM_MEDIA_FIELD_PATH_IMAGE_FOLDER_DESC="Geli waddada sawirrada ee ku xaddidan xididka webkaaga. Jidkan <strong>waxaa loogu talagalay inuu noqdo mid la mid ah waddada faylasha (default) ama subfolder ka mid ah waddada faylasha.</strong> Fiiro gaar ah: Ha ku bilaabin waddada far slash!"
COM_MEDIA_FIELD_PATH_IMAGE_FOLDER_LABEL="Waddada Xidhmada Sawirrada"
COM_MEDIA_FIELD_RESTRICT_UPLOADS_DESC="Xaddid uploads-ka isticmaalayaasha ka hooseeya maareeyaha sawirrada haddii aan Fileinfo ama MIME Magic la rakibin."
COM_MEDIA_FIELD_RESTRICT_UPLOADS_EXTENSIONS_DESC="Xaddid uploads inaad ku sameyso isticmaalayaasha ka hooseeya maareeyaha faylasha ku jira liistada."
COM_MEDIA_FIELD_RESTRICT_UPLOADS_EXTENSIONS_LABEL="Noocyada La Ogolyahay"
COM_MEDIA_FIELD_RESTRICT_UPLOADS_LABEL="Xaddid Uploads"
COM_MEDIA_FILE="Fayl"
COM_MEDIA_FILE_EXISTS_AND_OVERRIDE="%s horay ayaa u jiray. Ma rabtaa inaad bedesho?"
COM_MEDIA_FOLDER="Kayd"
COM_MEDIA_FOLDERS="Kaydka Warbaahinta"
COM_MEDIA_FOLDER_NAME="Magaca Kaydka"
COM_MEDIA_INCREASE_GRID="Kordhi cabbirka shabakadda"
COM_MEDIA_MANAGE_ITEM="Maamul shayga: %s"
COM_MEDIA_MEDIA_DATE_CREATED="Taariikhda La Abuuray"
COM_MEDIA_MEDIA_DATE_MODIFIED="Taariikhda La Beddelay"
COM_MEDIA_MEDIA_DIMENSION="Cabir"
COM_MEDIA_MEDIA_EXTENSION="Kordhin"
COM_MEDIA_MEDIA_MIME_TYPE="Nooca MIME"
COM_MEDIA_MEDIA_NAME="Magaca"
COM_MEDIA_MEDIA_SIZE="Cabbir"
COM_MEDIA_MEDIA_TYPE="Nooc"
COM_MEDIA_MOVE_FILE_ALREADY_EXISTS="Suurtagal ma aha in faylka loo raro meel kale sababtoo ah meesha loo raro faylka horey ayuu ugu jiraa"
COM_MEDIA_MOVE_FILE_EXTENSION_INVALID="Suurtagal ma aha in faylka loo raro sababtoo ah kordhinta waa mid aan sax ahayn"
COM_MEDIA_MOVE_FILE_NOT_POSSIBLE="Suurtagal ma aha in faylka loo raro"
COM_MEDIA_MOVE_FOLDER_ALREADY_EXISTS="Suurtagal ma aha in galka loo raro meel kale sababtoo ah meesha loo raro galka horey ayuu ugu jiraa"
COM_MEDIA_MOVE_FOLDER_EXISTING_DESTINATION_FAILED="Suurtagal ma aha in galka loo raro meelku jiro"
COM_MEDIA_MOVE_FOLDER_NOT_POSSIBLE="Suurtagal ma aha in galka loo raro sababtoo ah meesha loo raro waa fayl oo lama tirtiri karo"
COM_MEDIA_NAME="Magaca"
COM_MEDIA_ORDER_ASC="Sareynta"
COM_MEDIA_ORDER_BY="Kala saar"
COM_MEDIA_ORDER_DESC="Hoos u dhig"
COM_MEDIA_ORDER_DIRECTION="Jiihka Amarka"
COM_MEDIA_PLEASE_SELECT_ITEM="Fadlan dooro shay."
COM_MEDIA_RENAME="Magac Bedel"
COM_MEDIA_RENAME_ERROR="Khalad ku dhacay magac bedelidda shayga."
COM_MEDIA_RENAME_SUCCESS="Shayga magac cusub ayaa loo bixiyay."
COM_MEDIA_RESET="Celi"
COM_MEDIA_SEARCH="Raadi"
COM_MEDIA_SELECT_ALL="Dooro dhammaan"
COM_MEDIA_SERVER_ERROR="Khalad gudaha serverka ah"
COM_MEDIA_SHARE="Wadaag faylka"
COM_MEDIA_SHARE_COPY="Nuqul ku samee sabuuradda"
COM_MEDIA_SHARE_COPY_FAILED_ERROR="Khalad nuqul ku sameynta sabuuradda"
COM_MEDIA_SHARE_DESC="Qof kasta oo haysta xiriirka wuxuu arki karaa faylka."
COM_MEDIA_TOGGLE_INFO="Beddel macluumaadka shayga"
COM_MEDIA_TOGGLE_LIST_VIEW="Beddel ka dhexeeya aragtida shabag ama miiska"
COM_MEDIA_TOGGLE_SELECT_ITEM="Dooro shayga"
COM_MEDIA_TOOLBAR_LABEL="Maareeyaha Warbaahinta"
COM_MEDIA_UPLOAD_SUCCESS="Shaygu waa la soo raray."

