; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_MODULES="Qaybaha"
COM_MODULES_ACTION_EDITFRONTEND="Tafatirka Hore"
COM_MODULES_ADD_CUSTOM_POSITION="Kudar booska gaarka ah"
COM_MODULES_ADMIN_LANG_FILTER_DESC="Waxay u oggolaaneysaa shaandheynta qaybaha maamulaha iyadoo lagu saleynayo luqadda maamulaha."
COM_MODULES_ADMIN_LANG_FILTER_FIELDSET_LABEL="Qaybaha Maamulaha"
COM_MODULES_ADMIN_LANG_FILTER_LABEL="Luqadda Shaandaynta"
COM_MODULES_ADVANCED_FIELDSET_LABEL="Hormaris"
COM_MODULES_ASSIGNED_VARIES_EXCEPT="Dhamaan waa laga reebay kuwa lasoo xulay"
COM_MODULES_ASSIGNED_VARIES_ONLY="Waxay ahayd la xulay"
COM_MODULES_BASIC_FIELDSET_LABEL="Xulashooyinka"
COM_MODULES_BATCH_OPTIONS="Habka xidhmada ee qaybaha la doortay"
COM_MODULES_BATCH_POSITION_LABEL="Deji Booska"
COM_MODULES_BATCH_POSITION_NOCHANGE="Iyo meesha asalka ah ee la jadiliyo"
COM_MODULES_BATCH_POSITION_NOPOSITION="Meesha Lamoodhka Ma leh"
COM_MODULES_BATCH_TIP="Haddaad doorato inaad nuqul ka sameeyso qayb, ficil kasta oo kale oo la doorto waxaa laga hirgelin doonaa qeybta la nuqulanayo. Haddii kale, dhammaan ficilada waxaa lagu hirgelin doonaa qaybta la doortay. Markaad iska nuqulayso oon booska beddelayn, waxaa si kastaba lagama maarmaan ah inaad doorato 'Ilaali Booska Asalka ah' ee liiska hoos-u-dhaca."
COM_MODULES_CHANGE_POSITION_BUTTON="Dooro"
COM_MODULES_CHANGE_POSITION_TITLE="Beddel"
COM_MODULES_COLLAPSE="Isku laab"
COM_MODULES_CONFIGURATION="Qayb: Xulashooyinka"
COM_MODULES_CUSTOM_OUTPUT="Soo saarid Gaar ah"
COM_MODULES_CUSTOM_POSITION="Boosas Firfircoon"
COM_MODULES_DESELECT="Ka Daa Doorashada"
COM_MODULES_EMPTYSTATE_BUTTON_ADD="Kudar qayb"
COM_MODULES_EMPTYSTATE_CONTENT="Qaybaha waa fidinta fudud oo dabacsan loo isticmaalo in lagu soo bandhigo bogga. Adeegso si aad ugu darto baloogyo yar-yar oo shaqeynaya boggaaga."
COM_MODULES_EMPTYSTATE_TITLE_ADMINISTRATOR="Lama abuurin weli wax Qaybo Maamul ah."
COM_MODULES_EMPTYSTATE_TITLE_SITE="Wax Modules Goob loo abuuray weli ma jiraan."
COM_MODULES_ERR_XML="Module XML xog lama heli karo"
COM_MODULES_ERROR_CANNOT_FIND_MODULE="Module lama heli karo"
COM_MODULES_ERROR_INVALID_EXTENSION="Module aan sax ahayn"
COM_MODULES_ERROR_NO_MODULES_SELECTED="Lama xulan module."
COM_MODULES_EXPAND="Ballaadhi"
COM_MODULES_EXTENSION_PUBLISHED_DISABLED="Module naafo ah iyo la daabacay."
COM_MODULES_EXTENSION_PUBLISHED_ENABLED="Module karti leh oo la daabacay."
COM_MODULES_EXTENSION_UNPUBLISHED_DISABLED="Module naafo ah oo aan la daabicin."
COM_MODULES_EXTENSION_UNPUBLISHED_ENABLED="Module karti leh oo aan la daabicin."
COM_MODULES_FIELD_AUTOMATIC_TITLE_LABEL="Cinwaan Toos ah"
COM_MODULES_FIELD_BOOTSTRAP_SIZE_LABEL="Cabbirka Bootstrap"
COM_MODULES_FIELD_CACHE_TIME_LABEL="Waqtiga Kaydka"
COM_MODULES_FIELD_CACHING_LABEL="Kaydinta"
COM_MODULES_FIELD_CLIENT_ID_LABEL="Goobta Module"
COM_MODULES_FIELD_CONTENT_LABEL="Qoraal"
COM_MODULES_FIELD_CONTENT_TOO_LARGE="Qoraalka wuxuu ka badan yahay xaddidyada la oggol yahay"
COM_MODULES_FIELD_HEADER_CLASS_LABEL="Fasalka Madaxa"
COM_MODULES_FIELD_HEADER_TAG_LABEL="Tag Madaxa"
COM_MODULES_FIELD_MODULE_LABEL="Nooca Module"
COM_MODULES_FIELD_MODULE_STYLE_LABEL="Qaabka Module"
COM_MODULES_FIELD_MODULE_TAG_LABEL="Tag Module"
COM_MODULES_FIELD_MODULECLASS_SFX_LABEL="Fasalka Module"
COM_MODULES_FIELD_NOTE_LABEL="Qoraal"
COM_MODULES_FIELD_POSITION_LABEL="Boos"
COM_MODULES_FIELD_PUBLISH_DOWN_LABEL="Dhamaystir Daabacaadda"
COM_MODULES_FIELD_PUBLISH_UP_LABEL="Bilow Daabacaadda"
COM_MODULES_FIELD_SHOWTITLE_LABEL="Cinwaan"
COM_MODULES_FIELD_VALUE_NOCACHING="Kaydin la'aan"
COM_MODULES_FIELDSET_RULES="Oggolaansho"
COM_MODULES_FILTER_SEARCH_DESC="Shaandheyn magaca booska."
COM_MODULES_FORM_TITLE_EDIT="Tafatir Module"
COM_MODULES_FORM_TITLE_NEW="Module Cusub"
COM_MODULES_GENERAL_FIELDSET_DESC="Habaynta goobaha tafatirka module."
COM_MODULES_GLOBAL="Ku qoondee Moduleka Qodobbada Menu"
COM_MODULES_GLOBAL_ASSIGN="Ku qeex Qodobbada Menu"
COM_MODULES_GLOBAL_TREE_EXPAND="Ballaadhi laamaha Menu"
COM_MODULES_HEADING_MODULE="Nooc"
COM_MODULES_HEADING_MODULE_ASC="Nooc sii kordhaya"
COM_MODULES_HEADING_MODULE_DESC="Nooc sii yaraanaya"
COM_MODULES_HEADING_PAGES="Bogagga"
COM_MODULES_HEADING_PAGES_ASC="Bogagga sii kordhaya"
COM_MODULES_HEADING_PAGES_DESC="Bogagga sii yaraanaya"
COM_MODULES_HEADING_POSITION="Booska"
COM_MODULES_HEADING_POSITION_ASC="Booska sii kordhaya"
COM_MODULES_HEADING_POSITION_DESC="Booska sii yaraanaya"
COM_MODULES_HEADING_TEMPLATES="Templates"
COM_MODULES_HTML_PUBLISH_DISABLED="Daabac module::Kordhinta naafo"
COM_MODULES_HTML_PUBLISH_ENABLED="Daabac module::Kordhinta karti leh"
COM_MODULES_HTML_UNPUBLISH_DISABLED="Ka jooji module::Kordhinta naafo"
COM_MODULES_HTML_UNPUBLISH_ENABLED="Dami module::Ballaadhan ayaa la daaray"
COM_MODULES_MANAGER_MODULE="Modules: %s"
COM_MODULES_MANAGER_MODULES_ADMIN="Modules (Maamulaha)"
COM_MODULES_MANAGER_MODULES_SITE="Modules (Bogga)"
COM_MODULES_MENU_ASSIGNMENT="Xulashada Menu"
COM_MODULES_MENU_ITEM_ALIAS="Miciin"
COM_MODULES_MENU_ITEM_HEADING="Cinwaan"
COM_MODULES_MENU_ITEM_SEPARATOR="Kala-fure"
COM_MODULES_MENU_ITEM_URL="URL"
COM_MODULES_MODULE="Module"
COM_MODULES_MODULE_ASSIGN="Xulashada Module"
COM_MODULES_MODULE_DESCRIPTION="Sharaxa Module"
COM_MODULES_MODULE_TEMPLATE_POSITION="%1$s (%2$s)"
COM_MODULES_MODULES="Modules"
COM_MODULES_MODULES_FILTER_SEARCH_DESC="Raadi cinwaanka iyo xusuusta module. Ku soo horreey ID: si aad u raadsato module ID."
COM_MODULES_MODULES_FILTER_SEARCH_LABEL="Raadi Modules"
COM_MODULES_MSG_MANAGE_EXTENSION_DISABLED="Module-ka '%s' waa la naafoobiyay. U adeegso Nidaamka &rarr; Maamul &rarr; Ballaadhan si aad u sheegto."
COM_MODULES_MSG_MANAGE_NO_MODULES="Ma jiraan modules ku habboon su'aashaada"
COM_MODULES_N_ITEMS_ARCHIVED="%d modules la kaydiyay."
COM_MODULES_N_ITEMS_ARCHIVED_1="Module la kaydiyay."
COM_MODULES_N_ITEMS_CHECKED_IN_1="Module la xidhay."
COM_MODULES_N_ITEMS_CHECKED_IN_MORE="%d modules la xidhay."
COM_MODULES_N_ITEMS_DELETED="%d modules la tirtiray."
COM_MODULES_N_ITEMS_DELETED_1="Module tirtiray."
COM_MODULES_N_ITEMS_PUBLISHED="%d modules la daabacay."
COM_MODULES_N_ITEMS_PUBLISHED_1="Module la daabacay."
COM_MODULES_N_ITEMS_TRASHED="%d modules la tuuray."
COM_MODULES_N_ITEMS_TRASHED_1="Module la tuuray."
COM_MODULES_N_ITEMS_UNPUBLISHED="%d modules aan la daabacin."
COM_MODULES_N_ITEMS_UNPUBLISHED_1="Module aan la daabacin."
COM_MODULES_N_MODULES_DUPLICATED="%d modules la nuqulaystay."
COM_MODULES_N_MODULES_DUPLICATED_1="Module la nuqulaystay."
COM_MODULES_N_QUICKICON="Modules"
COM_MODULES_N_QUICKICON_0="Modules"
COM_MODULES_N_QUICKICON_1="Module"
COM_MODULES_N_QUICKICON_SRONLY="Modules: %d modules ayaa la heli karaa."
COM_MODULES_N_QUICKICON_SRONLY_0="Modules: Module la heli karo ma jiro."
COM_MODULES_N_QUICKICON_SRONLY_1="Modules: Hal module ayaa la heli karaa."
COM_MODULES_NO_ITEM_SELECTED="Ma jiraan modules la doortay."
COM_MODULES_NODESCRIPTION="Sharaxaad lama heli karo."
COM_MODULES_NONE=":: Midna ::"
COM_MODULES_OPTION_MENU_ALL="Bogagga oo dhan"
COM_MODULES_OPTION_MENU_EXCLUDE="Bogagga oo dhan marka laga reebo kuwa la xushay"
COM_MODULES_OPTION_MENU_INCLUDE="Kaliya bogagga la xushay"
COM_MODULES_OPTION_MENU_NONE="Bogag la’aan"
COM_MODULES_OPTION_ORDER_POSITION="%d. %s"
COM_MODULES_OPTION_POSITION_TEMPLATE_DEFINED="Qaabka"
COM_MODULES_OPTION_POSITION_USER_DEFINED="Isticmaale"
COM_MODULES_OPTION_SELECT_CLIENT="- Xulo Nooca -"
COM_MODULES_OPTION_SELECT_MENU_ITEM="- Xulo Shayga Menu -"
COM_MODULES_OPTION_SELECT_MODULE="- Doorasho Nooc -"
COM_MODULES_OPTION_SELECT_POSITION="- Doorasho Booska -"
COM_MODULES_OPTION_SELECT_TYPE="- Doorasho Nooc -"
COM_MODULES_POSITION_ANALYTICS="Falanqayn"
COM_MODULES_POSITION_BANNER="Boorsada"
COM_MODULES_POSITION_BOTTOM="Hoose"
COM_MODULES_POSITION_BREADCRUMB="Tilsameed"
COM_MODULES_POSITION_BREADCRUMBS="Tilsameedyo"
COM_MODULES_POSITION_DEBUG="Saxeexa"
COM_MODULES_POSITION_FOOTER="Qeybta hoose"
COM_MODULES_POSITION_HEADER="Qeybta sare"
COM_MODULES_POSITION_LEFT2="Bidix 2"
COM_MODULES_POSITION_LEFT="Bidix"
COM_MODULES_POSITION_MAINNAV="Hagitaanka Ugu Weyn"
COM_MODULES_POSITION_NAV="Hagitaan"
COM_MODULES_POSITION_OFFLINE="Khadka Ka Baxsan"
COM_MODULES_POSITION_POSITION-0="Booska 0"
COM_MODULES_POSITION_POSITION-10="Booska 10"
COM_MODULES_POSITION_POSITION-11="Booska 11"
COM_MODULES_POSITION_POSITION-12="Booska 12"
COM_MODULES_POSITION_POSITION-13="Booska 13"
COM_MODULES_POSITION_POSITION-14="Booska 14"
COM_MODULES_POSITION_POSITION-15="Booska 15"
COM_MODULES_POSITION_POSITION-1="Booska 1"
COM_MODULES_POSITION_POSITION-2="Booska 2"
COM_MODULES_POSITION_POSITION-3="Booska 3"
COM_MODULES_POSITION_POSITION-4="Booska 4"
COM_MODULES_POSITION_POSITION-5="Booska 5"
COM_MODULES_POSITION_POSITION-6="Booska 6"
COM_MODULES_POSITION_POSITION-7="Booska 7"
COM_MODULES_POSITION_POSITION-8="Booska 8"
COM_MODULES_POSITION_POSITION-9="Booska 9"
COM_MODULES_POSITION_RIGHT2="Midig 2"
COM_MODULES_POSITION_RIGHT="Midig"
COM_MODULES_POSITION_SUB1="Qeybta 1"
COM_MODULES_POSITION_SUB2="Qeybta 2"
COM_MODULES_POSITION_SUB3="Qeybta 3"
COM_MODULES_POSITION_SUB4="Qeybta 4"
COM_MODULES_POSITION_SUB5="Qeybta 5"
COM_MODULES_POSITION_SUB6="Qeybta 6"
COM_MODULES_POSITION_SUB="Qeybta"
COM_MODULES_POSITION_SUBNAV="Qeybta Navigation"
COM_MODULES_POSITION_SYNDICATE="Syndicate"
COM_MODULES_POSITION_TOP2="Sare 2"
COM_MODULES_POSITION_TOP3="Sare 3"
COM_MODULES_POSITION_TOP4="Sare 4"
COM_MODULES_POSITION_TOP="Sare"
COM_MODULES_POSITION_USER1="Isticmaale 1"
COM_MODULES_POSITION_USER2="Isticmaale 2"
COM_MODULES_POSITION_USER3="Isticmaale 3"
COM_MODULES_POSITION_USER4="Isticmaale 4"
COM_MODULES_POSITION_USER5="Isticmaale 5"
COM_MODULES_POSITION_USER6="Isticmaale 6"
COM_MODULES_POSITION_USER7="Isticmaale 7"
COM_MODULES_POSITION_USER8="Isticmaale 8"
COM_MODULES_SAVE_SUCCESS="Cutubka waa la keydiyay."
COM_MODULES_SEARCH_MENUITEM="Raadi walxaha Menu-ga"
COM_MODULES_SELECT_MODULE="Xulo cutub, %s"
COM_MODULES_SUBITEMS="Walxaha hoosaadka"
COM_MODULES_TABLE_CAPTION="Cutubyada"
COM_MODULES_TYPE_CHOOSE="Xulo nooca cutubka"
COM_MODULES_TYPE_OR_SELECT_POSITION="Qor ama dooro boos"
COM_MODULES_XML_DESCRIPTION="Qayb ka mid ah maareynta cutubyada ee maamulaha Backend."

JLIB_RULES_SETTING_NOTES_COM_MODULES="Isbeddeladu waxay ku khuseeyaan kaliya shaygan.<br><em><strong>Dhaxaltooyo</strong></em> - Goobaha Qaabeynta Guud ama heer sare ayaa la dhaqan gelinayaa.<br><em><strong>Diiday</strong></em> mar walba wuu guuleystaa - waxa la dejiyey Heerka Guud ama heer sare oo tixgelinaya dhammaan qaybaha ilmaha.<br><em><strong>La Ogolaaday</strong></em> waxay u oggolaan doontaa ficilka shaygan ilaa laga hor joogsado dejinta Qaabeynta Guud."

