; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_LOGIN="Soo gal"
COM_LOGIN_JOOMLA_ADMINISTRATION_LOGIN="Joomla! Soo gal Maamulka"
COM_LOGIN_RETURN_TO_SITE_HOME_PAGE="Tag bogga hore ee goobta"
COM_LOGIN_VALID="Isticmaal magac isticmaale iyo eray sir ah oo sax ah si aad u gasho kala dambeeyaha maamulka."
COM_LOGIN_XML_DESCRIPTION="Qaybtani waxay u ogolaanaysaa isticmaalayaasha inay soo galaan goobta."

