; Joomla! Project
; (C) 2007 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_CONTACT="Xiriirada"  
COM_CONTACT_CATEGORIES="Qeybaha"  
COM_CONTACT_CATEGORIES_VIEW_DEFAULT_DESC="Waxay tusaysaa liiska qaybaha gudaha geedka qeybah xiriirka."  
COM_CONTACT_CATEGORIES_VIEW_DEFAULT_OPTION="Caadiga"  
COM_CONTACT_CATEGORIES_VIEW_DEFAULT_TITLE="Liis garee dhammaan qaybaha geedka qeybaha xiriirka"  
COM_CONTACT_CATEGORY_VIEW_DEFAULT_DESC="Muuqaalkan waxa uu liiska ku jiraa xiriirada ku jira qayb."  
COM_CONTACT_CATEGORY_VIEW_DEFAULT_OPTION="Caadiga"  
COM_CONTACT_CATEGORY_VIEW_DEFAULT_TITLE="Liis garee xiriirada ku jira qayb"  
COM_CONTACT_CONTACT_VIEW_DEFAULT_DESC="Tani waxay xiriir la leedahay macluumaadka xiriirka ee hal xiriir."  
COM_CONTACT_CONTACT_VIEW_DEFAULT_OPTION="Caadiga"  
COM_CONTACT_CONTACT_VIEW_DEFAULT_TITLE="Hal Xiriir"  
COM_CONTACT_CONTACTS="Xiriirada"  
COM_CONTACT_CONTENT_TYPE_CATEGORY="Qeybta Xiriirka"  
COM_CONTACT_CONTENT_TYPE_CONTACT="Xiriir"  
COM_CONTACT_FEATURED_VIEW_DEFAULT_DESC="Muuqaalkaan wuxuu liiska ku jiraa xiriirada la soo bandhigay."  
COM_CONTACT_FEATURED_VIEW_DEFAULT_OPTION="Caadiga"  
COM_CONTACT_FEATURED_VIEW_DEFAULT_TITLE="Xiriirada La Soo Bandhigay"  
COM_CONTACT_FORM_VIEW_DEFAULT_DESC="Samee xiriir cusub."  
COM_CONTACT_FORM_VIEW_DEFAULT_TITLE="Abuur Xiriir"  
COM_CONTACT_NO_CONTACTS_LABEL="Farriin Xiriir La'aan"  
COM_CONTACT_TAGS_CATEGORY="Qeybta Xiriirka"  
COM_CONTACT_TAGS_CONTACT="Xiriir"  
COM_CONTACT_XML_DESCRIPTION="Qaybtan waxay soo bandhigtaa liiska macluumaadka xiriirka."

