; Joomla! Project
; (C) 2010 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_LANGUAGES="Luuqadaha"
COM_LANGUAGES_INSTALLED_VIEW_DEFAULT_DESC="Waxay muujineysaa xirmooyinka luqadaha ee ku rakiban boggaaga Joomla!"
COM_LANGUAGES_INSTALLED_VIEW_DEFAULT_TITLE="Luuqadaha la rakibay"
COM_LANGUAGES_LANGUAGES_VIEW_DEFAULT_DESC="Abuur ama maamul luqadaha qoraalka ee boggaaga Joomla!"
COM_LANGUAGES_LANGUAGES_VIEW_DEFAULT_TITLE="Luuqadaha Qoraalka"
COM_LANGUAGES_OVERRIDE_VIEW_DEFAULT_DESC="Halkan waxaad ku xilqaaqeysaa qoraal gaara xogta luuqad kaas oo aad dooneyso inaad isticmaasho halkii qoraalka caadiga ah ee xirmada luqadda."
COM_LANGUAGES_OVERRIDE_VIEW_DEFAULT_TITLE="Beddelka Luuqadda"
COM_LANGUAGES_XML_DESCRIPTION="Qeybta maamulka luqadda."

