; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_LANGUAGES="Luqadaha"
COM_LANGUAGES_CONFIGURATION="Luqadaha: Xulashooyinka"
COM_LANGUAGES_CONTENT_TABLE_CAPTION="Luqadaha Mawduuca"
COM_LANGUAGES_ERR_NO_LANGUAGE_SELECTED="Luuqad lama xulan."
COM_LANGUAGES_ERR_PUBLISH="Xulo luuqad lagu daabaco."
COM_LANGUAGES_ERROR_LANG_TAG="<br>Calaamada Luuqadda waa inay leedahay 2 ama 3 xarfo yar oo u dhiganta ISO luuqadda, xariiq meel iyo 2 xarfo waaweyn oo u dhiganta koodka waddanka ISO. <br>Tani waa inay noqotaa horudhaca saxda ah ee loo isticmaalo luuqadda la rakibay ama la rakibi doono. Tusaale: en-GB, srp-ME."
COM_LANGUAGES_ERROR_LANGUAGE_METAFILE_MISSING="Lama soo dejin karin %s luuqad meta faylka XML ka ah %s."
COM_LANGUAGES_ERROR_SEF="<br>Koodhka Luuqadda URL waa inuu leeyahay oo kaliya xarfaha alfanumic iyo xariiqyada (-).<br>Si aad u isticmaasho xarfaha UTF-8, Waa in "Unicode Aliases" loo dejiyaa "Haa" Deegaanka Guud."
COM_LANGUAGES_FIELD_IMAGE_LABEL="Sawir"
COM_LANGUAGES_FIELD_LANG_CODE_DESC="Koodhkan Luuqadda waxa uu ku jiri doonaa cinwaanka bogga. Fiiro gaar ah <em>Koodhka Luuqadda waa inuu kaligiis ahaado dhammaan luqadaha</em>."
COM_LANGUAGES_FIELD_LANG_CODE_LABEL="Koodhka Luuqadda URL"
COM_LANGUAGES_FIELD_LANG_TAG_DESC="Geli calaamada luuqadda - tusaale: en-GB ee Ingiriisiga (en-GB). Tani waa inay noqotaa horudhaca saxda ah ee loo isticmaalo luuqadda la rakibay ama la rakibi doono."
COM_LANGUAGES_FIELD_LANG_TAG_LABEL="Calaamada Luuqadda"
COM_LANGUAGES_FIELD_SITE_NAME_LABEL="Magaca Goobta ee gaarka ah"
COM_LANGUAGES_FIELD_TITLE_NATIVE_LABEL="Cinwaanka Luuqadda Hooyo"
COM_LANGUAGES_FIELDSET_SITE_NAME_LABEL="Magaca Goobta"
COM_LANGUAGES_HEADING_AUTHOR="Qoraha"
COM_LANGUAGES_HEADING_AUTHOR_ASC="Qoraha kor"
COM_LANGUAGES_HEADING_AUTHOR_DESC="Qoraha hoos"
COM_LANGUAGES_HEADING_AUTHOR_EMAIL="Emailka Qoraha"
COM_LANGUAGES_HEADING_AUTHOR_EMAIL_ASC="Emailka Qoraha kor"
COM_LANGUAGES_HEADING_AUTHOR_EMAIL_DESC="Emailka Qoraha hoos"
COM_LANGUAGES_HEADING_DATE="Taariikhda"
COM_LANGUAGES_HEADING_DATE_ASC="Taariikhda kor"
COM_LANGUAGES_HEADING_DATE_DESC="Taariikhda hoos"
COM_LANGUAGES_HEADING_DEFAULT="Bilaawga"
COM_LANGUAGES_HEADING_DEFAULT_ASC="Bilawga kor u socod"
COM_LANGUAGES_HEADING_DEFAULT_DESC="Bilawga hoos u socod"
COM_LANGUAGES_HEADING_HOMEPAGE="Bogga Hore"
COM_LANGUAGES_HEADING_HOMEPAGE_ASC="Bogga Hore kor u socod"
COM_LANGUAGES_HEADING_HOMEPAGE_DESC="Bogga Hore hoos u socod"
COM_LANGUAGES_HEADING_LANG_CODE="Koodhka Luqadda URL"
COM_LANGUAGES_HEADING_LANG_CODE_ASC="Koodhka Luqadda URL kor u socod"
COM_LANGUAGES_HEADING_LANG_CODE_DESC="Koodhka Luqadda URL hoos u socod"
COM_LANGUAGES_HEADING_LANG_IMAGE="Sawir"
COM_LANGUAGES_HEADING_LANG_IMAGE_ASC="Sawir kor u socod"
COM_LANGUAGES_HEADING_LANG_IMAGE_DESC="Sawir hoos u socod"
COM_LANGUAGES_HEADING_LANG_TAG="Calaamadda Luqadda"
COM_LANGUAGES_HEADING_LANG_TAG_ASC="Calaamadda Luqadda kor u socod"
COM_LANGUAGES_HEADING_LANG_TAG_DESC="Calaamadda Luqadda hoos u socod"
COM_LANGUAGES_HEADING_TITLE_ASC="Cinwaan kor u socod"
COM_LANGUAGES_HEADING_TITLE_DESC="Cinwaan hoos u socod"
COM_LANGUAGES_HEADING_TITLE_NATIVE="Cinwaan Dabiici ah"
COM_LANGUAGES_HEADING_TITLE_NATIVE_ASC="Cinwaan Dabiici ah kor u socod"
COM_LANGUAGES_HEADING_TITLE_NATIVE_DESC="Cinwaan Dabiici ah hoos u socod"
COM_LANGUAGES_HEADING_VERSION="Nooca"
COM_LANGUAGES_HEADING_VERSION_ASC="Nooca kor u socod"
COM_LANGUAGES_HEADING_VERSION_DESC="Nooca hoos u socod"
COM_LANGUAGES_HOMEPAGE="Bogga Hore"
COM_LANGUAGES_INSTALL="Luqadaha Ku Rakib"
COM_LANGUAGES_INSTALLED_FILTER_SEARCH_DESC="Raadi ciwaanka iyo summada luqadda."
COM_LANGUAGES_INSTALLED_FILTER_SEARCH_LABEL="Raadi Luqadaha La Rakibay"
COM_LANGUAGES_INSTALLED_TABLE_CAPTION="Luqadaha La Rakibay"
COM_LANGUAGES_LANGUAGE_FORM_EDIT="Tafatirka Luqadda"
COM_LANGUAGES_LANGUAGE_FORM_NEW="Luqad Cusub"
COM_LANGUAGES_LANGUAGE_NEW_LANGUAGE_TITLE="Faahfaahinta Luqadda Mawduuca Cusub"
COM_LANGUAGES_MSG_DEFAULT_LANGUAGE_SAVED="Luqadda Difaaca ah Waa La Badbaadiyay. Tani waxba kama beddelayso isticmaalayaasha doortay luqad gaar ah astaantooda ama bogga gelitaanka."
COM_LANGUAGES_MSG_DEFAULT_MULTILANG_SAVED="Luqadda Difaaca ah Waa La Badbaadiyay. Tani waxba kama beddelayso isticmaalayaasha doortay luqad gaar ah astaantooda ama bogga gelitaanka.<br><strong>Digniin!</strong> Luqadda Difaaca Bogga sidoo kale waa in ay noqotaa luqadda Mawduuca la daabacay."
COM_LANGUAGES_MSG_SWITCH_ADMIN_LANGUAGE_SUCCESS="Luqadda Maamulka waa la beddelay waxaana loo rogay &quot;<strong>%s</strong>&quot;."
COM_LANGUAGES_MULTILANGSTATUS_CONTACTS_ERROR="Qaar ka mid ah xiriirada la xiriira isticmaalaha <strong>%s</strong> waa khalad."
COM_LANGUAGES_MULTILANGSTATUS_CONTACTS_ERROR_TIP="Digniin! Isticmaale/qore waa inuu lahaadaa hal xiriir oo loo qoondeeyay luqadda 'Dhammaan' AMA xiriir kasta oo loogu talagalay Luqadda Mawduuca ee la daabacay."
COM_LANGUAGES_MULTILANGSTATUS_CONTENT_LANGUAGE_HOME_UNPUBLISHED="Labada Luqadaha Mawduuca <strong>%s</strong> iyo boggeeda Hore waa la joojiyay. <strong>Luqadda looma soo bandhigi doono barta.</strong>"
COM_LANGUAGES_MULTILANGSTATUS_CONTENT_LANGUAGE_MISSING="Luqadda Mawduuca <strong>%s</strong> waa la tirtiray in kastoo Luqadda Bogga ee u dhiganta ay firfircoon tahay oo bog Hore loo qoondeeyay luqaddan. <strong>Luqadda looma soo bandhigi doono barta.</strong>"
COM_LANGUAGES_MULTILANGSTATUS_CONTENT_LANGUAGE_PUBLISHED="Luqadaha Mawduuca ee la Daabacay"
COM_LANGUAGES_MULTILANGSTATUS_CONTENT_LANGUAGE_SEF_MISSING="\"Koodhka URL Luqadda\" ayaa ka maqan Luqadda Mawduuca <strong>%s</strong>. <strong>Sifada luqadaha badan waxay dhici kartaa in aysan si sax ah u shaqeynin ama barta lama gaari karo!</strong>"
COM_LANGUAGES_MULTILANGSTATUS_CONTENT_LANGUAGE_TRASHED="Luqadda Mawduuca <strong>%s</strong> waa la qashin joojiyay. <strong>Luqadda looma soo bandhigi doono barta.</strong>"
COM_LANGUAGES_MULTILANGSTATUS_CONTENT_TABLE_CAPTION="Xaaladda Luqadda Mawduuca"
; The following string is deprecated and will be removed with 7.0
COM_LANGUAGES_MULTILANGSTATUS_DEFAULT_HOME_MODULE_PUBLISHED="Qaybta menu-ga ee ku tusaysa shayga menu ee Home kaasoo u jeedadiisu tahay luuqada &quot;Dhammaan&quot; waa in aan la daabicin."
COM_LANGUAGES_MULTILANGSTATUS_ERROR_CONTENT_LANGUAGE="Bogga Guriga ee Muhiimka ah waxaa loo asteeyay <strong>%s</strong> Luqadda Mawduuca inkastoo Luuqadda Mareeshinka ee Luqadda Mawduuca aan la rakibin ama aan la daarin IYO/AMA Luqadda Mawduuca aan la daabicin. <strong>Luuqadda kuma soo bixi doonto mareegta.</strong>"
COM_LANGUAGES_MULTILANGSTATUS_ERROR_DEFAULT_CONTENT_LANGUAGE="Luqadda Mawduuca ee luuqadda Mareegta Muhiimka ah ee <strong>%s</strong> lama daabicin ama ma jirto. <strong>Sifeynta luuqadaha badan waxay u shaqeyn kartaa si aan sax ahayn ama goobtu ma noqon karto la heli karo!</strong>"
COM_LANGUAGES_MULTILANGSTATUS_ERROR_LANGUAGE_TAG="Calaamadda Luqadda Mawduuca <strong>%s</strong> ma laha calaamad la mid ah tii Luuqadda Mareegta. Hubi in Luqadda Mareegtu ay rakibantahay oo shidanyahay IYO calaamad luuqadda saxda ah ayaa loo istcimaalayaa Luqadda Mawduuca. Tusaale ahaan: Ingiriis (en-GB) labadaba calaamadoodu waa inay ahaadaan 'en-GB'. <strong>Luqaddu kuma soo bixi doonto mareegta.</strong>"
COM_LANGUAGES_MULTILANGSTATUS_HOMES_PUBLISHED="Bogagga Guriga Muhiimka ah ee La Daabacay"
COM_LANGUAGES_MULTILANGSTATUS_HOMES_PUBLISHED_ALL="1 u loo asteeyay luuqadda 'Dhammaan'."
COM_LANGUAGES_MULTILANGSTATUS_HOMES_PUBLISHED_INCLUDING_ALL="Bogagga Guriga Muhiimka ah ee La Daabacay (oo ay ku jiraan 1 loo asteeyay luuqadda &quot;Dhammaan&quot;)."
COM_LANGUAGES_MULTILANGSTATUS_HOME_UNPUBLISHED="Bogga Guriga Muhiimka ah ee loo asteeyay <strong>%s</strong> Luqadda Mawduuca lama daabicin. <strong>Luqaddu kuma soo bixi doonto mareegta.</strong>"
COM_LANGUAGES_MULTILANGSTATUS_LANGSWITCHER_PUBLISHED="Modules-ka Beddelka Luuqadda ee La Daabacay."
COM_LANGUAGES_MULTILANGSTATUS_LANGSWITCHER_UNPUBLISHED="Ugu yaraan hal module Bedel Luuqad ah oo loo dhigay &quot;Dhamaan&quot; waa in la daabaco. Haddii kale, suurtagal noqon mayso in la beddelo luuqadaha goobta. Kasoo qaad fariintaan haddii aanad isticmaalin module bedel luuqad laakiin xiriiriyeyaasha tooska ah."
COM_LANGUAGES_MULTILANGSTATUS_LANGUAGEFILTER="Plugin-ka Filtro Luuqadda"
COM_LANGUAGES_MULTILANGSTATUS_LANGUAGEFILTER_DISABLED="Plugin-ka Filtro Luuqadda lama shidin inkasta oo mid ama in ka badan Modules-ka Bedel Luuqad ah AMA/INA kas bilaha ah Luuqad Qoran oo Default ah la daabacay."
COM_LANGUAGES_MULTILANGSTATUS_NONE="Goobtaan laguma dejin si luuqado badan loogu isticmaalo."
COM_LANGUAGES_MULTILANGSTATUS_SITE_LANG_PUBLISHED="Luuqadaha Goobta la Daaray"
COM_LANGUAGES_MULTILANGSTATUS_TABLE_CAPTION="Xaaladda Luuqadaha Badan"
COM_LANGUAGES_MULTILANGSTATUS_USELESS_HOMES="Goobtaan laguma dejin si luuqado badan loogu isticmaalo.<br><strong>Ogeysiis</strong>: ugu yaraan hal Bog Guriga Default ah ayaa loo qoondeeyay Luuqad Qoraal. Tani ma jebin doonto goob luuqad keliya ah laakiin waa caafimaad darro."
COM_LANGUAGES_NO_ITEM_SELECTED="Luuqado lama xulan."
COM_LANGUAGES_N_ITEMS_DELETED="%d Luuqado Qoraal ayaa la tirtiray."
COM_LANGUAGES_N_ITEMS_DELETED_1="Luuqad Qoraal ayaa la tirtiray."
COM_LANGUAGES_N_ITEMS_PUBLISHED="%d Luuqado Qoraal ayaa la daabacay."
COM_LANGUAGES_N_ITEMS_PUBLISHED_1="Luuqad Qoraal ayaa la daabacay."
COM_LANGUAGES_N_ITEMS_TRASHED="%d Luuqado Qoraal ayaa la tuuray."
COM_LANGUAGES_N_ITEMS_TRASHED_1="Luuqad Qoraal ayaa la tuuray."
COM_LANGUAGES_N_ITEMS_UNPUBLISHED="%d Luuqado Qoraal lama daabacay. <br><strong>Digniin!</strong> Markaad isticmaalayso shaqada luuqadaha badan (tusaale ahaan marka plugin-ka System - Language Filter uu shidan yahay) Luuqada Goobta Default waa inay leeyihiin luuqad qoran oo daabacan."
COM_LANGUAGES_N_ITEMS_UNPUBLISHED_1="Luuqad Qoraal lama daabacay. <br><strong>Digniin!</strong> Markaad isticmaalayso shaqada luuqadaha badan (tusaale ahaan marka plugin-ka System - Language Filter uu shidan yahay) Luuqada Goobta Default waa inay leeyihiin luuqad qoran oo daabacan."
COM_LANGUAGES_N_QUICKICON="Luuqado"
COM_LANGUAGES_N_QUICKICON_1="Luuqad"
COM_LANGUAGES_N_QUICKICON_SRONLY="Luuqado: %d luuqado ayaa la daaray."
COM_LANGUAGES_N_QUICKICON_SRONLY_1="Luuqado: Hal luuqad ayaa la daaray."
COM_LANGUAGES_OVERRIDE_ERROR_RESERVED_WORDS="HAA, MAYA, NULL, BEEN, ON, OFF, MAJIRAAN, RUN waa ereyo kaydsan kuma isticmaali kartid sidii lagdhaaso luuqadeed."
COM_LANGUAGES_OVERRIDE_FIELD_BOTH_LABEL="Labada Meel"
COM_LANGUAGES_OVERRIDE_FIELD_CLIENT_LABEL="Meesha"
COM_LANGUAGES_OVERRIDE_FIELD_FILE_LABEL="Faylka"
COM_LANGUAGES_OVERRIDE_FIELD_KEY_LABEL="Qadarka Luuqadda"
COM_LANGUAGES_OVERRIDE_FIELD_LANGUAGE_LABEL="Luuqadda"
COM_LANGUAGES_OVERRIDE_FIELD_OVERRIDE_LABEL="Qoraalka"
COM_LANGUAGES_OVERRIDE_FIELD_SEARCHSTRING_LABEL="Raadi Qoraalka"
COM_LANGUAGES_OVERRIDE_FIELD_SEARCHTYPE_CONSTANT="Dhexjoog"
COM_LANGUAGES_OVERRIDE_FIELD_SEARCHTYPE_LABEL="Raadi"
COM_LANGUAGES_OVERRIDE_FIELD_SEARCHTYPE_TEXT="Qiimaha"
COM_LANGUAGES_OVERRIDE_FIRST_SELECT_MESSAGE="Si aad u abuurto wax ka beddel cusub, fadlan marka hore dooro luuqadda iyo macmiilka."
COM_LANGUAGES_OVERRIDE_SELECT_LANGUAGE="- Dooro Luuqadda & Macmiilka -"
COM_LANGUAGES_OVERRIDE_SELECT_LANGUAGECLIENT="Dooro Luuqadda & Macmiilka"
COM_LANGUAGES_OVERRIDES_TABLE_CAPTION="Wax ka Beddelada Luuqadda"
COM_LANGUAGES_SAVE_SUCCESS="Luuqadda Mawduuca waa la keydiyay."
COM_LANGUAGES_SEARCH_IN_TITLE="Raadi cinwaanka."
COM_LANGUAGES_SWITCH_ADMIN="Isbeddel Luuqadda"
COM_LANGUAGES_VIEW_INSTALLED_ADMIN_TITLE="Luuqadaha: La rakibey (Maamule)"
COM_LANGUAGES_VIEW_INSTALLED_SITE_TITLE="Luuqadaha: La rakibey (Goob)"
COM_LANGUAGES_VIEW_LANGUAGE_EDIT_EDIT_TITLE="Luuqadaha: Wax ka Beddel Luuqadda Mawduuca"
COM_LANGUAGES_VIEW_LANGUAGE_EDIT_NEW_TITLE="Luuqadaha: Luuqad Mawduuc Cusub"
COM_LANGUAGES_VIEW_LANGUAGES_TITLE="Luuqadaha: Mawduuca"
COM_LANGUAGES_VIEW_OVERRIDE_CLIENT_ADMINISTRATOR="Maamule"
COM_LANGUAGES_VIEW_OVERRIDE_CLIENT_SITE="Goob"
COM_LANGUAGES_VIEW_OVERRIDE_EDIT_EDIT_OVERRIDE_LEGEND="Wax ka Beddelkan"
COM_LANGUAGES_VIEW_OVERRIDE_EDIT_NEW_OVERRIDE_LEGEND="Abuur Wax ka Beddel Cusub"
COM_LANGUAGES_VIEW_OVERRIDE_EDIT_TITLE="Luuqadaha: Wax ka Beddel"
COM_LANGUAGES_VIEW_OVERRIDE_FORM_EDIT="Wax ka Beddel"
COM_LANGUAGES_VIEW_OVERRIDE_FORM_NEW="Isbedel Cusub"
COM_LANGUAGES_VIEW_OVERRIDE_LANGUAGE="%1$s [%2$s]"
COM_LANGUAGES_VIEW_OVERRIDE_MORE_RESULTS="Natiijooyin Kale"
COM_LANGUAGES_VIEW_OVERRIDE_NO_RESULTS="Ma helin qoraallo la mid ah."
COM_LANGUAGES_VIEW_OVERRIDE_REFRESHING="Fadlan sug inta kaydka dib loo abuurayo."
COM_LANGUAGES_VIEW_OVERRIDE_REQUEST_ERROR="Khalad ayaa dhacay markii Ajax la samaynayay."
COM_LANGUAGES_VIEW_OVERRIDE_RESULTS_LEGEND="Natiijooyinka Raadinta"
COM_LANGUAGES_VIEW_OVERRIDE_SAVE_SUCCESS="Isbeddelka Luqadda waa la keydiyey."
COM_LANGUAGES_VIEW_OVERRIDE_SEARCH_BUTTON="Raadi"
COM_LANGUAGES_VIEW_OVERRIDE_SEARCH_LEGEND="Raadi qoraalka aad rabto inaad bedesho."
COM_LANGUAGES_VIEW_OVERRIDE_SEARCH_TIP="Silsiladda luqadeed waxay ka kooban tahay laba qaybood: isku xirka luqad gaar ah iyo qiimaheeda.<br>Tusaale ahaan, silsiladda: COM_CONTENT_READ_MORE=&quot;Akhri waxbadan: &quot;<br>'<u>COM_CONTENT_READ_MORE</u>' waa isbadal joogto ah iyo '<u>Akhri waxbadan: </u>' waa qiimaha.<br>Waxaad u baahan tahay inaad isticmaasho isbadalka luqadda si aad u abuurto isbedel cusub oo qiime ah.<br>Markaa waxaad raadin kartaa isbadalka ama qiimaha aad rabto inaad bedesho adigoo isticmaalaya meesha raadinta ee hoos ku xusan.<br>Markaad doorato natiijada la doonayo isbadalka joogtada ah si tooska ah waxaa lagu gelin doonaa foomka."
COM_LANGUAGES_VIEW_OVERRIDES_FILTER_SEARCH_DESC="Raadi isbadalka ama qoraalka."
COM_LANGUAGES_VIEW_OVERRIDES_KEY="Go'an"
COM_LANGUAGES_VIEW_OVERRIDES_KEY_ASC="Go'an oo kor u kacaya"
COM_LANGUAGES_VIEW_OVERRIDES_KEY_DESC="Go'an oo hoos u dhacaya"
COM_LANGUAGES_VIEW_OVERRIDES_LANGUAGES_BOX_ITEM="%1$s - %2$s"
COM_LANGUAGES_VIEW_OVERRIDES_N_ITEMS_DELETED="%d isbeddelada luqadda waa la tirtiray."
COM_LANGUAGES_VIEW_OVERRIDES_N_ITEMS_DELETED_1="Isbeddelka luqadda waa la tirtiray."
COM_LANGUAGES_VIEW_OVERRIDES_NO_ITEM_SELECTED="Kama aadan dooran wax isbeddel ah."
COM_LANGUAGES_VIEW_OVERRIDES_PURGE="Nadiifi Kaydka"
COM_LANGUAGES_VIEW_OVERRIDES_PURGE_SUCCESS="Jadwalka kaydka isbeddelka ayaa la nadiifiyey."
COM_LANGUAGES_VIEW_OVERRIDES_TEXT="Qoraal"
COM_LANGUAGES_VIEW_OVERRIDES_TEXT_ASC="Qoraalka kor u kacaya"
COM_LANGUAGES_VIEW_OVERRIDES_TEXT_DESC="Qoraalka hoos u dhacaya"
COM_LANGUAGES_VIEW_OVERRIDES_TITLE="Luqadaha: Isbedelada"
COM_LANGUAGES_XML_DESCRIPTION="Kala soocidda luuqadda"

JLIB_RULES_SETTING_NOTES_COM_LANGUAGES="Isbeddelladu waxay ku khuseeyaan qalabkan oo keliya.<br><em><strong>Dhaxlan</strong></em> - Dejin Qaabeyn Guud ama heerka sare ayaa la hirgelinayaa.<br><em><strong>Laga diiday</strong></em> had iyo jeer ayaa guuleysta - wax kasta oo lagu dejiyay Qaabeyn Guud ama heerka sare ee lagu dabaqi karo dhammaan walxaha ilmaha ah.<br><em><strong>La oggol yahay</strong></em> waxay awoodi doontaa ficilka qalabkan illaa ay ka horjoogsato Dejinta Qaabeynta Guud."

