; Joomla! Project
; (C) 2009 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_USERS="Isticmaalayaasha"
COM_USERS_CONTENT_TYPE_CATEGORY="Nooca Qoraalka Isticmaalaha"
COM_USERS_CONTENT_TYPE_NOTE="Qoraalada Isticmaalaha"
COM_USERS_CONTENT_TYPE_USER="Isticmaalaha"
COM_USERS_GROUP_VIEW_EDIT_DESC="Tusayaa foom si loo abuuro Koox Isticmaalaheen cusub"
COM_USERS_GROUP_VIEW_EDIT_TITLE="Abuur Koox Isticmaalaheen"
COM_USERS_GROUPS_VIEW_DEFAULT_DESC="Tusayaa Liiska Kooxaha Isticmaalaheen"
COM_USERS_GROUPS_VIEW_DEFAULT_TITLE="Kooxaha Isticmaalaheen"
COM_USERS_LEVEL_VIEW_EDIT_DESC="Tusayaa foom si loo abuuro Heer-Galitaan cusub"
COM_USERS_LEVEL_VIEW_EDIT_TITLE="Abuur Heer-Galitaan"
COM_USERS_LEVELS_VIEW_DEFAULT_DESC="Tusayaa Liiska Heer-Galitaan"
COM_USERS_LEVELS_VIEW_DEFAULT_TITLE="Heer-Galitaan"
COM_USERS_LOGIN_VIEW_DEFAULT_DESC="Tusayaa foom-galitaan."
COM_USERS_LOGIN_VIEW_DEFAULT_OPTION="Foom-Galitaan"
COM_USERS_LOGIN_VIEW_DEFAULT_TITLE="Foom-Galitaan"
COM_USERS_LOGOUT_VIEW_DEFAULT_DESC="Si toos ah uga bax oo u jiheey bog."
COM_USERS_LOGOUT_VIEW_DEFAULT_OPTION="Ka Bax"
COM_USERS_LOGOUT_VIEW_DEFAULT_TITLE="Ka Bax"
COM_USERS_MAIL_VIEW_DEFAULT_DESC="Tusayaa foom si loo diro iimayl ballaaran oo loo diro isticmaalayaal badan."
COM_USERS_MAIL_VIEW_DEFAULT_TITLE="Iimayl Guud Isticmaalayaasha"
COM_USERS_MENUS="Isticmaalayaasha"
COM_USERS_MENUS_ADD_GROUP="Kudar Koox"
COM_USERS_MENUS_ADD_LEVEL="Kudar Heer-Galitaan"
COM_USERS_MENUS_ADD_NOTE="Kudar Qoraal Isticmaale"
COM_USERS_MENUS_ADD_USER="Kudar Isticmaale"
COM_USERS_MENUS_FIELDS="Goobaha Isticmaalaha"
COM_USERS_MENUS_GROUPS="Kooxaha"
COM_USERS_MENUS_LEVELS="Heerarka Gelitaanka"
COM_USERS_MENUS_MISC="Kale duwan"
COM_USERS_MENUS_NOTE_CATEGORIES="Qaybaha Xusuus-qorka Isticmaalaha"
COM_USERS_MENUS_NOTES="Xusuus-qorka Isticmaalaha"
COM_USERS_MENUS_PRESET_USERS="Cabirka Hore - Dashboard-ka Isticmaalayaasha"
COM_USERS_MENUS_USER_MANAGER="Maamul"
COM_USERS_MENUS_USERS="Isticmaalayaasha"
COM_USERS_NOTE_VIEW_EDIT_DESC="Waxayna muujisaa foom si loo abuuro Xusuus-qorka Isticmaalaha cusub"
COM_USERS_NOTE_VIEW_EDIT_TITLE="Abuur Xusuus-qor Isticmaale"
COM_USERS_NOTES_VIEW_DEFAULT_DESC="Waxay muujisaa Liiska Xusuus-qorka Isticmaalaha"
COM_USERS_NOTES_VIEW_DEFAULT_TITLE="Xusuus-qorka Isticmaalaha"
COM_USERS_PROFILE_EDIT_DEFAULT_DESC="Tafatir macluumaadka isticmaaleyaasha."
COM_USERS_PROFILE_EDIT_DEFAULT_OPTION="Tafatir Macluumaadka Isticmaalaha"
COM_USERS_PROFILE_EDIT_DEFAULT_TITLE="Tafatir Macluumaadka Isticmaalaha"
COM_USERS_PROFILE_VIEW_DEFAULT_DESC="Waxay muujisaa macluumaadka isticmaalaha."
COM_USERS_PROFILE_VIEW_DEFAULT_OPTION="Macluumaadka Isticmaalaha"
COM_USERS_PROFILE_VIEW_DEFAULT_TITLE="Macluumaadka Isticmaalaha"
COM_USERS_REGISTRATION_VIEW_DEFAULT_DESC="Waxay muujisaa foomka diiwaangelinta. Waa in la oggolaadaa Diiwaangelinta Isticmaalaha ee xulashada isticmaalaha."
COM_USERS_REGISTRATION_VIEW_DEFAULT_OPTION="Caadi ah"
COM_USERS_REGISTRATION_VIEW_DEFAULT_TITLE="Foomka Diiwaangelinta"
COM_USERS_REMIND_VIEW_DEFAULT_DESC="Waxay muujisaa codsiga xasuusinta magaca isticmaal."
COM_USERS_REMIND_VIEW_DEFAULT_OPTION="Caadi ah"
COM_USERS_REMIND_VIEW_DEFAULT_TITLE="Codsiga Xasuusinta Magaca Isticmaal"
COM_USERS_RESET_VIEW_DEFAULT_DESC="Muujiyaa codsi dib loogu dejinayo erayga sirta ah."
COM_USERS_RESET_VIEW_DEFAULT_OPTION="Asal"
COM_USERS_RESET_VIEW_DEFAULT_TITLE="Dib-u-dejin Erayga sirta ah"
COM_USERS_TAGS_CATEGORY="Qaybta Ogaysiiska Isticmaale"
COM_USERS_USER_VIEW_EDIT_DESC="Muujiyaa foom lagu abuurayo Xisaab Isticmaale cusub"
COM_USERS_USER_VIEW_EDIT_TITLE="Abuur Isticmaale"
COM_USERS_USERS_VIEW_DEFAULT_DESC="Soo bandhigaa Liiska Isticmaalayaasha"
COM_USERS_USERS_VIEW_DEFAULT_TITLE="Isticmaalayaasha"
COM_USERS_XML_DESCRIPTION="Qayb maamuleysa isticmaalayaasha."

