; Joomla! Project
; (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_ASSOCIATIONS="Isku-xirnaanta Luuqadaha Badan"
COM_ASSOCIATIONS_ADD_NEW_ASSOCIATION="Ku dar isku-xir cusub"
COM_ASSOCIATIONS_ASSOCIATED_ITEM="Bartilmaameedka"
COM_ASSOCIATIONS_CHANGE_TARGET="Beddel Bartilmaameedka"
COM_ASSOCIATIONS_COMPONENT_NOT_SUPPORTED="Kordhinta %s ma taageerto isku-xirnaanta luuqadaha badan."
COM_ASSOCIATIONS_CONFIGURATION="Isku-xirnaanta Luuqadaha Badan: Xulashooyinka"
COM_ASSOCIATIONS_COPY_REFERENCE="Ku Koobi Tixraac Bartilmaameedka"
COM_ASSOCIATIONS_DELETE_ORPHANS="Tirtir Orfo"
COM_ASSOCIATIONS_DELETE_ORPHANS_FAILED="Ku guuldareystay tirtirka orfada."
COM_ASSOCIATIONS_DELETE_ORPHANS_NONE="Ma jiro orfo la tirtirayo."
COM_ASSOCIATIONS_DELETE_ORPHANS_SUCCESS="Orfadii oo dhan waa la tirtiray."
COM_ASSOCIATIONS_EDIT_ASSOCIATION="Wax ka beddel isku-xirka"
COM_ASSOCIATIONS_EDIT_HIDE_REFERENCE="Qari Tixraac"
COM_ASSOCIATIONS_EDIT_SHOW_REFERENCE="Muji Tixraac"
COM_ASSOCIATIONS_ERROR_NO_ASSOC="Ma abuuri kartid isku-xirnaanta luuqadaha badan haddii goobtu aanay u dhigin sidii luuqadaha badan iyo/ama isku-xirnaanta aan la hawlgelin <a href=\"%s\">Plugin-ka Sifeeyo Luuqadaha</a>."
COM_ASSOCIATIONS_ERROR_NO_TYPE="Nooca shayga ee la xulay uma jiro qaybtaan."
COM_ASSOCIATIONS_FILTER_SEARCH_DESC="Raadi shayga adoo ku magacawaya cinwaankiisa"
COM_ASSOCIATIONS_FILTER_SEARCH_LABEL="Raadi shay"
COM_ASSOCIATIONS_FILTER_SELECT_ITEM="Xulo Nooca Shayga"
COM_ASSOCIATIONS_FILTER_SELECT_ITEM_TYPE="- Xulo Nooca Shayga -"
COM_ASSOCIATIONS_FILTER_SELECT_LANGUAGE="Xulo Luuqadda"
COM_ASSOCIATIONS_HEADING_ASSOCIATION="Isku-xirnaanta"
COM_ASSOCIATIONS_HEADING_MENUTYPE="Liiska"
COM_ASSOCIATIONS_HEADING_MENUTYPE_ASC="Liiska kor u socda"
COM_ASSOCIATIONS_HEADING_MENUTYPE_DESC="Liiska hoos u socda"
COM_ASSOCIATIONS_HEADING_NO_ASSOCIATION="Lama Xirin"
COM_ASSOCIATIONS_ITEMS="Qodobbada"
COM_ASSOCIATIONS_NO_ASSOCIATION="Ma jiro waxna xidhiidh ah luuqaddan"
COM_ASSOCIATIONS_NOTICE_NO_SELECTORS="Fadlan dooro Nooca Shayga iyo luuqada tixraaca si aad u aragto xidhiidhada."
COM_ASSOCIATIONS_PURGE="Tirtir Dhammaan Xidhiidhada"
COM_ASSOCIATIONS_PURGE_CONFIRM_PROMPT="Ma hubtaa inaad doonayso inaad tirtirto dhammaan xidhiidhada? Xaqiijinta waxay si joogto ah u tirtiri doontaa!"
COM_ASSOCIATIONS_PURGE_FAILED="Ku guuldaraystay tirtirista dhammaan xidhiidhada."
COM_ASSOCIATIONS_PURGE_NONE="Ma jiraan wax xidhiidho ah oo la tirtiray."
COM_ASSOCIATIONS_PURGE_SUCCESS="Dhammaan xidhiidhada waa la tirtiray."
COM_ASSOCIATIONS_REFERENCE_ITEM="Tixraac"
COM_ASSOCIATIONS_SAVE_REFERENCE="Kaydi Tixraaca"
COM_ASSOCIATIONS_SAVE_TARGET="Kaydi Bartilmaameedka"
COM_ASSOCIATIONS_SELECT_MENU="- Dooro Menu -"
COM_ASSOCIATIONS_SELECT_TARGET="Dooro Bartilmaameedka"
COM_ASSOCIATIONS_SELECT_TARGET_LANGUAGE="- Dooro Luuqada Bartilmaameedka -"
COM_ASSOCIATIONS_SELECT_TARGET_LANGUAGE_LABEL="Dooro Luuqada Bartilmaameedka"
COM_ASSOCIATIONS_TABLE_CAPTION="Xidhiidhada"
COM_ASSOCIATIONS_TITLE="Xidhiidhada"
COM_ASSOCIATIONS_TITLE_EDIT="Xidhiidhada Multilingual: Tafatir Xidhiidhada (%1$s &rarr; %2$s)"
COM_ASSOCIATIONS_TITLE_LIST="Xidhiidhada Multilingual (%1$s &rarr; %2$s)"
COM_ASSOCIATIONS_TITLE_LIST_SELECT="Xidhiidhada Multilingual: Dooro Nooca Shayga iyo Luuqada"
COM_ASSOCIATIONS_XML_DESCRIPTION="Qaybta maamulka nuxurka badanluuqad leh ee la hagaajiyay"
COM_ASSOCIATIONS_YOU_ARE_NOT_ALLOWED_TO_CHECKIN_THIS_ITEM="Ma awoodid inaad hubiso shaygan"

