; Joomla! Project
; (C) 2013 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_CONTENTHISTORY_BUTTON_COMPARE="Isbarbardhig"
COM_CONTENTHISTORY_BUTTON_COMPARE_DESC="Xulo laba nooc oo xulo si aad u isbarbar dhigto."
COM_CONTENTHISTORY_BUTTON_DELETE="Tirtir"
COM_CONTENTHISTORY_BUTTON_DELETE_DESC="Xulo hal ama in ka badan oo ka dibna xulo si khaas ah u tirtirto."
COM_CONTENTHISTORY_BUTTON_KEEP="Hayso/Waa musuq"
COM_CONTENTHISTORY_BUTTON_KEEP_DESC="Xulo hal ama ka badan oo xulo si aad u hagaajiso in la hayn doono weligiis ama la joojiyo."
COM_CONTENTHISTORY_BUTTON_LOAD="Soo celi"
COM_CONTENTHISTORY_BUTTON_LOAD_DESC="Badhankan wuxuu galinayaa nooca la xusho foomka tafatirka."
COM_CONTENTHISTORY_BUTTON_PREVIEW="Hordhac"
COM_CONTENTHISTORY_BUTTON_PREVIEW_DESC="Badhaman wuxuu ku ogolaanayaa inaad aragto aragti hordhac ah ee nooca la xushay."
COM_CONTENTHISTORY_BUTTON_SELECT_ONE_VERSION="Fadlan hal nooc xulo."
COM_CONTENTHISTORY_BUTTON_SELECT_TWO_VERSIONS="Fadlan laba nooc xulo."
COM_CONTENTHISTORY_CHARACTER_COUNT="Tirada Xarfaha"
COM_CONTENTHISTORY_COMPARE_CAPTION="Isbarbardhiga Laba Nooc"
COM_CONTENTHISTORY_COMPARE_DIFF="Bedelka"
COM_CONTENTHISTORY_COMPARE_NEW="Cusub"
COM_CONTENTHISTORY_COMPARE_OLD="Hore"
COM_CONTENTHISTORY_COMPARE_TITLE="Isbarbardhig Muuqaalka"
COM_CONTENTHISTORY_ERROR_FAILED_LOADING_CONTENT_TYPE="Nooca muuqaalka oo la saarin waayey."
COM_CONTENTHISTORY_ERROR_INVALID_ID="ID khaldan ayaa la soo xulay."
COM_CONTENTHISTORY_ERROR_KEEP_NOT_PERMITTED="Laguma ogola in aad bedesho xaaladda hayso weligiin."
COM_CONTENTHISTORY_ERROR_VERSION_NOT_FOUND="Muuqaalka ma helin."
COM_CONTENTHISTORY_KEEP_VERSION="Hayso Weligiin"
COM_CONTENTHISTORY_MODAL_TITLE="Sooyaalka Nooca Shayga"
COM_CONTENTHISTORY_N_ITEMS_DELETED="%d sooyaal noocyada la tirtiray."
COM_CONTENTHISTORY_N_ITEMS_DELETED_1="Nuqulka taariikhda ayaa la tirtiray."
COM_CONTENTHISTORY_N_ITEMS_KEEP_TOGGLE="Qiimaha joogtada ah ee la bedelay %d nuqulka taariikhda."
COM_CONTENTHISTORY_N_ITEMS_KEEP_TOGGLE_1="Qiimaha joogtada ah ee la bedelay nuqulka taariikhda."
COM_CONTENTHISTORY_NO_ITEM_SELECTED="Ma jiro nuqul taariikh ah oo la xushay."
COM_CONTENTHISTORY_PREVIEW_CAPTION="Faahfaahinta Nuqulka"
COM_CONTENTHISTORY_PREVIEW_FIELD="Qeyd"
COM_CONTENTHISTORY_PREVIEW_SUBTITLE="Nuqul Fiiro gaar ah: %s"
COM_CONTENTHISTORY_PREVIEW_SUBTITLE_DATE="Muuqaalka nuqulka laga bilaabo %s"
COM_CONTENTHISTORY_PREVIEW_VALUE="Qiimaha"
COM_CONTENTHISTORY_VERSION_CAPTION="Dhammaan Nuqulka"
COM_CONTENTHISTORY_VERSION_NOTE="Nuqul Fiiro gaar ah"

