; Joomla! Project
; (C) 2018 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_WORKFLOW_BASIC_STAGE="Marxaladda Asaasiga ah"
COM_WORKFLOW_BASIC_WORKFLOW="Shaqad Cusub"
COM_WORKFLOW_CHOOSE_CONTEXT_LABEL="Qorshe"
COM_WORKFLOW_COUNT_STAGES="Marxalado"
COM_WORKFLOW_COUNT_TRANSITIONS="Isbeddelada"
COM_WORKFLOW_CREATED_LABEL="Taariikhda La Sameeyay"
COM_WORKFLOW_DEFAULT="Dejinta Caadiga ah"
COM_WORKFLOW_DESCRIPTION="Sharaxaad"
COM_WORKFLOW_DISABLE_DEFAULT="Xaaladda caadiga ah lama beddeli karo."
COM_WORKFLOW_ERROR_EXTENSION_NOT_SET="Kordhinta lama dejin."
COM_WORKFLOW_ERROR_WORKFLOW_ID_NOT_SET="Aqoonsiga Shaqada lama dejin."
COM_WORKFLOW_FIELD_IS_DEFAULT_LABEL="Caadi"
COM_WORKFLOW_FIELD_NAME_LABEL="Magac"
COM_WORKFLOW_FILTER_SEARCH_DESC="Raadi cinwaanka iyo sharaxaadda."
COM_WORKFLOW_FILTER_SEARCH_LABEL="Raadi"
COM_WORKFLOW_FORM_EDIT="Sax Shaqada"
COM_WORKFLOW_FORM_NEW="Shaqada Cusub"
COM_WORKFLOW_FROM_STAGE="Marxaladda Hada"
COM_WORKFLOW_FROM_STAGE_FILTER_ASC="Marxaladda Hadda soo kordhaysa"
COM_WORKFLOW_FROM_STAGE_FILTER_DESC="Marxaladda hadda hoos u dhacayso"
COM_WORKFLOW_ID="Aqoonsi"
COM_WORKFLOW_INHERIT_WORKFLOW="Dhaxlay (%s)"
COM_WORKFLOW_INHERIT_WORKFLOW_NEW="Dhaxlay"
COM_WORKFLOW_ITEM_MUST_PUBLISHED="Shayga waa in la daabaco si loo dejiyo marxaladda caadiga ah."
COM_WORKFLOW_ITEM_UNSET_DEFAULT="Marxaladda caadiga ah lama dejin."
COM_WORKFLOW_MODIFIED_LABEL="Taariikhda La Bedelay"
COM_WORKFLOW_MSG_DELETE_IS_DEFAULT="Waxaad tirtiri karin sheyga asalka ah."
COM_WORKFLOW_MSG_DELETE_STAGE_IS_ASSIGNED="Marxaladani waxaa loo xilsaaray shey ka mid ah qaybtaan oo waa inay ku sii jirto xaalad la-daabacay."
COM_WORKFLOW_MSG_DELETE_WORKFLOW_IS_ASSIGNED="Hawl socodkan waxaa isticmaalaya qaybtaan."
COM_WORKFLOW_MSG_DISABLE_DEFAULT="Sheyga asalka ah waa inuu ku sii jiraa la-daabacna."
COM_WORKFLOW_MSG_WORKFLOWS_DELETE_ERROR="Dhibaato ayaa dhacday marka la tirtirayo sheyga: %s"
COM_WORKFLOW_NAME="Magaca"
COM_WORKFLOW_NO_ITEM_SELECTED="Hawl socod lama xulin."
COM_WORKFLOW_N_ITEMS_CHECKED_IN="%d hawl socod dib ayaa loo galiyo."
COM_WORKFLOW_N_ITEMS_CHECKED_IN_1="Hawl socod dib loo galiyeey."
COM_WORKFLOW_N_ITEMS_DELETED="%d hawl socod ayaa la tirtiray."
COM_WORKFLOW_N_ITEMS_DELETED_1="Hawl socod la tirtiray."
COM_WORKFLOW_N_ITEMS_PUBLISHED="%d hawl socod waa la suurta geliyay."
COM_WORKFLOW_N_ITEMS_PUBLISHED_1="Hawl socod waa la suurta geliyay."
COM_WORKFLOW_N_ITEMS_TRASHED="%d hawl socod ayaa kaleexay qashinka."
COM_WORKFLOW_N_ITEMS_TRASHED_1="Hawl socod kaleexay qashinka."
COM_WORKFLOW_N_ITEMS_UNPUBLISHED="%d hawl socod waa la demiyeey."
COM_WORKFLOW_N_ITEMS_UNPUBLISHED_1="Hawl socod waa la demiyeey."
COM_WORKFLOW_PUBLISHED_LABEL="Xaaladda"
COM_WORKFLOW_RULES_TAB="Ogolaanshaha"
COM_WORKFLOW_SELECT_FROM_STAGE="- Dooro Marxaladda Hadda -"
COM_WORKFLOW_SELECT_TO_STAGE="- Dooro Marxaladda Bar-tilmamaadka -"
COM_WORKFLOW_SET_DEFAULT="Hawl socod waxaa loo dhigay in uu yahay asalka."
COM_WORKFLOW_STAGES="Marxaladaha"
COM_WORKFLOW_STAGES_LIST="Marxaladaha: %s"
COM_WORKFLOW_STAGES_N_ITEMS_CHECKED_IN="%d heerar ayaa la hubiyey."
COM_WORKFLOW_STAGES_N_ITEMS_CHECKED_IN_1="Heer la hubiyey."
COM_WORKFLOW_STAGES_N_ITEMS_DELETED="%d heerar ayaa la tirtiray."
COM_WORKFLOW_STAGES_N_ITEMS_DELETED_1="Heer la tirtiray."
COM_WORKFLOW_STAGES_N_ITEMS_PUBLISHED="%d heerar ayaa la awood siiyey."
COM_WORKFLOW_STAGES_N_ITEMS_PUBLISHED_1="Heer la awood siiyey."
COM_WORKFLOW_STAGES_N_ITEMS_TRASHED="%d heerar ayaa la qashinsaaray."
COM_WORKFLOW_STAGES_N_ITEMS_TRASHED_1="Heer la qashinsaaray."
COM_WORKFLOW_STAGES_N_ITEMS_UNPUBLISHED="%d heerar ayaa la naafoobay."
COM_WORKFLOW_STAGES_N_ITEMS_UNPUBLISHED_1="Heer la naafoobay."
COM_WORKFLOW_STAGES_TABLE_CAPTION="Heerarka Qaab shaqadeedka"
COM_WORKFLOW_STAGE_ADD="Ku dar Heer"
COM_WORKFLOW_STAGE_EDIT="Tafatir Heer"
COM_WORKFLOW_STAGE_FORM_EDIT="Tafatir Heer"
COM_WORKFLOW_STAGE_FORM_NEW="Ku dar Heer"
COM_WORKFLOW_STAGE_NOTE="Qoraal"
COM_WORKFLOW_STAGE_SET_DEFAULT="Heerka waxaa loo dejiyay sida caadiga ah."
COM_WORKFLOW_TITLE_TRANSLATION="Magac (%s)"
COM_WORKFLOW_TOOLBAR_DEFAULT="Caadi"
COM_WORKFLOW_TOO_MANY_STAGES="Hal heer oo keliya ayaa loo dejin karaa sida caadiga ah."
COM_WORKFLOW_TOO_MANY_WORKFLOWS="Hal qaab shaqo oo keliya ayaa loo dejin karaa sida caadiga ah."
COM_WORKFLOW_TO_STAGE="Heer Bartilmaameed"
COM_WORKFLOW_TO_STAGE_FILTER_ASC="Heer Bartilmaameed koraya"
COM_WORKFLOW_TO_STAGE_FILTER_DESC="Heer Bartilmaameed hoos u dhacaya"
COM_WORKFLOW_TRANSITION="Kala guurka"
COM_WORKFLOW_TRANSITIONS="Habaynta"
COM_WORKFLOW_TRANSITIONS_LIST="Habaynta: %s"
COM_WORKFLOW_TRANSITIONS_N_ITEMS_CHECKED_IN="%d habaynta waa la hubiyay."
COM_WORKFLOW_TRANSITIONS_N_ITEMS_CHECKED_IN_1="Habaynta waa la hubiyay."
COM_WORKFLOW_TRANSITIONS_N_ITEMS_DELETED="%d habaynta waa la tirtiray."
COM_WORKFLOW_TRANSITIONS_N_ITEMS_DELETED_1="Habaynta waa la tirtiray."
COM_WORKFLOW_TRANSITIONS_N_ITEMS_PUBLISHED="%d habaynta ayaa la awood siiyay."
COM_WORKFLOW_TRANSITIONS_N_ITEMS_PUBLISHED_1="Habaynta waa la awood siiyay."
COM_WORKFLOW_TRANSITIONS_N_ITEMS_TRASHED="%d habaynta ayaa qashinka la dhigay."
COM_WORKFLOW_TRANSITIONS_N_ITEMS_TRASHED_1="Habaynta ayaa qashinka la dhigay."
COM_WORKFLOW_TRANSITIONS_N_ITEMS_UNPUBLISHED="%d habaynta ayaa la naafoobay."
COM_WORKFLOW_TRANSITIONS_N_ITEMS_UNPUBLISHED_1="Habaynta waa la naafoobay."
COM_WORKFLOW_TRANSITIONS_TABLE_CAPTION="Habaynta Hawsha"
COM_WORKFLOW_TRANSITION_ACTIONS_LABEL="Ficillada Habaynta"
COM_WORKFLOW_TRANSITION_ADD="Ku dar Habaynta"
COM_WORKFLOW_TRANSITION_EDIT="Tafatir Habaynta"
COM_WORKFLOW_TRANSITION_FORM_EDIT="Tafatir Habaynta"
COM_WORKFLOW_TRANSITION_FORM_NEW="Habaynta Cusub"
COM_WORKFLOW_TRANSITION_NOTE="Qoraal"
COM_WORKFLOW_UNPUBLISH_DEFAULT_ERROR="Hawsha asaliga ah lama naafoobi karo."
COM_WORKFLOW_USE_DEFAULT_WORKFLOW="Adeegso asalka (%s)"
COM_WORKFLOW_WORKFLOWS_ADD="Ku dar Hawsha"
COM_WORKFLOW_WORKFLOWS_EDIT="Tafatir Hawsha"
COM_WORKFLOW_WORKFLOWS_LIST="Hawlgallada"
COM_WORKFLOW_WORKFLOWS_TABLE_CAPTION="Hawlgallada"
COM_WORKFLOW_WORKFLOW_NOTE="Qoraal"
JLIB_HTML_PUBLISH_ITEM="Dami"
JLIB_HTML_UNPUBLISH_ITEM="Awoodi"

