; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

CATEGORIES_FIELDSET_OPTIONS="Ikhtiyaarada"
COM_CATEGORIES="Qaybaha"
COM_CATEGORIES_BATCH_CANNOT_CREATE="Ma tihid loo ogol yahay inaad abuurto qayb cusub qaybtaan."
COM_CATEGORIES_BATCH_CANNOT_EDIT="Ma tihid loo ogol yahay inaad wax ka bedesho mid ama in ka badan oo ka mid ah qaybahan."
COM_CATEGORIES_BATCH_OPTIONS="Habka xidhmada u habayn qaybaha la xushay."
COM_CATEGORIES_BATCH_TIP="Haddii qayb la doortay oo lagu wareejinayo/nuqulayo, waxqabad kasta oo la xusho waxaa lagu dabaqi doonaa qaybaha la koobiyeeyay ama lagu wareejiyay. Haddaysan sidaas ahayn, dhammaan ficillada waxaa lagu dabaqi doonaa qaybaha la xushay."
COM_CATEGORIES_CATEGORIES_BASE_TITLE="Qaybaha"
COM_CATEGORIES_CATEGORIES_TITLE="%s: Qaybaha"
COM_CATEGORIES_CATEGORY_ADD_TITLE="%s: Qayb cusub"
COM_CATEGORIES_CATEGORY_BASE_ADD_TITLE="Qayb cusub"
COM_CATEGORIES_CATEGORY_BASE_EDIT_TITLE="Tafatir Qayb"
COM_CATEGORIES_CATEGORY_EDIT_TITLE="%s: Tafatir Qayb"
COM_CATEGORIES_COUNT_ARCHIVED_ITEMS="Qodobbada Aarkhifka"
COM_CATEGORIES_COUNT_PUBLISHED_ITEMS="Qodobbada La Daabacay"
COM_CATEGORIES_COUNT_TRASHED_ITEMS="Qodobbada La Diiday"
COM_CATEGORIES_COUNT_UNPUBLISHED_ITEMS="Qodobbada Aan La Daabacin"
COM_CATEGORIES_DELETE_NOT_ALLOWED="Tirtirid looma ogola qaybta %s."
COM_CATEGORIES_EDIT_CATEGORY="Tafatir Qayb"
COM_CATEGORIES_EMPTYSTATE_BUTTON_ADD="Kudar Qayb"
COM_CATEGORIES_EMPTYSTATE_CONTENT="Ma jiraan qayb haatan loogu talagalay kordhintaan."
COM_CATEGORIES_ERROR_ALL_LANGUAGE_ASSOCIATED="Shayga qaybta oo loo dhigay dhammaan luqadaha lama xiriirin karo. Isku-xirnaanta lama dhigin."
COM_CATEGORIES_FIELD_BASIC_LABEL="Ikhtiyaarada"
COM_CATEGORIES_FIELD_IMAGE_ALT_EMPTY_DESC="Sawir Qurxin - sharaxaad uma baahna"
COM_CATEGORIES_FIELD_IMAGE_ALT_EMPTY_LABEL="Sharaxaad Ma Jirto"
COM_CATEGORIES_FIELD_IMAGE_ALT_LABEL="Sharaxaada Sawirka (Alt Text)"
COM_CATEGORIES_FIELD_IMAGE_LABEL="Sawir"
COM_CATEGORIES_FIELD_NOTE_LABEL="Qoraal"
COM_CATEGORIES_FIELD_PARENT_LABEL="Waalid"
COM_CATEGORIES_FIELDSET_DETAILS="Faahfaahinta Qaybta"
COM_CATEGORIES_FIELDSET_PUBLISHING="Daabacaadda"
COM_CATEGORIES_FIELDSET_RULES="Ogolaansho"
COM_CATEGORIES_FILTER_SEARCH_DESC="Raadi cinwaanka, magaca iyo qoraalka. Ku hormari ID: si aad u raadsato aqoonsiga qaybta."
COM_CATEGORIES_FILTER_SEARCH_LABEL="Raadi Qaybaha"
COM_CATEGORIES_FORM_TITLE_EDIT="Tafatir Qaybta"
COM_CATEGORIES_FORM_TITLE_NEW="Qayb Cusub"
COM_CATEGORIES_HAS_SUBCATEGORY_ITEMS="%d shay ayaa loo qoondeeyay qaybo-hoosaadyada qaybtaan."
COM_CATEGORIES_HAS_SUBCATEGORY_ITEMS_1="Hal shay ayaa loo qoondeeyay mid ka mid ah qayb-hoosaadka qaybtaan."
COM_CATEGORIES_HEADING_ARCHIVED="Kaydiyay"
COM_CATEGORIES_HEADING_PUBLISHED="La daabacay"
COM_CATEGORIES_HEADING_TRASHED="La tuuray"
COM_CATEGORIES_HEADING_UNPUBLISHED="Lama daabicin"
COM_CATEGORIES_HEADING_ASSOCIATION="Urur"
COM_CATEGORIES_ITEMS_SEARCH_FILTER="Raadi"
COM_CATEGORIES_N_ITEMS_ARCHIVED="%d qaybo kaydiyay."
COM_CATEGORIES_N_ITEMS_ARCHIVED_1="Qayb la kaydiyay."
COM_CATEGORIES_N_ITEMS_ASSIGNED="%d shay ayaa loo qoondeeyay qaybtaan."
COM_CATEGORIES_N_ITEMS_ASSIGNED_1="Hal shay ayaa loo qoondeeyay qaybtaan."
COM_CATEGORIES_N_ITEMS_CHECKED_IN_1="Qayb la saxay."
COM_CATEGORIES_N_ITEMS_CHECKED_IN_MORE="%d qaybo la saxay."
COM_CATEGORIES_N_ITEMS_DELETED="%d qaybo la tirtiray."
COM_CATEGORIES_N_ITEMS_DELETED_1="Qaybta waa la tirtiray."
COM_CATEGORIES_N_ITEMS_FAILED_PUBLISHING="Waa lagu guuldareystay daabicida %d qaybood sababtoo ah ugu yaraan mid ka mid ah waalidiintooda lama daabicin ama mid ka mid ah carruurtooda waa la hubiyay."
COM_CATEGORIES_N_ITEMS_FAILED_PUBLISHING_1="Waa lagu guuldareystay daabicida %d qayb sababtoo ah ugu yaraan mid ka mid ah waalidiinteeda lama daabicin ama mid ka mid ah carruurteeda waa la hubiyay."
COM_CATEGORIES_N_ITEMS_PUBLISHED="%d qaybood ayaa la daabacay."
COM_CATEGORIES_N_ITEMS_PUBLISHED_1="Qaybta waa la daabacay."
COM_CATEGORIES_N_ITEMS_TRASHED="%d qaybood ayaa la tuuray."
COM_CATEGORIES_N_ITEMS_TRASHED_1="Qaybta waa la tuuray."
COM_CATEGORIES_N_ITEMS_UNPUBLISHED="%d qaybood lama daabicin."
COM_CATEGORIES_N_ITEMS_UNPUBLISHED_1="Qayb lama daabicin."
COM_CATEGORIES_N_QUICKICON="Qaybo Maqaal"
COM_CATEGORIES_N_QUICKICON_0="Qaybo Maqaal"
COM_CATEGORIES_N_QUICKICON_1="Qayb Maqaal"
COM_CATEGORIES_N_QUICKICON_SRONLY="Qaybaha: %d qaybo maqaal ayaa la daabacay."
COM_CATEGORIES_N_QUICKICON_SRONLY_0="Qaybaha: Ma jiro qayb maqaal oo la daabacay."
COM_CATEGORIES_N_QUICKICON_SRONLY_1="Qaybaha: Hal qayb maqaal ayaa la daabacay."
COM_CATEGORIES_NEW_CATEGORY="Qayb Cusub"
COM_CATEGORIES_NO_ITEM_SELECTED="Fadlan marka hore xulo liiska."
COM_CATEGORIES_PATH_LABEL="Jidka Qaybta"
COM_CATEGORIES_REBUILD_FAILURE="Ku guuldareystay dib u dhiska xogta geedka qaybo."
COM_CATEGORIES_REBUILD_SUCCESS="Xogta geedka qaybo ayaa dib loo dhisay."
COM_CATEGORIES_SAVE_SUCCESS="Qaybta waa la keydiyay."
COM_CATEGORIES_SELECT_A_CATEGORY="Xulo Qayb"
COM_CATEGORIES_TABLE_CAPTION="Qaybaha"
COM_CATEGORIES_TIP_ASSOCIATION="Qaybaha la xiriira"
COM_CATEGORIES_XML_DESCRIPTION="Qaybtan waxay maamushaa qaybo."
JGLOBAL_NO_ITEM_SELECTED="Noocyo kuma jiraan."
JLIB_HTML_ACCESS_SUMMARY_DESC="Hoos waxaa ka muuqda dulmar ku saabsan dejimaha oggolaanshaha ee qaybtan. Dooro tab-yada kor ku xusan si aad u habayso dejimahaan ficilka."
JLIB_RULES_SETTING_NOTES_ITEM="Isbeddelladu waxay khuseeyaan qaybtan iyo dhammaan qaybaha hoos yimaada.<br><em><strong>Dhalad</strong></em> - waxaa la dhigaa dejinta Qaabaynta Guud ama heer sare.<br><em><strong>Diiday</strong></em> mar walba guulaysata - wax kasta oo la dhigaa Qaabaynta Guud ama heer sare waxay khusaysaa dhammaan waxyaabaha hoos yimaada.<br><em><strong>Oggolaaday</strong></em> waxay oggolaan doontaa ficilka qaybtan ilaa laga bilaabo Dejinta Qaabaynta Guud."

