; Joomla! Project
; (C) 2012 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_JOOMLAUPDATE="Joomla! Cusboonaysiinta"
COM_JOOMLAUPDATE_DEFAULT_VIEW_DEFAULT_DESC="Hubi Cusboonaysiinta Joomla! Oo cusboonaysii boggaaga iyadoo la adeegsanayo nooca ugu dambeeyay ee la heli karo."
COM_JOOMLAUPDATE_DEFAULT_VIEW_DEFAULT_TITLE="Eeg Cusboonaysiinta Joomla!"
COM_JOOMLAUPDATE_JOOMLAUPDATE_VIEW_DISPLAY_BADGE="Muuji Calaamad"
COM_JOOMLAUPDATE_XML_DESCRIPTION="Hal-guji oo ku cusboonaysii nooca ugu dambeeya ee Joomla."

