; Joomla! Project
; (C) 2006 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_CACHE="Kaydka"
COM_CACHE_CLEAR_CACHE="Dayactirka: Nadiifi Kaydka"
COM_CACHE_CONFIGURATION="Kaydka: Xulashooyinka"
COM_CACHE_EMPTYSTATE_CONTENT="Haddii aad shidid kaydka ee Konfiga Guud ee Joomla, markaas waxyaabaha la haysto ayaa halkan lagu soo bandhigi doonaa."
COM_CACHE_EMPTYSTATE_TITLE="Waxaad haysataa waxyaabo aan ku jirin kaydka."
COM_CACHE_ERROR_CACHE_CONNECTION_FAILED="Lama awoodin in lagu xirto kaydka si loo soo helo xogta kaydka."
COM_CACHE_ERROR_CACHE_DRIVER_UNSUPPORTED="Lama akhriyi karo xogta kaydka, maamulaha la dejiyay ee kaydka laguma taageero deegaankaan."
COM_CACHE_EXPIRED_ITEMS_DELETE_ERROR="Khalad fiican marka la nadiifiyo kooxaha kaydka: %s."
COM_CACHE_EXPIRED_ITEMS_HAVE_BEEN_DELETED="Kooxaha kaydka ee la doortay waa la nadiifiyay."
COM_CACHE_EXPIRED_ITEMS_HAVE_BEEN_PURGED="Waxyaabaha kaydka ee dhammaaday waa la nadiifiyay."
COM_CACHE_EXPIRED_ITEMS_PURGING_ERROR="Khalad ku yimid marka la nadiifinayo waxyaabaha kaydka ee dhamaaday."
COM_CACHE_FILTER_SEARCH_DESC="Raadi kooxaha kaydka."
COM_CACHE_FILTER_SEARCH_LABEL="Kaydka Raadi"
COM_CACHE_GROUP="Kooxda Kaydka"
COM_CACHE_HEADING_COUNT_ASC="Tirada Faylasha oo koraya"
COM_CACHE_HEADING_COUNT_DESC="Tirada Faylasha oo hoos u dhacaya"
COM_CACHE_HEADING_GROUP_ASC="Kooxda Kaydka oo koraya"
COM_CACHE_HEADING_GROUP_DESC="Kooxda Kaydka oo hoos u dhacaya"
COM_CACHE_HEADING_SIZE_ASC="Cabbirka oo koraya"
COM_CACHE_HEADING_SIZE_DESC="Cabbirka oo hoos u dhacaya"
COM_CACHE_MSG_ALL_CACHE_GROUPS_CLEARED="Dhamaan kooxaha kaydka waa la nadiifiyay."
COM_CACHE_MSG_SOME_CACHE_GROUPS_CLEARED="Kaliya qaar ka mid ah kooxaha kaydka ayaa la nadiifiyay."
COM_CACHE_NUMBER_OF_FILES="Tirada Fayllada"
COM_CACHE_PURGE_EXPIRED="Nadiifi Kaydka Dhamaada"
COM_CACHE_PURGE_EXPIRED_ITEMS="Nadiifi waxyaabaha dhamaaday"
COM_CACHE_PURGE_INSTRUCTIONS="Dooro badhanka Tirtir Kaydka Dhacay ee ku jira qalabka si aad u tirtirto dhammaan faylasha kaydka ee dhacay. Fiiro gaar ah: Faylasha kaydka ah ee wali ansax ah lama tirtiri doono."
COM_CACHE_QUICKICON_SRONLY="Kayd: Cabbirka kaydku waa %s."
COM_CACHE_QUICKICON_SRONLY_NOCACHE="Kaydku ma leh."
COM_CACHE_RESOURCE_INTENSIVE_WARNING="Tani waxay noqon kartaa mid kheyraad badan ku baahda goobaha leh shay badan!"
COM_CACHE_SELECT_CLIENT="- Dooro Goobta -"
COM_CACHE_SIZE="Cabbir"
COM_CACHE_TABLE_CAPTION="Faylasha la kaydiyey"
COM_CACHE_XML_DESCRIPTION="Qaybta maamulka kaydka."

JLIB_RULES_SETTING_NOTES_COM_CACHE="Isbeddeladu waxa ay khuseeyaan qaybtaan oo keliya.<br><em><strong>La dhaxlay</strong></em> - habaynta caalamiga ah ama heer sare ayaa la adeegsadaa.<br><em><strong>La diido</strong></em> had iyo jeer waa ku guuleysataa - wax kasta oo lagu dejiyo heer caalami ah ama heer sare oo khuseeya dhammaan walxaha caruurtu.<br><em><strong>La ogolaaday</strong></em> waxa ay awood siin doontaa ficilka qaybtii haddii aan laga hor istaagin habaynta guud."

