; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_CONTENT="Qoraallo"
COM_CONTENT_ADD_NEW_MENU_ITEM="Shay Cusub oo Menu ah"
COM_CONTENT_ARTICLE_CONTENT="Mawduuc"
COM_CONTENT_ARTICLES_TABLE_CAPTION="Qoraallo"
COM_CONTENT_ARTICLES_TITLE="Qoraallo"
COM_CONTENT_ATTRIBS_ARTICLE_SETTINGS_LABEL="Xulashooyinka"
COM_CONTENT_ATTRIBS_FIELDSET_LABEL="Xulashooyinka"
COM_CONTENT_BATCH_OPTIONS="Habka Agaasinka Guga ee Qoraallada La Xushay"
COM_CONTENT_BATCH_TIP="Haddii qayb la doorto oo loo guuriyo/nuskhadaynayo, falalkan la doortay waxa loo adeegsan doonaa qoraallada la guuriyay ama la ilaaliyo. Haddii kale, dhammaan falalka waxa lagu fulin doonaa qoraallada la xushay."
COM_CONTENT_CHANGE_STAGE="Beddel wejiga"
COM_CONTENT_CHANGE_STAGE_AMBIGUOUS_TRANSITIONS="Kala wareegyada qaarkood way la aqoon daranyihiin xaaladdan. Fadlan dooro kala wareegga aad doorbideyso oo sii wad."
COM_CONTENT_CONFIG_ARTICLE_SETTINGS_DESC="Xulashooyinkan waxay khuseeyaan habeynta qoraallada haddii aan loo bedelin wax isku gaar ah ama qoraal gaar ah."
COM_CONTENT_CONFIG_BLOG_SETTINGS_DESC="Xulashooyinkan waxay khuseeyaan habeyn qormo ama muuqaal la muujiyey haddii aan loo bedelin wax isku gaar ah."
COM_CONTENT_CONFIG_BLOG_SETTINGS_LABEL="Habeynta Qormooyinka/Laga Heli Karo"
COM_CONTENT_CONFIG_CATEGORIES_SETTINGS_DESC="Xulashooyinkan waxay khuseeyaan Qeybaha Qoraallada, haddii aan la bedelin qaybta/ikhtiyaarka wax gaar ah."
COM_CONTENT_CONFIG_CATEGORY_SETTINGS_DESC="Xulashooyinkan waxay khuseeyaan Qeybaha Qoraallada, haddii aan la bedelin qaybta/ikhtiyaarka wax gaar ah."
COM_CONTENT_CONFIG_EDITOR_LAYOUT="Xulashooyinkani waxay xakameeyaan habeynta bogga tifaftirka maqaalka."
COM_CONTENT_CONFIG_INTEGRATION_SETTINGS_DESC="Xulashooyinkan waxay go'aaminayaan sida Qeybta Qoraallada ay ula falgalaan waxyaabo kale."
COM_CONTENT_CONFIG_LIST_SETTINGS_DESC="Xulashooyinkan waxay khuseeyaan xulashooyinka habeynta liiska ilaa intay aan loo bedelin halkii qayb/khiyara gaar ah."
COM_CONTENT_CONFIGURATION="Qoraallo: Xulashooyinka"
COM_CONTENT_CREATE_ARTICLE_CANCEL_REDIRECT_MENU_DESC="Dooro bogga la isticmaali doono marka isticmaaluhu kansaleeyo soo gudbinta maqaalka. Asal ahaan waxaa la toosinayaa isla bogga gudbinta maqaalka (qaabka nadiifinta)."
COM_CONTENT_CREATE_ARTICLE_CANCEL_REDIRECT_MENU_LABEL="Diidmada Caymiska"
COM_CONTENT_CREATE_ARTICLE_CATEGORY_LABEL="Qeyb Gaar Ah"
COM_CONTENT_CREATE_ARTICLE_CUSTOM_CANCEL_REDIRECT_DESC="Haddii lagu dejiyo 'Haa', waxaad dejin kartaa bog kale oo lagu kala beddelo, oo ka duwan 'Gudbinta/Diidmo', marka isticmaaluhu kansaleeyo soo gudbinta maqaalka.<br>Haddii lagu dejiyo 'Maya', marka isticmaaluhu kansaleeyo soo gudbinta maqaalka, waa loo kala wareejiyaa bogga kor lagu xusay ee 'Gudbinta/Diidmada Caymiska'."
COM_CONTENT_CREATE_ARTICLE_CUSTOM_CANCEL_REDIRECT_LABEL="Toosin Dhaqan Malaha Marka La Kansaleeyo"
COM_CONTENT_CREATE_ARTICLE_ERROR="Marka qaybta gaarka ah la hawlgeliyo, waa in la doortaa qayb."
COM_CONTENT_CREATE_ARTICLE_REDIRECTMENU_DESC="Xulo bogga isticmaaluhu u wareegi doono ka dib markii la sameeyo maqaal guuleysta iyo ka dib marka la joojiyo (hadii la dejin kalee aan hoos loo dejin). Caadiga ah waa in loo wareego bogga guriga."
COM_CONTENT_CREATE_ARTICLE_REDIRECTMENU_LABEL="Wareejinta/Soo-celinta ka dib"
COM_CONTENT_DASHBOARD_TITLE="Dashboard-ka Mawduuca"
COM_CONTENT_EDIT_ARTICLE="Wax-ka-bedel Maqaal"
COM_CONTENT_EDIT_CATEGORY="Wax-ka-bedel Qayb"
COM_CONTENT_EDITING_LAYOUT="Qaabka Wax-ka-bedelka"
COM_CONTENT_EDITORCONFIG_FIELDSET_LABEL="Habeynta Shaashada Wax-ka-bedelka"
COM_CONTENT_EMPTYSTATE_BUTTON_ADD="Ku dar maqaalkaaga ugu horreeya"
COM_CONTENT_EMPTYSTATE_CONTENT="Maqaallada waa mawduucyada ugu muhiimsan ee goobo badan oo Joomla ah. Waxaad u isticmaali kartaa Tifaftire Maqaalka Joomla si aad u abuurto oo aad u maamusho nuxurkaaga."
COM_CONTENT_EMPTYSTATE_TITLE="Maqaallo lagama abuurin weli."
COM_CONTENT_ERROR_ALL_LANGUAGE_ASSOCIATED="Mawduuc set loo guufsaday luqadaha oo dhan lama isku xiriirin karo. Isku xirrida lama dejin."
COM_CONTENT_ERROR_CANNOT_ARCHIVE="Maqaallada la xulay mid ama ka badan looma dejin karo in la keydiyo."
COM_CONTENT_ERROR_CANNOT_PUBLISH="Maqaallada la xulay mid ama ka badan looma dejin karo in la daabaco."
COM_CONTENT_ERROR_CANNOT_TRASH="Maqaallada la xulay mid ama ka badan looma dejin karo in la tuuro."
COM_CONTENT_ERROR_CANNOT_UNPUBLISH="Maqaallada la xulay mid ama ka badan looma dejin karo in aan la daabacin."
COM_CONTENT_ERROR_UNIQUE_ALIAS="Qoraal kale oo ku jira qaybtaan ayaa leh magaca isku midka ah."
COM_CONTENT_ERROR_UNIQUE_ALIAS_TRASHED="Maqaal la tuuray oo ku jira qaybtaan ayaa leh magaca isku midka ah."
COM_CONTENT_ERROR_UPDATE_STAGE="Ma qabsan kartid isbedelkan ama ma cusbooneysiin kartid marxaladda."
COM_CONTENT_FEATURED_ARTICLES="Maqaallada la Muujiyay"
COM_CONTENT_FEATURED_CATEGORIES_LABEL="Xulo Qaybo"
COM_CONTENT_FEATURED_N_QUICKICON="Maqaallada la Muujiyay"
COM_CONTENT_FEATURED_N_QUICKICON_1="Maqaal La Muujiyay"
COM_CONTENT_FEATURED_N_QUICKICON_SRONLY="Maqaallada la Muujiyay: %d maqaal oo muuqda ayaa la daabacay."
COM_CONTENT_FEATURED_N_QUICKICON_SRONLY_1="Maqaal La Muujiyay: Hal maqaal oo muuqda ayaa la daabacay."
COM_CONTENT_FEATURED_ORDER="Amarka Maqaallo Muhiim ah"
COM_CONTENT_FEATURED_TABLE_CAPTION="Maqaallo Muhiim ah"
COM_CONTENT_FEATURED_TITLE="Maqaallo: Muhiim ah"
COM_CONTENT_FIELD_ARTICLETEXT_LABEL="Qoraalka Maqaalka"
COM_CONTENT_FIELD_BROWSER_PAGE_TITLE_LABEL="Cinwaanka Bogga Shabakadda"
COM_CONTENT_FIELD_CAPTCHA_LABEL="U oggolow Captcha marka la gudbiyo"
COM_CONTENT_FIELD_CREATED_BY_ALIAS_LABEL="Waxaa Abuuray Magac-La'aan"
COM_CONTENT_FIELD_CREATED_BY_LABEL="Waxaa Abuuray"
COM_CONTENT_FIELD_CREATED_LABEL="Taariikhda La Abuuray"
COM_CONTENT_FIELD_FEATURED_DOWN_LABEL="Dhameysti Muhiimka ah"
COM_CONTENT_FIELD_FEATURED_UP_LABEL="Bilow Muhiimka ah"
COM_CONTENT_FIELD_FULL_LABEL="Sawirka Maqaalka oo Dhammeystiran"
COM_CONTENT_FIELD_FULLTEXT="Qoraal dhameystiran"
COM_CONTENT_FIELD_IMAGE_ALT_EMPTY_DESC="Sawir Qurxin - ma jiro sharaxaad loo baahan yahay"
COM_CONTENT_FIELD_IMAGE_ALT_EMPTY_LABEL="Wax Sharaxaad ah Ma Jirto"
COM_CONTENT_FIELD_IMAGE_ALT_LABEL="Sharaxaadda Sawirka (Qoraalka Alt)"
COM_CONTENT_FIELD_IMAGE_CAPTION_LABEL="Qoraalka Sawirka"
COM_CONTENT_FIELD_IMAGE_CLASS_DESC="Waxaad ku dari kartaa fasal CSS gaar ah fikradahaaga qaabeynta.<br>Si aad u dhigato sawirka isticmaal tusaale ahaan float-start iyo float-end."
COM_CONTENT_FIELD_IMAGE_CLASS_LABEL="Fasalka Sawirka"
COM_CONTENT_FIELD_IMAGE_OPTIONS="Ikhtiyaarada Sawirka"
COM_CONTENT_FIELD_INFOBLOCK_POSITION_LABEL="Meel ku xidhan Macluumaadka Maqaalka"
COM_CONTENT_FIELD_INFOBLOCK_TITLE_LABEL="Cinwaanka Macluumaadka Maqaalka"
COM_CONTENT_FIELD_INTRO_LABEL="Sawirka Hordhac"
COM_CONTENT_FIELD_INTROTEXT="Qoraalka Hordhaca"
COM_CONTENT_FIELD_NOTE_LABEL="Qoraal"
COM_CONTENT_FIELD_OPTION_ABOVE="Kor"
COM_CONTENT_FIELD_OPTION_BELOW="Hoos"
COM_CONTENT_FIELD_OPTION_SPLIT="Kala qayb"
COM_CONTENT_FIELD_PUBLISH_DOWN_LABEL="Dhameyso Daabacaadda"
COM_CONTENT_FIELD_PUBLISH_UP_LABEL="Bilaab Daabacaadda"
COM_CONTENT_FIELD_SELECT_ARTICLE_LABEL="Xulo Maqaal"
COM_CONTENT_FIELD_SHOW_CAT_TAGS_LABEL="Tags"
COM_CONTENT_FIELD_SHOW_TAGS_LABEL="Tags"
COM_CONTENT_FIELD_URLA_LABEL="Link A"
COM_CONTENT_FIELD_URLA_LINK_TEXT_LABEL="Qoraalka Link A"
COM_CONTENT_FIELD_URLB_LABEL="Link B"
COM_CONTENT_FIELD_URLB_LINK_TEXT_LABEL="Qoraalka Link B"
COM_CONTENT_FIELD_URLC_LABEL="Link C"
COM_CONTENT_FIELD_URLC_LINK_TEXT_LABEL="Qoraalka Link C"
COM_CONTENT_FIELD_URLS_OPTIONS="Doorashooyinka URL"
COM_CONTENT_FIELD_URLSPOSITION_LABEL="Meelaynta Xiriirrada"
COM_CONTENT_FIELD_VALUE_USE_ARTICLE_SETTINGS="Isticmaal Habaynta Maqaalkan"
COM_CONTENT_FIELD_VERSION_LABEL="Dib-u-habeyn"
COM_CONTENT_FIELDS_ARTICLE_FIELD_ADD_TITLE="Maqaallada: Goob Cusub"
COM_CONTENT_FIELDS_ARTICLE_FIELD_EDIT_TITLE="Maqaallada: Tafatir Goob"
COM_CONTENT_FIELDS_ARTICLE_FIELDS_TITLE="Maqaallada: Goobaha"
COM_CONTENT_FIELDS_TYPE_MODAL_ARTICLE="Maqaal"
COM_CONTENT_FIELDSET_PUBLISHING="Daabacaadda"
COM_CONTENT_FIELDSET_RULES="Ogolaanshaha"
COM_CONTENT_FIELDSET_URLS_AND_IMAGES="Sawiro iyo Xiriirro"
COM_CONTENT_FILTER_AUTHORS_BY_ME="- Waxaa abuuray aniga -"
COM_CONTENT_FILTER_FEATURED_NO="Maqaallada aan muujin"
COM_CONTENT_FILTER_FEATURED_YES="Maqaallada Muujin"
COM_CONTENT_FILTER_SEARCH_DESC="Raadi cinwaanka, magaca iyo qoraalka. Hore ee ID: ama AASAASAHA: ama MAQAALKA: si aad u raadsato aqoonsi maqaal, qoraaga maqaalka ama raadinta gudaha maqaalka. Hore ee HUBI: si aad u raadsato maqaallada la hubiyay isticmaalaha mushmaksaiya."
COM_CONTENT_FILTER_SEARCH_LABEL="Raadina Maqaallo"
COM_CONTENT_FORM_TITLE_EDIT="Wax Ka Bedel Maqaal"
COM_CONTENT_FORM_TITLE_NEW="Maqaal Cusub"
COM_CONTENT_HEADING_ASSOCIATION="Isku Xirka"
COM_CONTENT_HEADING_DATE_CREATED="Taariikhda La Abuuray"
COM_CONTENT_HEADING_DATE_MODIFIED="Taariikhda Wax Ka Bedelka"
COM_CONTENT_HEADING_DATE_PUBLISH_DOWN="Dhammaadka Daabacaadda"
COM_CONTENT_HEADING_DATE_PUBLISH_UP="Bilowga Daabacaadda"
COM_CONTENT_ID_LABEL="ID"
COM_CONTENT_IMAGE_FULLTEXT_CLASS_LABEL="Fasalka Sawirka Qoraalka Dhammaatay"
COM_CONTENT_IMAGE_INTRO_CLASS_LABEL="Fasalka Sawirka Hordhac"
COM_CONTENT_MODIFIED_ASC="Taariikhda wax ka beddelka kordhinaysa"
COM_CONTENT_MODIFIED_DESC="Taariikhda wax ka beddelka hoosaysa"
COM_CONTENT_MONTH="Bisha"
COM_CONTENT_N_ITEMS_ARCHIVED="%d maqaal oo la diiwaan geliyay."
COM_CONTENT_N_ITEMS_ARCHIVED_1="Maqaal ayaa la diiwaan geeyay."
COM_CONTENT_N_ITEMS_CHECKED_IN_1="Maqaal ayaa la hubiyay."
COM_CONTENT_N_ITEMS_CHECKED_IN_MORE="%d maqaal ayaa la hubiyay."
COM_CONTENT_N_ITEMS_DELETED="%d maqaal ayaa la tirtiray."
COM_CONTENT_N_ITEMS_DELETED_1="Maqaal ayaa la tirtiro."
COM_CONTENT_N_ITEMS_FEATURED="%d maqaal ayaa la muujiyay."
COM_CONTENT_N_ITEMS_FEATURED_1="Maqaal la muujiyay."
COM_CONTENT_N_ITEMS_PUBLISHED="%d maqaallo la daabacay."
COM_CONTENT_N_ITEMS_PUBLISHED_1="Maqaal la daabacay."
COM_CONTENT_N_ITEMS_TRASHED="%d maqaallo la tuuray."
COM_CONTENT_N_ITEMS_TRASHED_1="Maqaal la tuuray."
COM_CONTENT_N_ITEMS_UNFEATURED="%d maqaallo aan la muujin."
COM_CONTENT_N_ITEMS_UNFEATURED_1="Maqaal aan la muujin."
COM_CONTENT_N_ITEMS_UNPUBLISHED="%d maqaallo aan la daabicin."
COM_CONTENT_N_ITEMS_UNPUBLISHED_1="Maqaal aan la daabicin."
COM_CONTENT_N_QUICKICON="Maqaallo"
COM_CONTENT_N_QUICKICON_0="Maqaallo"
COM_CONTENT_N_QUICKICON_1="Maqaal"
COM_CONTENT_N_QUICKICON_SRONLY="Maqaallo: %d maqaallo ayaa la heli karaa."
COM_CONTENT_N_QUICKICON_SRONLY_0="Maqaallo: Ma jiro maqaallo la heli karo."
COM_CONTENT_N_QUICKICON_SRONLY_1="Maqaallo: Hal maqaal ayaa la heli karaa."
COM_CONTENT_NEW_ARTICLE="Maqaal Cusub"
COM_CONTENT_NO_ARTICLES_LABEL="Fariin Ma Jiraan Maqaallo"
COM_CONTENT_NO_ITEM_SELECTED="Fadlan marka hore xulo wax ka mid ah liiska."
COM_CONTENT_NUMBER_CATEGORY_ITEMS_LABEL="# Maqaallo ee Qaybta"
COM_CONTENT_OTHER_OPTIONS="Ikhtiyaaro"
COM_CONTENT_PAGE_ADD_ARTICLE="Maqaallo: Cusub"
COM_CONTENT_PAGE_EDIT_ARTICLE="Maqaallo: Wax ka beddel"
COM_CONTENT_PAGE_VIEW_ARTICLE="Maqaallo: Daawasho"
COM_CONTENT_PAGEBREAK_DOC_TITLE="Burburinta Bogga"
COM_CONTENT_PAGEBREAK_INSERT_BUTTON="Geli Burburinta Bogga"
COM_CONTENT_PAGEBREAK_TITLE="Cinwaanka Bogga"
COM_CONTENT_PAGEBREAK_TOC="Magac-u-yaalka Liiska Mawduucyada"
COM_CONTENT_PUBLISH_DOWN_ASC="Dhameysashada Soo-saarista koraya"
COM_CONTENT_PUBLISH_DOWN_DESC="Dhameysashada Soo-saarista soo degaya"
COM_CONTENT_PUBLISH_UP_ASC="Bilowga Soo-saarista koraya"
COM_CONTENT_PUBLISH_UP_DESC="Bilowga Soo-saarista soo degaya"
COM_CONTENT_PUBLISHED="La daabacay"
COM_CONTENT_RUN_TRANSITION="Sii Daadaguura"
COM_CONTENT_RUN_TRANSITIONS="Sii Daadaguura Kala Duwan"
COM_CONTENT_SAVE_SUCCESS="Maqaalku waa la badbaadiyay."
COM_CONTENT_SAVE_WARNING="Magac-u-yaalkii hore ayuu maqnaaday sidaa darteed lambarka ayaa lagu daray dhammaadka. Waxaad dib u tafatiri kartaa maqaalka si aad ula qabsato magac-u-yaalka."
COM_CONTENT_SELECT_AN_ARTICLE="Xulo Maqaal"
COM_CONTENT_SELECT_FEATURED="- Xulo Xulashada -"
COM_CONTENT_SHARED_DESC="Dejinta kuwan waxay khuseeyaan Xulasho Wadaaga ee Liiska, Blogga iyo Xulashada ilaa ay ka bedelmaan dejinta menu-ga."
COM_CONTENT_SHARED_LABEL="Wadaaga"
COM_CONTENT_SHOW_ARTICLE_OPTIONS_LABEL="Doorashada Maqaalk"
COM_CONTENT_SHOW_ASSOCIATIONS_LABEL="Xiriirada Luuqadaha Kala Duwan"
COM_CONTENT_SHOW_CONFIGURE_EDIT_LABEL="Doorashooyinka Shaashada Tafatirka"
COM_CONTENT_SHOW_IMAGES_URLS_BACK_LABEL="Maamulka Sawirada iyo Isku-xirka"
COM_CONTENT_SHOW_IMAGES_URLS_FRONT_LABEL="Sawirada Hore iyo Isku-xirka"
COM_CONTENT_SHOW_PERMISSIONS_LABEL="Oggolaanshaha Maqaalk"
COM_CONTENT_SHOW_PUBLISHING_OPTIONS_LABEL="Doorashooyinka Daabacaadda"
COM_CONTENT_SLIDER_EDITOR_CONFIG="Dejinta Shaashada Tafatirka"
COM_CONTENT_STAGE_ARTICLE_TITLE="%1$s <small>(Aqoon: %2$d)</small>"
COM_CONTENT_SUBMENU_CATEGORIES="Qaybo"
COM_CONTENT_SUBMENU_FEATURED="Maqaallada Muuqda"
COM_CONTENT_SUBMENU_WORKFLOWS="Qaabdhismeedka Shaqada"
COM_CONTENT_TIP_ASSOCIATION="Maqaallada la xidhiidha"
COM_CONTENT_TRANSITION="Kala-guur"
COM_CONTENT_TRASHED="Loo tuuray"
COM_CONTENT_UNPUBLISHED="Aan la daabicin"
COM_CONTENT_URL_FIELD_A_BROWSERNAV_LABEL="URL A Daaqad Bartilmaameed ah"
COM_CONTENT_URL_FIELD_B_BROWSERNAV_LABEL="URL B Daaqad Bartilmaameed ah"
COM_CONTENT_URL_FIELD_BROWSERNAV_LABEL="URL Daaqad Bartilmaameed ah"
COM_CONTENT_URL_FIELD_C_BROWSERNAV_LABEL="URL C Daaqad Bartilmaameed ah"
COM_CONTENT_WARNING_PROVIDE_VALID_NAME="Fadlan bixiso ciwaan ansax ah oo aan bannaanayn."
COM_CONTENT_WORKFLOW="Qaabdhismeedka Shaqada"
COM_CONTENT_WORKFLOW_NOT_FOUND="Ma jiro qaab-dhismeedka shaqo ee default ah, fadlan mid qeex ama la xidhiidh maamulaha."
COM_CONTENT_WORKFLOW_STAGE="Heerka Qaabdhismeedka Shaqada"
COM_CONTENT_WORKFLOW_TRANSITION_NOT_ALLOWED="Laguma ogola inaad ku dhaqaaqdo kala-guurkan"
COM_CONTENT_WORKFLOWS="Qaabdhismeedyada Shaqada"
COM_CONTENT_XML_DESCRIPTION="Qaybta maamulka maqaalka."
JGLOBAL_NO_ITEM_SELECTED="Ma jiro maqaal la doortay"
JLIB_APPLICATION_ERROR_BATCH_CANNOT_CREATE="Laguma ogola inaad abuurto maqaallo cusub qaybtaan."
JLIB_APPLICATION_ERROR_BATCH_CANNOT_EDIT="Laguma ogola inaad wax ka beddesho mid ama in ka badan oo ka mid ah maqaalladaan."
JLIB_APPLICATION_ERROR_BATCH_CANNOT_EXECUTE_TRANSITION="Laguma ogola inaad fuliso kala-guur mid ama in ka badan oo ka mid ah maqaalladaan."

JLIB_RULES_SETTING_NOTES_COM_CONTENT="Isbeddellada waxay khuseeyaan keliya qaybtaan.<br><em><strong>Dharow</strong></em> - habayn Heerka Caalamiga ama dejintaan heer sare ah ayaa la dabaqayaa.<br><em><strong>Diidmo</strong></em> mar walba ma guulaysato - wax kasta oo lagu dejiyay heerka Caalamiga ah ama heerka sare iyo waxa lagu dabaqayaa dhammaan waxyaabaha caruurta.<br><em><strong>Ogolaansho</strong></em> wuxuu u oggolaanayaa ficilka qaybtaan ilaa laga horjoogsado dejintaan Caalamiga ah."
JLIB_RULES_SETTING_NOTES_ITEM_COM_CONTENT_ARTICLE="Isbeddellada waxay khuseeyaan maqaalkan oo kaliya.<br><em><strong>Dharow</strong></em> - habayn Heerka Caalamiga ama dejintaan heer sare ah ayaa la dabaqayaa.<br><em><strong>Diidmo</strong></em> mar walba ma guulaysato - wax kasta oo lagu dejiyay heerka Caalamiga ah ama heerka sare iyo waxa lagu dabaqayaa dhammaan waxyaabaha caruurta.<br><em><strong>Ogolaansho</strong></em> wuxuu u oggolaanayaa ficilka qaybtaan ilaa laga horjoogsado dejintaan Caalamiga ah."

COM_CONTENT_ARTICLE_CATEGORIES_TITLE="Maqaallada: Kooxaha Goobaha"
COM_CONTENT_ARTICLE_CATEGORY_ADD_TITLE="Maqaallada: Koox Goob Cusub"
COM_CONTENT_ARTICLE_CATEGORY_EDIT_TITLE="Qoraallada: Tafatirka Kooxda Goobta"

