; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_BANNERS="Xayeysiisyada"
COM_BANNERS_BANNER_DETAILS="Faahfaahinta"
COM_BANNERS_BANNER_EDIT="Tafatir Xayeysiis"
COM_BANNERS_BANNER_NEW="Xayeysiis Cusub"
COM_BANNERS_BANNER_SAVE_SUCCESS="Xayeysiiska waa la keydiyay."
COM_BANNERS_BANNERS_FILTER_SEARCH_DESC="Raadi magaca xayeysiiska iyo naanayska. DHUUX ID: si aad u raadiyo aqoonsiga xayeysiiska."
COM_BANNERS_BANNERS_FILTER_SEARCH_LABEL="Raadi Xayeysiis"
COM_BANNERS_BANNERS_HTML_PIN_BANNER="Xiid Xayeysiis"
COM_BANNERS_BANNERS_HTML_UNPIN_BANNER="Ka-qaad Xayeysiis"
COM_BANNERS_BANNERS_N_ITEMS_ARCHIVED="%d xayeysiisyo ayaa la kaydiyay."
COM_BANNERS_BANNERS_N_ITEMS_ARCHIVED_1="Xayeysiiska waa la kaydiyay."
COM_BANNERS_BANNERS_N_ITEMS_CHECKED_IN_1="Xayeysiiska waa la geliyay."
COM_BANNERS_BANNERS_N_ITEMS_CHECKED_IN_MORE="%d xayeysiisyo waa la geliyay."
COM_BANNERS_BANNERS_N_ITEMS_DELETED="%d xayeysiisyo la tirtiray."
COM_BANNERS_BANNERS_N_ITEMS_DELETED_1="Xayeysiiska waa la tirtiray."
COM_BANNERS_BANNERS_N_ITEMS_PUBLISHED="%d xayeysiisyo la daabacay."
COM_BANNERS_BANNERS_N_ITEMS_PUBLISHED_1="Xayeysiiska waa la daabacay."
COM_BANNERS_BANNERS_N_ITEMS_TRASHED="%d xayeysiisyo waa la tuuray."
COM_BANNERS_BANNERS_N_ITEMS_TRASHED_1="Xayeysiiska waa la tuuray."
COM_BANNERS_BANNERS_N_ITEMS_UNPUBLISHED="%d xayeysiisyo aan la daabicin."
COM_BANNERS_BANNERS_N_ITEMS_UNPUBLISHED_1="Xayeysiiska waa aan la daabicin."
COM_BANNERS_BANNERS_NO_ITEM_SELECTED="Ma jiro Xayeysiis la xushay."
COM_BANNERS_BANNERS_PINNED="Xayeysiiska Xaraysan"
COM_BANNERS_BANNERS_TABLE_CAPTION="Xayeysiisyada"
COM_BANNERS_BANNERS_UNPINNED="Xayeysiiska aan Xaraysnayn"
COM_BANNERS_BATCH_CLIENT_LABEL="Deji Macmiil"
COM_BANNERS_BATCH_CLIENT_NOCHANGE="- Qabo Macmiilkii Asalka ahaa -"
COM_BANNERS_BATCH_OPTIONS="Wadajir u habee xayaysiisyada la doortay"
COM_BANNERS_BATCH_TIP="Haddii qayb la doorto in la raro/la koobiyeeyo, ficil kasta oo la doorto waxa lagu dhaqangelin doonaa xayaysiisyada la koobiyeeyay ama la raray. Haddii kale, dhammaan falalka waxa lagu dhaaqlin doonaa xayaysiisyada la doortay."
COM_BANNERS_BEGIN_HINT="Taariikhda bilaabashada (yyyy-mm-dd)"
COM_BANNERS_BEGIN_LABEL="Taariikhda Bilaabashada"
COM_BANNERS_CANCEL="Jooji"
COM_BANNERS_CLICK="Guji"
COM_BANNERS_CLIENT_EDIT="Wax ka bedel Macmiilka"
COM_BANNERS_CLIENT_EMPTYSTATE_BUTTON_ADD="Kudar macmiilkaaga ugu horreeya"
COM_BANNERS_CLIENT_EMPTYSTATE_CONTENT="Macmiilka Xayaysiiska waxa uu ka kooban yahay faahfaahinta xidhiidhka iyo macluumaad dheeraad ah sida doorashada raadraaca."
COM_BANNERS_CLIENT_EMPTYSTATE_TITLE="Ilaa hadda ma jiraan Macaamiil la sameeyay."
COM_BANNERS_CLIENT_NEW="Macmiil Cusub"
COM_BANNERS_CLIENT_SAVE_SUCCESS="Macmiilka waa la keydiyay."
COM_BANNERS_CLIENTS_FILTER_SEARCH_DESC="Raadi magacyada macmiilka. Ku dar ID: si aad uga raadsato ID-ga macmiilka."
COM_BANNERS_CLIENTS_FILTER_SEARCH_LABEL="Raadi Macaamiisha"
COM_BANNERS_CLIENTS_N_ITEMS_ARCHIVED="%d macmiil ayaa la kaydiyay."
COM_BANNERS_CLIENTS_N_ITEMS_ARCHIVED_1="Macmiil la kaydiyay."
COM_BANNERS_CLIENTS_N_ITEMS_CHECKED_IN_1="Macmiil la xaqiijiyay."
COM_BANNERS_CLIENTS_N_ITEMS_CHECKED_IN_MORE="%d macmiil ayaa la xaqiijiyay."
COM_BANNERS_CLIENTS_N_ITEMS_DELETED="%d macmiil ayaa la tirtiray."
COM_BANNERS_CLIENTS_N_ITEMS_DELETED_1="Macmiil la tirtiray."
COM_BANNERS_CLIENTS_N_ITEMS_PUBLISHED="%d macmiil ayaa la daabacay."
COM_BANNERS_CLIENTS_N_ITEMS_PUBLISHED_1="Macmiil la daabacay."
COM_BANNERS_CLIENTS_N_ITEMS_TRASHED="%d macmiil ayaa la tuuray."
COM_BANNERS_CLIENTS_N_ITEMS_TRASHED_1="Macmiil la tiray."
COM_BANNERS_CLIENTS_N_ITEMS_UNPUBLISHED="%d macmiil aan la faafin."
COM_BANNERS_CLIENTS_N_ITEMS_UNPUBLISHED_1="Macmiil aan la faafin."
COM_BANNERS_CLIENTS_NO_ITEM_SELECTED="Macmiil lama xulan."
COM_BANNERS_CLIENTS_TABLE_CAPTION="Macmiisha"
COM_BANNERS_CONFIGURATION="Banners: Xulasho"
COM_BANNERS_COUNT_ARCHIVED_ITEMS="Qalabka La Kaydiyay"
COM_BANNERS_COUNT_PUBLISHED_ITEMS="Qalabka La Daabacay"
COM_BANNERS_COUNT_TRASHED_ITEMS="Qalabka La Tirtiray"
COM_BANNERS_COUNT_UNPUBLISHED_ITEMS="Qalabka Aan La Daabicin"
COM_BANNERS_DEFAULT="Caadi (%s)"
COM_BANNERS_DELETE_MSG="Ma hubtaa inaad tirtirayso dhammaan raadadkan?"
COM_BANNERS_EDIT_CLIENT="Faahfaahin"
COM_BANNERS_EMPTYSTATE_BUTTON_ADD="Kudar banner-kaaga koowaad"
COM_BANNERS_EMPTYSTATE_CONTENT="Banners waa qoraallo ku jira macluumaad xayeysiin iyo diiwaan lagu hayo inta jeer ee banner la soo bandhigay. Waxaad u isticmaali kartaa qaybtaan si aad abuurto oo aad u maamusho banneryadaada."
COM_BANNERS_EMPTYSTATE_TITLE="Lama abuurin wax Banners ah weli."
COM_BANNERS_END_HINT="Taariikhda dhammaadka (yyyy-mm-dd)"
COM_BANNERS_END_LABEL="Taariikhda Dhammaadka"
COM_BANNERS_ERR_ZIP_ADAPTER_FAILURE="Khaladka zip adapter"
COM_BANNERS_ERR_ZIP_CREATE_FAILURE="Khaladka abuuridda zip"
COM_BANNERS_ERR_ZIP_DELETE_FAILURE="Khaladka tirtirka zip"
COM_BANNERS_ERROR_UNIQUE_ALIAS="Banner kale oo ka socda qeybtaan ayaa leh alias isku mid ah (xusuusnow waxaa laga yaabaa inuu yahay shay la tirtiray)."
COM_BANNERS_EXTRA="Macluumaad Dheeraad ah"
COM_BANNERS_FIELD_ALT_LABEL="Qoraalka Beddelka ah"
COM_BANNERS_FIELD_BANNEROWNPREFIX_LABEL="Isticmaal Horey Gaarka ah"
COM_BANNERS_FIELD_BASENAME_DESC="Qaabka magac faylka kaas oo yeelan kara<br>__SITE__ magaca goobta<br>__CATID__ Aqoonsiga qeybta<br>__CATNAME__ magaca qeybta<br>__CLIENTID__ Aqoonsiga macmiilka<br>__CLIENTNAME__ magaca macmiilka<br>__TYPE__ nooca<br>__TYPENAME__ magaca nooca<br>__BEGIN__ taariikhda bilaabidda<br>__END__ taariikhda dhammaadka."
COM_BANNERS_FIELD_BASENAME_LABEL="Magaca Faylka"
COM_BANNERS_FIELD_CLICKS_LABEL="Guud ahaan Gujisyada"
COM_BANNERS_FIELD_CLICKURL_LABEL="URL-ka Gujiska"
COM_BANNERS_FIELD_CLIENT_LABEL="Macmiil"
COM_BANNERS_FIELD_CLIENT_METAKEYWORDPREFIX_DESC="Marka la isu dhigayo erayada muhiimka ah, kaliya raadi erayada muhiimka ah ee leh hormoodkan (waxay hagaajisaa waxqabadka)."
COM_BANNERS_FIELD_CLIENT_METAKEYWORDPREFIX_LABEL="Hormood Erayga Muhiimka ah"
COM_BANNERS_FIELD_CLIENTOWNPREFIX_LABEL="Isticmaal Hormoodka Gaar ah"
COM_BANNERS_FIELD_COMPRESSED_LABEL="La-Xoqay"
COM_BANNERS_FIELD_CONTACT_LABEL="Magaca Xiriirka"
COM_BANNERS_FIELD_CREATED_BY_ALIAS_LABEL="Waxa Abuuray Magac Kale"
COM_BANNERS_FIELD_CREATED_BY_LABEL="Waxaa Abuuray"
COM_BANNERS_FIELD_CREATED_LABEL="Taariikhda La Abuuray"
COM_BANNERS_FIELD_CUSTOMCODE_LABEL="Code Gaar ah"
COM_BANNERS_FIELD_EMAIL_LABEL="E-mailka Xiriirka"
COM_BANNERS_FIELD_EXTRAINFO_LABEL="Macluumaad Dheeraad ah"
COM_BANNERS_FIELD_HEIGHT_LABEL="Dherer"
COM_BANNERS_FIELD_IMAGE_LABEL="Sawir"
COM_BANNERS_FIELD_IMPMADE_LABEL="Guud ahaan Ra'yi Qaadashadaha"
COM_BANNERS_FIELD_IMPTOTAL_LABEL="Ra'yi Qaadashada ugu Badan"
COM_BANNERS_FIELD_METAKEYWORDPREFIX_DESC="Marka la isu dhigayo erayada muhiimka ah, kaliya raadi erayada muhiimka ah ee leh hormoodkan (waxay hagaajisaa waxqabadka)."
COM_BANNERS_FIELD_METAKEYWORDPREFIX_LABEL="Hormood Erayga Muhiimka ah"
COM_BANNERS_FIELD_NAME_LABEL="Magac"
COM_BANNERS_FIELD_PUBLISH_DOWN_LABEL="Dhameystir Daabacaadda"
COM_BANNERS_FIELD_PUBLISH_UP_LABEL="Bilaab Daabacaadda"
COM_BANNERS_FIELD_PURCHASETYPE_LABEL="Nooca Iibsiga"
COM_BANNERS_FIELD_STICKY_DESC="Haddii mid ama in ka badan Xayaysiisyo ka mid ah Qayb ay ku lifaaqan yihiin, waxay mudnaanta siinayaan Xayaysiisyo aan ku lifaaqnayn. Tusaale ahaan, haddii laba Xayaysiisyo ah oo ku jira Qayb ay ku lifaaqan yihiin iyo Xayaysiis saddexaad aynaan lahayn lifaaqan, Xayaysiiska saddexaad ma soo baxayo haddii dejinta moduleku tahay 'Ku lifaaqan, Si tartiib ah'. Kaliya labada Xayaysiis ee ku lifaaqan ayaa soo muuqan doona."
COM_BANNERS_FIELD_STICKY_LABEL="Ku lifaaqan"
COM_BANNERS_FIELD_TRACKCLICK_LABEL="Raac Gujiyaash"
COM_BANNERS_FIELD_TRACKIMPRESSION_LABEL="Raac Taabashooyin"
COM_BANNERS_FIELD_TRACKROBOTSIMPRESSION_LABEL="Ka mid noqo taabashooyinka Mashiinada Raadiyaha"
COM_BANNERS_FIELD_TYPE_LABEL="Nooca"
COM_BANNERS_FIELD_VALUE_CUSTOM="La habeeyay"
COM_BANNERS_FIELD_VALUE_DAILY="Maalmeed"
COM_BANNERS_FIELD_VALUE_IMAGE="Sawir"
COM_BANNERS_FIELD_VALUE_MONTHLY="Bille"
COM_BANNERS_FIELD_VALUE_UNLIMITED="Aan Xadidnayn"
COM_BANNERS_FIELD_VALUE_USECLIENTDEFAULT="- Isticmaal Caadiga Macaamiisha -"
COM_BANNERS_FIELD_VALUE_WEEKLY="Usbuuc"
COM_BANNERS_FIELD_VALUE_YEARLY="Sanadle"
COM_BANNERS_FIELD_VERSION_LABEL="Dib-u-eegis"
COM_BANNERS_FIELD_WIDTH_LABEL="Balaadhka"
COM_BANNERS_FIELDSET_CONFIG_BANNER_OPTIONS_DESC="Dejimahaas waxay khuseeyaan taariikhda nooca loogu talagalay Xayaysiis, Qaybo Xayaysiisyo iyo Macaamiisha Xayaysiisyo."
COM_BANNERS_FIELDSET_CONFIG_BANNER_OPTIONS_LABEL="Taariikhda"
COM_BANNERS_FIELDSET_CONFIG_CLIENT_OPTIONS_DESC="Dejimahaas ayaa khuseeya dhammaan macaamiisha ilaa laga bedelo macmiil gaara."
COM_BANNERS_FIELDSET_CONFIG_CLIENT_OPTIONS_LABEL="Macmiil"
COM_BANNERS_GROUP_LABEL_BANNER_DETAILS="Faahfaahinta Xayaysiis"
COM_BANNERS_GROUP_LABEL_PUBLISHING_DETAILS="Xulashada Daabacaadda"
COM_BANNERS_HEADING_ACTIVE="Furan"
COM_BANNERS_HEADING_BANNERS="Xayaysiisyo"
COM_BANNERS_HEADING_BANNERS_ASC="Boorridooyinka koraya"
COM_BANNERS_HEADING_BANNERS_DESC="Boorridooyinka hoos dhacaya"
COM_BANNERS_HEADING_CLICKS="Gujiya"
COM_BANNERS_HEADING_CLICKS_ASC="Gujiya koraya"
COM_BANNERS_HEADING_CLICKS_DESC="Gujiya hoos dhacaya"
COM_BANNERS_HEADING_CLIENT="Macmiil"
COM_BANNERS_HEADING_CLIENT_ASC="Macmiil koraya"
COM_BANNERS_HEADING_CLIENT_DESC="Macmiil hoos dhacaya"
COM_BANNERS_HEADING_CONTACT="La xiriir"
COM_BANNERS_HEADING_CONTACT_ASC="La xiriir koraya"
COM_BANNERS_HEADING_CONTACT_DESC="La xiriir hoos dhacaya"
COM_BANNERS_HEADING_COUNT="Tirada"
COM_BANNERS_HEADING_COUNT_ASC="Tirada koraya"
COM_BANNERS_HEADING_COUNT_DESC="Tirada hoos dhacaya"
COM_BANNERS_HEADING_IMPRESSIONS="Aragtida"
COM_BANNERS_HEADING_IMPRESSIONS_ASC="Aragtida koraya"
COM_BANNERS_HEADING_IMPRESSIONS_DESC="Aragtida hoos dhacaya"
COM_BANNERS_HEADING_NAME="Magaca"
COM_BANNERS_HEADING_PURCHASETYPE="Nooca iibka"
COM_BANNERS_HEADING_PURCHASETYPE_ASC="Nooca iibka koraya"
COM_BANNERS_HEADING_PURCHASETYPE_DESC="Nooca iibka hoos dhacaya"
COM_BANNERS_HEADING_STICKY="La dhajiyay"
COM_BANNERS_HEADING_STICKY_ASC="La dhajiyay koraya"
COM_BANNERS_HEADING_STICKY_DESC="La dhajiyay hoos dhacaya"
COM_BANNERS_HEADING_TYPE="Nooca"
COM_BANNERS_HEADING_TYPE_ASC="Nooca kor u kacaya"
COM_BANNERS_HEADING_TYPE_DESC="Nooca hoos u dhacaya"
COM_BANNERS_IMPRESSION="Arag"
COM_BANNERS_IMPRESSIONS="%1$s ee %2$s"
COM_BANNERS_MANAGER_BANNER_EDIT="Astaamaha: Wax ka beddel"
COM_BANNERS_MANAGER_BANNER_NEW="Astaamaha: Cusub"
COM_BANNERS_MANAGER_BANNERS="Astaamaha"
COM_BANNERS_MANAGER_CLIENT_EDIT="Astaamaha: Wax ka beddel Macaamiisha"
COM_BANNERS_MANAGER_CLIENT_NEW="Astaamaha: Macaamiil Cusub"
COM_BANNERS_MANAGER_CLIENTS="Astaamaha: Macaamiisha"
COM_BANNERS_MANAGER_TRACKS="Astaamaha: Raac"
COM_BANNERS_N_BANNERS_STUCK="%d astaamo la xidhay."
COM_BANNERS_N_BANNERS_STUCK_1="Astaanta la xidhay."
COM_BANNERS_N_BANNERS_UNSTUCK="%d astaamo la furay."
COM_BANNERS_N_BANNERS_UNSTUCK_1="Astaanta la furay."
COM_BANNERS_N_QUICKICON="Astaamaha"
COM_BANNERS_N_QUICKICON_1="Astaanta"
COM_BANNERS_N_QUICKICON_SRONLY="Astaamaha: %d astaamo ayaa la daabacay."
COM_BANNERS_N_QUICKICON_SRONLY_1="Astaamaha: Hal astaanta ayaa la daabacay."
COM_BANNERS_NEW_BANNER="Astaanta Cusub"
COM_BANNERS_NEW_CLIENT="Macaamiil Cusub"
COM_BANNERS_NO_BANNERS_SELECTED="Astaamo la doortay ma jiro."
COM_BANNERS_NO_CLIENT="- Macaamiil ma leh -"
COM_BANNERS_NOCATEGORYNAME="Qayb la'aan"
COM_BANNERS_NOCLIENTNAME="Macaamiil la'aan"
COM_BANNERS_PROVIDE_VALID_CONTACT="Fadlan bixiya magac xiriir ansax ah oo aan madhanayn"
COM_BANNERS_SEARCH_IN_TITLE="Raadi cinwaanka"
COM_BANNERS_SELECT_CLIENT="- Xulo Macaamil -"
COM_BANNERS_SELECT_TYPE="- Xulo Nooca -"
COM_BANNERS_SUBMENU_BANNERS="Bannaanado"
COM_BANNERS_SUBMENU_CATEGORIES="Qaybaha"
COM_BANNERS_SUBMENU_CLIENTS="Macaamiisha"
COM_BANNERS_SUBMENU_TRACKS="Jidad"
COM_BANNERS_TRACKS_DELETE="Tirtir Jidadka"
COM_BANNERS_TRACKS_DOWNLOAD="Soo deji jidadka"
COM_BANNERS_TRACKS_EMPTYSTATE_CONTENT="Halkan waxaad ka daawan kartaa oo dhoofin kartaa macluumaadka raadraaca ee kaleetaada haddii raadraac loo oggolaaday kaleetadaas."
COM_BANNERS_TRACKS_EMPTYSTATE_TITLE="Jidad wali ma jiraan."
COM_BANNERS_TRACKS_EXPORT="Dhoofin"
COM_BANNERS_TRACKS_FILTER_SEARCH_DESC="Raadi magaca jidka iyo magaca macmiilka jidka."
COM_BANNERS_TRACKS_FILTER_SEARCH_LABEL="Raadi Jidadka"
COM_BANNERS_TRACKS_N_ITEMS_DELETED="%d jidad la tirtiray."
COM_BANNERS_TRACKS_N_ITEMS_DELETED_1="Jid la tirtiray."
COM_BANNERS_TRACKS_NO_ITEMS_DELETED="Jidad tirtire oo ma jiro."
COM_BANNERS_TRACKS_TABLE_CAPTION="Jidad"
COM_BANNERS_TYPE1="Aragtida"
COM_BANNERS_TYPE2="Guji"
COM_BANNERS_UNLIMITED="Aan xad lahayn"
COM_BANNERS_WARNING_PROVIDE_VALID_NAME="Fadlan bixiya magac ansax ah oo aan madhanayn"
COM_BANNERS_XML_DESCRIPTION="Qaybtan waxay maamushaa bannaanadaha iyo macaamiisha bannaanadaha."

JLIB_RULES_SETTING_NOTES_COM_BANNERS="Isbeddelladu waxay khuseeyaan qaybtaan oo keliya.<br><em><strong>Dhaxal</strong></em> - goobaha Guud ama nidaamka heerka sare ayaa la dalbaday.<br><em><strong>La diiday</strong></em> had iyo jeer wuu guuleystaa - waxa kasta oo ku jira Heerka Guud ama heerka sare oo khuseeya dhammaan walxaha ubadka.<br><em><strong>La oggol yahay</strong></em> wuxuu suurtagal ka dhigi doonaa tallaabada qaybtaan ilaa si kale loogu dhaafo nidaamka Heerka Guud."

