; Joomla! Project
; (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_SCHEDULER="Hawlaha la Qorsheeyay"
COM_SCHEDULER_CLEAR_FAIL="Waa ku guuldareystay in la tirtiro taariikhda fulinta."
COM_SCHEDULER_CONFIGURATION="Hawlaha la Qorsheeyay ee Dhaqangelinta"
COM_SCHEDULER_CONFIG_FIELDSET_LAZY_SCHEDULER_DESC="Deji sida booqashooyinka goobtu u kiciyaan Hawlaha Qorsheysan."
COM_SCHEDULER_CONFIG_FIELDSET_LAZY_SCHEDULER_LABEL="Qorsheeye Qaabay"
COM_SCHEDULER_CONFIG_GENERATE_WEBCRON_KEY_DESC="Webcron wuxuu u baahan yahay furaha ilaalinta kahor inta uusan shaqeyn. Kaydinta qaabeyntan ayaa si toos ah u abuuri doonta furaha."
COM_SCHEDULER_CONFIG_GLOBAL_WEBCRON_KEY_LABEL="Furaha Guud"
COM_SCHEDULER_CONFIG_GLOBAL_WEBCRON_LINK_DESC="Marka sicirka la codsado, iskuxirka salduhu wuxuu kaliya qaban doonaa hawlaha la qorsheeyay. Si aad u fuliso hawl gaar ah, isticmaal aqoonsiga hawsha sidii qodob baaritaan ku lifaaqan URL: <code>BASE_URL&id=&lt;taskId&gt;</code>"
COM_SCHEDULER_CONFIG_GLOBAL_WEBCRON_LINK_LABEL="Xiriirka Webcron (Salka)"
COM_SCHEDULER_CONFIG_HASH_PROTECTION_DESC="Haddii la hawlgaliyo, hawlaha waxaa kaliya la kicin doonaa marka URL-yada ay leeyihiin hashka qorsheeyaha sidii qodob."
COM_SCHEDULER_CONFIG_LAZY_SCHEDULER_ENABLED_DESC="Haddii la naafo yahay, hawlaha la qorsheeyay kuma kici doonaan booqdayaasha goobta.<br>Waa la doorbidi doonaa in la naafo ahaado Qorsheeye Qaabay, haddii la kiciyay iyadoo lagu isticmaalayo cron asalka ah."
COM_SCHEDULER_CONFIG_LAZY_SCHEDULER_ENABLED_LABEL="Qorsheeye Qaabay"
COM_SCHEDULER_CONFIG_LAZY_SCHEDULER_INTERVAL_DESC="Fasaxa u dhexeeya codsiyada kicinta qorsheeyaha ee ka yimaada macaamilka."
COM_SCHEDULER_CONFIG_LAZY_SCHEDULER_INTERVAL_LABEL="Fasaxa Codsiga (ilbiriqsi)"
COM_SCHEDULER_CONFIG_RESET_WEBCRON_KEY_LABEL="Warcelin Furaha Gelitaanka"
COM_SCHEDULER_CONFIG_TASKS_FIELDSET_LABEL="Qaabeey Hawlaha"
COM_SCHEDULER_CONFIG_TASK_TIMEOUT_LABEL="Kharashka Waqtiga Hawsha (ilbiriqsi)"
COM_SCHEDULER_CONFIG_WEBCRON_DESC="Kicina oo maamul hawl-fulinta adeega dibadda."
COM_SCHEDULER_CONFIG_WEBCRON_ENABLED_LABEL="Web Cron"
COM_SCHEDULER_CONFIG_WEBCRON_LABEL="Web Cron"
COM_SCHEDULER_CONFIG_WEBCRON_LINK_COPY_DESC="Nuqul ka samee xiriirka makatoore."
COM_SCHEDULER_CONFIG_WEBCRON_LINK_COPY_FAIL="Lama nuqulan karin xiriirka."
COM_SCHEDULER_CONFIG_WEBCRON_LINK_COPY_SUCCESS="Xiriir nuqul ah."
COM_SCHEDULER_DESCRIPTION_TASK_PRIORITY="Hawlaha mudnaanta sare leh waxay hor istaagi karaan hawlaha mudnaanta hoose."
COM_SCHEDULER_DURATION_ASC="Muddo sii kordhaya"
COM_SCHEDULER_DURATION_DESC="Mudada hoos u socda"
COM_SCHEDULER_EDIT_TASK="Wax ka beddel Hawsha"
COM_SCHEDULER_EMPTYSTATE_BUTTON_ADD="Kudar Hawshaada ugu Horeysa"
COM_SCHEDULER_EMPTYSTATE_CONTENT="Howlaha waa ficillo ka dhaca boggaaga internetka oo lagu qorsheeyey inay dhacaan waqtiyo cayiman."
COM_SCHEDULER_EMPTYSTATE_TITLE="Wax Hawlo ah wali laguma abuuran."
COM_SCHEDULER_ERROR_FORBIDDEN_JUMP_TO_ADD_VIEW="Waa inaad marka hore doorataa Nooca Hawsha."
COM_SCHEDULER_ERROR_INVALID_TASK_TYPE="Nooca Hawsha waa khaldan yahay"
COM_SCHEDULER_EXECUTION_CRON_EXPRESSION="Hadalku Cron (Horudhac)"
COM_SCHEDULER_EXECUTION_HISTORY="Taariikhda Hawlgalka"
COM_SCHEDULER_EXECUTION_INTERVAL_DAYS="Kala Xiriir, Maalmaha"
COM_SCHEDULER_EXECUTION_INTERVAL_HOURS="Kala Xiriir, Saacadaha"
COM_SCHEDULER_EXECUTION_INTERVAL_MINUTES="Kala Xiriir, Daqiiqadaha"
COM_SCHEDULER_EXECUTION_INTERVAL_MONTHS="Kala Xiriir, Bilaha"
COM_SCHEDULER_EXITCODE="Kodhka Ka bixida"
COM_SCHEDULER_EXIT_CODE_ASC="Kodhka Ka bixida oo kor u socda"
COM_SCHEDULER_EXIT_CODE_DESC="Kodhka Ka bixida hoos u socda"
COM_SCHEDULER_EXIT_CODE_EXECUTED="La Fulin"
COM_SCHEDULER_EXIT_CODE_FAILED="Guuldaro"
COM_SCHEDULER_EXIT_CODE_WILLRESUME="Hawlgalka La sii wadi doonaa"
COM_SCHEDULER_FIELDSET_BASIC="Goobo Asaasiga ah"
COM_SCHEDULER_FIELDSET_CRON_OPTIONS="U Qabasho Cron"
COM_SCHEDULER_FIELDSET_EXEC_HIST="Taariikhda Hawlgalka"
COM_SCHEDULER_FIELDSET_LOGGING="Diiwaangelinta"
COM_SCHEDULER_FIELDSET_NOTIFICATIONS="Ogeysiisyada"
COM_SCHEDULER_FIELDSET_PRIORITY="Mudnaanta"
COM_SCHEDULER_FIELDSET_TASK_PARAMS="Qiyaasta Waafiga"
COM_SCHEDULER_FIELD_HINT_LOG_FILE_AUTO="waxay asal ahaan tahay 'task_<taskId>.log.php'"
COM_SCHEDULER_FIELD_LABEL_EXEC_RULE="Xeerka Fulinta"
COM_SCHEDULER_FIELD_LABEL_INDIVIDUAL_LOG="Diiwaangelinta Shaqsiyeed"
COM_SCHEDULER_FIELD_LABEL_INTERVAL_DAYS="Inta Jeer Ee Maalmaha"
COM_SCHEDULER_FIELD_LABEL_INTERVAL_HOURS="Inta Jeer Saacadaha"
COM_SCHEDULER_FIELD_LABEL_INTERVAL_MINUTES="Inta Jeer Daqiiqo"
COM_SCHEDULER_FIELD_LABEL_INTERVAL_MONTHS="Inta Jeer Bishii"
COM_SCHEDULER_FIELD_LABEL_LOG_FILE="Magaca Faylka Diiwaanka"
COM_SCHEDULER_FIELD_LABEL_SHOW_ORPHANED="Tus kuwa waayey"
COM_SCHEDULER_FIELD_OPTION_INTERVAL_MATCH_DAYS_M="Maalmaha Bisha"
COM_SCHEDULER_FIELD_OPTION_INTERVAL_MATCH_DAYS_W="Maalmaha Toddobaadka"
COM_SCHEDULER_FIELD_OPTION_INTERVAL_MATCH_HOURS="Saacadaha"
COM_SCHEDULER_FIELD_OPTION_INTERVAL_MATCH_MINUTES="Daqiiqadaha"
COM_SCHEDULER_FIELD_OPTION_INTERVAL_MATCH_MONTHS="Bilaha"
COM_SCHEDULER_FIELD_TASK_TYPE="Nooca Aqoonsiga"
COM_SCHEDULER_FILTER_SEARCH_DESC="Raadi cinwaanka iyo qoraalka. Hore u mari ID: si aad ugu raadsato aqoonsiga waafinta."
COM_SCHEDULER_FILTER_SEARCH_HISTORY_DESC="Raadi cinwaanka waafinta. Hore u mari ID: si aad ugu raadsato aqoonsiga taariikhda."
COM_SCHEDULER_FILTER_SEARCH_LABEL="Raadi Waafiyadaha"
COM_SCHEDULER_FILTER_SELECT_OPTION_EXITCODE="- Koodhka Bixitaanka -"
COM_SCHEDULER_FORM_TITLE_EDIT="Wax ka Beddel Waafinta"
COM_SCHEDULER_FORM_TITLE_NEW="Waafi Cusub"
COM_SCHEDULER_HEADING_TASK_TYPE="- Nooca Waafinta -"
COM_SCHEDULER_LABEL_DURATION="Mudada"
COM_SCHEDULER_LABEL_EXEC_DAY="Maalinta Fulinta"
COM_SCHEDULER_LABEL_EXEC_INTERVAL="Xilliga Fulinta"
COM_SCHEDULER_LABEL_EXEC_TIME="Waqtiga Fulinta (UTC)"
COM_SCHEDULER_LABEL_EXIT_CODE="Koodhka Soo Baxay Ugu Dambeeyay"
COM_SCHEDULER_LABEL_LAST_EXEC="Fulintii Ugu Danbeysay"
COM_SCHEDULER_LABEL_NEXT_EXEC="Fulinta Xigta"
COM_SCHEDULER_LABEL_NOTES="Ogeysiis"
COM_SCHEDULER_LABEL_TASK_PRIORITY="Ahaamiyad"
COM_SCHEDULER_LABEL_TASK_PRIORITY_HIGH="Sare"
COM_SCHEDULER_LABEL_TASK_PRIORITY_LOW="Hoose"
COM_SCHEDULER_LABEL_TASK_PRIORITY_NORMAL="Caadi"
COM_SCHEDULER_LABEL_TIMES_EXEC="Tirinta Fulinta"
COM_SCHEDULER_LABEL_TIMES_FAIL="Tirinta Fashilka"
COM_SCHEDULER_LAST_RUN_ASC="Socodkii u dambeeyay oo kordhinaya"
COM_SCHEDULER_LAST_RUN_DATE="Taariikhda Socodkii u Dambeeyay"
COM_SCHEDULER_LAST_RUN_DESC="Socodkii u dambeeyay oo hoos udhacaya"
COM_SCHEDULER_LOGS_CLEAR="Dhammaan taariikhda socodka ayaa la tirtiray."
COM_SCHEDULER_LOGS_N_ITEMS_DELETED="%d diiwaangalinta la tirtiray."
COM_SCHEDULER_LOGS_N_ITEMS_DELETED_1="Diiwaanka la tirtiray."
COM_SCHEDULER_MANAGER_TASKS="Hawlah Cooska u qabanaya"
COM_SCHEDULER_MANAGER_TASK_EDIT="Tafatir Hawl"
COM_SCHEDULER_MANAGER_TASK_NEW="Hawl Cusub"
COM_SCHEDULER_MANAGER_TOOLTIP_NOT_AUTHORIZED="Aan la oggolaan"
COM_SCHEDULER_MANAGER_TOOLTIP_TASK_FAILING="Hawl ku fashilantay. Koodhka Soo Baxay: %1$d"
COM_SCHEDULER_MANAGER_TOOLTIP_TASK_TRASHED="Hawsha ayaa lagu shubay qashinka"
COM_SCHEDULER_MSG_DUETASKS="Waxaa jira ugu yaraan hal hawl oo jirta oo horey loo fulin lahaa. Fadlan hubi in ugu yaraan mid ah jadwaleyayaasha cron waa la furay oo shaqaynaya."
COM_SCHEDULER_MSG_MANAGE_NO_TASK_PLUGINS="Ma jiraan noocyo hawlo oo la mid ah baaritaankaaga."
COM_SCHEDULER_NEW_TASK="Hawl Cusub"
COM_SCHEDULER_NEXT_RUN_ASC="Orodka Xiga kordhinaya"
COM_SCHEDULER_NEXT_RUN_DATE="Taariikhda Orodka Xiga"
COM_SCHEDULER_NEXT_RUN_DESC="Orodka Xiga hoos u dhigaya"
COM_SCHEDULER_NEXT_RUN_MANUAL="Gacanta"
COM_SCHEDULER_N_ITEMS_CHECKED_IN_1="Hawl la hubiyay."
COM_SCHEDULER_N_ITEMS_CHECKED_IN_MORE="%d hawlo la hubiyay."
COM_SCHEDULER_N_ITEMS_DELETED="%d hawlo la tirtiray."
COM_SCHEDULER_N_ITEMS_DELETED_1="Hawl la tirtiray."
COM_SCHEDULER_N_ITEMS_FAILED_UNLOCKING="Ku guuldaraystay in la furo %d hawlo."
COM_SCHEDULER_N_ITEMS_FAILED_UNLOCKING_1="Ku guuldaraystay in la furo hal hawl."
COM_SCHEDULER_N_ITEMS_PUBLISHED="%d hawlo la hawlgeliyay."
COM_SCHEDULER_N_ITEMS_PUBLISHED_1="Hawl la hawlgeliyay."
COM_SCHEDULER_N_ITEMS_TRASHED="%d hawlo la qashinka lagu daray."
COM_SCHEDULER_N_ITEMS_TRASHED_1="Hawl la qashinka lagu daray."
COM_SCHEDULER_N_ITEMS_UNPUBLISHED="%d hawlo la joojiyay."
COM_SCHEDULER_N_ITEMS_UNPUBLISHED_1="Hawl la joojiyay."
COM_SCHEDULER_N_ITEMS_UNLOCKED="%d hawlo la furay."
COM_SCHEDULER_N_ITEMS_UNLOCKED_1="Hawl la furay."
COM_SCHEDULER_OPTION_EXECUTION_MANUAL_LABEL="Hawlgal Gacanta"
COM_SCHEDULER_OPTION_ORPHANED_HIDE="Qari Caanaha"
COM_SCHEDULER_OPTION_ORPHANED_ONLY="Caanaha Kaliya"
COM_SCHEDULER_OPTION_ORPHANED_SHOW="Muuji Caanaha"
COM_SCHEDULER_PERMISSION_TESTRUN="Tijaabi hawl"
COM_SCHEDULER_ROUTINE_LOG_PREFIX="Hawl> "
COM_SCHEDULER_RUNNING_SINCE="Wuxuu socdey tan iyo %s"
COM_SCHEDULER_SCHEDULER="Jadwal"
COM_SCHEDULER_SCHEDULER_TASK_COMPLETE="Si guul leh ayuu u dhammaystiray hawl#%1$02d %2$.2f (wadar %3$.2f) ilbidhiqsi gudahood."
COM_SCHEDULER_SCHEDULER_TASK_LOCKED="hawl#%1$02d waa la xannibay."
COM_SCHEDULER_SCHEDULER_TASK_ROUTINE_NA="Hawl#%1$02d ma laha habka isku xidhka ee si ku habboon. Waxa laga yaabaa in lagu naafoobay ama la tiray. Ka bood hawlgalkii."
COM_SCHEDULER_SCHEDULER_TASK_START="Wuxuu bilaabay hawl#%1$02d '%2$s'."
COM_SCHEDULER_SCHEDULER_TASK_UNKNOWN_EXIT="Hawl#%1$02d wuxuu ka baxay cod %4$d %2$.2f (wadar %3$.2f) ilbidhiqsi gudahood."
COM_SCHEDULER_SCHEDULER_TASK_UNLOCKED="Hawl#%1$02d waa la furay."
COM_SCHEDULER_SCHEDULER_TASK_WILL_RESUME="Hawl#%1$02d waxay u baahan tahay inay samayso shaqo dheeraad ah."
COM_SCHEDULER_SELECT_INTERVAL_MINUTES="- Dooro fogaanta Daqiiqadaha -"
COM_SCHEDULER_SELECT_TASK_TYPE="Dooro hawsha, %s"
COM_SCHEDULER_SELECT_TYPE="- Nooca Hawsha -"
COM_SCHEDULER_TABLE_CAPTION="Hawlaha"
COM_SCHEDULER_TASK="Hawl"
COM_SCHEDULER_TASKS_VIEW_DEFAULT_DESC="Jadwal u samee oo Maamul Hawlaha Habraacyada."
COM_SCHEDULER_TASKS_VIEW_DEFAULT_TITLE="Hawlo Jadwalaysan"
COM_SCHEDULER_TASK_EXECUTED="Lafuliyey: %s"
COM_SCHEDULER_TASK_FAILED="Fashilintay: %s"
COM_SCHEDULER_TASK_PARAMS_FIELDSET_LABEL="Xuduudaha Hawsha"
COM_SCHEDULER_TASK_PRIORITY="Mudnaanta Hawsha"
COM_SCHEDULER_TASK_PRIORITY_ASC="Mudnaanta Hawsha kor u kaca"
COM_SCHEDULER_TASK_PRIORITY_DESC="Mudnaanta Hawsha sii dhaqaaqid"
COM_SCHEDULER_TASK_RESUME="Dib u Bilaabmayaa: %s"
COM_SCHEDULER_TASK_ROUTINE_EXCEPTION="Habraacuvu wuxu tuuray qalad: %1$s"
COM_SCHEDULER_TASK_TIMES_ASC="Waqtiyada sii kordhaya"
COM_SCHEDULER_TASK_TIMES_DESC="Waqtiyada sii dhacaaya"
COM_SCHEDULER_TASK_TYPE="Nooca Hawsha"
COM_SCHEDULER_TASK_TYPE_ASC="Nooca Hawsha sii kordhaya"
COM_SCHEDULER_TASK_TYPE_DESC="Nooca Hawsha sii dhacaaya"
COM_SCHEDULER_TEST_RUN="Orod Imtixaan"
COM_SCHEDULER_TEST_RUN_DURATION="Muddada: %s ilbiriqsi"
COM_SCHEDULER_TEST_RUN_OUTPUT="Soo saar:<br>%s"
COM_SCHEDULER_TEST_RUN_STATUS_COMPLETED="Xaaladda: Dhameystiran"
COM_SCHEDULER_TEST_RUN_STATUS_STARTED="Xaaladda: Bilawday"
COM_SCHEDULER_TEST_RUN_STATUS_TERMINATED="Xaaladda: La joojiyay"
COM_SCHEDULER_TEST_RUN_TASK="Hawsha: \"%s\""
COM_SCHEDULER_TEST_RUN_TITLE="Hawsha Imtixaanka (ID: %d)"
COM_SCHEDULER_TEST_TASK="Hawsha Imtixaanka"
COM_SCHEDULER_TOOLBAR_PURGE="Tirtir Taariikhda"
COM_SCHEDULER_TOOLBAR_PURGE_CONFIRM="Ma hubtaa inaad rabto inaad tirtirto Dhammaan Taariikhda Fulinta?"
COM_SCHEDULER_TOOLBAR_UNLOCK="Fur"
COM_SCHEDULER_TYPE_CHOOSE="Dooro nooca Hawsha"
COM_SCHEDULER_WARNING_EXISTING_TASK_TYPE_NOT_FOUND="Hawlaha noocan ah lama heli karin!<br>Waxaa laga yaabaa in plugin-ka bixiyaha laga saaray ama la curyaamiyay."
COM_SCHEDULER_XML_DESCRIPTION="Qayb u ah maamulidda hawlaha jadwalka iyo cronjobs-ka (haddii uu taageerayo server-ka)."
JLIB_HTML_PUBLISH_ITEM="Shaal hawsha"
JLIB_HTML_UNPUBLISH_ITEM="Curyaami hawsha"

