; Joomla! Project
; (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_GUIDEDTOURS="Wareegyado Hagida"
COM_GUIDEDTOURS_AUTOSTART_DESC="Bilow wareega si toos ah marka isticmaaluhu gaaro macnaha ay tahay inuu wareeggu soo bandhigo."
COM_GUIDEDTOURS_AUTOSTART_LABEL="Bilow Toos ah"
COM_GUIDEDTOURS_CONFIG_DELAYED_TIME_DESCRIPTION="Waqtiga (daqiiqado) wareeggu dib loo dhigayo ka dib marka isticmaaluhu joojiyo iyo ilaa uu dib u soo muuqdo (kaliya marka wareeggu lagu dejiyo inuu si toos ah ku bilowdo).<br>Tusaale ahaan, gali 60 saacad, 1440 24 saacadood, ama 10080 usbuuc 1 ah."
COM_GUIDEDTOURS_CONFIG_DELAYED_TIME_LABEL="Dib-u-dhigid Bilow Toos ah (daqiiqadaha)"
COM_GUIDEDTOURS_CONFIG_USER_ALLOWTOURAUTOSTART_DESCRIPTION="Daar ama dami shaqada bilowga tooska ah ee wareegyado."
COM_GUIDEDTOURS_CONFIG_USER_ALLOWTOURAUTOSTART_LABEL="U Ogolow Wareegyado Bilowga Toos ah"
COM_GUIDEDTOURS_CONFIGURATION="Wareegyado Hagida: Xulashooyinka"
COM_GUIDEDTOURS_DESCRIPTION="Sharaxaad"
COM_GUIDEDTOURS_DESCRIPTION_TRANSLATION="Sharaxaad (%s)"
COM_GUIDEDTOURS_EDIT_TOUR="Tafatir Wareeg"
COM_GUIDEDTOURS_ERROR_NO_GUIDEDTOURS_SELECTED="Wax wareeg ah lama soo xulan."
COM_GUIDEDTOURS_EXTENSIONS_DESC="Xaddid wareeggu inuu soo muuqdo kaliya marka qaybta la xusho firfircoon tahay."
COM_GUIDEDTOURS_EXTENSIONS_LABEL="Xulashada Qaybta"
COM_GUIDEDTOURS_FIELD_NOTE_LABEL="Ogeysiis"
COM_GUIDEDTOURS_FIELD_VALUE_INTERACTIVESTEP_TYPE_BUTTON="Batoon"
COM_GUIDEDTOURS_FIELD_VALUE_INTERACTIVESTEP_TYPE_CHECKBOX_RADIO_FIELD="Sanduuq/batton"
COM_GUIDEDTOURS_FIELD_VALUE_INTERACTIVESTEP_TYPE_FORM_SUBMIT="Foom Gudbin"
COM_GUIDEDTOURS_FIELD_VALUE_INTERACTIVESTEP_TYPE_OTHER="Mid Kale"
COM_GUIDEDTOURS_FIELD_VALUE_INTERACTIVESTEP_TYPE_SELECT_LIST="Liiska Xulashada"
COM_GUIDEDTOURS_FIELD_VALUE_INTERACTIVESTEP_TYPE_TEXT_FIELD="Goob Qoraal"
COM_GUIDEDTOURS_FIELD_VALUE_STEP_TYPE_INTERACTIVE="Is-dhexgal"
COM_GUIDEDTOURS_FIELD_VALUE_STEP_TYPE_NEXT="Xiga"
COM_GUIDEDTOURS_FIELD_VALUE_STEP_TYPE_REDIRECT="Dib U Ridayn"
COM_GUIDEDTOURS_FILTER_SEARCH_DESC="Raadi ciwaanka iyo ogeysiiska. Hore ugu dar ID: si loo raadiyo ID-ga wareega ama DESCRIPTION: si loogu raadiyo sharaxaad."
COM_GUIDEDTOURS_FILTER_SEARCH_LABEL="Raadi Dalxiis"
COM_GUIDEDTOURS_GUIDEDTOURS_TABLE_CAPTION="Dalxiisyo"
COM_GUIDEDTOURS_MANAGER_STEP_EDIT="Dalxiisyo: Tallaabo Tafatir"
COM_GUIDEDTOURS_MANAGER_STEP_NEW="Dalxiisyo: Tallaabo Cusub"
COM_GUIDEDTOURS_MANAGER_TOUR_EDIT="Dalxiisyo: Dalxiis Tafatir"
COM_GUIDEDTOURS_MANAGER_TOUR_NEW="Dalxiisyo: Dalxiis Cusub"
COM_GUIDEDTOURS_N_ITEMS_ARCHIVED_1="Shay la kaydiyay."
COM_GUIDEDTOURS_N_ITEMS_ARCHIVED="%d shay la kaydiyay."
COM_GUIDEDTOURS_N_ITEMS_CHECKED_IN_1="Shay la hubiyey."
COM_GUIDEDTOURS_N_ITEMS_CHECKED_IN_MORE="%d shay la hubiyey."
COM_GUIDEDTOURS_N_ITEMS_DELETED_1="Shay la tirtiray."
COM_GUIDEDTOURS_N_ITEMS_DELETED="%d shay la tirtiray."
COM_GUIDEDTOURS_N_ITEMS_PUBLISHED_1="Shay la daabacay."
COM_GUIDEDTOURS_N_ITEMS_PUBLISHED="%d shay la daabacay."
COM_GUIDEDTOURS_N_ITEMS_TRASHED_1="Shay la qashqasha."
COM_GUIDEDTOURS_N_ITEMS_TRASHED="%d shay la qashqasha."
COM_GUIDEDTOURS_N_ITEMS_UNPUBLISHED_1="Shay la daabicin."
COM_GUIDEDTOURS_N_ITEMS_UNPUBLISHED="%d shay la daabicin."
COM_GUIDEDTOURS_NEW_TOUR="Dalxiis Cusub"
COM_GUIDEDTOURS_ORDER_TYPE_ASC="Nooca koraya"
COM_GUIDEDTOURS_ORDER_TYPE_DESC="Nooca soo dhacaya"
COM_GUIDEDTOURS_PLUGIN_DISABLED="Plugin-ka Nidaamka Dalxiisyo Hagitaan ah ayaa naafo ah. Habboon Dalxiisyo la hagayo lama soo bandhigi doono haddii aan la furin."
COM_GUIDEDTOURS_STEP_DESCRIPTION_TRANSLATION="Sharaxaadda (%s)"
COM_GUIDEDTOURS_STEP_EDIT_STEP="Tafatiro Tallaabo"
COM_GUIDEDTOURS_STEP_FILTER_SEARCH_DESC="Raadi cinwaanka iyo qoraal. Waxaan ID: ku daray si aad u baarto ID tallaabo ama DESCRIPTION: si aad u baarto sharaxaadda."
COM_GUIDEDTOURS_STEP_FILTER_SEARCH_LABEL="Raadi Tallaabooyinka"
COM_GUIDEDTOURS_STEP_NEW_STEP="Tallaabo Cusub"
COM_GUIDEDTOURS_STEP_POSITION_DESC="Xulo booska furaha tallaabada, marka loo eego qaybta uu tilmaamayo."
COM_GUIDEDTOURS_STEP_POSITION_LABEL="Boos"
COM_GUIDEDTOURS_STEP_TARGETNOTE_MESSAGE="Marka tallaabo loo aqoonsado inuu yahay mid is-dhexgal ah, ikhtiyaarrada gaarka ah ee is-dhexgalka waxay qaadi karaan waxqabadyo gaar ah oo dheeri ah inta lagu jiro is-dhexgalka isticmaaleha."
COM_GUIDEDTOURS_STEP_TARGETVALUES_HEADING="Ikhtiyaarrada Qiimaha Bartilmaameedka"
COM_GUIDEDTOURS_STEP_TITLE="Cinwaanka"
COM_GUIDEDTOURS_STEP_TITLE_TRANSLATION="Cinwaanka (%s)"
COM_GUIDEDTOURS_STEP_TARGET_DESC="Qaybta bartilmaameedka ee tallaabada lagu lifaaqi doono. Ikhtiyaarrada: .classname, #id, ama wax kastoo raacaya qaanuunka CSS (hubi inay tahay qayb lagu fiiro karo haddii tallaabadu tahay mid is-dhexgal ah), ama u dhaaf maran tallaabo dhexe."
COM_GUIDEDTOURS_STEP_TARGET_LABEL="Bartilmaameedka"
COM_GUIDEDTOURS_STEP_TYPE="Nooca"
COM_GUIDEDTOURS_STEP_TYPE_LABEL="Nooca"
COM_GUIDEDTOURS_STEP_TYPE_DESC="Xulo <em>Next</em> ee socodka tallaabooyinka, <em>Redirect</em> si loo gudbiyo bog kale, ama <em>Interactive</em> si loo oggolaado is-dhexgalka isticmaalaha."
COM_GUIDEDTOURS_STEPS="Tallaabooyinka"
COM_GUIDEDTOURS_STEPS_EMPTYSTATE_CONTENT="Socod-baridku wuxuu shaqeyn karaa oo keliya haddii tallaabooyin la abuuro."
COM_GUIDEDTOURS_STEPS_EMPTYSTATE_TITLE="Tallaabooyin socod-baridkan ayaa wali lama abuurin."
COM_GUIDEDTOURS_STEPS_EMPTYSTATE_BUTTON_ADD="Ku dar tallaabadaada ugu horreysa"
COM_GUIDEDTOURS_STEPS_LIST="Socod-barid Hagitaan: %s"
COM_GUIDEDTOURS_STEPS_TABLE_CAPTION="Tallaabooyinka"
COM_GUIDEDTOURS_STEPS_UNKNOWN_TOUR="Aqoonsi Socod-barid Maqan"
COM_GUIDEDTOURS_TITLE="Cinwaanka"
COM_GUIDEDTOURS_TITLE_TRANSLATION="Cinwaanka (%s)"
COM_GUIDEDTOURS_TOUR_UID_LABEL="Aqoonsiga Socod-baridka"
COM_GUIDEDTOURS_TOUR_UID_DESC="Aqoonsiga Socod-baridku wuxuu ubaahanyahay inuu gaar ahaado.<br>Waxaa lagu talinayaa qaab sida magac-qore-socod-barid, magac-shirkadeed-socod-barid, ama domain-shabakad-socod-barid.<br>Haddii aqoonsi aan la bixin waxaa lagu xisaabin doona qiimo kuu gaar ah."
COM_GUIDEDTOURS_TOUR_UID_HINT="Aqoonsi gaar ah tusaale ahaan qoraa-shabakada-domain-socod-barid"
COM_GUIDEDTOURS_TOURS_DUPLICATED="%d safar ayaa la nuqul yeelay."
COM_GUIDEDTOURS_TOURS_DUPLICATED_1="Safarka waa la nuqulay."
COM_GUIDEDTOURS_TOURS_LIST="Safarrada Hagaha"
COM_GUIDEDTOURS_TOURS_LIST_EMPTYSTATE_BUTTON_ADD="Ku dar safarkaaga ugu horreeya"
COM_GUIDEDTOURS_TOURS_LIST_EMPTYSTATE_CONTENT="Abuur safar si uu u noqdo waxtar leh."
COM_GUIDEDTOURS_TOURS_LIST_EMPTYSTATE_TITLE="Safar lama abuurin weli."
COM_GUIDEDTOURS_TYPE_INPUT_REQUIRED_DESC="Habee haddii isticmaaluhu uu u baahan yahay inuu bixiyo qiime, dhaqaajiyo badhan raadiye ama sax badhan si uu ugu gudbo tallaabada xigta ee safarka."
COM_GUIDEDTOURS_TYPE_INPUT_REQUIRED_LABEL="Loo baahan yahay"
COM_GUIDEDTOURS_TYPE_INPUT_REQUIREDVALUE_DESC="Qiimaha saxda ah ee la galinayo, oo ay ku jiraan xuruufta waaweyn iyo calaamadaha, si loo gudbo tallaabada xigta (haddii bartilmaameedka ay tahay liis alaab, isticmaal qiimaha walxaha dookha ah)."
COM_GUIDEDTOURS_TYPE_INPUT_REQUIREDVALUE_LABEL="Qiimaha Loo Baahan Yahay"
COM_GUIDEDTOURS_TYPE_INTERACTIVE_STEP_DESC="Xulo <em>Gudbinta Foomka</em> si aad foom u gudbiso, <em>Gararaha Qoraalka</em> ee gelitaanka isticmaalaha, <em>Badhamada</em> ee badhamada, <em>Checkbox/Radio</em> ama <em>Liiska Xulashada</em> ee xulashada, ama <em>Kale</em> loogu talagalay is dhexgal kale."
COM_GUIDEDTOURS_TYPE_INTERACTIVE_STEP_LABEL="Nooca isdhexgalka"
COM_GUIDEDTOURS_TYPE_REDIRECT_URL_DESC="Gali URL-ta bogga aad rabto in talabo loo gudbiyo, tusaale maamulka/index.php?option=com_guidedtours&view=tours ee bogga liiska safarada."
COM_GUIDEDTOURS_TYPE_REDIRECT_URL_LABEL="URL-ka xidhiidhsan"
COM_GUIDEDTOURS_URL_LABEL="URL-ka xidhiidhsan"
COM_GUIDEDTOURS_URL_DESC="Geli URL-ta bogga aad rabto in safarka laga bilaabo, tusaale maamulka/index.php?option=com_guidedtours&view=tours ee bogga liiska safarada."
COM_GUIDEDTOURS_USERSTATE_BADTOURID="Safarku wuxuu u baahan yahay inuu leeyahay aqoonsi wanaagsan."
; 'Tour User states' are conditions in which a guided tour user leaves a tour, either by cancelling, completing or skipping a tour.
COM_GUIDEDTOURS_USERSTATE_CONNECTEDONLY="Diiwaangelinta xaalada isticmaalaha ee safarka waxaa heli kara oo kaliya isticmaalayaasha soo saxeexan."
COM_GUIDEDTOURS_USERSTATE_STATENOTSAVED="Xaalada isticmaale lama keydin isticmaalaha %1$s iyo safarka %2$s."
COM_GUIDEDTOURS_USERSTATE_STATESAVED="Xaalada isticmaale waa la keydiyay isticmaalaha %1$s iyo safarka %2$s."
COM_GUIDEDTOURS_USERSTATE_WRONGCONTEXT="Macnaha saxda ee Xaaladda Isticmaalaha Safarka waa qalad."
COM_GUIDEDTOURS_XML_DESCRIPTION="Qeybta maamusha howlaha Hanuuninta Safarada."

