; Joomla! Project
; (C) 2013 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_TAGS="Tags"
COM_TAGS_ALL="Dhammaan"
COM_TAGS_ALL_TAGS_DESCRIPTION_LABEL="Sharraxaadda Cinwaan"
COM_TAGS_ALL_TAGS_MEDIA_LABEL="Faylka Sawirka Cinwaan"
COM_TAGS_ANY="Mid kasta"
COM_TAGS_BASIC_FIELDSET_LABEL="Xulashooyinka"
COM_TAGS_BATCH_OPTIONS="Waxaa lagu farsameynayaa tag-yada la doortay"
COM_TAGS_COMPACT_COLUMNS_LABEL="Tirada Safafka"
COM_TAGS_CONFIG_ALL_TAGS_FIELD_LAYOUT_LABEL="Habaynta Dhammaan Tag-yada Hoos U Qoran"
COM_TAGS_CONFIG_ALL_TAGS_SETTINGS_DESC="Qaababkan waxay khuseeyaan Liiska dhammaan Tag-yada ilaa ay laga badalo badeecadda menu-ga gaarka ah."
COM_TAGS_CONFIG_ALL_TAGS_SETTINGS_LABEL="Liiska Dhammaan Tag-yada"
COM_TAGS_CONFIG_DATA_ENTRY_SETTINGS_DESC="Qaababkan waxay maamulaan sida tag-yadu u galaya."
COM_TAGS_CONFIG_DATA_ENTRY_SETTINGS_LABEL="Gelinta Xogta"
COM_TAGS_CONFIG_INTEGRATION_SETTINGS_DESC="Qaababkan waxay go'aaminayaan sida Qaybta Tag-yadu ula falgelaan fidinta kale."
COM_TAGS_CONFIG_NUMBER_OF_ITEMS="Tirada Shayga Lagu Tago"
COM_TAGS_CONFIG_SELECTION_SETTINGS_DESC="Qaababkan waxay maamulaan shayada la dooranayo liiska la soo xigsaday ee shayada."
COM_TAGS_CONFIG_SELECTION_SETTINGS_LABEL="Doorashada Shayga"
COM_TAGS_CONFIG_SHARED_SETTINGS_DESC="Qaababkan waxay khuseeyaan dhammaan qaababka tagyada ilaa ay laga badalo badeecadda menu-ga gaarka ah."
COM_TAGS_CONFIG_SHARED_SETTINGS_LABEL="Qaab Wadageed"
COM_TAGS_CONFIG_TAG_MIN_LENGTH_LABEL="Dhererka Raadinta ugu Yar"
COM_TAGS_CONFIG_TAG_SETTINGS_DESC="Qaababkan waxay khuseeyaan Liiska Shayada La Tago ama Liis Gaaban oo Shayada La Tago ilaa ay laga badalo badeecadda menu-ga gaarka ah."
COM_TAGS_CONFIG_TAG_SETTINGS_LABEL="Shayada La Tago"
COM_TAGS_CONFIG_TAGGED_ITEMS_FIELD_LAYOUT_LABEL="Qaabeynta Shayada La Tago ee Asalka ah"
COM_TAGS_CONFIGURATION="Tagyada: Xulashooyinka"
COM_TAGS_COUNT_ARCHIVED_ITEMS="Shayada la keydiyay"
COM_TAGS_COUNT_PUBLISHED_ITEMS="Alaabaha la daabacay"
COM_TAGS_COUNT_TAGGED_ITEMS="Qalabka leh calaamadaha"
COM_TAGS_COUNT_TAGGED_ITEMS_ASC="Qalabka leh calaamadaha oo koraya"
COM_TAGS_COUNT_TAGGED_ITEMS_DESC="Qalabka leh calaamadaha oo hoos u dhacaya"
COM_TAGS_COUNT_TRASHED_ITEMS="Alaabaha qashinka la dhigay"
COM_TAGS_COUNT_UNPUBLISHED_ITEMS="Alaabaha aan la daabicin"
COM_TAGS_EMPTYSTATE_BUTTON_ADD="Ku dar calaamaddaada ugu horreysa"
COM_TAGS_EMPTYSTATE_CONTENT="Tags-ka Joomla! waxay bixiyaan hab dabacsan oo lagu abaabulo macluumaadka. Calaamad isku mid ah ayaa lagu dabaqi karaa waxyaalo kala duwan oo noocyo kala duwan ah."
COM_TAGS_EMPTYSTATE_TITLE="Calaamado looma abuurin weli."
COM_TAGS_ERROR_UNIQUE_ALIAS="Calaamad kale ayaa leh sumad isku mid ah."
COM_TAGS_ERROR_UNIQUE_ALIAS_TRASHED="Calaamad qashin dhig ah oo leh calaamad waalid isku mid ah ayaa leh sumad isku mid ah."
COM_TAGS_EXCLUDE="Ka reeb"
COM_TAGS_FIELD_CONTENT_TYPE_LABEL="Noocyada macluumaadka"
COM_TAGS_FIELD_FULL_LABEL="Sawirka buuxa"
COM_TAGS_FIELD_IMAGE_ALT_LABEL="Qoraalka bedelka ah"
COM_TAGS_FIELD_IMAGE_CAPTION_LABEL="Qoraalka hoosta"
COM_TAGS_FIELD_IMAGE_LABEL="Sawir"
COM_TAGS_FIELD_INTRO_LABEL="Sawirka hordhaca"
COM_TAGS_FIELD_LANGUAGE_FILTER_LABEL="Shaandheynta luqadda"
COM_TAGS_FIELD_NOTE_LABEL="Qoraal"
COM_TAGS_FIELD_NUMBER_ITEMS_LIST_LABEL="# Qalabka Liiska"
COM_TAGS_FIELD_PARENT_LABEL="Waalid"
COM_TAGS_FIELD_PARENT_TAG_LABEL="Calaamada waalid"
COM_TAGS_FIELD_TAG_BODY_LABEL="Sharaxa"
COM_TAGS_FIELD_TAG_LABEL="Calaamad"
COM_TAGS_FIELD_TAG_LINK_CLASS="Fasalka CSS ee isku xirka sumadda"
COM_TAGS_FIELD_TYPE_LABEL="Xulo Nooca Mawduuca"
COM_TAGS_FIELD_VERSION_LABEL="Dib-u-eegid"
COM_TAGS_FIELDSET_DETAILS="Faahfaahinta Sumadda"
COM_TAGS_FIELDSET_OPTIONS="Xulashooyinka"
COM_TAGS_FIELDSET_PUBLISHING="Faafinta"
COM_TAGS_FIELDSET_TAGGED_ITEMS="Waxyaabaha Lagu Calaamadeeyay"
COM_TAGS_FIELDSET_URLS_AND_IMAGES="Isku xirka iyo Sawirada"
COM_TAGS_FILTER_SEARCH_DESC="Raadi ciwaanka sumadda, magac-garowga iyo qoraalka. Ku dar HOR-ID: si aad u raadiso sumad ID."
COM_TAGS_FILTER_SEARCH_LABEL="Raadi Sumooyinka"
COM_TAGS_FLOAT_LABEL="Sabayn"
COM_TAGS_FORM_TITLE_EDIT="Sax Sumadda"
COM_TAGS_FORM_TITLE_NEW="Sumad Cusub"
COM_TAGS_HAS_SUBCATEGORY_ITEMS="%d walxood ayaa loo qoondeeyay summadaha hoosaadka ee sumaddan."
COM_TAGS_HAS_SUBCATEGORY_ITEMS_1="Walax ayaa loo qoondeeyay mid ka mid ah summad hoosaadka sumaddan."
COM_TAGS_HEADING_TAGTYPE="Nooca Sumadda"
COM_TAGS_INCLUDE="Kudar"
COM_TAGS_INCLUDE_CHILDREN_LABEL="Summadaha Ilmaha"
COM_TAGS_ITEM_OPTIONS="Xulashooyinka Shayga"
COM_TAGS_ITEMS_SEARCH_FILTER="Raadi"
COM_TAGS_LEFT="Bidix"
COM_TAGS_LIST_ALL_SELECTION_OPTIONS="Xulasho Xulasho"
COM_TAGS_LIST_MAX_CHARACTERS_LABEL="Tirada Ugu Badan Xarfaha"
COM_TAGS_LIST_MAX_LABEL="Waxyaabaha Ugu Badan"
COM_TAGS_LIST_SELECTION_OPTIONS="Xulashooyinka Shayga"
COM_TAGS_MANAGER_TAG_EDIT="Tags: Tafatirid"
COM_TAGS_MANAGER_TAG_NEW="Tags: Cusub"
COM_TAGS_MANAGER_TAGS="Tags"
COM_TAGS_MATCH_COUNT="Tirada tags-ka is waafajiya"
COM_TAGS_N_ITEMS_ARCHIVED="%d tags la kaydiyay."
COM_TAGS_N_ITEMS_ARCHIVED_1="Tag la kaydiyay."
COM_TAGS_N_ITEMS_CHECKED_IN_1="Tag la hubiyey."
COM_TAGS_N_ITEMS_CHECKED_IN_MORE="%d tags la hubiyey."
COM_TAGS_N_ITEMS_DELETED="%d tags la tirtiray."
COM_TAGS_N_ITEMS_DELETED_1="Tag la tirtiray."
COM_TAGS_N_ITEMS_FAILED_PUBLISHING="Qalad dhacay oo %d tags laguma daabici karo ugu yaraan mid ka mid ah waalidiintooda ayaa la daabicin ama mid ka mid ah carruurtooda ayaa la hubiyay."
COM_TAGS_N_ITEMS_FAILED_PUBLISHING_1="Qalad dhacay oo tag-ka laguma daabici karo ugu yaraan mid ka mid ah waalidiintiisa ayaa la daabicin ama mid ka mid ah carruurtiisa ayaa la hubiyay."
COM_TAGS_N_ITEMS_PUBLISHED="%d tags la daabacay."
COM_TAGS_N_ITEMS_PUBLISHED_1="Tag la daabacay."
COM_TAGS_N_ITEMS_TRASHED="%d tags la qashinka la saaray."
COM_TAGS_N_ITEMS_TRASHED_1="Tag la qashinka la saaray."
COM_TAGS_N_ITEMS_UNPUBLISHED="%d tags aan la daabicin."
COM_TAGS_N_ITEMS_UNPUBLISHED_1="Tag aan la daabicin."
COM_TAGS_N_QUICKICON="Tags"
COM_TAGS_N_QUICKICON_0="Tags"
COM_TAGS_N_QUICKICON_1="Tag"
COM_TAGS_N_QUICKICON_SRONLY="Tags: %d tags ayaa la daabacay."
COM_TAGS_N_QUICKICON_SRONLY_0="Tags: Hal tag lama daabacin."
COM_TAGS_N_QUICKICON_SRONLY_1="Tags: Hal tag ayaa la daabacay."
COM_TAGS_NONE="Midna"
COM_TAGS_NUMBER_TAG_ITEMS_LABEL="Tusay Tirada Walxaha"
COM_TAGS_OPTIONS="Xulashooyin Tag"
COM_TAGS_PAGINATION_OPTIONS="Xulashooyin Bogag"
COM_TAGS_PARAMS_IMAGE_FULLTEXT="Sawirka Dhamaystiran"
COM_TAGS_PARAMS_IMAGE_INTRO="Sawirka Hordhaca"
COM_TAGS_REBUILD_FAILURE="Ku guuldaraystay dib-u-dhisida xogta geedka Tags."
COM_TAGS_REBUILD_SUCCESS="Xogta geedka Tags ayaa dib loo dhisay."
COM_TAGS_RIGHT="Midig"
COM_TAGS_SAVE_SUCCESS="Tag waa la keydiyay."
COM_TAGS_SEARCH_TYPE_LABEL="Nooca Waafaqid"
COM_TAGS_SELECT_TAGTYPE="- Doorow Nooca Tag -"
COM_TAGS_SHOW_ALL_TAGS_IMAGE_LABEL="Tuso Sawirka Cinwaanka"
COM_TAGS_SHOW_ITEM_BODY_LABEL="Jidhka Shayga"
COM_TAGS_SHOW_ITEM_DESCRIPTION_LABEL="Sharaxaadaha Tag"
COM_TAGS_SHOW_ITEM_IMAGE_LABEL="Sawirada Shayga"
COM_TAGS_SHOW_TAG_BODY_LABEL="Tus Sharaxaada Tag"
COM_TAGS_SHOW_TAG_DESCRIPTION_LABEL="Sharaxaada Tag"
COM_TAGS_SHOW_TAG_IMAGE_LABEL="Sawirka Tag"
COM_TAGS_SHOW_TAG_LIST_DESCRIPTION_LABEL="Sharaxaad"
COM_TAGS_SHOW_TAG_TITLE_LABEL="Magaca Tag"
COM_TAGS_SUBSLIDER_DRILL_TAG_LIST_LABEL="Xulashooyin walba shayga ku jira liiska."
COM_TAGS_TABLE_CAPTION="Tags"
COM_TAGS_TAG_FIELD_MODE_AJAX="AJAX"
COM_TAGS_TAG_FIELD_MODE_DESC="Habka Ajax wuxuu baadhaya tags inta lagu jiro qorista waxayna kuu ogolaanaysaa abuurida tag socda. Tags isku xidhan waxay kuu tusayaan muuqaal is-xidhxidhan oo leh dhammaan tags-ka la heli karo."
COM_TAGS_TAG_FIELD_MODE_LABEL="Habka Gelida Tag"
COM_TAGS_TAG_FIELD_MODE_NESTED="Ku dhex nool"
COM_TAGS_TAG_LIST_DESCRIPTION_DESC="Sharaxaad ikhtiyaari ah oo lagu muujinayo dusha sare ee liiska. Tusaale ahaan, tan ayaa loo isticmaali karaa marka aad leedahay qaab-dhismeed ay ku jiraan wax ka badan hal tag."
COM_TAGS_TAG_LIST_DESCRIPTION_LABEL="Sharaxaada Qaabka"
COM_TAGS_TAG_LIST_FIELD_ITEM_DESCRIPTION_LABEL="Jirka Shayga"
COM_TAGS_TAG_LIST_MEDIA_ALT_EMPTY_DESC="Sawir Qurxoon - sharaxaad looma baahna"
COM_TAGS_TAG_LIST_MEDIA_ALT_EMPTY_LABEL="Ma jiro Sharaxaad"
COM_TAGS_TAG_LIST_MEDIA_ALT_LABEL="Sharaxaada Sawirka (Qoraalka Beddelka ah)"
COM_TAGS_TAG_LIST_MEDIA_LABEL="Sawir"
COM_TAGS_TAG_LIST_SHOW_DATE_LABEL="Taariikh"
COM_TAGS_TAG_LIST_SHOW_HEADINGS_LABEL="Cinwaanada Jadwalka"
COM_TAGS_TAG_LIST_SHOW_ITEM_DESCRIPTION_LABEL="Sharaxaada Shayga"
COM_TAGS_TAG_LIST_SHOW_ITEM_IMAGE_LABEL="Sawirka Shayga"
COM_TAGS_TAGGED_ITEMS_ACCESS="Helitaanka"
COM_TAGS_TAGGED_ITEMS_AUTHOR="Qoraa"
COM_TAGS_TAGGED_ITEMS_DATE="Taariikh"
COM_TAGS_TAGGED_ITEMS_ID="ID"
COM_TAGS_TAGGED_ITEMS_LANGUAGE="Luqadda"
COM_TAGS_TAGGED_ITEMS_TITLE="Cinwaan"
COM_TAGS_XML_DESCRIPTION="Qaybtani waxay maamushaa tags."
JGLOBAL_NO_ITEM_SELECTED="Noocyo aan la dooran"

