; Joomla! Project
; (C) 2010 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_MODULES="Qeybaha"
COM_MODULES_ACTION_EDITFRONTEND="Tafatirka Hore"
COM_MODULES_GENERAL="Guud ahaan"
COM_MODULES_MODULES_VIEW_DEFAULT_DESC="Waxay muujisaa liiska qaybaha si loo maareeyo"
COM_MODULES_MODULES_VIEW_DEFAULT_TITLE="Maareeyaha Qeybaha"
COM_MODULES_REDIRECT_EDIT_DESC="Dooro haddii tafatirka qaybta ay tahay in lagu furo goobta ama isdhexgalka maamulka."
COM_MODULES_REDIRECT_EDIT_LABEL="Tafatir Qayb"
COM_MODULES_XML_DESCRIPTION="Qayb lagu maamulo qaybaha gudaha Maamulka Backend."

