; Joomla! Project
; (C) 2011 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_FINDER="Raadinta Caqliga Leh"
COM_FINDER_FILTERS="Shaandheyn"
COM_FINDER_FILTERS_VIEW_DEFAULT_DESC="Soo bandhig shaandheynta raadinta."
COM_FINDER_FILTERS_VIEW_DEFAULT_TITLE="Shaandheyn Raadinta Caqliga Leh"
COM_FINDER_INDEX="Tusmo"
COM_FINDER_INDEX_VIEW_DEFAULT_DESC="Soo bandhig waxyaabaha tusmeysan."
COM_FINDER_INDEX_VIEW_DEFAULT_TITLE="Nuxurka Tusaaleedka Raadinta Caqliga Leh"
COM_FINDER_MAPS="Khariidado Nuxur"
COM_FINDER_MAPS_VIEW_DEFAULT_DESC="Soo bandhig habeynta nuxurka raadinta."
COM_FINDER_MAPS_VIEW_DEFAULT_TITLE="Habeynta Nuxurka Raadinta Caqliga Leh"
COM_FINDER_MENU_SEARCH_VIEW_DEFAULT_TEXT="Qaabka raadinta ee caadiga ah."
COM_FINDER_MENU_SEARCH_VIEW_DEFAULT_TITLE="Raadi"
COM_FINDER_SEARCH_VIEW_DEFAULT_DESC="Soo bandhig natiijooyinka raadinta."
COM_FINDER_SEARCH_VIEW_DEFAULT_TITLE="Natiijooyinka Raadinta Caqliga Leh"
COM_FINDER_SEARCHES="Ereyada Raadinta"
COM_FINDER_STATS_VIEW_DEFAULT_DESC="Soo bandhig tirakoobka raadinta."
COM_FINDER_STATS_VIEW_DEFAULT_TITLE="Tirakoobyada Raadinta Caqliga Leh"
COM_FINDER_XML_DESCRIPTION="Raadinta Caqliga Leh"

