; Joomla! Project
; (C) 2011 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_FINDER="Raadiinta Caqliga leh"
COM_FINDER_ALLOW_EMPTY_QUERY_DESC="Kaliya haddii la doorto shaandhayn, ogolow xariga raadinta madhan in la bilaabo raadinta gudaha xaddiga shaandhaynta."
COM_FINDER_ALLOW_EMPTY_QUERY_LABEL="Ogolow Raadinta Madhan"
COM_FINDER_AN_ERROR_HAS_OCCURRED="Khalad Ayaa Dhacay"
COM_FINDER_CONFIG_ALLOW_EMPTY_QUERY_LABEL="Ogolow Raadinta Madhan"
COM_FINDER_CONFIG_BATCH_SIZE_LABEL="Cabbirka Xidhmada Tusaha"
COM_FINDER_CONFIG_DESCRIPTION_LENGTH_LABEL="Dhererka Sharaxaadda"
COM_FINDER_CONFIG_ENABLE_LOGGING_LABEL="Ogolow Diiwaangelinta"
COM_FINDER_CONFIG_EXPAND_ADVANCED_LABEL="Balaari Raadinta Farsamada Sare"
COM_FINDER_CONFIG_FIELD_OPENSEARCH_DESCRIPTION_LABEL="Sharaxaadda Raadiinta Furan"
COM_FINDER_CONFIG_FIELD_OPENSEARCH_NAME_LABEL="Magaca Raadiinta Furan"
COM_FINDER_CONFIG_FILTER_COMMONWORDS_LABEL="Shaandhayso Ereyada Caadiga ah"
COM_FINDER_CONFIG_FILTER_NUMERICS_LABEL="Shaandhayso Ereyada Tirooyinka"
COM_FINDER_CONFIG_GATHER_SEARCH_STATISTICS_LABEL="Ururi Tirakoobka Raadinta"
COM_FINDER_CONFIG_HIGHLIGHT_CONTENT_SEARCH_TERMS_DESC="Sababo la xiriira waxqabadka awgood, tani ma muujin doonto wax ka badan 10 shuruud oo kala duwan natiijooyinka raadinta."
COM_FINDER_CONFIG_HIGHLIGHT_CONTENT_SEARCH_TERMS_LABEL="Muujinta Shuruudaha Raadinta"
; deprecated will be removed in 6.0
COM_FINDER_CONFIG_HILIGHT_CONTENT_SEARCH_TERMS_LABEL="Soo bandhig Erayada Raadinta"
COM_FINDER_CONFIG_IMAGE_CLASS_LABEL="Fasalka Sawirka"
COM_FINDER_CONFIG_LANGUAGE_DEFAULT_DEFAULT_LANGUAGE="Luuqadda Degelka ee Caadiga ah"
COM_FINDER_CONFIG_LANGUAGE_DEFAULT_DESC="Deji luuqadda loo isticmaali doono degellada aan luuqado badan lahayn ama nuxurka lagu calaamadeeyay \"Dhammaan\"."
COM_FINDER_CONFIG_LANGUAGE_DEFAULT_LABEL="Luuqadda Caadiga ah"
COM_FINDER_CONFIG_LANGUAGE_DEFAULT_NONE="Midna"
COM_FINDER_CONFIG_LINKED_IMAGE_LABEL="Sawir Isku Xiran"
COM_FINDER_CONFIG_META_MULTIPLIER_LABEL="Miisaanka Macluumaadka Wageerka ah"
COM_FINDER_CONFIG_MISC_MULTIPLIER_LABEL="Miisaanka Qoraalada Kale ee Wageerka ah"
COM_FINDER_CONFIG_OPENSEARCH_LABEL="Furan raadinta OpenSearch"
COM_FINDER_CONFIG_PATH_MULTIPLIER_LABEL="Miisaanka Qorista Waddada"
COM_FINDER_CONFIG_SHOW_ADVANCED_LABEL="Raadin Farsamo"
COM_FINDER_CONFIG_SHOW_ADVANCED_TIPS_LABEL="Talooyin Farsamo"
COM_FINDER_CONFIG_SHOW_AUTOSUGGEST_LABEL="Talo Soo Jeedin"
COM_FINDER_CONFIG_SHOW_DATE_FILTERS_LABEL="Shaandheynta Taariikhda"
COM_FINDER_CONFIG_SHOW_DATE_LABEL="Natiijada Taariikhda"
COM_FINDER_CONFIG_SHOW_DESCRIPTION_LABEL="Sharaxaadda Natiijada"
COM_FINDER_CONFIG_SHOW_EXPLAINED_QUERY_LABEL="Sharaxaada Weydiinta"
COM_FINDER_CONFIG_SHOW_IMAGE_LABEL="Sawirka Natiijada"
COM_FINDER_CONFIG_SHOW_SORT_ORDER_LABEL="Muuji Goobaha Kala-saarida"
COM_FINDER_CONFIG_SHOW_SUGGESTED_QUERY_LABEL="Ma U Jeeddaa"
COM_FINDER_CONFIG_SHOW_TAXONOMY_LABEL="Baahinta Natiijada"
COM_FINDER_CONFIG_SHOW_URL_LABEL="URL-ka Natiijada"
COM_FINDER_CONFIG_SORT_DIRECTION_LABEL="Jiho Kala-saarida"
COM_FINDER_CONFIG_SORT_OPTION_ASCENDING="Sii Kordhaya"
COM_FINDER_CONFIG_SORT_OPTION_DESCENDING="Sii Dhaadhacaya"
COM_FINDER_CONFIG_SORT_OPTION_LIST_PRICE="Qiimaha liiska"
COM_FINDER_CONFIG_SORT_OPTION_RELEVANCE="Xidhiidh Adaabiyad"
COM_FINDER_CONFIG_SORT_OPTION_SALES_PRICE="Qiimaha Iibka"
COM_FINDER_CONFIG_SORT_OPTION_START_DATE="Taariikhda Bilawga"
COM_FINDER_CONFIG_SORT_OPTION_TITLE="Cinwaanka"
COM_FINDER_CONFIG_SORT_ORDER_FIELDS_LABEL="Meelo dheeraad ah oo Kala-saarid ah"
COM_FINDER_CONFIG_SORT_ORDER_LABEL="Goobta Kala-saarida"
COM_FINDER_CONFIG_TEXT_MULTIPLIER_DESCRIPTION="Multiplier-ka waxaa loo isticmaalaa in lagu xukumo sida aadka ah ee qormooyinku saameyn ugu yeelanayaan darajada muhiimadda ee natiijada raadinta guud ahaan. Multiplier-ka wuxuu la xisaabtamaa inta kale ee multiplier-yada. Qoraalka jirka wuxuu ka yimaadaa koobitaanka iyo/ama jirka nuxurka."
COM_FINDER_CONFIG_TEXT_MULTIPLIER_LABEL="Miisaanka Qoraalka Jirka"
COM_FINDER_CONFIG_TITLE_MULTIPLIER_DESCRIPTION="Miisaanka ayaa loo adeegsadaa in lagu xakameeyo sida xoogan ee qoraalka la jaanqaaday ugu yeelanayo dhibcaha guud ee ku habboonaanta natiijada raadinta. Miisaanku waxaa loo tixgeliyaa sida uu la xiriiro miisaannada kale. Qoraalka cinwaanka wuxuu ka yimaadaa cinwaanka mawduuca."
COM_FINDER_CONFIG_TITLE_MULTIPLIER_LABEL="Miisaanka Qoraalka Cinwaanka"
COM_FINDER_CONFIG_TUPLECOUNT_LABEL="Raadi Weedho"
COM_FINDER_CONFIG_TUPLECOUNT_PHRASE_DISABLED="Dami (Waxqabadka La Hagaajiyay)"
COM_FINDER_CONFIG_TUPLECOUNT_PHRASE_ENABLED="Iffilan (Natiijooyin Raadinta oo La Hagaajiyay)"
COM_FINDER_CONFIG_WORD_MATCH_DESC="Deji sida ereyada raadinta loo dhigayo tusmada. Asal ahaan erey ayaa si sax ah loo dhigaa, balse marka afku taageero ereyadha isku xiran, tani waxay u oggolaanaysaa in ereyga raadinta loogu dhigo bilaabida ama meel kasta oo ku dhex jirta ereyada tusmada."
COM_FINDER_CONFIG_WORD_MATCH_LABEL="Luqadda Ereyga"
COM_FINDER_CONFIG_WORD_MATCH_OPTION_BEGIN="U dhigista ereyada bilaabaya ereyga raadinta"
COM_FINDER_CONFIG_WORD_MATCH_OPTION_EXACT="Si sax ah u dhigi"
COM_FINDER_CONFIG_WORD_MATCH_OPTION_FUZZY="U dhigi ereyo ka kooban ereyga raadinta meel kasta"
COM_FINDER_CONFIGURATION="Raadi Caqli: Xulashooyinka"
COM_FINDER_CONTENT_PLUGIN="Caqliga Raadi Mawduuca Plugin"
COM_FINDER_CREATE_FILTER="Abuur miiraha."
COM_FINDER_EDIT_FILTER="Tafatir Miiraha"
COM_FINDER_EDIT_PLUGIN_SETTINGS="Tafatir Dejinta Plugin"
COM_FINDER_EMPTYSTATE_BUTTON_ADD="Ku bilow tusiyaha"
COM_FINDER_EMPTYSTATE_CONTENT="Wax koob ah lama miisaamay ama waxaad tirtirtay dhammaan khariiddooyinkaaga. Fadlan booqo bogga Indeexa Caqliga ah si aad dib ugu miisaanto tilmaantaada."
COM_FINDER_EMPTYSTATE_SEARCHES_CONTENT="Waxay jiraan wax weedho loo adeegsaday raadinta goobta dhammaadka in la daawado."
COM_FINDER_FIELD_CREATED_BY_ALIAS_LABEL="Waxaa Abuuray Aliyas"
COM_FINDER_FIELD_CREATED_BY_LABEL="Waxaa Abuuray"
COM_FINDER_FIELD_FINDER_PLUGIN_LABEL="Raadi Plugin"
COM_FINDER_FIELDSET_INDEX_OPTIONS_DESCRIPTION="Xulashooyinkaani waxay saameeyaan sida muuqashada loo miisaamay. Kadib mar marka aad halkan ku bedesho dejinta, indeexu wuxuu u baahan yahay in dib loo dhiso."
COM_FINDER_FIELDSET_INDEX_OPTIONS_LABEL="Indhexa"
COM_FINDER_FIELDSET_SEARCH_OPTIONS_LABEL="Raadlinta Caqliga"
COM_FINDER_FILTER_BRANCH_LABEL="Raadi %s"
COM_FINDER_FILTER_EDIT_TOOLBAR_TITLE="Raadi Casri: Tafatir Shaandheyn"
COM_FINDER_FILTER_END_DATE_LABEL="Taariikhda Dhammaadka"
COM_FINDER_FILTER_ERROR_UNIQUE_ALIAS="Shaandheyn kale ayaa leh ablaablaha la mid ah."
COM_FINDER_FILTER_FIELDSET_PARAMS="Shaandhaynta Jadwalka"
COM_FINDER_FILTER_FORM_TITLE_EDIT="Tafatir Shaandheyn"
COM_FINDER_FILTER_FORM_TITLE_NEW="Shaandheyn Cusub"
COM_FINDER_FILTER_HIDE_ALL="Isku laab Dhammaan"
COM_FINDER_FILTER_MAP_COUNT="Tirada Khariidadaha"
COM_FINDER_FILTER_NEW_TOOLBAR_TITLE="Raadi Casri: Shaandheyn Cusub"
COM_FINDER_FILTER_SELECT_ALL_LABEL="Raadi Dhammaan"
COM_FINDER_FILTER_SELECT_CONTENT_MAP="- Dooro Khariidada Waxyaabaha -"
COM_FINDER_FILTER_SHOW_ALL="Fidi Dhammaan"
COM_FINDER_FILTER_START_DATE_DESCRIPTION="Qaabka Sannad-Bisha-Maalinta"
COM_FINDER_FILTER_START_DATE_LABEL="Taariikhda Bilowga"
COM_FINDER_FILTER_TIMESTAMP="Waxaa la Abuuray"
COM_FINDER_FILTER_WHEN_AFTER="Ka Dib"
COM_FINDER_FILTER_WHEN_BEFORE="Ka Hor"
COM_FINDER_FILTER_WHEN_END_DATE_LABEL="Goorma (Taariikhda Dhammaadka)"
COM_FINDER_FILTER_WHEN_EXACTLY="Si Sax ah"
COM_FINDER_FILTER_WHEN_START_DATE_LABEL="Goorma (Taariikhda Bilowga)"
COM_FINDER_FILTERS="Shaandheeyayaasha"
COM_FINDER_FILTERS_EMPTYSTATE_BUTTON_ADD="Ku dar shaandheyn"
COM_FINDER_FILTERS_EMPTYSTATE_CONTENT="Shaandheyn weli ma aadan abuurin."
COM_FINDER_FILTERS_N_ITEMS_CHECKED_IN="%d shaandheeyayaal ah ayaa hubiyey."
COM_FINDER_FILTERS_N_ITEMS_CHECKED_IN_1="Shaandheynta la hubiyay."
COM_FINDER_FILTERS_N_ITEMS_DELETED="%d shaandhooyin la tirtiray."
COM_FINDER_FILTERS_N_ITEMS_DELETED_1="Shaandho la tirtiray."
COM_FINDER_FILTERS_N_ITEMS_PUBLISHED="%d shaandhooyin la daabacay."
COM_FINDER_FILTERS_N_ITEMS_PUBLISHED_1="Shaandho la daabacay."
COM_FINDER_FILTERS_N_ITEMS_UNPUBLISHED="%d shaandhooyin aan la daabicin."
COM_FINDER_FILTERS_N_ITEMS_UNPUBLISHED_1="Shaandho aan la daabicin."
COM_FINDER_FILTERS_TABLE_CAPTION="Shaandhooyinka"
COM_FINDER_FILTERS_TOOLBAR_TITLE="Raadinta Caqliga Badan: Shaandhooyinka Raadi"
COM_FINDER_FINDER_PLUGINS="Plugin-yada Raadiyaha Raadinta Caqliga Badan"
COM_FINDER_HEADING_CHILDREN="Khariidado"
COM_FINDER_HEADING_CREATED_BY="Waxaa Sameeyay"
COM_FINDER_HEADING_CREATED_BY_ASC="Waxaa Sameeyay kor u soconaya"
COM_FINDER_HEADING_CREATED_BY_DESC="Waxaa Sameeyay hoos u soconaya"
COM_FINDER_HEADING_CREATED_ON="Waxaa La Sameeyay"
COM_FINDER_HEADING_CREATED_ON_ASC="Waxaa La Sameeyay kor u soconaya"
COM_FINDER_HEADING_CREATED_ON_DESC="Waxaa La Sameeyay hoos u soconaya"
COM_FINDER_HEADING_INDEXER="Tus-meedka Raadinta Caqliga Badan"
COM_FINDER_HEADING_MAP_COUNT="Tirada Khariidadaha"
COM_FINDER_HEADING_MAP_COUNT_ASC="Tirada Khariidadaha kor u soconaya"
COM_FINDER_HEADING_MAP_COUNT_DESC="Tirada Khariidadaha hoos u soconaya"
COM_FINDER_HEADING_NODES="Walxaha"
COM_FINDER_HEADING_PHRASE="Nacnac Raadinta"
COM_FINDER_HEADING_RESULTS="Natiijooyinka"
COM_FINDER_HEADING_SEARCH_TERM_ASC="Nacnac Raadinta kor u soconaya"
COM_FINDER_HEADING_SEARCH_TERM_DESC="Qoraal Raadin hoos u socda"
COM_FINDER_INDEX="Tusmo"
COM_FINDER_INDEX_CONFIRM_DELETE_PROMPT="Ma hubtaa inaad rabto inaad tirtirto shay(yo)ga la doortay?"
COM_FINDER_INDEX_CONFIRM_PURGE_PROMPT="Ma hubtaa inaad rabto inaad ka tirtirto dhamaan shayada tusmada? Tani waxay qaadan kartaa waqti dheer boggaga waaweyn."
COM_FINDER_INDEX_DATE_INFO="<strong>Bilowga La Daabacay:</strong> %s<br><strong>Dhammaadka La Daabacay:</strong> %s<br><strong>Bilowga Mawduuca:</strong> %s<br><strong>Dhammaadka Mawduuca:</strong> %s"
COM_FINDER_INDEX_DATE_INFO_TITLE="Macluumaadka Taariikhda Link"
COM_FINDER_INDEX_FILTER_BY_STATE="Wax kasta oo La Daabacay"
COM_FINDER_INDEX_HEADING_DETAILS="Faahfaahinta"
COM_FINDER_INDEX_HEADING_INDEX_DATE="Markii Ugu Dambeeyay La Cusbooneysiiyay"
COM_FINDER_INDEX_HEADING_INDEX_DATE_ASC="Markii Ugu Dambeeyay La Cusbooneysiiyay oo soo socda"
COM_FINDER_INDEX_HEADING_INDEX_DATE_DESC="Markii Ugu Dambeeyay La Cusbooneysiiyay oo hoos u socda"
COM_FINDER_INDEX_HEADING_INDEX_TYPE="Nooca"
COM_FINDER_INDEX_HEADING_INDEX_TYPE_ASC="Nooca oo soo socda"
COM_FINDER_INDEX_HEADING_INDEX_TYPE_DESC="Nooca oo hoos u socda"
COM_FINDER_INDEX_HEADING_LINK_URL="URL-ka Dabiiciga ah"
COM_FINDER_INDEX_HEADING_LINK_URL_ASC="URL-ka Dabiiciga ah oo soo socda"
COM_FINDER_INDEX_HEADING_LINK_URL_DESC="URL-ka Dabiiciga ah oo hoos u socda"
COM_FINDER_INDEX_NO_CONTENT="Waxyaabo nuxur leh kama helin shuruudaha raadintaada."
COM_FINDER_INDEX_NO_DATA="Wax nuxur ah lama tixraacayo."
COM_FINDER_INDEX_OPTIMISE_FINISHED="Optimeesheeshan waa dhamaatay."
COM_FINDER_INDEX_PLUGIN_CONTENT_NOT_ENABLED="Plugin-ka Mawduuca Raadinta Smart waa naafo. Isbeddelada mawduucauma cusbooneysiin doonaan tusmada Raadinta Smart ilaa admiinka la awoodo."
COM_FINDER_INDEX_PLUGIN_CONTENT_NOT_ENABLED_LINK="%s waa naafo. Isbedelada mawduuca uma cusbooneysiin doonaan tusmada Raadinta Smart haddii aadan firfircoonin plugin-kan."
COM_FINDER_INDEX_PLUGIN_FINDER_NOT_ENABLED_LINK="%s waa naafo. Isbedelada mawduuca uma cusbooneysiin doonaan tusmada Raadinta Smart haddii aadan firfircoonin plugins-kan."
COM_FINDER_INDEX_PURGE_FAILED="Ku guuldareysatay inaad tirtirto shayada la doortay."
COM_FINDER_INDEX_PURGE_SUCCESS="Dhammaan shayada waa la tirtiray."
COM_FINDER_INDEX_SEARCH_DESC="Raadi cinwaanka, URL iyo taariikhda ugu dambeysay ee la cusbooneysiiyay."
COM_FINDER_INDEX_SEARCH_LABEL="Raadi Mawduucyo Diiwaangashan"
COM_FINDER_INDEX_TABLE_CAPTION="Mawduucyo Diiwaangashan"
COM_FINDER_INDEX_TIP="Bilow diiwaangelinta adigoo riixaya batoonka hoose, ama toolbar-ka."
COM_FINDER_INDEX_TOOLBAR_INDEX_DEBUGGING="Baadhis Index"
COM_FINDER_INDEX_TOOLBAR_MAINTENANCE="Dayactir"
COM_FINDER_INDEX_TOOLBAR_OPTIMISE="Hagaajin"
COM_FINDER_INDEX_TOOLBAR_PURGE="Nadiifi Index"
COM_FINDER_INDEX_TOOLBAR_TITLE="Raadinta caqliga leh: Mawduucyo Diiwaangashan"
COM_FINDER_INDEX_TYPE_FILTER="Nooca Mawduuc kasta"
COM_FINDER_INDEXER_ERROR_PLUGIN_FAILURE="Qalab \"finder\" ah ayaa la kulmay qalad."
COM_FINDER_INDEXER_FIELDSET_ATTRIBUTES="Natiijo Shay"
COM_FINDER_INDEXER_FIELDSET_ELEMENTS="Waxyaabo Dheeri ah"
COM_FINDER_INDEXER_FIELDSET_INSTRUCTIONS="Tilmaamo"
COM_FINDER_INDEXER_FIELDSET_TAXONOMIES="Canshuuraha"
COM_FINDER_INDEXER_HEADER_COMPLETE="Diiwaan gelinta waa dhameystiran."
COM_FINDER_INDEXER_HEADER_ERROR="Dhib ayaa dhacay."
COM_FINDER_INDEXER_HEADER_INIT="Diiwaangelinta Waxaa La Bilaabayaa"
COM_FINDER_INDEXER_HEADER_OPTIMIZE="Diiwaangelinta waa la hagaajinayaa."
COM_FINDER_INDEXER_HEADER_RUNNING="Diiwaangelinta Waa Socotaa"
COM_FINDER_INDEXER_INVALID_DRIVER="Diiwaangelintu ma taageerto habeynta darawal database-ka %s."
COM_FINDER_INDEXER_INVALID_PARSER="Nooca parser-ka lama aqbali karo %s"
COM_FINDER_INDEXER_INVALID_STEMMER="Nooca stemmer-ka lama aqbali karo %s"
COM_FINDER_INDEXER_MESSAGE_COMPLETE="Hannaanka diiwaangelintu waa dhameystiran yahay. Hadda waa ammaan in la xiro daaqaddan."
COM_FINDER_INDEXER_MESSAGE_INIT="Diiwaangelintu waa bilaabmaysaa. Ha xirin daaqaddan."
COM_FINDER_INDEXER_MESSAGE_OPTIMIZE="Jadwal miiska waxaa lagu hagaajinayaa waxqabadka ugu wanaagsan. Ha xirin daaqaddan."
COM_FINDER_INDEXER_MESSAGE_RUNNING="Waxyaabahaaga ayaa la soo galinayaa. Ha xirin daaqaddan."
COM_FINDER_INDEXER_MSG_DEBUGGING_INDEXING="Habka wax-meelmarinta ee Smart Search"
COM_FINDER_INDEXER_MSG_DEBUGGING_INDEXING_TEXT="Dooro habka plugin ee Smart Search oo bixi aqoonsi si aad u meelmariso. Natiijada plugin-kaas aqoonsigaas kaddib waxaa lagu soo bandhigi doonaa meelka hoose."
COM_FINDER_INDEXER_OUTPUT_AREA_TITLE="Soo Saarka"
COM_FINDER_INDEXER_TOOLBAR_TITLE="Indexer: Habka Cillad Bixinta"
COM_FINDER_ITEM_FIELDSET_ITEM_TITLE="Tilmaamaha Shayga"
COM_FINDER_ITEM_FIELDSET_TAXONOMIES_TITLE="Qeybaha"
COM_FINDER_ITEM_FIELDSET_TERMS_TITLE="Ereyada"
COM_FINDER_ITEM_TAXONOMIES_TABLE_CAPTION="Jadwalka qeybaha"
COM_FINDER_ITEM_TERMS_TABLE_CAPTION="Jadwalka ereyada"
COM_FINDER_ITEM_X_ONLY="Kaliya %s"
COM_FINDER_ITEMS="Waxyaabaha"
COM_FINDER_LOGGING_DISABLED="Ururinta tirakoobka waa la naafoobay. Ku xiro %s."
COM_FINDER_LOGGING_DISABLED_NO_AUTH="Ururinta tirakoobka waa la naafoobay. Uma lihid ogolaansho in aad tan beddesho. Fadlan la xiriir maamulaha bogga haddii tani aysan sax ahayn."
COM_FINDER_MANAGER_SEARCHES="Raadiyada Caqliga leh: Falanqaynta Erayga Raadi"
COM_FINDER_MAPS="Khariidadaha"
COM_FINDER_MAPS_CONFIRM_DELETE_PROMPT="Ma hubtaa inaad rabto inaad tirtirto khariidadaha la xushay?"
COM_FINDER_MAPS_COUNT_PUBLISHED_ITEMS="Waxyaabo la sii daabacay oo la soo galay"
COM_FINDER_MAPS_COUNT_UNPUBLISHED_ITEMS="Waxyaabo aan la daabacin oo la soo galay"
COM_FINDER_MAPS_HEADING_BRANCH="Kooxda Khariidada"
COM_FINDER_MAPS_HEADING_CONTENT_MAP="Khariidada Waxyaabaha"
COM_FINDER_MAPS_HEADING_TYPE="Nooca Waxyaabaha"
COM_FINDER_MAPS_MULTILANG="Ogeysiin: Plugin nidaamka sifeynta luqadda ayaa la dhaqaajiyay, sidaa darteed kooxdan loo isticmaali maayo."
COM_FINDER_MAPS_N_ITEMS_DELETED="%d khariidadaha ayaa la tirtiray."
COM_FINDER_MAPS_N_ITEMS_DELETED_1="Khariidad la tirtiray."
COM_FINDER_MAPS_N_ITEMS_FAILED_PUBLISHING="Ku guuldareystay daabacaadda %d khariidad waxaana ugu yaraan mid ka mid ah waalidkood aan la daabicin ama mid ka mid ah carruurtood ayaa la hubiyay."
COM_FINDER_MAPS_N_ITEMS_FAILED_PUBLISHING_1="Ku guuldareystay daabacaadda %d khariidad maadaama ugu yaraan mid ka mid ah waalidkeed aan la daabicin ama mid ka mid ah carruurteeda la hubiyay."
COM_FINDER_MAPS_N_ITEMS_PUBLISHED="%d khariidadood la daabacay."
COM_FINDER_MAPS_N_ITEMS_PUBLISHED_1="Khariidad la daabacay."
COM_FINDER_MAPS_N_ITEMS_UNPUBLISHED="%d khariidadood aan la daabicin."
COM_FINDER_MAPS_N_ITEMS_UNPUBLISHED_1="Khariidad aan la daabicin."
COM_FINDER_MAPS_NO_CONTENT="Natiijooyin lama soo bandhigay. Ama waxyaabaha lama qaabeyn ama waxyaabaha ma buuxiyaan shuruudahaaga shaandhaynta."
COM_FINDER_MAPS_SELECT_BRANCH="- Xulo Kooxda Khariidada -"
COM_FINDER_MAPS_SELECT_TYPE="- Xulo Nooca Mawduuca -"
COM_FINDER_MAPS_TABLE_CAPTION="Khariidadaha Mawduuca"
COM_FINDER_MAPS_TOOLBAR_TITLE="Raadinta Caqliga leh: Khariidadaha Mawduuca"
COM_FINDER_MESSAGE_RETURNED="Fariinta soo socota waxaa soo celisay serverka:"
COM_FINDER_N_ITEMS_CHECKED_IN_1="Shay la xaqiijiyay."
COM_FINDER_N_ITEMS_CHECKED_IN_MORE="%d shay la xaqiijiyay."
COM_FINDER_N_ITEMS_DELETED="%d shay la tirtiray."
COM_FINDER_N_ITEMS_DELETED_1="Shay la tirtiray."
COM_FINDER_N_ITEMS_PUBLISHED="%d shay la daabacay."
COM_FINDER_N_ITEMS_PUBLISHED_1="Shay la daabacay."
COM_FINDER_N_ITEMS_TRASHED="%d shay la qashinka la dhigay."
COM_FINDER_N_ITEMS_TRASHED_1="Shay la qashinka la dhigay."
COM_FINDER_N_ITEMS_UNPUBLISHED="%d shay aan la daabicin."
COM_FINDER_N_ITEMS_UNPUBLISHED_1="Shay aan la daabicin."
COM_FINDER_NO_ERROR_RETURNED="Khalad lama soo celin. Hubi in soo tabinta khaladka la jiro."
COM_FINDER_NO_FILTERS="Shaandhooyin weli lama abuurin."
COM_FINDER_NO_RESULTS="Natiijooyin ma jiraan oo ku habboon shuruudahaaga raadinta."
COM_FINDER_NO_RESULTS_OR_FILTERS="Natiijooyin ma jiraan oo ku habboon shuruudahaaga ama ma jiro miirayaal la sameeyay weli."
COM_FINDER_PREFILL_SEARCH_LABEL="Erayga Raadinta ee La Buuxiyay"
COM_FINDER_QUERY_FILTER_TODAY="Maanta"
COM_FINDER_QUERY_OPERATOR_AND="Iyo"
COM_FINDER_QUERY_OPERATOR_NOT="Maya"
COM_FINDER_QUERY_OPERATOR_OR="Ama"
COM_FINDER_SEARCH_FILTER_SEARCH_DESC="Raadi ciwaanka miiraha."
COM_FINDER_SEARCH_FILTER_SEARCH_LABEL="Miirayaha Raadinta"
COM_FINDER_SEARCH_IN_PHRASE_DESC="Raadi eray bixinta lagu galey raadinta."
COM_FINDER_SEARCH_IN_PHRASE_LABEL="Ku miiri eray bixinta la raadiyay"
COM_FINDER_SEARCH_LABEL="Raadi %s:"
COM_FINDER_SEARCH_SEARCH_QUERY_DESC="Raadi ciwaanka khariidadda nuxurka."
COM_FINDER_SEARCH_SEARCH_QUERY_LABEL="Raadi Khariidadaha Nuxurka"
COM_FINDER_SEARCHES_TABLE_CAPTION="Tirada Raadinta"
COM_FINDER_SELECT_FILTER_LABEL="Ku miiri"
COM_FINDER_SELECT_SEARCH_FILTER="Xulo miiraha"
COM_FINDER_STATISTICS="Tirada"
COM_FINDER_STATISTICS_LINK_TYPE_COUNT="Tirada"
COM_FINDER_STATISTICS_LINK_TYPE_HEADING="Nooca Xiriirka"
COM_FINDER_STATISTICS_LINK_TYPE_TOTAL="Wadarta"
COM_FINDER_STATISTICS_STATS_DESCRIPTION="Waxyaabaha la tixraacay ee goobtan waxaa ka mid ah %s erayo ku saabsan %s xiriir leh %s astaamo oo ku yaal %s laamood."
COM_FINDER_STATISTICS_TITLE="Tirada Raadinta Casrigan"
COM_FINDER_XML_DESCRIPTION="Raadinta Casrigan."

