; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_NEWSFEEDS="Wararka Cusub"
COM_NEWSFEEDS_BATCH_OPTIONS="Habka kooxeynta ee wararka la soo xulay"
COM_NEWSFEEDS_BATCH_TIP="Haddii qayb la xulo oo la guuriyo/kopiiyo, ficilada la doortay waxaa la saari doonaa wararka cusub ee la kopiiyey ama la guuriyey. Haddii kale, dhammaan ficilada waxaa lagu dabaqayaa wararka cusub ee la soo xulay."
COM_NEWSFEEDS_CACHE_TIME_HEADING="Waqtiga Kaydka"
COM_NEWSFEEDS_CACHE_TIME_HEADING_ASC="Waqtiga Kaydka si koror ah"
COM_NEWSFEEDS_CACHE_TIME_HEADING_DESC="Waqtiga Kaydka si hoos u dhac ah"
COM_NEWSFEEDS_CATEGORIES_DESC="Dejintan waxay ku dabaqmaan Ikhtiyaarka Qaybaha Wararka Cusub ilaa ay isbedelaan shay gaar ah oo menu ah."
COM_NEWSFEEDS_CONFIG_INTEGRATION_SETTINGS_DESC="Dejintan waxay go'aaminaysaa sida Qaybta Wararka Cusub ay ula falgalidoonto kordhinta kale."
COM_NEWSFEEDS_CONFIGURATION="War Cusub: Ikhtiyaaraadka"
COM_NEWSFEEDS_EDIT_NEWSFEED="Tafatir War Cusub"
COM_NEWSFEEDS_EMPTYSTATE_BUTTON_ADD="Ku dar wararkaaga cusub ee ugu horreeya"
COM_NEWSFEEDS_EMPTYSTATE_CONTENT="Ku darista Wararka Cusub ee bartahaaga waa sida loo is dhexgeliyo macluumaadka mareegaha kale."
COM_NEWSFEEDS_EMPTYSTATE_TITLE="Weli warar cusub looma abuurin."
COM_NEWSFEEDS_ERROR_ALL_LANGUAGE_ASSOCIATED="Qodobka wararka cusub oo loo dejiyay dhammaan luqadaha lama xidhi karo. Xidhiidhiyeyaasha lama dhigin."
COM_NEWSFEEDS_ERROR_UNIQUE_ALIAS="War kale oo cusub oo ka tirsan qaybtaan wuxuu leeyahay magac astaan isku mid ah."
COM_NEWSFEEDS_ERROR_UNIQUE_ALIAS_TRASHED="War cusub oo ka tirsan qaybtaan oo la tuuray wuxuu leeyahay magac astaan isku mid ah."
COM_NEWSFEEDS_FIELD_CACHETIME_LABEL="Waqtiga Kaydka"
COM_NEWSFEEDS_FIELD_CHARACTER_COUNT_DESC="0 wuxuu soo bandhigi doonaa dhammaan qoraalka."
COM_NEWSFEEDS_FIELD_CHARACTER_COUNT_LABEL="Tirinta Astaamaha"
COM_NEWSFEEDS_FIELD_CHARACTERS_COUNT_DESC="0 wuxuu soo bandhigi doonaa dhammaan qoraalka."
COM_NEWSFEEDS_FIELD_CHARACTERS_COUNT_LABEL="Tirinta Astaamaha"
COM_NEWSFEEDS_FIELD_CONFIG_CATEGORY_SETTINGS_DESC="Dejintan waxay ku dabaqmaan Ikhtiyaarka Qaybaha Wararka Cusub ilaa ay isbedelaan shay gaar ah oo menu ah."
COM_NEWSFEEDS_FIELD_CONFIG_LIST_SETTINGS_DESC="Dejintan waxay ku dabaqmaan Ikhtiyaarka Qaabka Liiska ilaa ay isbedelaan shay gaar ah oo menu ah."
COM_NEWSFEEDS_FIELD_CONFIG_NEWSFEED_SETTINGS_DESC="Dejintan waxay ku dabaqmaan wararka cusub ee gaarka ah ilaa ay isbedelaan shay gaar ah oo menu ah ama war cusub."
COM_NEWSFEEDS_FIELD_CONFIG_NEWSFEED_SETTINGS_LABEL="War Cusub"
COM_NEWSFEEDS_FIELD_FEED_DISPLAY_ORDER_LABEL="Habka Muuqaalka Feedka"
COM_NEWSFEEDS_FIELD_FIRST_LABEL="Sawirka Koowaad"
COM_NEWSFEEDS_FIELD_IMAGE_ALT_EMPTY_DESC="Sawir Qurxoon - sharraxaad looma baahna"
COM_NEWSFEEDS_FIELD_IMAGE_ALT_EMPTY_LABEL="Macluumaad Ma Jiro"
COM_NEWSFEEDS_FIELD_IMAGE_ALT_LABEL="Sharaxaada Sawirka (Qoraal Kale)"
COM_NEWSFEEDS_FIELD_IMAGE_CAPTION_LABEL="Sharaxaad"
COM_NEWSFEEDS_FIELD_LINK_LABEL="Isku-xirka"
COM_NEWSFEEDS_FIELD_NUM_ARTICLES_COLUMN_LABEL="# Maqaallo"
COM_NEWSFEEDS_FIELD_NUM_ARTICLES_LABEL="Tirada Maqaallada"
COM_NEWSFEEDS_FIELD_RTL_LABEL="Jihada Luqadda"
COM_NEWSFEEDS_FIELD_SECOND_LABEL="Sawirka Labaad"
COM_NEWSFEEDS_FIELD_SELECT_FEED_LABEL="Feed"
COM_NEWSFEEDS_FIELD_SHOW_CAT_ITEMS_LABEL="# Feeds ee Qaybta"
COM_NEWSFEEDS_FIELD_SHOW_CAT_TAGS_LABEL"Tags"
COM_NEWSFEEDS_FIELD_SHOW_FEED_DESCRIPTION_LABEL="Sharaxaadda Feedka"
COM_NEWSFEEDS_FIELD_SHOW_FEED_IMAGE_LABEL="Sawirka Feedka"
COM_NEWSFEEDS_FIELD_SHOW_ITEM_DESCRIPTION_LABEL="Mawduuc Feedka"
COM_NEWSFEEDS_FIELD_SHOW_LINKS_LABEL="Isku-xirka Feeds"
COM_NEWSFEEDS_FIELD_SHOW_TAGS_LABEL="Tags"
COM_NEWSFEEDS_FIELD_VALUE_LTR="Bidix ilaa Midig"
COM_NEWSFEEDS_FIELD_VALUE_RTL="Midig ilaa Bidix"
COM_NEWSFEEDS_FIELD_VALUE_SITE="Luqadda Bogga"
COM_NEWSFEEDS_FIELD_VERSION_LABEL="Dib-u-eegis"
COM_NEWSFEEDS_FIELDSET_MORE_OPTIONS_LABEL="Xulashooyinka Muuqaalka Feedka"
COM_NEWSFEEDS_FILTER_SEARCH_DESC="Raadi cinwaanka iyo magaca feedka wararka. Ku dar 'ID:' si aad u raadsato aqoonsi feed wararka."
COM_NEWSFEEDS_FILTER_SEARCH_LABEL="Raadi Wararka Quudinta"
COM_NEWSFEEDS_FLOAT_FIRST_LABEL="Sawirka Koowaad ee Socod Siin"
COM_NEWSFEEDS_FLOAT_LABEL="Sawirka Socod Siin"
COM_NEWSFEEDS_FLOAT_SECOND_LABEL="Sawirka Labaad ee Socod Siin"
COM_NEWSFEEDS_FORM_TITLE_EDIT="Tafatir Warka Quudinta"
COM_NEWSFEEDS_FORM_TITLE_NEW="War Quudin Cusub"
COM_NEWSFEEDS_HEADING_ASSOCIATION="Isku Xirnaanta"
COM_NEWSFEEDS_LEFT="Bidix"
COM_NEWSFEEDS_MANAGER_NEWSFEED_EDIT="Wararka Quudinta: Tafatir"
COM_NEWSFEEDS_MANAGER_NEWSFEED_NEW="Wararka Quudinta: Cusub"
COM_NEWSFEEDS_MANAGER_NEWSFEEDS="Wararka Quudinta"
COM_NEWSFEEDS_N_ITEMS_ARCHIVED="%d wararka quudinta kaydsan."
COM_NEWSFEEDS_N_ITEMS_ARCHIVED_1="Warka quudinta waa la kaydiyey."
COM_NEWSFEEDS_N_ITEMS_CHECKED_IN_1="Warka quudinta waa la hubiyey."
COM_NEWSFEEDS_N_ITEMS_CHECKED_IN_MORE="%d wararka quudinta waa la hubiyey."
COM_NEWSFEEDS_N_ITEMS_DELETED="%d wararka quudinta waa la tirtiray."
COM_NEWSFEEDS_N_ITEMS_DELETED_1="Warka quudinta waa la tirtiray."
COM_NEWSFEEDS_N_ITEMS_PUBLISHED="%d wararka quudinta waa la daabacay."
COM_NEWSFEEDS_N_ITEMS_PUBLISHED_1="Warka quudinta waa la daabacay."
COM_NEWSFEEDS_N_ITEMS_TRASHED="%d wararka quudinta waa la tuuray."
COM_NEWSFEEDS_N_ITEMS_TRASHED_1="Warka quudinta waa la tuuray."
COM_NEWSFEEDS_N_ITEMS_UNPUBLISHED="%d wararka quudinta lama daabacin."
COM_NEWSFEEDS_N_ITEMS_UNPUBLISHED_1="Warka quudinta lama daabacin."
COM_NEWSFEEDS_N_QUICKICON="Wararka Quudinta"
COM_NEWSFEEDS_N_QUICKICON_1="Warka Quudinta"
COM_NEWSFEEDS_N_QUICKICON_SRONLY="Quudinta Wararka: %d quudin warar ah ayaa la daabacay."
COM_NEWSFEEDS_N_QUICKICON_SRONLY_1="Quudinta Wararka: Hal quudin warar ah ayaa la daabacay."
COM_NEWSFEEDS_NEW_NEWSFEED="Quudin Warar Cusub"
COM_NEWSFEEDS_NEWSFEEDS="Quudinta Wararka"
COM_NEWSFEEDS_NO_ITEM_SELECTED="Lama xulin quudinta wararka."
COM_NEWSFEEDS_NONE="Midna"
COM_NEWSFEEDS_NUM_ARTICLES_HEADING="# Qodobbada"
COM_NEWSFEEDS_NUM_ARTICLES_HEADING_ASC="# Qodobbada kor u kaca"
COM_NEWSFEEDS_NUM_ARTICLES_HEADING_DESC="# Qodobbada hoos u dhaca"
COM_NEWSFEEDS_RIGHT="Midig"
COM_NEWSFEEDS_SAVE_SUCCESS="Quudinta wararka waa la badbaadiyay."
COM_NEWSFEEDS_SELECT_A_FEED="Dooro Quudin Warar"
COM_NEWSFEEDS_TABLE_CAPTION="Quudinta Wararka"
COM_NEWSFEEDS_TIP_ASSOCIATION="Quudinta wararka ee la xidhiidha"
COM_NEWSFEEDS_WARNING_PROVIDE_VALID_NAME="Fadlan bixiya magac sax ah."
COM_NEWSFEEDS_XML_DESCRIPTION="Qaybtan waxay maamushaa quudin wararka RSS iyo Atom."
JGLOBAL_NEWITEMSLAST_DESC="Quudinta wararka cusub ayaa asal ahaan ku jira booska ugu dambeeya. Dalbashada waa la bedeli karaa ka dib marka quudintan wararka la badbaadiyo."

JLIB_RULES_SETTING_NOTES_COM_NEWSFEEDS="Isbeddellada waxay quseeyaan qaybtan oo keliya.<br><em><strong>Dhowrid</strong></em> - meel la isugu keenay ama heer sare ayaa la dalbadaa.<br><em><strong>Diidmo</strong></em> mar walba guuleysato - si kasta ha la dhigo heerka bartamaha ama ka sareeya, waxa ay quseeyaan dhammaan walxaha carruurta.<br><em><strong>Ogolaansho</strong></em> waxay fursad siin doontaa ficilka qaybtaan ilaa lagaga soogo meel la isugu keenay."

