; Joomla! Project
; (C) 2009 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_CONTENT="Qoraallo"
COM_CONTENT_ARCHIVE_VIEW_DEFAULT_DESC="Tus dhammaan qoraallada la dhigay keydka."
COM_CONTENT_ARCHIVE_VIEW_DEFAULT_OPTION="Asalka"
COM_CONTENT_ARCHIVE_VIEW_DEFAULT_TITLE="Qoraallo Keyd ah"
COM_CONTENT_ARTICLE_MANAGER="Qoraallo"
COM_CONTENT_ARTICLE_VIEW_DEFAULT_DESC="Tus hal qoraal."
COM_CONTENT_ARTICLE_VIEW_DEFAULT_OPTION="Asalka"
COM_CONTENT_ARTICLE_VIEW_DEFAULT_TITLE="Qoraal Keliya"
COM_CONTENT_ARTICLE_VIEW_EDIT_DESC="Tus foom si loo abuuro Qoraal Cusub."
COM_CONTENT_ARTICLE_VIEW_EDIT_TITLE="Abuur Qoraal"
COM_CONTENT_ARTICLES="Qoraallo"
COM_CONTENT_ARTICLES_VIEW_DEFAULT_DESC="Tus liiska dhammaan qoraallada."
COM_CONTENT_ARTICLES_VIEW_DEFAULT_TITLE="Liiska Dhammaan Qoraallada"
COM_CONTENT_CATEGORIES="Qeybaha"
COM_CONTENT_CATEGORIES_VIEW_DEFAULT_DESC="Tus liiska dhammaan qaybaha ku jira geedka qaybaha qoraalka la xushay."
COM_CONTENT_CATEGORIES_VIEW_DEFAULT_OPTION="Asalka"
COM_CONTENT_CATEGORIES_VIEW_DEFAULT_TITLE="Liiska Dhammaan Qaybaha ku Jira Geedka Qaybaha Qoraalka"
COM_CONTENT_CATEGORY_VIEW_BLOG_DESC="Tus hordhacyo maqaallo qaab hal ama dhowr sadar qaab qaabaysan."
COM_CONTENT_CATEGORY_VIEW_BLOG_OPTION="Blog"
COM_CONTENT_CATEGORY_VIEW_BLOG_TITLE="Qaybta Blog"
COM_CONTENT_CATEGORY_VIEW_DEFAULT_DESC="Tus liis ka mid ah qoraallada ku jira qayb."
COM_CONTENT_CATEGORY_VIEW_DEFAULT_OPTION="Liis"
COM_CONTENT_CATEGORY_VIEW_DEFAULT_TITLE="Liiska Qaybta"
COM_CONTENT_CATEGORY_VIEW_FEATURED_DESC="Tus dhammaan maqaallada astaan ​​leh ee ka socda hal ama dhowr qeybood oo qaab ah hal ama dhowr sadar qaabaysan."
COM_CONTENT_CONTENT_TYPE_ARTICLE="Qoraal"
COM_CONTENT_CONTENT_TYPE_CATEGORY="Qaybta Maqaalka"
COM_CONTENT_FEATURED="Sifaysnaa"
COM_CONTENT_FEATURED_VIEW_DEFAULT_DESC="Waxay soo bandhigaysaa liiska maqaalada sifaysan."
COM_CONTENT_FEATURED_VIEW_DEFAULT_OPTION="Caadiga ah"
COM_CONTENT_FEATURED_VIEW_DEFAULT_TITLE="Maqaalada Sifaysan"
COM_CONTENT_FORM_VIEW_DEFAULT_DESC="Samee maqaal cusub."
COM_CONTENT_FORM_VIEW_DEFAULT_OPTION="Abuur"
COM_CONTENT_FORM_VIEW_DEFAULT_TITLE="Abuur Maqaal"
COM_CONTENT_MENUS="Waxyaabaha ku jira"
COM_CONTENT_MENUS_ARTICLE_MANAGER="Maqaalada"
COM_CONTENT_MENUS_CATEGORY_MANAGER="Qaybaha"
COM_CONTENT_MENUS_FEATURED="Maqaalada Sifaysan"
COM_CONTENT_MENUS_MANAGE="Dejinta Waxyaabaha Ku Jira"
COM_CONTENT_MENUS_MISC="Moodeelo & Warbaahineed"
COM_CONTENT_MENUS_NEW_ADMIN_MODULE="Kudar Moodeelka Maamulaha"
COM_CONTENT_MENUS_NEW_ARTICLE="Kudar Maqaal"
COM_CONTENT_MENUS_NEW_CATEGORY="Kudar Qayb"
COM_CONTENT_MENUS_NEW_SITE_MODULE="Kudar Moodeelka Goobta"
COM_CONTENT_MENUS_PRESET_CONTENT="Preset - Dashboard-Waxyaabaha ku jira"
COM_CONTENT_MENUS_WORKFLOW="Shaqooyinka"
COM_CONTENT_MENUS_WORKFLOW_MANAGER="Shaqooyinka"
COM_CONTENT_TAGS_ARTICLE="Maqaal"
COM_CONTENT_TAGS_CATEGORY="Qaybta Maqaalka"
COM_CONTENT_XML_DESCRIPTION="Qaybta maamulka maqaallada."

