; Joomla! Project
; (C) 2007 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_ADMIN="Macluumaadka Nidaamka"
COM_ADMIN_HELP_VIEW_DEFAULT_DESC="Ka hel caawimaad bogag kala duwan oo ku yaal interface-ka maamulka Joomla-gaaga."
COM_ADMIN_HELP_VIEW_DEFAULT_TITLE="Joomla! Caawinta"
COM_ADMIN_SYSINFO_VIEW_DEFAULT_DESC="Daawo macluumaadka faahfaahsan ee ku saabsan goobta Joomla-gaaga iyo dejinta qaabeynta serverka."
COM_ADMIN_SYSINFO_VIEW_DEFAULT_TITLE="Macluumaadka Nidaamka"
COM_ADMIN_XML_DESCRIPTION="Qaybta macluumaadka nidaamka maamulka."

