; Joomla! Project
; (C) 2018 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

; The placeholder for this key is the configured log path for the site.
COM_PRIVACY="Asturnaanta"
COM_PRIVACY_ACTION_DELETE_DATA="Tirtir Macluumaadka"
COM_PRIVACY_ACTION_EMAIL_EXPORT_DATA="Emailka Dhoofinta Macluumaadka"
COM_PRIVACY_ACTION_EXPORT_DATA="Dhoofinta Macluumaadka"
COM_PRIVACY_ACTION_LOG_ADMIN_COMPLETED_REQUEST="Isticmaalaha <a href='{accountlink}'>{username}</a> ayaa dhammeeyay <a href='{itemlink}'>codsiga #{id}</a> ee {subjectemail}"
COM_PRIVACY_ACTION_LOG_ADMIN_CREATED_REQUEST="Isticmaalaha <a href='{accountlink}'>{username}</a> ayaa abuuray <a href='{itemlink}'>codsiga #{id}</a> ee {subjectemail}"
COM_PRIVACY_ACTION_LOG_ADMIN_INVALIDATED_REQUEST="Isticmaalaha <a href='{accountlink}'>{username}</a> ayaa buriyay <a href='{itemlink}'>codsiga #{id}</a> ee {subjectemail}"
COM_PRIVACY_ACTION_LOG_CONFIRMED_REQUEST="{subjectemail} ayaa xaqiijiyay <a href='{itemlink}'>codsiga #{id}</a>"
COM_PRIVACY_ACTION_LOG_CREATED_REQUEST="{subjectemail} ayaa soo gudbiyay <a href='{itemlink}'>codsiga #{id}</a>"
COM_PRIVACY_ACTION_LOG_EXPORT="Isticmaalaha <a href='{accountlink}'>{username}</a> ayaa ka dhoofiyay xogta <a href='{itemlink}'>codsiga #{id}</a>"
COM_PRIVACY_ACTION_LOG_EXPORT_EMAILED="Isticmaalaha <a href='{accountlink}'>{username}</a> ayaa email u diray dhoofinta xogta ee <a href='{itemlink}'>codsiga #{id}</a> si uu ugu gaadho helaha"
COM_PRIVACY_ACTION_LOG_REMOVE="Isticmaalaha <a href='{accountlink}'>{username}</a> ayaa ka saaray xogta <a href='{itemlink}'>codsiga #{id}</a>"
COM_PRIVACY_ACTION_LOG_REMOVE_BLOCKED="Isticmaalaha <a href='{accountlink}'>{username}</a> ayaa isku dayay inuu ka saaro xogta <a href='{itemlink}'>codsiga #{id}</a> laakiin tallaabadan waa la horjoogsaday"
COM_PRIVACY_ACTION_VIEW="Eeg Codsiga"
COM_PRIVACY_BADGE_URGENT_REQUEST="Degdeg ah"
COM_PRIVACY_CONFIGURATION="Asturnaanta: Xulashooyinka"
COM_PRIVACY_CONSENTS_EMPTYSTATE_CONTENT="Shaashaddan waxa muujiya dhammaan Asturnaanta: Oggolaanshaha la siiyay. Waxaad sidoo kale ku burin kartaa ansixin halkan."
COM_PRIVACY_CONSENTS_EMPTYSTATE_TITLE="Oggolaansho lama siin weli."
COM_PRIVACY_CONSENTS_FILTER_STATE="Xaaladda Oggolaanshaha"
COM_PRIVACY_CONSENTS_FILTER_SUBJECT="Mawduuca"
COM_PRIVACY_CONSENTS_INVALIDATED_ALL="Dhammaan oggolaanshaha mawduucan waa la buriyay."
COM_PRIVACY_CONSENTS_STATE_INVALIDATED="Oggolaanshaha la buriyay"
COM_PRIVACY_CONSENTS_STATE_OBSOLETE="Oggolaanshaha aan sax ahayn"
COM_PRIVACY_CONSENTS_STATE_VALID="Oggolaansho Waara"
COM_PRIVACY_CONSENTS_SUBJECT_DEFAULT="Dhammaan Mawduucyada"
COM_PRIVACY_CONSENTS_TOOLBAR_INVALIDATE="Wax-Ka-Noqoshada Ogolaanshaha"
COM_PRIVACY_CONSENTS_TOOLBAR_INVALIDATE_ALL="Wax-Ka-Noqoshada Ogolaanshaha oo dhan"
COM_PRIVACY_CONSENTS_TOOLBAR_INVALIDATE_ALL_CONFIRM_MSG="Ma doonaysaa inaad dhab ahaan ka noqoto dhammaan ogolaanshada mawduuca la doortay? Tani waxay isticmaala deysanaysaa inay markale bixiyaan ogolaanshahooda."
COM_PRIVACY_CONSENTS_TOOLBAR_INVALIDATE_CONFIRM_MSG="Ma doonaysaa inaad dhab ahaan ka noqoto ogolaanshaha la doortay? Tani waxay isticmaala deysanaysaa inay markale bixiyaan ogolaanshahooda."
COM_PRIVACY_CORE_CAPABILITY_COMMUNICATION_WITH_JOOMLA_ORG="Marka xiriir shabakad la heli karo, rakibaada Joomla waxay isku dayi doontaa inay la xiriirto seerfarada joomla.org ee awoodo kala duwan, si ay ugu jirto:<ul><li>Hubinta cusboonaysiinta codsiga Joomla</li><li>Shaashadaha caawinta ee kordhinaya Joomla aasaasiga ah</li><li>Adeegga Rakibaada shabakad ka ah (ikhtiyaari)</li><li>Seerfarada ururinta istatistikada (ikhtiyaari)</li></ul>Sida dhammaan codsiyada HTTP, ciwaanka IP ee seerfaradaada waxaa lagu gudbin doonaa codsiga qeybtiisa. Wixii macluumaad ah ee ku saabsan sida Joomla u farsameyso xogta seerfaradiisa, fadlan eeg <a href=\"https://www.joomla.org/privacy-policy.html\" target=\"_blank\" rel=\"noopener noreferrer\">shuruucda gaarka ah</a>."
COM_PRIVACY_CORE_CAPABILITY_LOGGING_IP_ADDRESS="Nidaamka diiwaangelinta ee Joomla wuxuu diiwaangeliyaa ciwaanka IP ee booqdaha kaasoo keena in fariin loo diiwaangaliyo faylasha diiwaanka. Faylasha diiwaanka waxaa loo isticmaalaa in lagu diiwaangeliyo hawlaha kala duwan ee goobta Joomla, oo ay ku jiraan macluumaadka ku saabsan cusboonaysiinta aasaasiga ah, isku dayada galitaanka khaldan, khaladaad la maareyn karin, iyo macluumaadka horumarinta sida adeegsiga APIs horey loo isticmaalay. Qaabka faylasha diiwaanka waxaa la habeyn karaa kordhinta kasta oo yaqaan logger, sidaas darteed waxaa lagu dhiirrigelinayaa inaad soo dejiso oo dib u eegto faylasha diiwaanka ee boggaaga internetka oo laga heli karo `%s`."
COM_PRIVACY_CORE_CAPABILITY_SESSION_IP_ADDRESS_AND_COOKIE="Dhammaan codsiyada websaytk Joomla waxay bilaabaan fadhiyo oo kaydiya ciwaanka IP ee xogta fadhiga waxayna abuuraan kuki-fadhiye dhinaca daalacashada isticmaale. Ciwaanka IP waxaa loo isticmaalaa tallaabo amni ahaan si ay ka caawiso in laga ilaaliyo weeraryada dhacdada fadhiga suurtogalka ah tanina waxay tirtirantaa marka fadhigu ku dhammaado xogtiisii la nadiifiyo. Magaca kukika fadhiga waxaa laga sameeyey hash si aan kala sooc lahayn loo abuuro sidaas darteed ma laha aqoonsi joogto ah. Kuki fadhigeed waa la baabi'inayaa marka fadhiga dhaco ama isticmaaluhu ka baxo daalacashadooda."
COM_PRIVACY_DASHBOARD_BADGE_ACTIVE_REQUESTS_0="<span class=\"badge bg-info\">0</span> Codsiyada Firfircoon"
COM_PRIVACY_DASHBOARD_BADGE_ACTIVE_REQUESTS_1="<span class=\"badge bg-warning\">1</span> Codsi Firfircoon"
COM_PRIVACY_DASHBOARD_BADGE_ACTIVE_REQUESTS_MORE="<span class=\"badge bg-warning\">%d</span> Codsiyada Firfircoon"
COM_PRIVACY_DASHBOARD_BADGE_TOTAL_REQUESTS_0="<span class=\"badge bg-info\">0</span> Dhammaan Codsiyada"
COM_PRIVACY_DASHBOARD_BADGE_TOTAL_REQUESTS_1="<span class=\"badge bg-info\">1</span> Dhammaan Codsiga"
COM_PRIVACY_DASHBOARD_BADGE_TOTAL_REQUESTS_MORE="<span class=\"badge bg-info\">%d</span> Dhammaan Codsiyada"
COM_PRIVACY_DASHBOARD_HEADING_CHECK="Hubi"
COM_PRIVACY_DASHBOARD_HEADING_REQUEST_COUNT="# ee Codsiyada"
COM_PRIVACY_DASHBOARD_HEADING_REQUEST_STATUS="Xaalad"
COM_PRIVACY_DASHBOARD_HEADING_REQUEST_TYPE="Nooca Codsiga"
COM_PRIVACY_DASHBOARD_HEADING_STATUS="Xaaladda"
COM_PRIVACY_DASHBOARD_HEADING_STATUS_CHECK="Hubinta Xaaladda"
COM_PRIVACY_DASHBOARD_HEADING_TOTAL_REQUEST_COUNT="Tirada Codsiyada Wadarta Guud"
COM_PRIVACY_DASHBOARD_NO_REQUESTS="Ma jiraan wax codsiyo ah."
COM_PRIVACY_DASHBOARD_TITLE="Dashboardka Asturnaanta"
COM_PRIVACY_DASHBOARD_VIEW_REQUESTS="Daawo Codsiyada"
COM_PRIVACY_DATA_REMOVED="Xog la saaray"
COM_PRIVACY_EDIT_PRIVACY_CONSENT_PLUGIN="Wax ka beddelka Ogolaanshaha Asturnaanta Plugin"
COM_PRIVACY_EDIT_PRIVACY_POLICY="Wax ka beddel Siyaasadda Qarsoodiga"
COM_PRIVACY_EMAIL_ADMIN_REQUEST_BODY_EXPORT_REQUEST="Maamule u ah {URL} ayaa sameeyay codsi lagu dhoofinayo macluumaadka isku xiraya cinwaankan iimaylka. Si loo hubiyo nabadgelyada, waa inaad xaqiijisaa in tani ay tahay codsi ansax ah oo ku saabsan macluumaadkaaga shakhsiyeed ee ka yimid boggan.\n\nHaddii tani ahayd qalad, iska dhaaf iimaylkan waxna ma dhici doonaan.\n\nSi aad ugu xaqiijiso codsigan, waxaad dhamaystiri kartaa mid ka mid ah hawlahan soo socda:\n\n1. Booqo URL-ka soo socda: {TOKENURL}\n\n2. Koobi token-kaaga iimaylkan, booqo URL-ka loo tilmaamay, oo dhaji token-kaaga foomka.\nURL: {FORMURL}\nToken: {TOKEN}\n\nFiiro gaar ah u yeelo in token-kan uu ansax yahay oo keliya 24 saacadood laga bilaabo markii iimaylkan la diray."
COM_PRIVACY_EMAIL_ADMIN_REQUEST_BODY_REMOVE_REQUEST="Maamule u ah {URL} ayaa sameeyay codsi lagu saarayo dhammaan macluumaadka shakhsiyeed ee ku xiriira cinwaankan iimaylka. Si loo hubiyo nabadgelyada, waa inaad xaqiijisaa in tani ay tahay codsi ansax ah oo ku saabsan macluumaadkaaga shakhsiyeed in laga tirtiro boggan.\n\nHaddii tani ahayd qalad, iska dhaaf iimaylkan waxna ma dhici doonaan.\n\nSi aad ugu xaqiijiso codsigan, waxaad dhamaystiri kartaa mid ka mid ah hawlahan soo socda:\n\n1. Booqo URL-ka soo socda: {TOKENURL}\n\n2. Koobi token-kaaga iimaylkan, booqo URL-ka loo tilmaamay, oo dhaji token-kaaga foomka.\nURL: {FORMURL}\nToken: {TOKEN}\n\nFiiro gaar ah u yeelo in token-kan uu ansax yahay oo keliya 24 saacadood laga bilaabo markii iimaylkan la diray."
COM_PRIVACY_EMAIL_ADMIN_REQUEST_SUBJECT_EXPORT_REQUEST="Codsi Xog Guud oo la sameeyay at {SITENAME}"
COM_PRIVACY_EMAIL_ADMIN_REQUEST_SUBJECT_REMOVE_REQUEST="Codsi Tirtiris Xog ah oo la sameeyay at {SITENAME}"
COM_PRIVACY_EMAIL_DATA_EXPORT_COMPLETED_BODY="Maamule u ah {URL} ayaa dhamaystiray dhoofinta xogta aad codsatay, koobi macluumaadka lagu helayaa waxaa laga helayaa faylka ku lifaaqan farriintan."
COM_PRIVACY_EMAIL_DATA_EXPORT_COMPLETED_SUBJECT="Dhoofinta Xogta ee {SITENAME}"
COM_PRIVACY_ERROR_ACTIVE_REQUEST_FOR_EMAIL="Waxaa jira codsi xog firfircoon oo horay loogu sameeyay cinwaankan iimaylka, codsiga firfircoon waa in la qabtaa ka hor inta aan la bilaabin mid cusub."
COM_PRIVACY_ERROR_CANNOT_CREATE_REQUEST_FOR_SELF="Ma abuuri kartid codsi xog u gaar ah naftaada."
COM_PRIVACY_ERROR_CANNOT_CREATE_REQUEST_WHEN_SENDMAIL_DISABLED="Codsiyada xogta lama abuuri karo marka dirida iimaylka la joojiyo."
COM_PRIVACY_ERROR_CANNOT_EXPORT_UNCONFIRMED_REQUEST="Xogta codsi aan la xaqiijin ma la dhoofin karo."
COM_PRIVACY_ERROR_CANNOT_REMOVE_DATA="Xogta codsigan lama saari karo."
COM_PRIVACY_ERROR_CANNOT_REMOVE_UNCONFIRMED_REQUEST="Xogta codsi aan la xaqiijin ma la saari karo."
COM_PRIVACY_ERROR_COMPLETE_TRANSITION_NOT_PERMITTED="Rikoodhkani lagu cusboonaysiin karo xaaladda \"La dhameeyay\"."
COM_PRIVACY_ERROR_EXPORT_EMAIL_FAILED="Dhoofintu way guuldarreysatay iyadoo lagu qaldan yahay khaladka soo socda: %s"
COM_PRIVACY_ERROR_INVALID_TRANSITION_NOT_PERMITTED="Rikoodhkani lagu cusboonaysiin karo xaaladda \"Aan ansax ahayn\"."
COM_PRIVACY_ERROR_REMOVE_DATA_FAILED="Ka saaristu way guuldarreysatay iyadoo lagu qaldan yahay khaladka soo socda: %s"
COM_PRIVACY_ERROR_REQUEST_ID_REQUIRED_FOR_EXPORT="Aqoonsiga codsiga ayaa loo baahan yahay si loo dhoofiyo xogta."
COM_PRIVACY_ERROR_REQUEST_ID_REQUIRED_FOR_REMOVE="Aqoonsiga codsiga ayaa loo baahan yahay si loogu saaro xogta."
COM_PRIVACY_ERROR_REQUEST_TYPE_NOT_EXPORT="Kaliya codsiyada dhoofinta ayaa la dhoofin karaa."
COM_PRIVACY_ERROR_REQUEST_TYPE_NOT_REMOVE="Kaliya codsiyada saarka ayaa xogtooda laga saari karaa."
COM_PRIVACY_ERROR_UNKNOWN_REQUEST_TYPE="Noocka codsiga xog aan la aqoon ahayn."
COM_PRIVACY_EXPORT_EMAILED="Xogta la dhoofiyay waa la soo diray iimayl ahaan."
COM_PRIVACY_EXTENSION_CAPABILITY_PERSONAL_INFO="Si loo qabto codsiyada xogta, macluumaadka ku saabsan isticmaalaha waa in la ururiyaa lana diiwaangeliyaa ujeeddooyinka kaydinta raadraaca. Nidaamka codsiga waxaa lagu saleyn doonaa cinwaanka iimaylka shakhsi kaas oo loo isticmaali doono in lagu xidho codsiga isticmaale jira oo ku yaal goobta haddii la awoodo."
COM_PRIVACY_FIELD_REQUESTED_AT_LABEL="Taariikhda la Codsaday"
COM_PRIVACY_FIELD_REQUEST_TYPE_LABEL="Nooca Codsiga"
COM_PRIVACY_FIELD_STATUS_LABEL="Xaaladda Codsiga"
COM_PRIVACY_FILTER_SEARCH_LABEL="Raadi Codsiyada"
COM_PRIVACY_HEADING_ACTIONS="Tallaabooyinka"
COM_PRIVACY_HEADING_ACTION_LOG="Diiwaanka Tallaabooyinka"
COM_PRIVACY_HEADING_CONSENTS_BODY="Jirka"
COM_PRIVACY_HEADING_CONSENTS_CREATED="Ogolaaday"
COM_PRIVACY_HEADING_CONSENTS_SUBJECT="Mawduuca"
COM_PRIVACY_HEADING_CORE_CAPABILITIES="Awoodaha Asalka Joomla"
COM_PRIVACY_HEADING_CREATED_ASC="Ogolaaday kor u kaca"
COM_PRIVACY_HEADING_CREATED_DESC="Ogolaaday hoos u dhac"
COM_PRIVACY_HEADING_EMAIL_ASC="Email kor u kaca"
COM_PRIVACY_HEADING_EMAIL_DESC="Email hoos u dhac"
COM_PRIVACY_HEADING_NAME="Magaca"
COM_PRIVACY_HEADING_REQUESTED_AT="La codsaday"
COM_PRIVACY_HEADING_REQUESTED_AT_ASC="La codsaday kor u kaca"
COM_PRIVACY_HEADING_REQUESTED_AT_DESC="La codsaday hoos u dhac"
COM_PRIVACY_HEADING_REQUEST_INFORMATION="Macluumaadka Codsiga"
COM_PRIVACY_HEADING_REQUEST_TYPE="Nooca Codsiga"
COM_PRIVACY_HEADING_REQUEST_TYPE_ASC="Nooca Codsiga kor u kaca"
COM_PRIVACY_HEADING_REQUEST_TYPE_DESC="Nooca Codsiga hoos u dhac"
COM_PRIVACY_HEADING_REQUEST_TYPE_TYPE_EXPORT="Dhoofinta"
COM_PRIVACY_HEADING_REQUEST_TYPE_TYPE_REMOVE="Ka saarid"
COM_PRIVACY_HEADING_STATUS_ASC="Xaalad kor u kaca"
COM_PRIVACY_HEADING_STATUS_DESC="Xaalad hoos u dhac"
COM_PRIVACY_HEADING_SUBJECT_ASC="Mowduuc kor u socota"
COM_PRIVACY_HEADING_SUBJECT_DESC="Mowduuc hoos u socota"
COM_PRIVACY_HEADING_USERID="Aqoonsiga Isticmaalaha"
COM_PRIVACY_HEADING_USERID_ASC="Aqoonsiga Isticmaalaha kor u socota"
COM_PRIVACY_HEADING_USERID_DESC="Aqoonsiga Isticmaalaha hoos u socota"
COM_PRIVACY_HEADING_USERNAME_ASC="Magaca Isticmaalaha kor u socota"
COM_PRIVACY_HEADING_USERNAME_DESC="Magaca Isticmaalaha hoos u socota"
COM_PRIVACY_MAIL_NOTIFICATION_ADMIN_EXPORT_DESC="Mail si ay ugu wargeliyaan isticmaalaha in codsi lagu dhoofiyo xogta ka timid mareegtan uu abuuray maamulaha"
COM_PRIVACY_MAIL_NOTIFICATION_ADMIN_EXPORT_TITLE="Arimaha Gaarka ah: Dalbo Dhoofinta Xogta (Maamul)"
COM_PRIVACY_MAIL_NOTIFICATION_ADMIN_REMOVE_DESC="Mail si ay ugu wargeliyaan isticmaalaha in codsi xogta looga saaro mareegtan uu abuuray maamulaha"
COM_PRIVACY_MAIL_NOTIFICATION_ADMIN_REMOVE_TITLE="Arimaha Gaarka ah: Dalbo Ka saarida Xogta (Maamul)"
COM_PRIVACY_MAIL_NOTIFICATION_EXPORT_DESC="Mail si loo xaqiijiyo in xogta isticmaalaha laga dhoofiyo mareegta"
COM_PRIVACY_MAIL_NOTIFICATION_EXPORT_TITLE="Arimaha Gaarka ah: Dalbo Dhoofinta Xogta"
COM_PRIVACY_MAIL_NOTIFICATION_REMOVE_DESC="Mail si loo xaqiijiyo in xogta isticmaalaha laga saaro mareegta"
COM_PRIVACY_MAIL_NOTIFICATION_REMOVE_TITLE="Arimaha Gaarka ah: Dalbo Ka saarida Xogta"
COM_PRIVACY_MAIL_USERDATAEXPORT_DESC="Mail oo wata dhoofinta xogta isticmaalaha"
COM_PRIVACY_MAIL_USERDATAEXPORT_TITLE="Arimaha Gaarka ah: Dhoofinta Xogta Isticmaalaha"
COM_PRIVACY_MSG_CAPABILITIES_ABOUT_THIS_INFORMATION="Ku saabsan Macluumaadkan"
COM_PRIVACY_MSG_CAPABILITIES_INTRODUCTION="Macluumaadka shaashaddan waxaa laga soo ururiyey kordhinta kuwaas oo soo sheegaya awoodahooda la xiriira asturnaanta nidaamkan. Waxaa loogu talagalay in ay ku caawiso mulkiilayaasha goobaha in ay ka warqabaan awoodaha kordhinta lagu rakibay oo ay bixiyaan macluumaad si ay uga caawiyaan mulkiilaha abuurista siyaasad maqaal oo maxalli ah sida siyaasadda asturnaanta. Maadaama shaashaddan ay u baahan tahay kordhinta si ay u taageerto nidaamka soo sheegida, kuna soo bandhigto kaliya macluumaadka kordhinta furan, tani waa in aan loo tixgelin liis dhammaystiran oo lagugu dhiirrigeliyaa inaad la tashato dukumenti kasta kordhintiisa si aad u hesho macluumaad dheeraad ah."
COM_PRIVACY_MSG_CAPABILITIES_NO_CAPABILITIES="Ma jiraan awood kordhin ah oo la sheegay."
COM_PRIVACY_MSG_CONFIRM_EMAIL_SENT_TO_USER="E-mail xaqiijin ah oo ku saabsan codsigaan ayaa loo diray isticmaalaha."
COM_PRIVACY_MSG_EXTENSION_NO_CAPABILITIES="Kordhintaan ma soo sheegin wax awood ah."
COM_PRIVACY_NOTIFY_DESC="Soo bandhig ogeysiis marka ay jiraan codsiyo ka weynaaday tirada maalmaha la cayimay."
COM_PRIVACY_NOTIFY_LABEL="Maalmaha Loo Tixgeliyo Codsiga Degdegga ah"
COM_PRIVACY_N_CONSENTS_INVALIDATED="%d ogolaanshiyo ayaa la dhaqan-geliyay."
COM_PRIVACY_N_CONSENTS_INVALIDATED_1="Oggolaanshaha waa la awoodsiiyey."
COM_PRIVACY_OPTION_LABEL="Ikhtiyaarrada"
COM_PRIVACY_POSTINSTALL_BODY="<p>Wixii la xiriira soo bandhigidda GDPR ee muwaadiniinta EU iyo xeerar la mid ah meelaha kale ee adduunka waxaa laga yaabaa inay lama huraan tahay inaad codsato oggolaansho ka hor inta aan la kaydin wax kasta oo <strong>Macluumaadka Shaqsiga ah</strong> ee isticmaalaha.</p><p>Joomla 3.9 waxay soo bandhigaysaa kartiyo cusub si ay kaa caawiyaan inaad abuurto siyaasad sirta ah oo goobta ah oo aad ururiso oggolaanshaha isticmaalaha. Intaa waxaa dheer, nidaam hawshu waa diyaar si ay kuu caawiso inaad maamusho codsiyada macluumaadka isticmaale sida codsiyada saaridda xogtooda shakhsiyeed ee boggaaga.</p><p>Wixii macluumaad dheeraad ah ee ku saabsan astaantan cusub akhri <a href='https://docs.joomla.org/Special:MyLanguage/J3.x:Privacy' target='_blank' rel='noopener noreferrer'>Dukumentiga Sirta</a>.</p>"
COM_PRIVACY_POSTINSTALL_TITLE="Maamulka Kordhinta Sirtu ee Isticmaalayaasha"
COM_PRIVACY_REQUESTS_EMPTYSTATE_BUTTON_ADD="Kudar codsigaaga ugu horeeya"
COM_PRIVACY_REQUESTS_EMPTYSTATE_CONTENT="Shaashadani waxay soo bandhigaysaa dhammaan Sirta: Codsiyada Macluumaadka ee la helay iyo xaaladaheeda. Waxaad sidoo kale abuuri kartaa codsi cusub halkan."
COM_PRIVACY_REQUESTS_EMPTYSTATE_TITLE="Wali lama soo gudbin wax Codsi Macluumaad ah."
COM_PRIVACY_REQUEST_COMPLETED="Codsiga waa la dhameystiray."
COM_PRIVACY_REQUEST_FORM_EDIT="Tafatir Codsiga"
COM_PRIVACY_REQUEST_FORM_NEW="Codsi Cusub"
COM_PRIVACY_REQUEST_INVALIDATED="Codsiga waa la awoodsiiyey."
COM_PRIVACY_SEARCH_IN_EMAIL="Raadi cinwaanka emailka ee codsadayaasha. Ku horreeyaan ID: si aad u raadsato ID-ga codsiga."
COM_PRIVACY_SEARCH_IN_USERNAME="Raadi magaca isticmaale. Ku horreeyaan Name: si aad u raadsato magac. Ku horreeyaan ID: si aad u raadsato oggolaanshaha ID. Ku horreeyaan UID: si aad u raadsato ID isticmaalaha."
COM_PRIVACY_SELECT_REQUEST_TYPE="- Dooran Nooca Codsiga -"
COM_PRIVACY_SHOW_URGENT_REQUESTS="Tus Codsiyada Degdega ah"
COM_PRIVACY_STATUS_CHECK_NOT_AVAILABLE="Lama Helin"
COM_PRIVACY_STATUS_CHECK_OUTSTANDING_URGENT_REQUESTS="Codsiyada Degdegga ah ee Muhiimka ah"
COM_PRIVACY_STATUS_CHECK_OUTSTANDING_URGENT_REQUESTS_DESCRIPTION="Codsiyada oo ka weyn %d maalmood, sida lagu dejiyay qaabeynta qaybta."
COM_PRIVACY_STATUS_CHECK_PRIVACY_POLICY_PUBLISHED="Xeerka Sirta oo La daabacay"
COM_PRIVACY_STATUS_CHECK_REQUEST_FORM_MENU_ITEM_PUBLISHED="Qalabka Codsiga Foomka Menu oo La daabacay"
COM_PRIVACY_STATUS_CHECK_SENDMAIL_DISABLED="Diridda Emailka waa La Curyaamiyay"
COM_PRIVACY_STATUS_CHECK_SENDMAIL_DISABLED_DESCRIPTION="Diridda Emailka waa in la awoodsiiyaa, waa shuruudo lagu xiro nidaamka codsiga"
COM_PRIVACY_STATUS_CHECK_SENDMAIL_ENABLED="Diridda Emailka La Awoodsiiyay"
COM_PRIVACY_STATUS_COMPLETED="La dhameystiray"
COM_PRIVACY_STATUS_CONFIRMED="La xaqiijiyay"
COM_PRIVACY_STATUS_INVALID="Sharcidarro"
COM_PRIVACY_STATUS_PENDING="Sugaya"
COM_PRIVACY_TABLE_CAPTION="Codsiyada Qarsoodiga"
COM_PRIVACY_TABLE_CONSENTS_CAPTION="Oggolaanshaha Qarsoodiga"
COM_PRIVACY_TOOLBAR_COMPLETE="Dhameystiran"
COM_PRIVACY_TOOLBAR_INVALIDATE="Maqal"
COM_PRIVACY_USER_FIELD_EMAIL_DESC="Cinwaanka iimaylka ee shakhsiga leh macluumaadka la doonayo."
COM_PRIVACY_VIEW_CAPABILITIES="Qarsoodi: Awoodaha Balaarinta"
COM_PRIVACY_VIEW_CONSENTS="Qarsoodi: Oggolaanshah"
COM_PRIVACY_VIEW_DASHBOARD="Qarsoodi: Guddi"
COM_PRIVACY_VIEW_REQUESTS="Qarsoodi: Codsiyada Macluumaadka"
COM_PRIVACY_VIEW_REQUEST_ADD_REQUEST="Qarsoodi: Codsi Macluumaad Cusub"
COM_PRIVACY_VIEW_REQUEST_SHOW_REQUEST="Qarsoodi: Eeg Codsi Macluumaad"
COM_PRIVACY_WARNING_CANNOT_CREATE_REQUEST_WHEN_SENDMAIL_DISABLED="Codsiyada macluumaadka lama abuuri karo marka diridda iimaylka la naafo."
COM_PRIVACY_XML_DESCRIPTION="Qayb ka caawisa maaraynta hawlaha la xiriira qarsoodiga."

