; Joomla! Project
; (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_SCHEDULER="Hawlaha La Qorsheeyay"
COM_SCHEDULER_ERROR_FORBIDDEN_JUMP_TO_ADD_VIEW="Waa inaad doorataa Nooca Hawsha marka hore."
COM_SCHEDULER_ERROR_INVALID_TASK_TYPE="Nooca Hawsha Waa Khalad"
COM_SCHEDULER_MANAGER_TASK="Maareeyaha Hawsha"
COM_SCHEDULER_MANAGER_TASK_EDIT="Sax Hawsha"
COM_SCHEDULER_MANAGER_TASK_NEW="Hawsha Cusub"
COM_SCHEDULER_MANAGER_TASKS="Maareeyaha Hawlaha"
COM_SCHEDULER_MSG_MANAGE_NO_TASK_PLUGINS="Ma jiraan noocyo hawlo oo ku habboon su'aalahaaga."
COM_SCHEDULER_TASKS_VIEW_DEFAULT_DESC="Qorshee oo Maaree Hawlaha Caadiga ah."
COM_SCHEDULER_TASKS_VIEW_DEFAULT_TITLE="Hawlaha La Qorsheeyay"
COM_SCHEDULER_XML_DESCRIPTION="Qayb ka mid ah maareynta hawlaha la qorsheeyay iyo shaqooyinka cronkaha (haddii serverka uu taageero)."

