; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_CHECKIN="Diyaarso"
COM_CHECKIN_CONFIGURATION="Diyaarso: Xulashooyinka"
COM_CHECKIN_DATABASE_TABLE="Jadwalka Macluumaadka"
COM_CHECKIN_DATABASE_TABLE_ASC="Jadwalka Macluumaadka kor u kaca"
COM_CHECKIN_DATABASE_TABLE_DESC="Jadwalka Macluumaadka hoos u kaca"
COM_CHECKIN_EMPTYSTATE_CONTENT="Ma jiraan wax jadwal ah oo leh walxo la hubiyay."
COM_CHECKIN_FILTER_SEARCH_DESC="Raadi jadwalka macluumaadka leh walxo la hubin karo."
COM_CHECKIN_FILTER_SEARCH_LABEL="Raadi Jadwalada Macluumaadka"
COM_CHECKIN_GLOBAL_CHECK_IN="Dayactir: Diyaarso Guud"
COM_CHECKIN_ITEMS_TO_CHECK_IN="Walxaha la diyaarinayo"
COM_CHECKIN_ITEMS_TO_CHECK_IN_ASC="Walxaha la diyaarinayo kor u kaca"
COM_CHECKIN_ITEMS_TO_CHECK_IN_DESC="Walxaha la diyaarinayo hoos u kaca"
COM_CHECKIN_N_ITEMS_CHECKED_IN_1="Walax ayaa la diyaariyay."
COM_CHECKIN_N_ITEMS_CHECKED_IN_MORE="%d walxo ayaa la diyaariyay."
COM_CHECKIN_N_QUICKICON_SRONLY="Diyaarinta Guud: %d jadwal ayaa leh walxo xiran."
COM_CHECKIN_N_QUICKICON_SRONLY_0="Diyaarinta Guud: Ma jiraan jadwal leh walxo xiran."
COM_CHECKIN_N_QUICKICON_SRONLY_1="Diyaarinta Guud: Jadwalka hal waxaa ku jira walxo xiran."
COM_CHECKIN_NO_ITEMS="Ma jiraan wax jadwal ah oo leh walxo la hubiyay ama ma jiraan wax jadwal ah oo leh walxo la hubiyay oo ku habboon raadintaada."
COM_CHECKIN_TABLE="<em>%s</em> jadwal"
COM_CHECKIN_TABLE_CAPTION="Walaxyo la hubiyay"
COM_CHECKIN_XML_DESCRIPTION="Qeybta Diyaarinta."

JLIB_RULES_SETTING_NOTES_COM_CHECKIN="Isbedeladu waxay khuseeyaan kaliya qaybtaan.<br><em><strong>Wax-ka-dhaxla</strong></em> - goobta Qaabeynta Global ama heer sare ayaa lagu dabaqayaa.<br><em><strong>Diidmo</strong></em> mar walba guuleysata - wax kasta oo lagu dejiyo heerka guud ama heerka sare waxayna khuseeysaa dhammaan walxaha caruurta.<br><em><strong>La ogolyahay</strong></em> waxay u oggolaan doontaa ficilka qaybtaan illaa ama lagu gacan-sareeyo goobta Qaabeynta Global."

