; Joomla! Project
; (C) 2013 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_POSTINSTALL="Fariimaha Kadib Rakibitaanka"
COM_POSTINSTALL_BTN_ARCHIVE="Keyd"
COM_POSTINSTALL_BTN_HIDE="Qari fariintan"
COM_POSTINSTALL_BTN_REPUBLISH="Akhriso Mar Kale"
COM_POSTINSTALL_CONFIGURATION="Fariimaha Kadib Rakibitaanka: Xulashooyinka"
COM_POSTINSTALL_EMPTYSTATE_BUTTON_ADD="Dejinta Fariimaha Mar Kale"
COM_POSTINSTALL_EMPTYSTATE_CONTENT="Waxaad akhriday dhammaan fariimaha."
COM_POSTINSTALL_EMPTYSTATE_TITLE="Fariimaha Kadib Rakibitaanka iyo Cusbooneysiinta"
COM_POSTINSTALL_HIDE_ALL_MESSAGES="Qari dhammaan Fariimaha"
COM_POSTINSTALL_LBL_SINCEVERSION="Laga bilaabo nooca %s"
COM_POSTINSTALL_MESSAGES_FOR="Tusaya fariimaha loogu talagalay"
COM_POSTINSTALL_MESSAGES_TITLE="Fariimaha Kadib Rakibitaanka ee %s"
COM_POSTINSTALL_XML_DESCRIPTION="Muujiya fariimaha kadib rakibida iyo kadib cusbooneysiinta ee Joomla iyo fidintiisa."

