; Joomla! Project
; (C) 2019 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_MAILS="Qaab-Dhismeedka Boostada"
COM_MAILS_CONFIG_FIELD_ALTERNATIVE_MAILCONFIG_LABEL="Goobaha Boostada ee Template kasta"
COM_MAILS_CONFIG_FIELD_ATTACHMENT_FOLDER_DESC="Bixi waddo qaraabo ah laga bilaabo xididka rakibaaddaada ilaa galka ku jira faylasha aad rabto inaad ku darto boostada. Haddii la banneeyo markaas ikhtiyaarka lifaaqa lama heli doono gudaha template-ka boostada."
COM_MAILS_CONFIG_FIELD_ATTACHMENT_FOLDER_LABEL="Folderka Lifaaqyada"
COM_MAILS_CONFIG_FIELD_COPY_MAILS_LABEL="Nuqul Dir"
COM_MAILS_CONFIG_MAIL_OPTIONS="Boostada"
COM_MAILS_CONFIGURATION="Qaab-Dhismeedka Boostada: Ikhtiyaarada"
COM_MAILS_ERROR_UNHELD_ID="Laguma oggola inaad isticmaasho isku xirkaas si aad si toos ah ugu gasho boggaas (Template: %s)."
COM_MAILS_FIELD_ALTERNATIVE_MAILCONFIG_LABEL="Goobaha Boostada"
COM_MAILS_FIELD_ATTACHMENTS_LABEL="Lifaaqyada"
COM_MAILS_FIELD_BASIC_LABEL="Ikhtiyaarada"
COM_MAILS_FIELD_BODY_LABEL="Jirka"
COM_MAILS_FIELD_FILE_LABEL="Faylka"
COM_MAILS_FIELD_FILENAME_LABEL="Magaca Faylka"
COM_MAILS_FIELD_HTMLBODY_LABEL="Jirka HTML"
COM_MAILS_FIELD_HTML_LAYOUT_LABEL="Qorsheynta"
COM_MAILS_FIELD_HTML_LAYOUT_OFF_LABEL="Qaab-Dhismeedka Template-ka Boostada"
COM_MAILS_FIELD_HTML_LAYOUT_LOGO_OFF_LABEL="Faylka Logo"
COM_MAILS_FIELD_LANGUAGE_CODE_INVALID="Koodhka Luqadda waa khalad"
COM_MAILS_FIELD_MAIL_COPY_MAIL_LABEL="Nuqul ugu dir Email"
COM_MAILS_FIELD_MAIL_FROM_EMAIL_LABEL="Laga Soo Diray Email"
COM_MAILS_FIELD_MAIL_FROM_NAME_LABEL="Laga Soo Diray Magaca"
COM_MAILS_FIELD_MAIL_MAILER_LABEL="Dirayaasha"
COM_MAILS_FIELD_MAIL_REPLY_TO_EMAIL_LABEL="Ku Soo Jawaab Emailka"
COM_MAILS_FIELD_MAIL_REPLY_TO_NAME_LABEL="Ku Soo Jawaab Magaca"
COM_MAILS_FIELD_MAIL_SENDMAIL_PATH_LABEL="Waddada Sendmail"
COM_MAILS_FIELD_MAIL_SMTP_AUTH_LABEL="Aqoonsiga SMTP"
COM_MAILS_FIELD_MAIL_SMTP_HOST_LABEL="SMTP Martigelin"
COM_MAILS_FIELD_MAIL_SMTP_PASSWORD_LABEL="Furaha SMTP"
COM_MAILS_FIELD_MAIL_SMTP_PORT_LABEL="Dekadda SMTP"
COM_MAILS_FIELD_MAIL_SMTP_SECURE_LABEL="Amniga SMTP"
COM_MAILS_FIELD_MAIL_SMTP_USERNAME_LABEL="Magaca Isticmaalaha SMTP"
COM_MAILS_FIELD_MAIL_STYLE_LABEL="Qaabka Mailka"
COM_MAILS_FIELD_OPTION_BOTH="Labada"
COM_MAILS_FIELD_OPTION_HTML="HTML"
COM_MAILS_FIELD_OPTION_PLAINTEXT="Qoraal Cad"
COM_MAILS_FIELD_SUBJECT_LABEL="Cinwaan"
COM_MAILS_FIELD_VALUE_NONE="Maya"
COM_MAILS_FIELD_VALUE_PHP_MAIL="Mailka PHP"
COM_MAILS_FIELD_VALUE_SENDMAIL="Sendmail"
COM_MAILS_FIELD_VALUE_SMTP="SMTP"
COM_MAILS_FIELD_VALUE_SSL="SSL/TLS"
COM_MAILS_FIELD_VALUE_TLS="STARTTLS"
COM_MAILS_FIELDSET_TAGS_LABEL="Gelinta Tags"
COM_MAILS_FILTER_OPTION_SELECT_EXTENSION="- Dooro Kordhin -"
COM_MAILS_FILTER_SEARCH_DESC="Raadi mails. Ku billaaw ID: si aad u baadho ID template."
COM_MAILS_FILTER_SEARCH_LABEL="Raadi Template Mail"
COM_MAILS_HEADING_DESCRIPTION="Sharaxaad"
COM_MAILS_HEADING_EDIT_TEMPLATES="Tafatirka Templates"
COM_MAILS_HEADING_EXTENSION="Kordhinta"
COM_MAILS_FORM_EDIT="Tafatir Qaabka Boostada"
COM_MAILS_MAIL_CONTENT="Boosto"
COM_MAILS_MAILS_TITLE="Hababka Boostada"
COM_MAILS_PAGE_EDIT_MAIL="Tafatir Qaabka Boostada"
COM_MAILS_RESET_TO_DEFAULT_BODY="Soo Celinta Dhammaadka Jirka"
COM_MAILS_RESET_TO_DEFAULT_HTML_BODY="Soo Celinta Jirka HTML ee Dhammaan"
COM_MAILS_RESET_TO_DEFAULT_SUBJECT="Soo Celinta Dhammaadka Mawduuca"
COM_MAILS_SAVE_SUCCESS="Qaab-dhismeedka Boostada waa la keydiyay."
COM_MAILS_TABLE_CAPTION="Hababka Boostada"

