; Joomla! Project
; (C) 2010 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_MESSAGES="Fariimaha"
COM_MESSAGES_ADD="Fariin Gaar Ah Oo Cusub"
COM_MESSAGES_MANAGER="Fariimaha Gaarka ah"
COM_MESSAGES_MESSAGES_VIEW_DEFAULT_DESC="Waxay tusinaysaa liiska dhammaan fariimaha."
COM_MESSAGES_MESSAGES_VIEW_DEFAULT_TITLE="Liiska Dhammaan Fariimaha"
COM_MESSAGES_READ="Akhri Fariimaha Gaarka ah"
COM_MESSAGES_XML_DESCRIPTION="Qayb loogu talagalay taageerada fariimaha gaarka ah ee Backend."

