; Joomla! Project
; (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_GUIDEDTOURS_TOUR_BANNERS_STEP_NEW_TITLE="Doora badhanka 'Cusub'"
COM_GUIDEDTOURS_TOUR_BANNERS_STEP_NEW_DESCRIPTION="Dooro 'Cusub' si aad u abuurto banner cusub."

COM_GUIDEDTOURS_TOUR_BANNERS_STEP_TITLE_TITLE="Kudar cinwaan boostarka"
COM_GUIDEDTOURS_TOUR_BANNERS_STEP_TITLE_DESCRIPTION="Gali cinwaan looga baahan yahay boostarka."

COM_GUIDEDTOURS_TOUR_BANNERS_STEP_ALIAS_TITLE="Geli naanays"
COM_GUIDEDTOURS_TOUR_BANNERS_STEP_ALIAS_DESCRIPTION="Waxaad qori kartaa magaca gudaha ee boorarkan. Waxaad uga tagi kartaa faaruqan waxaana loo isticmaali doonaa qiimo asali ah oo xarfaha hoose ku jiro meel bannaan oo qayb ka ah URL-ka."

COM_GUIDEDTOURS_TOUR_BANNERS_STEP_DETAILS_TITLE="Geli macluumaad faahfaahsan"
COM_GUIDEDTOURS_TOUR_BANNERS_STEP_DETAILS_DESCRIPTION="Halkan ku dar faahfaahinta calaamadda."

COM_GUIDEDTOURS_TOUR_BANNERS_STEP_STATUS_TITLE="Dooro xaalada"
COM_GUIDEDTOURS_TOUR_BANNERS_STEP_STATUS_DESCRIPTION="Dooro xaalada la daabacay ee calanka."

COM_GUIDEDTOURS_TOUR_BANNERS_STEP_CATEGORY_TITLE="Dooro qayb"
COM_GUIDEDTOURS_TOUR_BANNERS_STEP_CATEGORY_DESCRIPTION="Dooro qaybta boorarkan. Sidoo kale waxaad geli kartaa qayb cusub adigoo magaca ku qoraya aagga oo riixaya galaas."

COM_GUIDEDTOURS_TOUR_BANNERS_STEP_PINNED_TITLE="Beddelka ku-dheggan"
COM_GUIDEDTOURS_TOUR_BANNERS_STEP_PINNED_DESCRIPTION="Xulo 'Ku dheggan' si aad mudnaanta u siisid boodhka markii la barbar dhigo kuwa aan ku dhegganayn."

COM_GUIDEDTOURS_TOUR_BANNERS_STEP_VERSIONNOTE_TITLE="Kudar qoraal nooca ah"
COM_GUIDEDTOURS_TOUR_BANNERS_STEP_VERSIONNOTE_DESCRIPTION="Tani waa goob ikhtiyaari ah oo lagu aqoonsanayo nooca heerkan."

COM_GUIDEDTOURS_TOUR_BANNERS_STEP_SAVECLOSE_TITLE="Xulo 'Kaydi oo Xir'"
COM_GUIDEDTOURS_TOUR_BANNERS_STEP_SAVECLOSE_DESCRIPTION="Kaydi oo xir boodhka."

COM_GUIDEDTOURS_TOUR_BANNERS_STEP_CONGRATULATIONS_TITLE="Hambalyo!"
COM_GUIDEDTOURS_TOUR_BANNERS_STEP_CONGRATULATIONS_DESCRIPTION="Waxaad abuurtay banner."

