; Joomla! Project
; (C) 2024 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_GUIDEDTOURS_TOUR_WHATSNEW_5_2_STEP_0_DESCRIPTION="<h3>Joomla 5.2 Warbixinta buuxda ee Soo-saarista</h3><p><a title=\"Qoraallada sii-deynta oo dhan\" href=\"https://www.joomla.org/announcements.html\" target=\"_blank\" rel=\"noopener noreferrer\">Eeg qoraallada sii-deynta oo dhan ee joomla.org</a></p><hr><h3>Caawinta iyo Macluumaadka</h3><p>Halkan waxaa laga heli karaa ilo badan oo kaa caawinaya, oo ay weheliyaan xiriiryo dheeraad ah oo loogu gudbo ilo kale, dukumentiyo, taageero, iyo sida loogu biiri karo Joomla.</p>"
COM_GUIDEDTOURS_TOUR_WHATSNEW_5_2_STEP_0_TITLE="Macluumaad Dheeraad ah iyo Caawimaad"

