; Joomla! Project
; (C) 2024 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_GUIDEDTOURS_TOUR_WELCOMETOJOOMLA_STEP_MENUS_TITLE="Liiska"
COM_GUIDEDTOURS_TOUR_WELCOMETOJOOMLA_STEP_MENUS_DESCRIPTION="<p>Liisku wuxuu helayaa gelitaanka bogagga maamulka Maareeyaha. Qayb kasta waxay leedahay urur ah bogag si loo maamulo dhankaas gaar ahaaneed ee Joomla, sida Maqaallada, Liisaska iyo Isticmaalayaasha.</p><p>Halkani daaqadu waxay la xiriirtaa dashboards gaar ah ee qaybahaas. Liiska Nidaamka laftiisu wuxuu horseedaa dashboards.</p>"

COM_GUIDEDTOURS_TOUR_WELCOMETOJOOMLA_STEP_QUICKACCESS_TITLE="Golayaasha Dashboardka"
COM_GUIDEDTOURS_TOUR_WELCOMETOJOOMLA_STEP_QUICKACCESS_DESCRIPTION="<p>Dashboard-yadu waxay bixiyaan marin deg deg ah oo loogu talagalay bogagga si badanaa loo isticmaalo iyada oo loo marayo calaamadaha.</p><p>Guddi kasta oo dashboardka ah waa module Maamul a oo la beddeli karo iyada oo loo marayo astaanta Dejimaha <span class=\"icon-cogs\" aria-hidden=\"true\"></span>.<br>Tani waxay kuu ogolaanaysaa inaad hagaajiso dashboard-yada boggaaga si ay ula jaanqaadaan danahaaga gaarka ah.</p>"

COM_GUIDEDTOURS_TOUR_WELCOMETOJOOMLA_STEP_NOTIFICATIONS_TITLE="Guddiga Ogeysiisyada"  
COM_GUIDEDTOURS_TOUR_WELCOMETOJOOMLA_STEP_NOTIFICATIONS_DESCRIPTION="<p>Gudiga Ogeysiisyada wuxuu muujinayaa marka la heli karo cusbooneysiinno Joomla iyo kordhiyo kale. Dalabyada Asturnaanta aan weli la bixin ayaa sidoo kale halkan lagu soo bandhigay.</p>"

COM_GUIDEDTOURS_TOUR_WELCOMETOJOOMLA_STEP_TOPBAR_TITLE="Baararka Sare"
COM_GUIDEDTOURS_TOUR_WELCOMETOJOOMLA_STEP_TOPBAR_DESCRIPTION="<p>Baararka sare wuxuu tusinaa cinwaanka bogga la soo bandhigay si aad mar walba u ogaato meesha aad ku sugan tahay. Shayada kale ee ku yaalla baararka sare waa modules ikhtiyaari ah.</p><p>Caadi ahaan nooca cusub ee Joomla iyo gelitaanka dalxiisyada hagida dheeraad ah ayaa halkan laga heli karaa.</p><p>Shayada ugu dambeeya badiyaa waa xiriiriyaasha hore ee Goobta iyo Menu User kaas oo aad ku maamuli karto akoonkaaga oo aad uga bixi karto.</p>"

COM_GUIDEDTOURS_TOUR_WELCOMETOJOOMLA_STEP_FINALWORDS_TITLE="Caawimo iyo Macluumaad"
COM_GUIDEDTOURS_TOUR_WELCOMETOJOOMLA_STEP_FINALWORDS_DESCRIPTION="<p>Halkan waxaad ka heli kartaa ilo badan oo kaa caawin kara, oo ay weheliso xiriirinta dheeraadka ah ee ilaha kale, dukumentiyada, taageerada iyo sida looga qaybqaato Joomla.</p>"

