; Joomla! Project
; (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_GUIDEDTOURS_TOUR_USERS_STEP_NEW_TITLE="Doorta badhanka 'Cusub'"
COM_GUIDEDTOURS_TOUR_USERS_STEP_NEW_DESCRIPTION="Doorta 'Cusub' si aad u abuurto isticmaale cusub."

COM_GUIDEDTOURS_TOUR_USERS_STEP_NAME_TITLE="Ku dar magac"
COM_GUIDEDTOURS_TOUR_USERS_STEP_NAME_DESCRIPTION="Geli magac looga baahan yahay isticmaale."

COM_GUIDEDTOURS_TOUR_USERS_STEP_LOGINNAME_TITLE="Kudar magac galitaan"
COM_GUIDEDTOURS_TOUR_USERS_STEP_LOGINNAME_DESCRIPTION="Gali magac galitaan oo loo baahan yahay oo ah midka isticmaale (magaca adeegsigga)."

COM_GUIDEDTOURS_TOUR_USERS_STEP_PASSWORD_TITLE="Gali eray sir ah"
COM_GUIDEDTOURS_TOUR_USERS_STEP_PASSWORD_DESCRIPTION="Buuxi eray sir ah (cusub). In kasta oo goobtan aan la doonayn, isticmaaluhu ma awoodi doono inuu galo marka aan eray sir ah la dejin."

COM_GUIDEDTOURS_TOUR_USERS_STEP_PASSWORD2_TITLE="Xaqiijinta erayga sirta ah"
COM_GUIDEDTOURS_TOUR_USERS_STEP_PASSWORD2_DESCRIPTION="Mar kale ku buuxi erayga sirta ah goobta kore, si aad u xaqiijiso. Goobtan waa waajib markaad buuxiso goobta erayga sirta cusub."

COM_GUIDEDTOURS_TOUR_USERS_STEP_EMAIL_TITLE="Ku dar cinwaan iimayl"
COM_GUIDEDTOURS_TOUR_USERS_STEP_EMAIL_DESCRIPTION="Geli cinwaan iimaylka isticmaalaha."

COM_GUIDEDTOURS_TOUR_USERS_STEP_SYSTEMEMAIL_TITLE="Beddel helitaanka iimaylada nidaamka"
COM_GUIDEDTOURS_TOUR_USERS_STEP_SYSTEMEMAIL_DESCRIPTION="Deji haa, haddii isticmaalehu u baahan yahay inuu helo iimaylada nidaamka."

COM_GUIDEDTOURS_TOUR_USERS_STEP_STATUS_TITLE="Beddel xaalada"
COM_GUIDEDTOURS_TOUR_USERS_STEP_STATUS_DESCRIPTION="Kartii ama xayir isticmaalkan."

COM_GUIDEDTOURS_TOUR_USERS_STEP_PASSWORDRESET_TITLE="Beddelka furaha ereyada"
COM_GUIDEDTOURS_TOUR_USERS_STEP_PASSWORDRESET_DESCRIPTION="Haddii la dejiyo in haa, isticmaaluhu waa inuu beddelaa furaha ereyada marka xigta ee uu ku soo galo bogga."

COM_GUIDEDTOURS_TOUR_USERS_STEP_SAVECLOSE_TITLE="Dooro 'Keydso oo Xir'"
COM_GUIDEDTOURS_TOUR_USERS_STEP_SAVECLOSE_DESCRIPTION="Keydso oo xir isticmaalaha."

COM_GUIDEDTOURS_TOUR_USERS_STEP_CONGRATULATIONS_TITLE="Hambalyo!"
COM_GUIDEDTOURS_TOUR_USERS_STEP_CONGRATULATIONS_DESCRIPTION="Waxaad abuurtay isticmaale."

