; Joomla! Project
; (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_COUNTER_TITLE="Dooro lambarka tiriyaha tillaabada"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_COUNTER_DESCRIPTION="Dooro lambarka si aad u darto tillaabo. Lambarku wuxuu metelaa tirada tillaabooyinka ilaa hadda loo abuuray socdaalka."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_NEW_TITLE="Dooro badhanka 'Cusub'"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_NEW_DESCRIPTION="Dooro 'Cusub' si aad u abuurto tallaabo cusub."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_TITLE_TITLE="Kudar cinwaan talaabada"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_TITLE_DESCRIPTION="Gali cinwaan loo baahan yahay talaabada. Tani caadi ahaan waa ficil isticmaaluhu uu sameeynayo."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_DESCRIPTION_TITLE="Ku dar sharaxaad tallaabada ah"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_DESCRIPTION_DESCRIPTION="Nuxurku waa inuu siinayaa isticmaalaha sharaxaad ku saabsan tallaabada."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_STATUS_TITLE="Xulo heerka"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_STATUS_DESCRIPTION="Xulo heerka daabac ee talaabada."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_POSITION_TITLE="Dooro booska"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_POSITION_DESCRIPTION="Kani waa booska popup-ka marka la barbardhigo curiyaha aad bartilmaameedsanaysid bogga. 'Bartamaha' waxaa loo isticmaalaa marka aysan jirin bartilmaameed gaar ah."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_TARGET_TITLE="Geli shayga bartilmaameedka"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_TARGET_DESCRIPTION="Kani waa shayga bogga ee talaabadan bartilmaameedsato. Waxay isticmaashaa qaabka ay CSS u isticmaasho si ay u bartilmaameedsato shayga.<br>Tusaale ahaan, <code>#jform_title</code> waxay bartilmaameedsan doontaa shayga leh id 'jform_title'."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_TYPE_TITLE="Xulo nooca"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_TYPE_DESCRIPTION="Kani waa nooca tallaabada aad rabto inaad abuurto. 'Ku xiga' si ay socodka ugu sii wado iyada oo aan is dhexgal, 'Dib u Toosin' si aad ugu guurto bog kale, 'Dhexgal' si aad u codsato gelinta isticmaale."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_SAVECLOSE_TITLE="Xulo 'Badbaadi oo Xir'"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_SAVECLOSE_DESCRIPTION="Badbaadi oo xir talaabada."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_CONGRATULATIONS_TITLE="Hambalyo!"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_CONGRATULATIONS_DESCRIPTION="Waxaad abuurtay tallaabo ku saabsan hagida dalxiiska."

