; Joomla! Project
; (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_GUIDEDTOURS_TOUR_SMARTSEARCH_STEP_NEW_TITLE="Xulo badhanka 'Cusub'"
COM_GUIDEDTOURS_TOUR_SMARTSEARCH_STEP_NEW_DESCRIPTION="Xulo 'Cusub' si aad u sameysato shaandhada raadiyaha cusub ee caqliga leh."

COM_GUIDEDTOURS_TOUR_SMARTSEARCH_STEP_TITLE_TITLE="Kudar cinwaan" 
COM_GUIDEDTOURS_TOUR_SMARTSEARCH_STEP_TITLE_DESCRIPTION="Gali cinwaan loo baahan yahay ee shaandhada raadinta caqliga."

COM_GUIDEDTOURS_TOUR_SMARTSEARCH_STEP_ALIAS_TITLE="Gali magac kale"
COM_GUIDEDTOURS_TOUR_SMARTSEARCH_STEP_ALIAS_DESCRIPTION="Waxaad qori kartaa magaca gudaha ee shaandhayntan. Waxaad uga tagi kartaa meel bannaan waxaana loo isticmaali doonaa qiimaha caadiga ah ee hoos loo dhigo oo leh dashes halkii laga isticmaali lahaa meelo bannaan sida qayb ka mid ah URL-ka."

COM_GUIDEDTOURS_TOUR_SMARTSEARCH_STEP_CONTENT_TITLE="Geli waxyaabaha"
COM_GUIDEDTOURS_TOUR_SMARTSEARCH_STEP_CONTENT_DESCRIPTION="Kudar waxa ku jira filter raadinta caqliga leh halkan."

COM_GUIDEDTOURS_TOUR_SMARTSEARCH_STEP_STATUS_TITLE="Dooro xaaladda"
COM_GUIDEDTOURS_TOUR_SMARTSEARCH_STEP_STATUS_DESCRIPTION="Dooro xaaladda la daabacay ee shaandhada."

COM_GUIDEDTOURS_TOUR_SMARTSEARCH_STEP_SAVECLOSE_TITLE="Xulo 'Badbaadi oo Xir'"
COM_GUIDEDTOURS_TOUR_SMARTSEARCH_STEP_SAVECLOSE_DESCRIPTION="Badbaadi oo xiro shaandhada raadiyaha caqliga leh."

COM_GUIDEDTOURS_TOUR_SMARTSEARCH_STEP_CONGRATULATIONS_TITLE="Hambalyo!"
COM_GUIDEDTOURS_TOUR_SMARTSEARCH_STEP_CONGRATULATIONS_DESCRIPTION="Waxaad abuurtey shaandhada raadinta caaqilka ah."

