; Joomla! Project
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_GUIDEDTOURS_TOUR_WHATSNEW_5_4_STEP_0_DESCRIPTION="<h3>Joomla 5.4 Faahfaahinta Sii-deynta Dhammeystiran</h3><p><a title=\"Faahfaahinta sii-deynta buuxda\" href=\"https://www.joomla.org/announcements.html\" target=\"_blank\" rel=\"noopener noreferrer\">Arag faahfaahinta sii-deynta buuxda ee joomla.org</a></p><hr><h3>Caawimaad iyo Macluumaad</h3><p>Khayraad badan oo ku caawin kara waxaa laga helaa halkan oo leh xiriirro dheeraad ah oo loogu talagalay khayraad badan, dukumiintiyo, taageero iyo sida looga qeybqaato Joomla.</p>"
COM_GUIDEDTOURS_TOUR_WHATSNEW_5_4_STEP_0_TITLE="Macluumaad dheeraad ah iyo Caawimaad"

