; Joomla! Project
; (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_GUIDEDTOURS_TOUR_TAGS_STEP_NEW_TITLE="Dooro badhanka 'Cusub'"
COM_GUIDEDTOURS_TOUR_TAGS_STEP_NEW_DESCRIPTION="Dooro 'Cusub' si aad u sameysato tag cusub."

COM_GUIDEDTOURS_TOUR_TAGS_STEP_TITLE_TITLE="Kudar cinwaan sumadda"
COM_GUIDEDTOURS_TOUR_TAGS_STEP_TITLE_DESCRIPTION="Geli cinwaanka loo baahan yahay ee sumadda."

COM_GUIDEDTOURS_TOUR_TAGS_STEP_ALIAS_TITLE="Geli magaca labaad"
COM_GUIDEDTOURS_TOUR_TAGS_STEP_ALIAS_DESCRIPTION="Waxaad qori kartaa magaca gudaha ee taggan. Waxaad ka tegi kartaa bannaan waxaana loo isticmaali doonaa qiimo asalka ah oo xuruuf yaryar wata iyo dhibco halkii meelaha bannaan."

COM_GUIDEDTOURS_TOUR_TAGS_STEP_CONTENT_TITLE="Kudar waxyaabaha"
COM_GUIDEDTOURS_TOUR_TAGS_STEP_CONTENT_DESCRIPTION="Kudar waxyaabaha sheegaaga ee tafatiraha."

COM_GUIDEDTOURS_TOUR_TAGS_STEP_PARENT_TITLE="Dooro tag waalid"
COM_GUIDEDTOURS_TOUR_TAGS_STEP_PARENT_DESCRIPTION="Dooro ama gali waalidka tag-ga."

COM_GUIDEDTOURS_TOUR_TAGS_STEP_STATUS_TITLE="Xullo xaaladda"
COM_GUIDEDTOURS_TOUR_TAGS_STEP_STATUS_DESCRIPTION="Xullo xaaladda la daabacay ee calaamadda."

COM_GUIDEDTOURS_TOUR_TAGS_STEP_ACCESS_TITLE="Deji heerka gelitaanka"
COM_GUIDEDTOURS_TOUR_TAGS_STEP_ACCESS_DESCRIPTION="Xulo heerka gelitaanka ee sumadda."

COM_GUIDEDTOURS_TOUR_TAGS_STEP_NOTE_TITLE="Kudar qoraal"
COM_GUIDEDTOURS_TOUR_TAGS_STEP_NOTE_DESCRIPTION="Tani waxay caadi ahaan loogu talagalay isticmaalka maamulaha mana muuqato qaybta hore."

COM_GUIDEDTOURS_TOUR_TAGS_STEP_VERSIONNOTE_TITLE="Kudar qoraal nooc ah"
COM_GUIDEDTOURS_TOUR_TAGS_STEP_VERSIONNOTE_DESCRIPTION="Tani waa goob ikhtiyaari ah oo lagu aqoonsanayo nooca sumaddan."

COM_GUIDEDTOURS_TOUR_TAGS_STEP_SAVECLOSE_TITLE="Xulo 'Kaydi oo Xir'"
COM_GUIDEDTOURS_TOUR_TAGS_STEP_SAVECLOSE_DESCRIPTION="Kaydi oo xiro summada."

COM_GUIDEDTOURS_TOUR_TAGS_STEP_CONGRATULATIONS_TITLE="Hambalyo!"
COM_GUIDEDTOURS_TOUR_TAGS_STEP_CONGRATULATIONS_DESCRIPTION="Waxaad abuurtay calaamad."


