; Joomla! Project
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_GUIDEDTOURS_TOUR_WHATSNEW_5_3_STEP_0_DESCRIPTION="<h3>Warbixinada Bixinta Buuxda ee Joomla 5.3</h3><p><a title=\"Warbixinada bixinta buuxa\" href=\"https://www.joomla.org/announcements.html\" target=\"_blank\" rel=\"noopener noreferrer\">Eeg warbixinada bixinta buuxda ee joomla.org</a></p><hr><h3>Caawin iyo Macluumaad</h3><p>Ilo badan oo kaa caawiya ayaa halkan laga heli karaa, oo leh isku xiridyo dheeraad ah oo ku saabsan ilo kale, dukumintiyo, taageero iyo sida loo qaybqaato Joomla.</p>"
COM_GUIDEDTOURS_TOUR_WHATSNEW_5_3_STEP_0_TITLE="Macluumaad Dheeraad ah iyo Caawin"

