; Joomla! Project
; (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_NEW_TITLE="Dooro badhanka 'Cusub'"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_NEW_DESCRIPTION="Dooro 'Cusub' si aad u abuurto wareeg cusub."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_TITLE_TITLE="Ku dar cinwaan socdaalka"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_TITLE_DESCRIPTION="Gali cinwaan loo baahan yahay ee socdaalka."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_CONTENT_TITLE="Kudar waxyaabo"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_CONTENT_DESCRIPTION="Gali nuxurka sharraxaya safarka."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_COMPONENT_TITLE="Xulo qayb ka mid ah"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_COMPONENT_DESCRIPTION="Xulo kordhinta(ha) halka aad rabto in safarkaagu ka muuqdo marka hore liiska safarada suurtagalka ah ee la socodsiin karo. Tusaale ahaan, haddii aad abuureyso safar loogu talagalay kordhinta 'Users', markaa xulo 'Users'. Xulo 'All' si safarka ugu muuqdo bog kasta."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_URL_TITLE="Kudar URL"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_URL_DESCRIPTION="Kudar URL-ka la xiriira ee bogga meesha dalxiisku ka bilaabmi doono. Tusaale ahaan, geli <em>administrator/index.php?option=com_users&view=users</em> si aad dalxiiska uga bilowdo bogga Isticmaalayaasha."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_AUTOSTART_TITLE="Beddel 'Bilowga Tooska ah'"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_AUTOSTART_DESCRIPTION="<p>Dejinta 'Bilowga Tooska ah' ilaa 'Haa' waxay si toos ah u bilaabeysaa dalxiiska marka shuruudaha la xiriira la buuxiyo.</p><p>Haddii dhowr dalxiisyo loo dejiyay inay si toos ah u bilaabaan isla shuruudaha, kaliya dalxiiska koowaad ee liiska ayaa bilaaban doona ilaa laga baajiyo, la dhameeyo ama laga boodo.</p>"

COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_SAVECLOSE_TITLE="Xulo 'Badbaadi oo Xidh'"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_SAVECLOSE_DESCRIPTION="Badbaadi oo xidh hage."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_CONGRATULATIONS_TITLE="Hambalyo!"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_CONGRATULATIONS_DESCRIPTION="Waxaad abuurtaa dalxiis hage ah. Hadda waa inaad tallaabooyin u samaysaa safarka."

