; Joomla! Project
; (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_GUIDEDTOURS_TOUR_TAGS_TITLE="Sida summadaha loo abuuro?"
COM_GUIDEDTOURS_TOUR_TAGS_DESCRIPTION="Booqashadani waxay ku tusi doontaa sida aad summad u abuuri karto."

