; Joomla! Project
; (C) 2024 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_GUIDEDTOURS_TOUR_WELCOMETOJOOMLA_TITLE="Ku soo dhowow Joomla!"
COM_GUIDEDTOURS_TOUR_WELCOMETOJOOMLA_DESCRIPTION="<p>Dulmar kana waxa uu ku siin doonaa dulmar degdeg ah oo ku saabsan sida loo bilaabo Joomla!</p><p>Waxaad ku jirtaa aagga Maamulaha Joomla, oo sidoo kale loo yaqaan '<strong>Backend</strong>'.<br>Kani waa meesha aad ku dejineyso oo aad ku maamuleyso bartaada Joomla oo dhan.</p><p><strong>Ma rabtaa inaad wax badan barato?</strong></p><p>Aynu bilowno dulmarka oo aan ku dhisno goobtaada awoodda Joomla!</p>"

