; Joomla! Project
; (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_NEW_TITLE="Dooro badhanka 'Cusub'"
COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_NEW_DESCRIPTION="Dooro 'Cusub' si aad u abuurto xiriir cusub."

COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_TITLE_TITLE="Ku dar magac"
COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_TITLE_DESCRIPTION="Geli magac loo baahan yahay ee xiriirka."

COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_ALIAS_TITLE="Geli naaneys"
COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_ALIAS_DESCRIPTION="Waxaad qori kartaa magaca gudaha ee xiriirkan. Waxaad ka tagi kartaa tan madhan waxaana lagu isticmaali doonaa qiime caadi ah oo ahaada hoos-jira oo leh jeexjeexyo halkii la isticmaali lahaa meelo bannaan oo qayb ka mid ah URL-ka."

COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_DETAILS_TITLE="Gali macluumaadka faahfaahsan"
COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_DETAILS_DESCRIPTION="Ku dar faahfaahinta xiriirka halkan."

COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_STATUS_TITLE="Dooro xaaladda"
COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_STATUS_DESCRIPTION="Dooro xaaladda la daabacay ee xiriirka."

COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_CATEGORY_TITLE="Dooro qayb"
COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_CATEGORY_DESCRIPTION="Dooro qaybta xiriirkan. Waxaad sidoo kale gali kartaa qayb cusub adiga oo qortay magaca goobta kadibna riixaya furaha gelida."

COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_FEATURED_TITLE="Beddel muuqaal"
COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_FEATURED_DESCRIPTION="Dooro 'Muuqaal' si aad u muujiso xiriirkaaga."

COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_ACCESS_TITLE="Deji heerka gelitaanka"
COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_ACCESS_DESCRIPTION="Xulo heerka gelitaanka ee xiriirka."

COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_TAGS_TITLE="Kudar calaamado"
COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_TAGS_DESCRIPTION="Xulo calaamado loogu talagalay xiriirkaaga. Waxa kale oo aad geli kartaa calaamad cusub adigoo magaceeda ku qoraya qayladda oo riixaya gali."

COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_VERSIONNOTE_TITLE="Kudar xusuus wershan"
COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_VERSIONNOTE_DESCRIPTION="Tani waa goob ikhtiyaari ah si loo aqoonsado wershada xidhiidhkan."

COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_SAVECLOSE_TITLE="Xulo 'Badbaadi oo Xir'"
COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_SAVECLOSE_DESCRIPTION="Badbaadi oo xiro xiriirka."

COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_CONGRATULATIONS_TITLE="Hambalyo!"
COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_CONGRATULATIONS_DESCRIPTION="Waxaad abuurtay xiriir."

