; Joomla! Project
; (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_GUIDEDTOURS_TOUR_MENUS_STEP_NEW_TITLE="Dooro badhanka 'Cusub'"
COM_GUIDEDTOURS_TOUR_MENUS_STEP_NEW_DESCRIPTION="Dooro 'Cusub' si aad u abuurto menu cusub."

COM_GUIDEDTOURS_TOUR_MENUS_STEP_TITLE_TITLE="Kudar cinwaan maadaxaaga menu-ga"
COM_GUIDEDTOURS_TOUR_MENUS_STEP_TITLE_DESCRIPTION="Gali cinwaan loo baahan yahay oo loogu talagalay menu-ga."

COM_GUIDEDTOURS_TOUR_MENUS_STEP_UNIQUENAME_TITLE="Kudar magac gaar ah"
COM_GUIDEDTOURS_TOUR_MENUS_STEP_UNIQUENAME_DESCRIPTION="Gali magac gaar ah ee loo baahan yahay menu-ga."

COM_GUIDEDTOURS_TOUR_MENUS_STEP_DESCRIPTION_TITLE="Kudar sawir"
COM_GUIDEDTOURS_TOUR_MENUS_STEP_DESCRIPTION_DESCRIPTION="Ku dar sharaxaad ku saabsan ujeedka liiska."

COM_GUIDEDTOURS_TOUR_MENUS_STEP_SAVECLOSE_TITLE="Xulo 'Kaydso oo Xir'"
COM_GUIDEDTOURS_TOUR_MENUS_STEP_SAVECLOSE_DESCRIPTION="Kaydi oo xidh liiska."

COM_GUIDEDTOURS_TOUR_MENUS_STEP_CONGRATULATIONS_TITLE="Hambalyo!"
COM_GUIDEDTOURS_TOUR_MENUS_STEP_CONGRATULATIONS_DESCRIPTION="Waxaad abuurtay menu."

