; Joomla! Project
; (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_GUIDEDTOURS_TOUR_CATEGORIES_STEP_NEW_TITLE="Dooro badhanka 'Cusub'"
COM_GUIDEDTOURS_TOUR_CATEGORIES_STEP_NEW_DESCRIPTION="Dooro 'Cusub' si aad ugu abuurto qayb cusub."

COM_GUIDEDTOURS_TOUR_CATEGORIES_STEP_TITLE_TITLE="Kudar ciwaan qaybta"
COM_GUIDEDTOURS_TOUR_CATEGORIES_STEP_TITLE_DESCRIPTION="Geli ciwaan loo baahan yahay oo ku saabsan qaybta."

COM_GUIDEDTOURS_TOUR_CATEGORIES_STEP_ALIAS_TITLE="Gali magac gaaban"
COM_GUIDEDTOURS_TOUR_CATEGORIES_STEP_ALIAS_DESCRIPTION="Waxaad qori kartaa magaca gudaha ee qaybtaan. Waxaad uga tagi kartaa madhan waxaana loo isticmaali doonaa qiime asluub ah oo xarfo yaryar leh oo xarfo ku jiraan meelo bannaan halkii boosaska."

COM_GUIDEDTOURS_TOUR_CATEGORIES_STEP_CONTENT_TITLE="Kudar waxyaabaha"
COM_GUIDEDTOURS_TOUR_CATEGORIES_STEP_CONTENT_DESCRIPTION="Ku dar waxyaabaha qaybtaada tafatiraha."

COM_GUIDEDTOURS_TOUR_CATEGORIES_STEP_PARENT_TITLE="Dooro qaybta hooyada"
COM_GUIDEDTOURS_TOUR_CATEGORIES_STEP_PARENT_DESCRIPTION="Dooro ama geli qaybta waalidka ee qaybta."

COM_GUIDEDTOURS_TOUR_CATEGORIES_STEP_STATUS_TITLE="Doora xaaladda"
COM_GUIDEDTOURS_TOUR_CATEGORIES_STEP_STATUS_DESCRIPTION="Doora xaaladda la daabacay ee qaybta."

COM_GUIDEDTOURS_TOUR_CATEGORIES_STEP_ACCESS_TITLE="Deji heerka helitaanka"
COM_GUIDEDTOURS_TOUR_CATEGORIES_STEP_ACCESS_DESCRIPTION="Xulo heerka helitaanka qaybtan."

COM_GUIDEDTOURS_TOUR_CATEGORIES_STEP_TAGS_TITLE="Kudar tags"
COM_GUIDEDTOURS_TOUR_CATEGORIES_STEP_TAGS_DESCRIPTION="Dooro tags-ka qeybtaada. Waxaad kaloo gali kartaa tag cusub adoo magaca ku qoraya booska una riixaya gal."

COM_GUIDEDTOURS_TOUR_CATEGORIES_STEP_NOTE_TITLE="Ku dar qoraal"
COM_GUIDEDTOURS_TOUR_CATEGORIES_STEP_NOTE_DESCRIPTION="Tani caadi ahaan waa isticmaalka maamulaha mana muuqato qaybta hore."

COM_GUIDEDTOURS_TOUR_CATEGORIES_STEP_VERSIONNOTE_TITLE="Kudar qoraal nooc ah"
COM_GUIDEDTOURS_TOUR_CATEGORIES_STEP_VERSIONNOTE_DESCRIPTION="Tani waa goob ikhtiyaari ah si loo aqoonsado nooca qaybtaan."

COM_GUIDEDTOURS_TOUR_CATEGORIES_STEP_SAVECLOSE_TITLE="Xulo 'Keydi oo Xir'"
COM_GUIDEDTOURS_TOUR_CATEGORIES_STEP_SAVECLOSE_DESCRIPTION="Keydi oo xidh qaybta."

COM_GUIDEDTOURS_TOUR_CATEGORIES_STEP_CONGRATULATIONS_TITLE="Hambalyo!"
COM_GUIDEDTOURS_TOUR_CATEGORIES_STEP_CONGRATULATIONS_DESCRIPTION="Waxaad abuurtay qayb"

