; Joomla! Project
; (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_NEW_TITLE="Xulo badhanka 'Cusub'"
COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_NEW_DESCRIPTION="Xulo 'Cusub' si aad maqaal cusub u abuurto."

COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_TITLE_TITLE="Kudar ciwaanka maqaalka" 
COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_TITLE_DESCRIPTION="Gali ciwaan khasab ah maqaalka."

COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_ALIAS_TITLE="Geli naanays"
COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_ALIAS_DESCRIPTION="Waxaad qori kartaa magaca gudaha ee maqaalkaan. Waad ka tegi kartaa tan bannaan waana laga isticmaali doonaa qiimo caadi ah oo kiiska hoose ah oo leh dashes halkii meel bannaanaha la isticmaali doono qayb ka mid ah URL-ka."

COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_CONTENT_TITLE="Kudar waxa ku jira" 
COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_CONTENT_DESCRIPTION="Ku dar waxa ku jira maqaalkaga tafatiraha."

COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_STATUS_TITLE="Dooro xaaladda"
COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_STATUS_DESCRIPTION="Dooro xaaladda la daabacay ee maqaalka."

COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_CATEGORY_TITLE="Dooro qayb"
COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_CATEGORY_DESCRIPTION="Dooro qaybta maqaalkan. Waxaad sidoo kale geli kartaa qayb cusub adoo ku qoranaya magaca meelaha oo gujinaya gelida."

COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_FEATURED_TITLE="Beddel muuqaalka"
COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_FEATURED_DESCRIPTION="Xulo 'Muuqaal' si aad maqaalkaaga u muuqatid."

COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_ACCESS_TITLE="Deji heerka helitaanka"
COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_ACCESS_DESCRIPTION="Xulo heerka helitaanka maqaalka."

COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_TAGS_TITLE="Ku dar qurub"
COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_TAGS_DESCRIPTION="Xulo qurubyada maqaalkaaga. Waxa kale oo aad geli kartaa qodob cusub adigoo magaca qortay booska oo riixaya galitaan."

COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_NOTE_TITLE="Kudar qoraal"
COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_NOTE_DESCRIPTION="Kani waa badanaa isticmaale maamulka mana muujiyaan dhinaca hore."

COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_VERSIONNOTE_TITLE="Kudar xusuus qoraalka nooca"
COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_VERSIONNOTE_DESCRIPTION="Kani waa meel ikhtiyaari ah oo lagu aqoonsanayo nooca maqaalkaan."

COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_SAVECLOSE_TITLE="Xulo 'Badbaadi oo Xir'"
COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_SAVECLOSE_DESCRIPTION="Badbaadi oo xiro maqaalka."

COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_CONGRATULATIONS_TITLE="Hambalyo!"
COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_CONGRATULATIONS_DESCRIPTION="Waxaad abuurtey maqaal."

