; Joomla! Project
; (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_NEW_TITLE="Dooro badhanka 'Cusub'"
COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_NEW_DESCRIPTION="Dooro 'Cusub' si aad u abuurto quudin warar cusub."

COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_TITLE_TITLE="Kudar ciwaanka"
COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_TITLE_DESCRIPTION="Geli ciwaan loo baahan yahay oo quseeya war-feedka."

COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_ALIAS_TITLE="Geli magac kooban"
COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_ALIAS_DESCRIPTION="Waxaad qori kartaa magaca gudaha ee naas-nuujintan. Waxaad tan uga tagi kartaa madhan, qiime-degdeg ah oo la jarjaray iyadoo la adeegsanayo dashes halkii boosaska ayaa loo isticmaali doonaa qayb ka mid ah URL-ka."

COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_LINK_TITLE="Gali xiriirinta"
COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_LINK_DESCRIPTION="Ku dar xiriirka quudinta wararka halkan."

COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_DESCRIPTION_TITLE="Geli faahfaahin"
COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_DESCRIPTION_DESCRIPTION="Ku dar faahfaahin dheefaha wararka ee tifatiraha."

COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_STATUS_TITLE="Dooro xaaladda"
COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_STATUS_DESCRIPTION="Dooro xaaladda la daabacay ee quudinta wararka."

COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_CATEGORY_TITLE="Dooro qayb"
COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_CATEGORY_DESCRIPTION="Dooro qaybta quudinta wararkan. Waxaad sidoo kale gelin kartaa qayb cusub adoo ku qoraya magaca beerka oo riixaya gelida."

COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_ACCESS_TITLE="Deji heerka gelitaanka"
COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_ACCESS_DESCRIPTION="Xulo heerka gelitaanka ee quudinta wararka."

COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_TAGS_TITLE="Ku dar sumadaha"
COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_TAGS_DESCRIPTION="Xulo sumadaha quudinta wararkaaga. Waxa kale oo aad gali kartaa sumad cusub adiga oo ku qoraya magaca berrinka oo gujinaya gelida."

COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_VERSIONNOTE_TITLE="Kudar qoraal nuqulo"
COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_VERSIONNOTE_DESCRIPTION="Tani waa goob ikhtiyaari ah oo lagu aqoonsanayo nuqulka quudinta wararka."

COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_SAVECLOSE_TITLE="Xulo 'Badbaadi oo xidh'"
COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_SAVECLOSE_DESCRIPTION="Badbaadi oo xidho quudinta wararka."

COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_CONGRATULATIONS_TITLE="Hambalyo!"
COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_CONGRATULATIONS_DESCRIPTION="Waxaad abuurtay quudin wararka."

