; Joomla! Project
; (C) 2008 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_FEED="Muuqaalka Quudinta"
MOD_FEED_ERR_CACHE="Fadlan ka dhig galka keydka mid la qori karo."
MOD_FEED_ERR_FEED_NOT_RETRIEVED="Quudin lama helin."
MOD_FEED_ERR_NO_URL="URL quudin ah lama cayimin."
MOD_FEED_FIELD_DATE_LABEL="Taariikhda Quudinta"
MOD_FEED_FIELD_DESCRIPTION_LABEL="Sharaxaada Quudinta"
MOD_FEED_FIELD_IMAGE_LABEL="Sawirka Quudinta"
MOD_FEED_FIELD_ITEMDATE_LABEL="Taariikhda Daabacaadda"
MOD_FEED_FIELD_ITEMDESCRIPTION_LABEL="Sharaxaadda Shayga"
MOD_FEED_FIELD_ITEMS_LABEL="Shayada la Muujinayo"
MOD_FEED_FIELD_RSSTITLE_LABEL="Cinwaanka Quudinta"
MOD_FEED_FIELD_RSSURL_LABEL="URL Quudinta"
MOD_FEED_FIELD_RTL_LABEL="RTL Quudinta"
MOD_FEED_XML_DESCRIPTION="Qaabkan wuxuu kuu ogolaanayaa in aad muujiso quudin wadajird ah."

