; Joomla! Project
; (C) 2006 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_TOOLBAR="Qalabka Shaqada"
MOD_TOOLBAR_FIELD_TOOLBAR_LABEL="Astaanta Qalabka Shaqada"
MOD_TOOLBAR_FIELD_TOOLBAR_DESCRIPTION="Qalabka shaqada ee caadiga ah ee maamulka waxaa loo yaqaan 'qalabka shaqada', haddii aad leedahay fidin sameysa qalab gaar ah waxaad abuuri kartaa module gaar ah oo leh aqoonsiga qalabka shaqada. Qalabka shaqada ee asalka ah waa in aan waligii la saarin!"
MOD_TOOLBAR_XML_DESCRIPTION="Module-kan wuxuu tusayaa astaamaha qalabka shaqada ee loo isticmaalo in lagu xakameeyo ficilada guud ahaan aagga Maamulka."

