; Joomla! Project
; (C) 2006 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_CUSTOM="Gaar ah"
MOD_CUSTOM_FIELD_PREPARE_CONTENT_DESC="U diyaari nuxurka ikhtiyaar ahaan Joomla Content Plugins."
MOD_CUSTOM_FIELD_PREPARE_CONTENT_LABEL="U Diyaari Nuxur"
MOD_CUSTOM_XML_DESCRIPTION="Cutubkan wuxuu kuu ogolaanayaa inaad sameysato cutub adiga kuu gaar ah adigoo isticmaalaya tafatiraha WYSIWYG."

