; Joomla! Project
; (C) 2018 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_LATESTACTIONS="Diiwaanka Ficillada - Kuwii Ugu Dambeeyay"
MOD_LATESTACTIONS_ACTION="Ficil"
MOD_LATESTACTIONS_FIELD_COUNT_LABEL="Alaabta in la Muujiyo"
MOD_LATESTACTIONS_LAYOUT_DEFAULT="Caadi"
MOD_LATESTACTIONS_NO_MATCHING_RESULTS="Natiijooyin Isku Mid ah Ma jiraan"
MOD_LATESTACTIONS_TITLE="Ficilladii Ugu Dambeeyay"
MOD_LATESTACTIONS_TITLE_1="Ficilkii Ugu Dambeeyay"
MOD_LATESTACTIONS_TITLE_MORE="%d Ficil ee Ugu Dambeeyay"
MOD_LATESTACTIONS_XML_DESCRIPTION="Qaybtaan waxay tusisaa liiska ficillada ugu dambeeyay."

