; Joomla! Project
; (C) 2019 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_MESSAGES="Fariimaha"
MOD_MESSAGES_PRIVATE_MESSAGES="Fariimaha Gaarka ah"
MOD_MESSAGES_XML_DESCRIPTION="Qaabkaani wuxuu soo bandhigayaa tirada fariimaha gaarka ah wuxuuna loogu talagalay in lagu soo bandhigo booska 'xaaladda'. Waxaa la soo bandhigi karaa oo keliya marka ay jiraan fariimo la akhriyo."

