; Joomla! Project
; (C) 2011 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_MULTILANGSTATUS="Xaaladda Luqadda Badan"  
MOD_MULTILANGSTATUS_XML_DESCRIPTION="Qaabkaani wuxuu muujinayaa xaaladda waxyaalaha luqadaha badan ee la xiriira wuxuuna loogu talagalay in lagu soo bandhigo booska 'xaaladda'."

