; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_LATEST="Maqaalada - Ugu Dambeeyay"
MOD_LATEST_CREATED="La Abuuray"
MOD_LATEST_CREATED_BY="Waxaa Abuuray"
MOD_LATEST_FIELD_AUTHORS_LABEL="Qorayaasha"
MOD_LATEST_FIELD_COUNT_LABEL="Shayada La Tusayo"
MOD_LATEST_FIELD_ORDERING_LABEL="Kala Horeynta"
MOD_LATEST_FIELD_VALUE_AUTHORS_ANYONE="Qof kasta"
MOD_LATEST_FIELD_VALUE_AUTHORS_BY_ME="Aniga ayaa ku daray ama wax ka beddelay"
MOD_LATEST_FIELD_VALUE_AUTHORS_NOT_BY_ME="Ma aniga ayaa ku daray ama wax ka beddelay"
MOD_LATEST_FIELD_VALUE_ORDERING_ADDED="Kuwa Ugu Dambeeyay Ee La Kudaray"
MOD_LATEST_FIELD_VALUE_ORDERING_MODIFIED="Kuwa Ugu Dambeeyay Ee Wax Laga Bedelay"
MOD_LATEST_HEADING_DATE_CREATED="Taariikhda La Abuuray"
MOD_LATEST_HEADING_DATE_MODIFIED="Taariikhda Wax Laga Bedelay"
MOD_LATEST_LATEST_ITEMS="Shayada Ugu Dambeeyay"
MOD_LATEST_NO_MATCHING_RESULTS="Natiijooyin La Waafajiyay Ma Jiraan"
MOD_LATEST_TITLE="Maqaalada La Abuuray Uun"
MOD_LATEST_TITLE_CREATED="Maqaalada Ugu Dambeeyay Ee La Kudaray"
MOD_LATEST_TITLE_CREATED_1="Maqaal Ugu Dambeeyay Ee La Kudaray"
MOD_LATEST_TITLE_CREATED_BY_ME="Maqaalada Ugu Dambeeyay Ee Aniga Ku Dartay"
MOD_LATEST_TITLE_CREATED_BY_ME_1="Maqaal Ugu Dambeeyay Ee Aniga Ku Dartay"
MOD_LATEST_TITLE_CREATED_BY_ME_MORE="%1$s Maqaalo Ugu Dambeeyay Ee Aniga Ku Dartay"
MOD_LATEST_TITLE_CREATED_CATEGORY="Maqaalada Ugu Dambeeyay (%2$s qaybood)"
MOD_LATEST_TITLE_CREATED_CATEGORY_1="Maqaal Ugu Dambeeyay (%2$s qaybood)"
MOD_LATEST_TITLE_CREATED_CATEGORY_BY_ME="Maqaalada Ugu Dambeeyay Ee Aniga Ku Dartay (%2$s qaybood)"
MOD_LATEST_TITLE_CREATED_CATEGORY_BY_ME_1="Maqaal Ugu Dambeeyay Ee Aniga Ku Dartay (%2$s qaybood)"
MOD_LATEST_TITLE_CREATED_CATEGORY_BY_ME_MORE="Maqaallada Ugu Dambeeyay ee Aan Kudaray (%2$s qeybta)"
MOD_LATEST_TITLE_CREATED_CATEGORY_MORE="Maqaallada Ugu Dambeeyay ee Kudaray (%2$s qeybta)"
MOD_LATEST_TITLE_CREATED_CATEGORY_NOT_ME="Maqaallada Ugu Dambeeyay ee Aan Igu Kudarin (%2$s qeybta)"
MOD_LATEST_TITLE_CREATED_CATEGORY_NOT_ME_1="Maqaalka Ugu Dambeeyay ee Aan Igu Kudarin (%2$s qeybta)"
MOD_LATEST_TITLE_CREATED_CATEGORY_NOT_ME_MORE="Maqaallada Ugu Dambeeyay ee Aan Igu Kudarin (%2$s qeybta)"
MOD_LATEST_TITLE_CREATED_MORE="Maqaallada Ugu Dambeeyay ee Kudaray %1$s"
MOD_LATEST_TITLE_CREATED_NOT_ME="Maqaallada Ugu Dambeeyay ee Aan Igu Kudarin"
MOD_LATEST_TITLE_CREATED_NOT_ME_1="Maqaalka Ugu Dambeeyay ee Aan Igu Kudarin"
MOD_LATEST_TITLE_CREATED_NOT_ME_MORE="Maqaallada Ugu Dambeeyay ee Aan Igu Kudarin %1$s"
MOD_LATEST_TITLE_MODIFIED="Maqaallada Ugu Dambeeyay ee Wax Laga Bedelay"
MOD_LATEST_TITLE_MODIFIED_1="Maqaalka Ugu Dambeeyay ee Wax Laga Bedelay"
MOD_LATEST_TITLE_MODIFIED_BY_ME="Maqaallada Ugu Dambeeyay ee Aan Wax Ka Bedelay"
MOD_LATEST_TITLE_MODIFIED_BY_ME_1="Maqaalka Ugu Dambeeyay ee Aan Wax Ka Bedelay"
MOD_LATEST_TITLE_MODIFIED_BY_ME_MORE="Maqaallada Ugu Dambeeyay ee Aan Wax Ka Bedelay %1$s"
MOD_LATEST_TITLE_MODIFIED_CATEGORY="Maqaallada Ugu Dambeeyay ee Wax Laga Bedelay (%2$s qeybta)"
MOD_LATEST_TITLE_MODIFIED_CATEGORY_1="Maqaalka Ugu Dambeeyay ee Wax Laga Bedelay (%2$s qeybta)"
MOD_LATEST_TITLE_MODIFIED_CATEGORY_BY_ME="Maqaallada Ugu Dambeeyay ee Aan Wax Ka Bedelay (%2$s qeybta)"
MOD_LATEST_TITLE_MODIFIED_CATEGORY_BY_ME_1="Maqaalka Ugu Dambeeyay ee Aan Wax Ka Bedelay (%2$s qeybta)"
MOD_LATEST_TITLE_MODIFIED_CATEGORY_BY_ME_MORE="Maqaallada Ugu Dambeeyay ee Aan Wax Ka Bedelay %1$s (%2$s qeybta)"
MOD_LATEST_TITLE_MODIFIED_CATEGORY_MORE="Maqaallada Ugu Dambeeyay ee Wax Laga Bedelay %1$s (%2$s qeybta)"
MOD_LATEST_TITLE_MODIFIED_CATEGORY_NOT_ME="Maqaallada Ugu Dambeeyay ee Aan Igu Wax Laga Bedelin (%2$s qeybta)"
MOD_LATEST_TITLE_MODIFIED_CATEGORY_NOT_ME_1="Maqaalka Ugu Dambeeyay ee Aan Igu Wax Laga Bedelin (%2$s qeybta)"
MOD_LATEST_TITLE_MODIFIED_CATEGORY_NOT_ME_MORE="Maqaallada Ugu Dambeeyay ee Aan Igu Wax Laga Bedelin %1$s (%2$s qeybta)"
MOD_LATEST_TITLE_MODIFIED_MORE="Maqaallada Ugu Dambeeyay ee Wax Laga Bedelay %1$s"
MOD_LATEST_TITLE_MODIFIED_NOT_ME="Maqaallada Ugu Dambeeyay ee Aan Igu Wax Laga Bedelin"
MOD_LATEST_TITLE_MODIFIED_NOT_ME_1="Maqaalka Ugu Dambeeyay Ee La Badalay Ma Ahan Aniga"
MOD_LATEST_TITLE_MODIFIED_NOT_ME_MORE="%1$s Maqaalada Ugu Dambeeyay Ee La Badalay Ma Ahan Aniga"
MOD_LATEST_UNEXISTING="<em>Ma jiro</em>"
MOD_LATEST_XML_DESCRIPTION="Qeybtan waxa ay soo bandhigaysaa liis ka mid ah Maqaallada ugu dambeeyay ee la abuuray."

