; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_POPULAR="Maqaallo Caanka Ah"
MOD_POPULAR_CREATED="La Abuuray"
MOD_POPULAR_FIELD_AUTHORS_LABEL="Qorayaasha"
MOD_POPULAR_FIELD_COUNT_LABEL="Shayada La Soo Bandhigayo"
MOD_POPULAR_FIELD_VALUE_ADDED_OR_MODIFIED_BY_ME="Anigaa Ku Daray ama Wax Ka Bedelay"
MOD_POPULAR_FIELD_VALUE_ANYONE="Qofkasta"
MOD_POPULAR_FIELD_VALUE_NOT_ADDED_OR_MODIFIED_BY_ME="Anigu kuma darin ama waxba kama aan bedelin"
MOD_POPULAR_ITEMS="Shayada Caanka Ah"
MOD_POPULAR_NO_MATCHING_RESULTS="Natiijooyin Isku Eeg Ma Jiraan"
MOD_POPULAR_TITLE="Maqaallo Caanka Ah"
MOD_POPULAR_TITLE_1="Maqaallo Caan Ah Oo Ugub"
MOD_POPULAR_TITLE_BY_ME="Maqaallo Caanka Ah oo Aniga Ka Timid"
MOD_POPULAR_TITLE_BY_ME_1="Maqaalka Caanka Ah oo Aniga Ka Timid"
MOD_POPULAR_TITLE_BY_ME_MORE="%1$s Maqaal Caan Ah oo Aniga Ka Timid"
MOD_POPULAR_TITLE_CATEGORY="Maqaallo Caanka Ah (%2$s qaybta)"
MOD_POPULAR_TITLE_CATEGORY_1="Maqaal Caan Ah (%2$s qaybta)"
MOD_POPULAR_TITLE_CATEGORY_BY_ME="Maqaallo Caanka Ah oo Aniga Ka Timid (%2$s qaybta)"
MOD_POPULAR_TITLE_CATEGORY_BY_ME_1="Maqaal Caan Ah oo Aniga Ka Timid (%2$s qaybta)"
MOD_POPULAR_TITLE_CATEGORY_BY_ME_MORE="%1$s Maqaal Caan oo Aniga Ka Timid (%2$s qaybta)"
MOD_POPULAR_TITLE_CATEGORY_MORE="%1$s Maqaal Caan Ah (%2$s qaybta)"
MOD_POPULAR_TITLE_CATEGORY_NOT_ME="Maqaallo Caanka Ah oo Aan Aniga Ku Jirin (%2$s qaybta)"
MOD_POPULAR_TITLE_CATEGORY_NOT_ME_1="Maqaal Caan Ah oo Aan Aniga Ku Jirin (%2$s qaybta)"
MOD_POPULAR_TITLE_CATEGORY_NOT_ME_MORE="%1$s Maqaal Caan Ah oo Aan Aniga Ku Jirin (%2$s qaybta)"
MOD_POPULAR_TITLE_MORE="%1$s Maqaal Caan Ah"
MOD_POPULAR_TITLE_NOT_ME="Maqaallo Caanka Ah oo Aan Aniga Ku Jirin"
MOD_POPULAR_TITLE_NOT_ME_1="Maqaallada ugu Caansan ee Igama Soo Qorin"
MOD_POPULAR_TITLE_NOT_ME_MORE="Top %1$s Maqaallo Caansan oo Igama Soo Qorin"
MOD_POPULAR_UNEXISTING="<em>Lama Jiro</em>"
MOD_POPULAR_XML_DESCRIPTION="Qeybtan waxay soo bandhigaysaa liiska Maqaallada ugu caansan ee la daabacay oo wali socda. Qaar soo muuqda ayaa laga yaabaa inay dhamaadeen inkastoo ay yihiin kuwa ugu dambeeyay."

