; Joomla! Project
; (C) 2006 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_MENU="Liiska Maamulaha"
MOD_MENU_ACCESS="Oggolaanshaha Isticmaalaha"
MOD_MENU_ACCESS_GROUPS="Kooxaha"
MOD_MENU_ACCESS_LEVELS="Heerarka Gelitaanka"
MOD_MENU_ACCESS_SETTINGS="Dejinta"
MOD_MENU_ACCESS_TEXT_FILTERS="Shaandheyn Qoraalka"
MOD_MENU_ARIA_CLOSE_SUBMENU="Xidh Submenu"
MOD_MENU_ARIA_MAIN_MENU="Liiska Guud"
MOD_MENU_CLEAR_CACHE="Nadiifi Kaydka"
MOD_MENU_COM_ACTIONLOGS="Diiwaanka Falalka Isticmaalaha"
MOD_MENU_COM_CONTENT="Waxyaabaha"
MOD_MENU_COM_LANGUAGES_SUBMENU_CONTENT="Luuqadaha Waxyaabaha"
MOD_MENU_COM_LANGUAGES_SUBMENU_INSTALLED="Rakibay"
MOD_MENU_COM_LANGUAGES_SUBMENU_OVERRIDES="Daboolidda"
MOD_MENU_COM_MAILS_TEMPLATES="Qoraallada Mails"
MOD_MENU_COM_PRIVACY="Asturnaanta"
MOD_MENU_COM_PRIVACY_CAPABILITIES="Kartida"
MOD_MENU_COM_PRIVACY_CONSENTS="Oggolaansho"
MOD_MENU_COM_PRIVACY_DASHBOARD="Guddiga"
MOD_MENU_COM_PRIVACY_REQUESTS="Codsiyada"
MOD_MENU_COM_TEMPLATES_SUBMENU_STYLES="Qaababka"
MOD_MENU_COM_TEMPLATES_SUBMENU_TEMPLATES="Qaab-dhismeedyada"
MOD_MENU_COM_USERS="Isticmaaleyaasha"
MOD_MENU_COMPONENTS="Qeybaha"
MOD_MENU_CONFIGURATION="Dejin Guud"
MOD_MENU_CONFIGURATION_MAILS="Qabyo-Tirisyada Boostada"
MOD_MENU_CONTROL_PANEL="Barta Hore"
MOD_MENU_DASHBOARD_LINK="%s Dashboardka"
MOD_MENU_EXTENSIONS_EXTENSION_MANAGER="Maaree"
MOD_MENU_EXTENSIONS_EXTENSIONS="Kordhinta"
MOD_MENU_EXTENSIONS_LANGUAGE_MANAGER="Luuqadaha"
MOD_MENU_EXTENSIONS_MODULE_MANAGER="Qaybaha"
MOD_MENU_EXTENSIONS_MODULE_MANAGER_ADMINISTRATOR="Qaybaha Maamulka"
MOD_MENU_EXTENSIONS_MODULE_MANAGER_SITE="Qaybaha Goobta"
MOD_MENU_EXTENSIONS_PLUGIN_MANAGER="Kordhinta"
MOD_MENU_EXTENSIONS_TEMPLATE_MANAGER="Qabyo-Tirisyada"
MOD_MENU_FIELD_CHECK_DESC="Fiiri jiritaanka waxyaabaha muhiimka ah ee menu-ga."
MOD_MENU_FIELD_CHECK_LABEL="Fiiri Menu-ga"
MOD_MENU_FIELD_FORUMURL_DESC="Geli URL-ka forumka ah ee aan caadiga ahayn."
MOD_MENU_FIELD_FORUMURL_LABEL="URL-ka Forumka Taageerada Gaarka ah"
MOD_MENU_FIELD_MENUTYPE_LABEL="Menu-ga Muujin"
MOD_MENU_FIELD_MENUTYPE_OPTION_PREDEFINED="Isticmaal Horay u Dhac"
MOD_MENU_FIELD_PRESET_DESC="Dooro horay u diyaargarow si aad uga isticmaasho menu-ga dhamaadka gadaal"
MOD_MENU_FIELD_PRESET_LABEL="Dooro Horay u Dhac"
MOD_MENU_FIELD_SHOWHELP="Caawinta Menu-ga"
MOD_MENU_FIELD_SHOWNEW="Ku dar Kooban Cusub"
MOD_MENU_FIELDS="Goobaha"
MOD_MENU_FIELDS_GROUP="Kooxo Goobo"
MOD_MENU_GLOBAL_CHECKIN="Is-diiwaangelinta Caalamiga ah"
MOD_MENU_HELP="Caawin"
MOD_MENU_HELP_COMMUNITY="Bogga Bulshada"
MOD_MENU_HELP_COMMUNITY_NEWS="Wararka Bulshada"
MOD_MENU_HELP_COMMUNITY_NEWSLETTER="Warqada Bulshada"
MOD_MENU_HELP_DEVELOPER="Khayraadka Horumarinta"
MOD_MENU_HELP_DOCUMENTATION="Wiki Dukumentiga"
MOD_MENU_HELP_EVENTS="Dhacdooyinka Joomla"
MOD_MENU_HELP_EXTENSIONS="Joomla! Kordhinta"
MOD_MENU_HELP_GITHUB="Joomla oo ku jira GitHub"
MOD_MENU_HELP_ISSUES_TRACKER="Raadiye Dhibco"
MOD_MENU_HELP_JOOMLA="Joomla! Caawinaad"
MOD_MENU_HELP_PARENT_FIND_HELP="Caawinaad Dheeraad ah"
MOD_MENU_HELP_PARENT_GET_INVOLVED="Ka qayb qaado"
MOD_MENU_HELP_PARENT_MEET_JOOMLERS="La kulan Joomlers"
MOD_MENU_HELP_PARENT_NEWS="Wararka"
MOD_MENU_HELP_PARENT_RESOURCES="Khayraad"
MOD_MENU_HELP_PARENT_START_HERE="Halkaan Ka Bilow"
MOD_MENU_HELP_RESOURCES="Joomla! Khayraad"
MOD_MENU_HELP_SECURITY="Xarunta Amniga"
MOD_MENU_HELP_SHOP="Dukaanka Joomla!"
MOD_MENU_HELP_SUPPORT_CUSTOM_FORUM="Madasha Taageerada Gaarka ah"
MOD_MENU_HELP_SUPPORT_OFFICIAL_FORUM="Madasha Taageerada Rasmiga ah"
MOD_MENU_HELP_SUPPORT_OFFICIAL_LANGUAGE_FORUM="Madalaha Luqadda Rasmiga ah"
MOD_MENU_HELP_SUPPORT_OFFICIAL_LANGUAGE_FORUM_VALUE="511"
MOD_MENU_HELP_TRANSLATIONS="Joomla! Turjumaadaha"
MOD_MENU_HELP_USER_GROUPS="Kooxaha Isticmaalayaasha Joomla"
MOD_MENU_HELP_XCHANGE="Stack Exchange"
MOD_MENU_HOME_DEFAULT="Bogga Hore"
MOD_MENU_HOME_MULTIPLE="Digniin! Guryo badan!"
MOD_MENU_IMPORTANT_ITEM_COMPONENTS_CONTAINER="Weelka Qeybaha"
MOD_MENU_IMPORTANT_ITEM_MENU_MANAGER="Maareeyaha Menu-ga"
MOD_MENU_IMPORTANT_ITEM_MODULE_MANAGER="Maareeyaha Module-ka"
MOD_MENU_IMPORTANT_ITEMS_INACCESSIBLE_LIST_WARNING="Menu-ga maamulka <strong>%1$s</strong> ma leh - <strong>%2$s</strong>. Dooro <strong><a href='%3$s'>qaabka soo kabashada menu-ga</a></strong> si loogu daro."
MOD_MENU_INFORMATION="Macluumaad"
MOD_MENU_INFORMATION_POST_INSTALL_MESSAGES="Fariimaha Rakibida Kadib"
MOD_MENU_INFORMATION_WARNINGS="Digniino"
MOD_MENU_INSTALL="Rakib"
MOD_MENU_INSTALL_DISCOVER="Soo Ogaado"
MOD_MENU_INSTALL_EXTENSIONS="Kordhinta"
MOD_MENU_INSTALL_LANGUAGES="Luqadaha"
MOD_MENU_INSTALLER_SUBMENU_DATABASE="Kaydka Xogta"
MOD_MENU_INSTALLER_SUBMENU_DISCOVER="Soo Ogaado"
MOD_MENU_INSTALLER_SUBMENU_INSTALL="Rakib"
MOD_MENU_INSTALLER_SUBMENU_LANGUAGES="Rakibida Luqadaha"
MOD_MENU_INSTALLER_SUBMENU_MANAGE="Maamul"
MOD_MENU_INSTALLER_SUBMENU_UPDATE="Cusbooneysiin"
MOD_MENU_INSTALLER_SUBMENU_UPDATESITES="Goobaha Cusbooneysiinta"
MOD_MENU_INSTALLER_SUBMENU_WARNINGS="Digniino"
MOD_MENU_LOGOUT="Ka Bax"
MOD_MENU_MAINTAIN="Dayactir"
MOD_MENU_MANAGE="Maamul"
MOD_MENU_MANAGE_EXTENSIONS="Kordhin"
MOD_MENU_MANAGE_GUIDEDTOURS="Safarrada Hagaya"
MOD_MENU_MANAGE_LANGUAGES="Luqadaha"
MOD_MENU_MANAGE_LANGUAGES_CONTENT="Mawduuca Luqadaha"
MOD_MENU_MANAGE_LANGUAGES_OVERRIDES="Badalidda Luqadda"
MOD_MENU_MANAGE_PLUGINS="Kordhin"
MOD_MENU_MANAGE_REDIRECTS="Dib-u-Dhacyo"
MOD_MENU_MANAGE_SCHEDULED_TASKS="Hawlaha Jadwalaysan"
MOD_MENU_MASS_MAIL_USERS="Isticmaalayaasha Imeel Dad Bantire"
MOD_MENU_MEDIA_MANAGER="Warbaahinta"
MOD_MENU_MENU_MANAGER="Maamuli"
MOD_MENU_MENU_MANAGER_NEW_ADMIN_MENU_ITEM="Ku Dar Qalabka Menu Maamulaha"
MOD_MENU_MENU_MANAGER_NEW_SITE_MENU_ITEM="Ku Dar Qalabka Menu Bogga"
MOD_MENU_MENUS="Menu-yada"
MOD_MENU_MENUS_ALL_ITEMS="Dhamaan Qalabka Menu"
MOD_MENU_MESSAGING="Fariimaha"
MOD_MENU_MESSAGING_NEW="Fariin Gaar Tiro Cusub"
MOD_MENU_MESSAGING_PRIVATE="Fariimaha Gaar ah"
MOD_MENU_QUICKTASK_NEW="Qalab Cusub"
MOD_MENU_READ_PRIVATE_MESSAGES="Akhri Fariimaha Gaar ah"
MOD_MENU_RECOVERY_EXIT="Ka Bax Qaabka Soo Kabashada"
MOD_MENU_RECOVERY_MENU_ROOT="Soo Kabashada Menu"
MOD_MENU_SETTINGS="Dejinta"
MOD_MENU_SYSTEM="Nidaamka"
MOD_MENU_SYSTEM_INFORMATION="Macluumaadka Nidaamka"
MOD_MENU_SYSTEM_INFORMATION_DATABASE="Kaydka"
MOD_MENU_SYSTEM_INFORMATION_SYSINFO="Macluumaadka Nidaamka"
MOD_MENU_SYSTEM_PARENT_SETUP="Qaabeynta"
MOD_MENU_TEMPLATE_ADMIN_STYLES="Qaababka Qaabka Maamulka"
MOD_MENU_TEMPLATE_ADMIN_TEMPLATES="Qaab-dhismeedka Maamulka"
MOD_MENU_TEMPLATE_SITE_STYLES="Qaababka Qaabka Goobta"
MOD_MENU_TEMPLATE_SITE_TEMPLATES="Qaab-dhismeedka Goobta"
MOD_MENU_TEMPLATES="Qaab-dhismeedyada"
MOD_MENU_UPDATE="Cusbooneysiin"
MOD_MENU_UPDATE_EXTENSIONS="Kordhinta"
MOD_MENU_UPDATE_JOOMLA="Joomla"
MOD_MENU_UPDATE_SOURCES="Cusbooneysii Goobaha"
MOD_MENU_USER_PROFILE="Macluumaadkeyga"
MOD_MENU_XML_DESCRIPTION="Qaabkan wuxuu soo bandhigayaa module-ka menu-ga maamulaha."

