; Joomla! Project
; (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_SAMPLEDATA="Xog Tusaale"
MOD_SAMPLEDATA_COMPLETED="Xogta tusaalaha waa la rakibay."
MOD_SAMPLEDATA_CONFIRM_START="Socdaalku wuxuu rakibi doonaa xog tusaale ah gudaha mareegtaada Joomla. Nidaamkan ma celin kartid markuu dhammaado."
MOD_SAMPLEDATA_ERROR_RESPONSE="Waxbaa qaldamay! Fadlan xir oo dib ugu fur biraawsarka kadibna isku day mar kale!"
MOD_SAMPLEDATA_INVALID_RESPONSE="Khalad ayaa ku jira plugin-ka xogta tusaalaha. Jawaabtu sax maaha."
MOD_SAMPLEDATA_ITEM_ALREADY_PROCESSED="Xogtan tusaale ah horay ayaa loo rakibay."
MOD_SAMPLEDATA_MANAGE_SAMPLEDATA="Maamul"
MOD_SAMPLEDATA_XML_DESCRIPTION="Module-kan wuxuu kuu oggolaanayaa inaad rakibto xog tusaale ah."

