; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_LOGGED="Isticmaalayaasha soo-galay"
MOD_LOGGED_FIELD_COUNT_LABEL="Isticmaalayaasha la soo bandhigo"
MOD_LOGGED_LOGOUT="Ka bax"
MOD_LOGGED_NAME="Magac"
MOD_LOGGED_NO_SESSION_METADATA="Xogta kulanka waa naafo, ma soo bandhigi karo liiska isticmaalayaasha soo-galay."
MOD_LOGGED_TITLE="Isticmaalayaasha ugu dambeeyay ee soo-galay"
MOD_LOGGED_TITLE_1="Isticmaalaha ugu dambeeyay ee soo galay"
MOD_LOGGED_TITLE_MORE="%d Isticmaalayaal oo soo galay"
MOD_LOGGED_XML_DESCRIPTION="Qaabkan wuxuu soo bandhigayaa liiska Isticmaalayaasha soo-galay."

