; Joomla! Project
; (C) 2019 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_MESSAGES="Fariimaha"
MOD_MESSAGES_LAYOUT_DEFAULT="Caadi"
MOD_MESSAGES_XML_DESCRIPTION="Qaybtani waxay muujisaa tirada fariimaha gaarka ah waxaana loogu talagalay in lagu soo bandhigo booska 'xaalad'. Kaliya waa la soo bandhigayaa marka ay jiraan fariimo akhris u baahan."

