; Joomla! Project
; (C) 2019 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_LOGINSUPPORT="Macluumaadka Taageerada Gelitaanka"
MOD_LOGINSUPPORT_DOCUMENTATION="Dukumentiyada Joomla!"
MOD_LOGINSUPPORT_FIELD_DOCUMENTATION_URL_LABEL="URL-ka Dukumentiyada"
MOD_LOGINSUPPORT_FIELD_FORUM_URL_LABEL="URL-ka Forum"
MOD_LOGINSUPPORT_FIELD_NEWS_URL_LABEL="URL-ka Wararka"
MOD_LOGINSUPPORT_FORUM="Forum Taageerada Joomla!"
MOD_LOGINSUPPORT_HEADLINE="Waxaad ka heli kartaa caawimo halkan:"
MOD_LOGINSUPPORT_NEWS="Wararka Joomla!"
MOD_LOGINSUPPORT_TITLE="Ma u Baahan Tahay Taageero?"
MOD_LOGINSUPPORT_XML_DESCRIPTION="Qeybtaan waxay soo bandhigaysaa xiriiriyayaal waxtar leh oo ku saabsan goobaha taageerada Joomla ee shaashada gelitaanka."

