; Joomla! Project
; (C) 2019 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_PRIVACY_STATUS="Hubinta Xaalada Qarsoodiga"
MOD_PRIVACY_STATUS_CHECK_DATABASE_CONNECTION_ENCRYPTION_DISABLED="Karaamada isku xirka xogta lama hawlgelin."
MOD_PRIVACY_STATUS_CHECK_DATABASE_CONNECTION_ENCRYPTION_ENABLED="Karaamada isku xirka xogta waa la hawlgaliyay.<br><small>Waxaa lagu karaamaynayaa dhammaan isku xiriiradii xogta %s</small>"
MOD_PRIVACY_STATUS_XML_DESCRIPTION="Qaabka Hubinta Xaalada Qarsoodiga wuxuu muujinayaa macluumaadka ku saabsan xaaladda qarsoodida boggaaga."

