; Joomla! Project
; (C) 2006 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_SUBMENU="Liiska Dashboard-ka Maamulka"
MOD_SUBMENU_FIELD_MENUTYPE_LABEL="Menu"
MOD_SUBMENU_FIELD_MENUTYPE_OPTION_PREDEFINED="Isticmaal Diyaar-garow Hore"
MOD_SUBMENU_FIELD_PRESET_LABEL="Diyaar-garow"
MOD_SUBMENU_XML_DESCRIPTION="Qaybtani waxay soo bandhigaysaa ururinta menus ee dashboard maamulka."

