; Joomla! Project
; (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_BEHAVIOUR_COMPAT="Habdhaqan - Iswaafajin Dib-u-noqosho"
PLG_COMPAT_FIELD_CLASSES_ALIASES_LABEL="Magacyo kale Oo Loogu Talagalay Fasallada"
PLG_COMPAT_FIELD_CLASSES_ALIASES_DESCRIPTION="Ku dar magacyo kale oo loogu talagalay fasallada kuwaas oo magacyo cusub helay ama loo raray boos magac gaar ah."
PLG_COMPAT_FIELD_ES5_ASSETS_DESCRIPTION="Fur xulashadan haddii kordhintaadu u baahan tahay waxyaabaha *.es5 oo keentay khalad. Waxyaabaha la bixiyey waa madhan yihiin laakiin waxay ka hortagayaan khaladka."
PLG_COMPAT_FIELD_ES5_ASSETS_LABEL="Xirmooyinka ES5"
PLG_COMPAT_FIELD_REMOVED_ASSETS_DESCRIPTION="Fur xulashadan haddii kordhintaadu u baahan tahay xirmooyin laga saaray oo keentay khalad. Xirmooyinka la bixiyey waa madhan yihiin laakiin waxay ka hortagayaan khaladka."
PLG_COMPAT_FIELD_REMOVED_ASSETS_LABEL="Xirmooyinka Laga Saaray"
PLG_COMPAT_XML_DESCRIPTION="Haddii aad isticmaasho kordhinno aan isticmaalin heerarka koodhka Joomla hadda jira markaa plugin-kan, marka la kiciyo, wuxuu bixin doonaa iswaafajin dib-u-noqosho nooca weyn ee hore."

