; Joomla! Project
; (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SCHEMAORG_BLOGPOSTING="Schema.org - BlogPosting"
PLG_SCHEMAORG_BLOGPOSTING_DESCRIPTION_LABEL="Macluumaad dheeraad ah oo ku saabsan nooca BlogPosting ee Schema.org ayaa laga helayaa <a href=\"https://schema.org/BlogPosting\" target=\"_blank\" rel=\"noopener noreferrer\">https://schema.org/BlogPosting</a>"
PLG_SCHEMAORG_BLOGPOSTING_FIELD_ADDRESS_LABEL="Cinwaanka"
PLG_SCHEMAORG_BLOGPOSTING_FIELD_AUTHOR_LABEL="Qoraa"
PLG_SCHEMAORG_BLOGPOSTING_FIELD_DATE_MODIFIED_LABEL="Taariikhda La Bedelay"
PLG_SCHEMAORG_BLOGPOSTING_FIELD_DATE_PUBLISHED_LABEL="Taariikhda La Daabacay"
PLG_SCHEMAORG_BLOGPOSTING_FIELD_DESCRIPTION_LABEL="Sharaxaad"
PLG_SCHEMAORG_BLOGPOSTING_FIELD_EMAIL_LABEL="Iimayl"
PLG_SCHEMAORG_BLOGPOSTING_FIELD_GENERIC_FIELD_LABEL="Garashan Guud"
PLG_SCHEMAORG_BLOGPOSTING_FIELD_GENERIC_TITLE_LABEL="Cinwaan"
PLG_SCHEMAORG_BLOGPOSTING_FIELD_GENERIC_VALUE_LABEL="Qiime"
PLG_SCHEMAORG_BLOGPOSTING_FIELD_HEADLINE_LABEL="Madaxa Sare"
PLG_SCHEMAORG_BLOGPOSTING_FIELD_IMAGE_LABEL="Sawir"
PLG_SCHEMAORG_BLOGPOSTING_FIELD_LOCALITY_LABEL="Degaan"
PLG_SCHEMAORG_BLOGPOSTING_FIELD_LOGO_LABEL="Astaanta"
PLG_SCHEMAORG_BLOGPOSTING_FIELD_NAME_LABEL="Magaca"
PLG_SCHEMAORG_BLOGPOSTING_FIELD_ORGANIZATION_LABEL="Urur"
PLG_SCHEMAORG_BLOGPOSTING_FIELD_PERSON_LABEL="Qof"
PLG_SCHEMAORG_BLOGPOSTING_FIELD_POSTAL_CODE_LABEL="Lambarka Boostada"
PLG_SCHEMAORG_BLOGPOSTING_FIELD_STREET_ADDRESS_LABEL="Cinwaanka Waddada"
PLG_SCHEMAORG_BLOGPOSTING_FIELD_TYPE_LABEL="Nooca"
PLG_SCHEMAORG_BLOGPOSTING_FIELD_URL_LABEL="Url"
PLG_SCHEMAORG_BLOGPOSTING_XML_DESCRIPTION="Waxay ku dartaa Blog sidii nooc cusub oo shey ontstay dhamaan sheyaasha jira."

