; Joomla! Project
; (C) 2011 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_QUICKICON_JOOMLAUPDATE="Asta Degdeg Ah - Ogeysiiska Cusboonaysiinta Joomla"
PLG_QUICKICON_JOOMLAUPDATE_CHECKING="Hubinta Joomla &hellip;"
PLG_QUICKICON_JOOMLAUPDATE_ERROR="Joomla aan la aqoon &hellip;"
PLG_QUICKICON_JOOMLAUPDATE_GROUP_DESC="Kooxda aaladdan (qiimahan waxaa loo barbar dhigaa qiimaha kooxda ee loo isticmaalo qaybo <strong>Ikono Degdeg ah</strong> si loogu daro ikonada)."
PLG_QUICKICON_JOOMLAUPDATE_GROUP_LABEL="Kooxda"
PLG_QUICKICON_JOOMLAUPDATE_UPDATEFOUND="%s Waa La Heli Karaa - Hadda Cusboonaysii!"
PLG_QUICKICON_JOOMLAUPDATE_UPTODATE="Joomla waa mid casri ah."
PLG_QUICKICON_JOOMLAUPDATE_XML_DESCRIPTION="Waxay kala hubisaa casriyeynta Joomla waxayna ku ogeysiinaysaa markaad booqato bogga Dashboard-ka Guriga."

