; Joomla! Project
; (C) 2020 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_ACCESSIBILITY="Nidaamka - Astaamo Dheeraad ah oo Helitaan ah"
PLG_SYSTEM_ACCESSIBILITY_XML_DESCRIPTION="Kordhintahani wuxuu ku daraa baararka helidda goobtaada oo leh doorashooyin helitaan dheeraad ah. Marka la hawlgeliyo baararka waxaa la furi karaa midkoodna mouse ama furaha kulul <strong>CTRL + ALT + A</strong>, ama <strong>CTRL + OPTION + A</strong> ee MacOS."

