; Joomla! Project
; (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FIELDS_RADIO="Goobo - Raadiyo"
PLG_FIELDS_RADIO_XML_DESCRIPTION="Kani qalabkan wuxuu kuu ogolaanayaa inaad abuurto goobo cusub oo nooca 'raadiyo' ah meel walba oo ka mid ah kordhinta taageerada lagu habeyn karo."

