; Joomla! Project
; (C) 2007 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_AUTHENTICATION_LDAP="Oggolaanshaha - LDAP"  
PLG_LDAP_XML_DESCRIPTION="<p>Waxay qabataa Oggolaanshaha Isticmaalaha ee ku lifaaqan server-ka LDAP.</p><p><strong>Digniin! Waa inaad leedahay ugu yaraan hal plugin oo oggolaansho ah oo karti leh ama waxaad lumi doontaa dhammaan gelitaanka boggaaga.</strong></p>"

