; Joomla! Project
; (C) 2013 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_MULTIFACTORAUTH_YUBIKEY="Aqoonsi badan - YubiKey"
PLG_MULTIFACTORAUTH_YUBIKEY_XML_DESCRIPTION="U ogolaanaya isticmaalayaasha bartaada inay isticmaalaan Aqoonsi badan iyagoo adeegsanaya YubiKey qalab ammaan ah. Isticmaalayaashu waxay u baahan yihiin YubiKey-kooda gaarka ah oo laga heli karo <a href=\"https://www.yubico.com\" target=\"_blank\" rel=\"noopener noreferrer\">www.yubico.com</a>. Si ay u isticmaalaan Aqoonsi badan, isticmaalayaashu waa inay wax ka beddelaan macluumaadkooda isticmaalaha oo ay dhaqaajiyaan Aqoonsi badan."

