; Joomla! Project
; (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FILESYSTEM_LOCAL="Nidaamka Faylasha - Maxalli"
PLG_FILESYSTEM_LOCAL_DEFAULT_NAME="Maxalli"
PLG_FILESYSTEM_LOCAL_DIRECTORIES_DIRECTORY_LABEL="Xulo Faylalka"
PLG_FILESYSTEM_LOCAL_DIRECTORIES_DIRECTORY_THUMBNAILS_LABEL="Abuur Sawirro Yaryar"
PLG_FILESYSTEM_LOCAL_DIRECTORIES_LABEL="Faylalka"
PLG_FILESYSTEM_LOCAL_XML_DESCRIPTION="Fiilooyinka nidaamka fayl waxay qeexaan hal ama dhowr fayl oo maxalli ah si loo kaydiyo faylladaada warbaahineed."

