; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_AUTHENTICATION_LDAP="Saxiixidda - LDAP"
PLG_LDAP_FIELD_AUTHMETHOD_LABEL="Habka Oggolaanshaha"
PLG_LDAP_FIELD_BASEDN_LABEL="Base DN"
PLG_LDAP_FIELD_CACERT_LABEL="Jidka shahaadada server-ka"
PLG_LDAP_FIELD_CACERT_DESC="Jidka buuxa ee faylka ama galka oo Joomla ka heli karo shahaadada server-ka LDAP (Certificate Authority). Haddii tani ay bannaan tahay, nidaamka caadada ah ee ikhtiyaarka macmiilka TLS_CACERT iyo TLS_CACERTDIR ee LDAP ayaa la adeegsanayaa."
PLG_LDAP_FIELD_ENCRYPTION_LABEL="Amniga Isku Xirka"
PLG_LDAP_FIELD_EMAIL_DESC="Astaanta LDAP oo leh cinwaanka iimaylka ee Isticmaalaha."
PLG_LDAP_FIELD_EMAIL_LABEL="Midhilka: Iimaylka"
PLG_LDAP_FIELD_FULLNAME_DESC="Astaanta LDAP oo leh magaca buuxa ee Isticmaalaha."
PLG_LDAP_FIELD_FULLNAME_LABEL="Midhilka: Magaca Buuxa"
PLG_LDAP_FIELD_HOST_LABEL="Martigeliyaha"
PLG_LDAP_FIELD_IGNORE_REQCERT_TLS_LABEL="Dhaafi Shahaadada"
PLG_LDAP_FIELD_LDAPDEBUG_DESC="Koobiyeynayaa cayayaanka ku socda heerka 7"
PLG_LDAP_FIELD_LDAPDEBUG_LABEL="Cayayaanka"
PLG_LDAP_FIELD_PASSWORD_DESC="Furaha Isku Xirka waa eray-ga-asraarta akoonka maamulka."
PLG_LDAP_FIELD_PASSWORD_LABEL="Furaha Isku Xirka"
PLG_LDAP_FIELD_PORT_LABEL="Deked"
PLG_LDAP_FIELD_REFERRALS_DESC="Ikhtiyaarkan wuxuu dejiyaa qiimaha calanka LDAP_OPT_REFERRALS. Waxaad u baahan tahay inaad dhigto Maya server-yada Windows 2003."
PLG_LDAP_FIELD_REFERRALS_LABEL="Raac Gudbinta"
PLG_LDAP_FIELD_SEARCHSTRING_DESC="Xadhko weyddi ah oo loo isticmaalo in lagu raadiyo Isticmaale la siiyay. Erayga [search] waxaa si firfircoon u beddela taageeraha login-ka ee Isticmaalaha. Xadhko tusaale ah waa: uid=[search]. Xargo badan ayaa loo adeegsan karaa oo lagu dhexyaaciyey fiiq. Waxa loo isticmaalaa ka dib markii horay loogu xidho dhammaan hababka."
PLG_LDAP_FIELD_SEARCHSTRING_LABEL="Xadhka Raadinta"
PLG_LDAP_FIELD_UID_DESC="Astaanta LDAP oo leh Aqoonsiga Isticmaalaha ee Login ID. Wixii Active Directory tan waa sAMAccountName."
PLG_LDAP_FIELD_UID_LABEL="Midhilka: Aqoonsiga Isticmaalaha"
PLG_LDAP_FIELD_USERNAME_DESC="Furaha Isku Xirka ee Isku Xirka iyo Furaha Isku Xirka waxay qeexayaan halbeega isku xidhka ee marxaladda baarista DN. Laba ikhtiyaar ayaa jira: baarista DN aan la qarin (Labada goobood ka tag oo bannaan) iyo isku xirnaanta maamulka (Furaha Isku Xirka waa magaca isticmaale ee akoonka maamulka, tusaale ahaan Maamule). Kaliya loo isticmaalo habka Xidhiidhka iyo Raadinta."
PLG_LDAP_FIELD_USERNAME_LABEL="Magaca Isticmaalaha ee Isku Xirka"
PLG_LDAP_FIELD_USERSDN_DESC="Erayga [username] si firfircoon ayaa loo bedelay sida Login-ka uu isticmaale bixiyo. Tusaale xarriiq ah waa: uid=[username], dc=my-domain, dc=com. Xadhko dhowr ah ayaa la isticmaali karaa, oo kala soocan semikolooyaal. Kaliya waxaa loo isticmaalaa habka Xiriir Toos ah sida Isticmaale."
PLG_LDAP_FIELD_USERSDN_LABEL="DN-ka Isticmaalaha"
PLG_LDAP_FIELD_V3_DESC="Muuqaalka caadiga ah waa LDAP2, laakiin noocyada ugu dambeeyay ee OpenLdap waxay dalbanayaan macaamiisha inay isticmaalaan LDAPV3."
PLG_LDAP_FIELD_V3_LABEL="LDAP V3"
PLG_LDAP_FIELD_VALUE_BINDSEARCH="Xidh oo Raadi"
PLG_LDAP_FIELD_VALUE_BINDUSER="Xidhiidh Toos ah sida Isticmaale"
PLG_LDAP_FIELD_VALUE_ENCRYPTIONNONE="Midna"
PLG_LDAP_FIELD_VALUE_ENCRYPTIONSSL="SSL/TLS"
PLG_LDAP_FIELD_VALUE_ENCRYPTIONTLS="STARTTLS"
PLG_LDAP_XML_DESCRIPTION="<p>Waxay ka shaqeysaa Aqoonsiga Isticmaalaha ee server-ka LDAP.</p><p><strong>Digniin! Waa inaad u adeegsato midkamida plugin Authentication ama waxaad waayi doontaa marin u helka goobta.</strong></p>"

