; Joomla! Project
; (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_QUICKICON_EOS="Asta Degdeg ah - Ogeysiiska Dhammaadka Taageerada Joomla 5"
PLG_QUICKICON_EOS_MESSAGE_ERROR_SUPPORT_ENDED="<p>Taageerada noocaaga Joomla 5 ayaa dhammaatay. <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\">U cusbooneysii Joomla 6</a> sida ugu dhaqsaha badan ee suurtogalka ah.</p>"
PLG_QUICKICON_EOS_MESSAGE_INFO_01="<p>Joomla 6 way timid! Wax walba ka ogow waxa Joomla 6 kuu hayso. Fiiri bogga bilowga ah ee <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\">sifooyinka Joomla 6</a> iyo horumarka.</p>"
PLG_QUICKICON_EOS_MESSAGE_INFO_02="<p>Goorma ayaa la gaadhay wakhtigii lagu cusboonaysiin lahaa Joomla 6? Marka kordhinada boggaagu ubaahanyihiin ay la jaan qaadaan. Baro <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\">sidii loo isticmaali lahaa Hubiyaha Hor-cusbooneysiinta</a>.</p>"
PLG_QUICKICON_EOS_MESSAGE_WARNING_SECURITY_ONLY="<p>Joomla 5 waxay gashay hab amni oo keliya. Taageeradu waxay dhammaanaysaa %1$s. Biloow <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\">qorsheynta si aad ugu cusboonaysiiso</a> Joomla 6 maanta.</p>"
PLG_QUICKICON_EOS_MESSAGE_WARNING_SUPPORT_ENDING="<p>Taageeradu waxay dhammaanaysaa %1$s ee Joomla 5 <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\">u cusbooneysii Joomla 6</a> sida ugu dhaqsaha badan ee suurtogalka ah.</p>"
PLG_QUICKICON_EOS_SNOOZE_BUTTON="Habeeci fariintan dhammaan isticmaalayaasha"
PLG_QUICKICON_EOS_XML_DESCRIPTION="Waxay hubisaa gabagabada taageerada Joomla 5 waxayna kugu soo ogeysiin markaad booqato bogga Maamulida Dhexe."

