; Joomla! Project
; (C) 2010 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_LANGUAGEFILTER="Nidaam - Filterka Luqadda"
PLG_SYSTEM_LANGUAGEFILTER_BROWSER_SETTINGS="Dejinta Shaashadda"
PLG_SYSTEM_LANGUAGEFILTER_ERROR_NO_CONTENT_LANGUAGE="Waxaad leedahay wax aan la daabicin oo luuqad ah, balse waxaad hawlgelisay kala-saarida plugin-ka Filterka Luqadda. Taas ayaa sababi doonta qaladaad badan!"
PLG_SYSTEM_LANGUAGEFILTER_FIELD_ALTERNATE_META_LABEL="Ku dar Calaamadaha Meta ee Kale"
PLG_SYSTEM_LANGUAGEFILTER_FIELD_AUTOMATIC_CHANGE_LABEL="Isbeddelka Luqadda Tooska ah"
PLG_SYSTEM_LANGUAGEFILTER_FIELD_COOKIE_LABEL="Nolosha Buskudka"
PLG_SYSTEM_LANGUAGEFILTER_FIELD_DETECT_BROWSER_LABEL="Xulashada Luqadda ee Booqdayaasha Cusub"
PLG_SYSTEM_LANGUAGEFILTER_FIELD_ITEM_ASSOCIATIONS_LABEL="Isku-xirnaanta Alaabta"
PLG_SYSTEM_LANGUAGEFILTER_FIELD_REMOVE_DEFAULT_PREFIX_LABEL="Ka saar Xeerka Luqadda ee URL"
PLG_SYSTEM_LANGUAGEFILTER_FIELD_XDEFAULT_LABEL="Ku dar x-default Meta Tag"
PLG_SYSTEM_LANGUAGEFILTER_FIELD_XDEFAULT_LANGUAGE_LABEL="Luqadda x-default"
PLG_SYSTEM_LANGUAGEFILTER_OPTION_DEFAULT_LANGUAGE="Luqadda hore ee hore"
PLG_SYSTEM_LANGUAGEFILTER_OPTION_SESSION="Fadhiga"
PLG_SYSTEM_LANGUAGEFILTER_OPTION_YEAR="Sannad"
PLG_SYSTEM_LANGUAGEFILTER_PRIVACY_CAPABILITY_LANGUAGE_COOKIE="Bogga taageera luqado badan, plugin-kan waxaa lagu dejin karaa si uu ugu dhigo buskud biraawsarka isticmaale si uu xusuusto doorashada luqadda isticmaale. Buskudkan waxaa loo isticmaalaa in isticmaale lagu hagaajiyo luqadda ay doorbidaan marka ay booqanayaan bogga isla markaana bilaabayo kulan cusub. Magaca buskudka waxaa lagu saleynayaa hash loo sameeyey si aan joogta aheyn, sidaas darteedna ma lahan aqoonsi joogto ah."
PLG_SYSTEM_LANGUAGEFILTER_SITE_LANGUAGE="Luqadda Goobta"
PLG_SYSTEM_LANGUAGEFILTER_XML_DESCRIPTION="Plugin-kan wuxuu hofinayaa waxyaabaha la soo bandhigo iyadoo ku salaysan luqadda."

