; Joomla! Project
; (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SCHEMAORG_JOBPOSTING_DESCRIPTION_LABEL="Macluumaad dheeraad ah oo ku saabsan nooca ShaqoBixinta Schema.org waxaa laga heli karaa <a href=\"https://schema.org/JobPosting\" target=\"_blank\" rel=\"noopener noreferrer\">https://schema.org/JobPosting</a>"

PLG_SCHEMAORG_JOBPOSTING_FIELD_ADDRESS_COUNTRY_LABEL="Waddan"

PLG_SCHEMAORG_JOBPOSTING_FIELD_ADDRESS_LABEL="Cinwaan"

PLG_SCHEMAORG_JOBPOSTING_FIELD_ADDRESS_REGION_LABEL="Gobol"

PLG_SCHEMAORG_JOBPOSTING_FIELD_APPLICANT_LOCATION_REQUIREMENT_COUNTRY_LABEL="Waddan"

PLG_SCHEMAORG_JOBPOSTING_FIELD_APPLICANT_LOCATION_REQUIREMENT_LABEL="Shuruudaha Meesha Codsadaha"

PLG_SCHEMAORG_JOBPOSTING_FIELD_BASESALARY_LABEL="Mushahar Asal"

PLG_SCHEMAORG_JOBPOSTING_FIELD_BASESALARY_UNIT_OPTION_DAY="Maalin"

PLG_SCHEMAORG_JOBPOSTING_FIELD_BASESALARY_UNIT_OPTION_HOUR="Saacad"

PLG_SCHEMAORG_JOBPOSTING_FIELD_BASESALARY_UNIT_OPTION_MONTH="Bishii"

PLG_SCHEMAORG_JOBPOSTING_FIELD_BASESALARY_UNIT_OPTION_WEEK="Toddobaad"

PLG_SCHEMAORG_JOBPOSTING_FIELD_BASESALARY_UNIT_OPTION_YEAR="Sannad"

PLG_SCHEMAORG_JOBPOSTING_FIELD_CURRENCY_LABEL="Lacag"

PLG_SCHEMAORG_JOBPOSTING_FIELD_DATE_LABEL="Taariikh"

PLG_SCHEMAORG_JOBPOSTING_FIELD_DATEPOSTED_LABEL="Taariikhda La Dhajiyay"

PLG_SCHEMAORG_JOBPOSTING_FIELD_DESCRIPTION_LABEL="Sharaxaad"

PLG_SCHEMAORG_JOBPOSTING_FIELD_EMAIL_LABEL="Email"

PLG_SCHEMAORG_JOBPOSTING_FIELD_EMPLOYMENTTYPE_LABEL="Nooca Shaqaalaysiinta"

PLG_SCHEMAORG_JOBPOSTING_FIELD_GENERIC_FIELD_LABEL="Goob Guud"

PLG_SCHEMAORG_JOBPOSTING_FIELD_GENERIC_TITLE_LABEL="Cinwaan"

PLG_SCHEMAORG_JOBPOSTING_FIELD_GENERIC_VALUE_LABEL="Qiimo"

PLG_SCHEMAORG_JOBPOSTING_FIELD_HIRINGORGANIZATION_LABEL="Ururka Shaqaaleysiinta"

PLG_SCHEMAORG_JOBPOSTING_FIELD_HIRINGORGANIZATION_NAME_LABEL="Cinwaan"

PLG_SCHEMAORG_JOBPOSTING_FIELD_HIRINGORGANIZATION_TYPE_LABEL="Nooc"

PLG_SCHEMAORG_JOBPOSTING_FIELD_HYBRID_LABEL="Isku-dhafan"
PLG_SCHEMAORG_JOBPOSTING_FIELD_IDENTIFIER_LABEL="Aqoonsi"
PLG_SCHEMAORG_JOBPOSTING_FIELD_IMAGE_LABEL="Astaanta"
PLG_SCHEMAORG_JOBPOSTING_FIELD_JOBLOCATION_LABEL="Goobta Shaqada"
PLG_SCHEMAORG_JOBPOSTING_FIELD_JOBLOCATIONTYPE_LABEL="Sharaxaadda Goobta Shaqada"
PLG_SCHEMAORG_JOBPOSTING_FIELD_JOBSTARTDATE_DATE_LABEL="Taariikh"
PLG_SCHEMAORG_JOBPOSTING_FIELD_JOBSTARTDATE_LABEL="Taariikhda Bilaabashada"
PLG_SCHEMAORG_JOBPOSTING_FIELD_JOBSTARTDATE_TEXT_HINT="UG"
PLG_SCHEMAORG_JOBPOSTING_FIELD_JOBSTARTDATE_TEXT_LABEL="Qoraal"
PLG_SCHEMAORG_JOBPOSTING_FIELD_JOBSTARTDATE_TYPE_LABEL="Nooc"
PLG_SCHEMAORG_JOBPOSTING_FIELD_LOCALITY_LABEL="Degmo"
PLG_SCHEMAORG_JOBPOSTING_FIELD_MAXVALUE_LABEL="Ugu Badnaan"
PLG_SCHEMAORG_JOBPOSTING_FIELD_MINVALUE_LABEL="Ugu Yaraan"
PLG_SCHEMAORG_JOBPOSTING_FIELD_NAME_LABEL="Magac"
PLG_SCHEMAORG_JOBPOSTING_FIELD_ONSITE_LABEL="Goobta Shaqada"
PLG_SCHEMAORG_JOBPOSTING_FIELD_ORGANIZATION_LABEL="Urur"
PLG_SCHEMAORG_JOBPOSTING_FIELD_PERSON_LABEL="Qof"
PLG_SCHEMAORG_JOBPOSTING_FIELD_POSTAL_CODE_LABEL="Lambarka Boostada"
PLG_SCHEMAORG_JOBPOSTING_FIELD_SALARY_VALUE_LABEL="Lacag"
PLG_SCHEMAORG_JOBPOSTING_FIELD_STREET_ADDRESS_LABEL="Cinwaanka Jidka"
PLG_SCHEMAORG_JOBPOSTING_FIELD_TELECOMMUTE_LABEL="Shaqo Guriga"
PLG_SCHEMAORG_JOBPOSTING_FIELD_TEXT_LABEL="Qoraal"
PLG_SCHEMAORG_JOBPOSTING_FIELD_TITLE_LABEL="Magac"
PLG_SCHEMAORG_JOBPOSTING_FIELD_UNITTEXT_LABEL="Unuga Lacagta"
PLG_SCHEMAORG_JOBPOSTING_FIELD_URL_LABEL="URL"
PLG_SCHEMAORG_JOBPOSTING_FIELD_VALIDTHROUGH_LABEL="Ansax ilaa"
PLG_SCHEMAORG_JOBPOSTING_FIELD_VALUE_LABEL="Qiimaha"
PLG_SCHEMAORG_JOBPOSTING="Schema.org - ShaqoKuShaandeyn"
PLG_SCHEMAORG_JOBPOSTING_XML_DESCRIPTION="Waxay ku dareysaa ShaqoKuShaandeyn nooc cusub oo sheybaar ah sheybaarada jira."

