; Joomla! Project
; (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_CONTENT_FIELDS="Mawduuc - Goobaha"
PLG_CONTENT_FIELDS_XML_DESCRIPTION="<p>Kani waa isku xiraha kuu suurtagelinaya inaad soo bandhigto goob khaas ah oo lagu soo geliyey plugin-ka 'Button - Fields' ama adigoo isticmaalaya xarfaha: {field #} si toos ah aagga tifaftiraha.</p><p><strong>Habka Macquul Ah:</strong></p><ul><li><code>{field 1}</code> waxay soo bandhigi doontaa goobta ID-ga 1</li><li><code>{field 1,foo}</code> waxaa loogu soo bandhigi doonaa goobta la doortay iyadoo la adeegsanayo qaabka kale 'foo'.</li><li><code>{fieldgroup 2}</code> wuxuu soo bandhigi doonaa dhammaan goobaha ku yaal fieldgroup-ka ID-ga 2.</li></ul>"

