; Joomla! Project
; (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FIELDS_USER="Goobo - Isticmaale"
PLG_FIELDS_USER_XML_DESCRIPTION="Qalabkan wuxuu kuu oggolaanayaa inaad abuurto goobo cusub oo nooca 'isticmaale' ah qaybo kasta oo meelo caado ah la taageerayo."

