; Joomla! Project
; (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_TASK_SITE_STATUS="Hawlgabka - Xaaladda Goobta"
PLG_TASK_SITE_STATUS_DESC="Waxaa laga rogaa xaaladda goobta hawlgab mar kasta oo la shaqeynayo."
PLG_TASK_SITE_STATUS_ERROR_CONFIGURATION_PHP_NOTUNWRITABLE="Lama dhigi karin configuration.php mid aan la qori karin."
PLG_TASK_SITE_STATUS_ERROR_CONFIGURATION_PHP_NOTWRITABLE="Lama dhigi karin configuration.php mid la qori karo."
PLG_TASK_SITE_STATUS_ERROR_WRITE_FAILED="Looma qori karin faylka habaynta!"
PLG_TASK_SITE_STATUS_ROUTINE_END_LOG_MESSAGE="Koodhka jawaabta ToggleOffline waa: %1$d. Wakhtiga Hawlgalka: %2$.2f ilbiriqsi."
PLG_TASK_SITE_STATUS_TASK_LOG_SITE_STATUS="Goobtu waxay ahayd %1$s, hadda waa %2$s."
PLG_TASK_SITE_STATUS_SET_OFFLINE_DESC="Waxay dhigaysaa xaaladda goobta mid aan toos ahayn hawlgal kasta."
PLG_TASK_SITE_STATUS_SET_OFFLINE_ROUTINE_END_LOG_MESSAGE="Koodhka jawaabta SetOffline waa: %1$d. Wakhtiga Hawlgalka: %2$.2f ilbiriqsi."
PLG_TASK_SITE_STATUS_SET_OFFLINE_TITLE="Dhig Goobta Aan Toos Ahayn"
PLG_TASK_SITE_STATUS_SET_ONLINE_DESC="Waxay dhigaysaa xaaladda goobta mid toos ah hawlgal kasta."
PLG_TASK_SITE_STATUS_SET_ONLINE_ROUTINE_END_LOG_MESSAGE="Koodhka jawaabta SetOnline waa: %1$d. Wakhtiga Hawlgalka: %2$.2f ilbiriqsi."
PLG_TASK_SITE_STATUS_SET_ONLINE_TITLE="Dhig Goobta Toos Ah"
PLG_TASK_SITE_STATUS_TITLE="Dhig Aan Toos Ahayn"
PLG_TASK_SITE_STATUS_XML_DESCRIPTION="Waxay bixisaa hawlgallo shaqo si loo badalo xaaladda goobta ee aan toos ahayn."

