; Joomla! Project
; (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_MULTIFACTORAUTH_EMAIL="Aqoonsiga Laba-Qodob - Koodhka Aqoonsiga ee Email"
PLG_MULTIFACTORAUTH_EMAIL_CONFIG_FORCE_ENABLE_DESC="Ma si otomaatig ah ayaan u dari karaa Koodhka Aqoonsiga ee Email-ka doorasho ahaan <em>dhammaan</em> isticmaalayaasha? Waxay faa'iido u leedahay isticmaalayaasha lumiyay marin u helida xaqiijiyehooda ugu weyn oo aan haynin nuqul ka mid ah koodhadhka keydka iyada oo lagu bixinayo maaraynta iyo amniga laga fogaado."
PLG_MULTIFACTORAUTH_EMAIL_CONFIG_FORCE_ENABLE_LABEL="Dhibic si uu u howlgeliyo"
PLG_MULTIFACTORAUTH_EMAIL_CONFIG_TIMESTEP_120="Laba daqiiqo (talo)"
PLG_MULTIFACTORAUTH_EMAIL_CONFIG_TIMESTEP_180="Saddex daqiiqo"
PLG_MULTIFACTORAUTH_EMAIL_CONFIG_TIMESTEP_300="Shan daqiiqo"
PLG_MULTIFACTORAUTH_EMAIL_CONFIG_TIMESTEP_30="Kala bar daqiiqo"
PLG_MULTIFACTORAUTH_EMAIL_CONFIG_TIMESTEP_60="Hal daqiiqo"
PLG_MULTIFACTORAUTH_EMAIL_CONFIG_TIMESTEP_DESC="Koodh cusub ayaa la abuuraa wakhti kasta oo daqiiqado ah. Fadlan ogow in koodh la sameeyay uu yahay mid ansax ah ugu yaraan wakhtigan iyo ugu badnaan labo jeer intaas ka badan. Muddada kor ku xusan waxay kordhisaa suurtagalnimada inuu koodhka la jebiyo, sidaas darteed waxaa yara amniga goobtaada. Madaxa laba daqiiqo waa trade-off wanaagsan oo u dhaxeeya isticmaal mashquul iyo amniga."
PLG_MULTIFACTORAUTH_EMAIL_CONFIG_TIMESTEP_LABEL="Muddada Abuurista Koodhka"
PLG_MULTIFACTORAUTH_EMAIL_EMAIL_BODY="Aqoonsiga Laba-Qodob ee {SITENAME}. Koodhkaaga aqoonsiga waa {CODE}."
PLG_MULTIFACTORAUTH_EMAIL_EMAIL_SUBJECT="Koodhkaaga {SITENAME} waa -{CODE}-"
PLG_MULTIFACTORAUTH_EMAIL_ERR_INVALID_CODE="Koodh aan ansax ahayn ama dhacay. Fadlan ku soo celi bogga si aad isugu dirto koodh cusub. Hubi inaad galaan koodhka daqiiqado laba ah markaad codsato koodhka."
PLG_MULTIFACTORAUTH_EMAIL_LBL_DISPLAYEDAS="Koodhka Email-ka"
PLG_MULTIFACTORAUTH_EMAIL_LBL_LABEL="Koodhka Aqoonsiga"
PLG_MULTIFACTORAUTH_EMAIL_LBL_PRE_MESSAGE="Waxaad ku heshay koodh aqoonsiga LabaQodob ah oo lix eray ah emailkaaga. Fadlan geli hoosta."
PLG_MULTIFACTORAUTH_EMAIL_LBL_SETUP_PLACEHOLDER="Lix lambar koodh aqoonsi"
PLG_MULTIFACTORAUTH_EMAIL_LBL_SHORTINFO="Hel lix koodh laba eray ah oo email ku ah."
PLG_MULTIFACTORAUTH_EMAIL_MAIL_MAIL_DESC="Waxaa loo diray isticmaalayaasha bogga Aqoonsiga Laba-Qodob marka la isticmaalayo fursadda \"Koodhka Aqoonsiga ee Email-ka\"."
PLG_MULTIFACTORAUTH_EMAIL_MAIL_MAIL_TITLE="Koodhka waxaa lagu soo diray email-ka"
PLG_MULTIFACTORAUTH_EMAIL_XML_DESCRIPTION="Isticmaal wakhti xaddidan, lix lambar koodh amni oo lagugu soo diro email."

