; Joomla! Project
; (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FIELDS_TEXT="Beeraha - Qoraal"
PLG_FIELDS_TEXT_XML_DESCRIPTION="Kuwan plugin ayaa ku ogolaanaya inaad abuurto beero cusub oo nooca 'qoraalka' ah ee kordhiyeyaasha kasta oo beero caado ah ay taageeraan."

