; Joomla! Project
; (C) 2011 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FINDER_CATEGORIES="Raadinta Caqliga - Qaybaha"
PLG_FINDER_CATEGORIES_FIELD_SEARCH_ARCHIVED_DESC="Marka aad badasho goobtan, waa inaad orodsiisaa amarka tusmada ee Raadinta Caqliga ka hor inta aanay saamayn."
PLG_FINDER_CATEGORIES_FIELD_SEARCH_ARCHIVED_LABEL="Raadi Mawduuca La Kaydiyay"
PLG_FINDER_CATEGORIES_TAXONOMIES_LABEL="Canshuuraha si loo tixraaco"
PLG_FINDER_CATEGORIES_TAXONOMIES_LANGUAGE="Luqadda"
PLG_FINDER_CATEGORIES_TAXONOMIES_TYPE="Nooc"
PLG_FINDER_CATEGORIES_XML_DESCRIPTION="Plugins-kan waxa uu qoraal ku tiriyaa Joomla! Qaybaha."

