; Joomla! Project
; (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FIELDS_INTEGER="Goobo - Tiro Dhan"
PLG_FIELDS_INTEGER_XML_DESCRIPTION="Qalabkan wuxuu kuu ogolaanayaa inaad abuurto goobo cusub oo nooca 'tiro dhan' ah meel kasta oo lagu taageero goobo gaar ah."

