; Joomla! Project
; (C) 2016 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_INSTALLER_PACKAGEINSTALLER_DRAG_FILE_HERE="Jiita oo siidaa faylka halkan si aad u geliso."
PLG_INSTALLER_PACKAGEINSTALLER_EXTENSION_PACKAGE_FILE="Faylka xirmada fidinta"
PLG_INSTALLER_PACKAGEINSTALLER_INSTALLING="Rakibaya &hellip;"
PLG_INSTALLER_PACKAGEINSTALLER_NO_PACKAGE="Fadlan xulo xirmo aad ku geli karto."
PLG_INSTALLER_PACKAGEINSTALLER_PLUGIN_XML_DESCRIPTION="Kusligan waxa uu kuu ogolaanayaa inaad ku rakibto fidinta kombiyuutarkaaga maxaliga ah."
PLG_INSTALLER_PACKAGEINSTALLER_SELECT_FILE="Ama eeg faylka"
PLG_INSTALLER_PACKAGEINSTALLER_UPLOAD_AND_INSTALL="Ku geli & Rakib"
PLG_INSTALLER_PACKAGEINSTALLER_UPLOAD_ERROR_EMPTY="Khalad: Server-ku wuxuu soo celiyaa jawaab madhan."
PLG_INSTALLER_PACKAGEINSTALLER_UPLOAD_ERROR_UNKNOWN="Khalad: Khalad aan la garanayn ama natiijo aan sax ahayn oo JSON ah."
PLG_INSTALLER_PACKAGEINSTALLER_UPLOAD_INSTALL_JOOMLA_EXTENSION="Ku geli & Rakib Fidinta Joomla"
PLG_INSTALLER_PACKAGEINSTALLER_UPLOAD_PACKAGE_FILE="Ku geli Faylka Xirmada"
PLG_INSTALLER_PACKAGEINSTALLER_UPLOADING="Gelaya &hellip;"

