; Joomla! Project
; (C) 2011 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FINDER_CONTENT="Raadinta Caqliga leh - Mawduuca"
PLG_FINDER_CONTENT_XML_DESCRIPTION="Cusboonaysiiyaa tusmooyinka maqaalada Joomla! Markasta oo maqaal la sameeyo, wax ka beddelo ama la tirtiro. OGOW in ku-darka Raadinta Caqliga leh ee Mawduuca la xoojiyey."
PLG_FINDER_STATISTICS_ARTICLE="Maqaal"

