; Joomla! Project
; (C) 2011 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FINDER_CONTENT="Raadi Gurmad - Mawduuc"
PLG_FINDER_CONTENT_FIELD_SEARCH_ARCHIVED_DESC="Markaad beddesho dejintan, waa inaad orodsiisaa amarka tusmaynta ee Raadi Gurmad ka hor inta aysan saameyn ku yeelan."
PLG_FINDER_CONTENT_FIELD_SEARCH_ARCHIVED_LABEL="Raadi Mawduucyo La Kaydiyay"
PLG_FINDER_CONTENT_TAXONOMIES_AUTHOR="Qoraa"
PLG_FINDER_CONTENT_TAXONOMIES_CATEGORY="Qeyb"
PLG_FINDER_CONTENT_TAXONOMIES_LABEL="Tacnuumyo la Tixraacayo"
PLG_FINDER_CONTENT_TAXONOMIES_LANGUAGE="Af"
PLG_FINDER_CONTENT_TAXONOMIES_TYPE="Nooc"
PLG_FINDER_CONTENT_XML_DESCRIPTION="Waxay cusbooneysiisaa tixraacyada Maqaallada Joomla! marka maqaal la abuuro, wax laga beddelo ama la tirtiro. OGOW in plugin-kani Content - Raadi Gurmad uu ansax yahay."
PLG_FINDER_QUERY_FILTER_BRANCH_P_ARTICLE="Maqaallo"
PLG_FINDER_QUERY_FILTER_BRANCH_P_AUTHOR="Qorayaal"
PLG_FINDER_QUERY_FILTER_BRANCH_S_ARTICLE="Maqaal"
PLG_FINDER_QUERY_FILTER_BRANCH_S_AUTHOR="Qoraa"

