; Joomla! Project
; (C) 2024 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SCHEMAORG_CUSTOM="Schema.org - Gaaban"
PLG_SCHEMAORG_CUSTOM_XML_DESCRIPTION="Waxay ku dartaa goob gaar ah si loo daro nooc kasta oo ajanabiga ah."
PLG_SCHEMAORG_CUSTOM_DESCRIPTION_LABEL="Isticmaal wax kasta oo JSON-LD ah halkan si aad ugu darto noocyada ajanabiga ee aan taageersaneyn."
PLG_SCHEMAORG_CUSTOM_JSON_ERROR="Koodhka JSON ma ansaxna ama @context ama @type ayaa maqan."
PLG_SCHEMAORG_CUSTOM_JSON_FIELD_LABEL="Koodhka JSON"

