; Joomla! Project
; (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_MEDIA-ACTION_CROP="Ficilka Warbaahinta - Goyn"
PLG_MEDIA-ACTION_CROP_LABEL="Goyn"
PLG_MEDIA-ACTION_CROP_PARAM_ASPECT="Tirsaanka Dhererka iyo Ballaca"
PLG_MEDIA-ACTION_CROP_PARAM_DEFAULT_RATIO="Tirsaanka dhererka iyo ballaca ee caadiga ah"
PLG_MEDIA-ACTION_CROP_PARAM_HEIGHT="Dherer"
PLG_MEDIA-ACTION_CROP_PARAM_LANDSCAPE="Muuqaal dhulka ah"
PLG_MEDIA-ACTION_CROP_PARAM_NO_RATIO="Maya"
PLG_MEDIA-ACTION_CROP_PARAM_PORTRAIT="Sawir Jeeda"
PLG_MEDIA-ACTION_CROP_PARAM_WIDTH="Ballac"
PLG_MEDIA-ACTION_CROP_PARAM_X="X-Axis"
PLG_MEDIA-ACTION_CROP_PARAM_Y="Y-Axis"
PLG_MEDIA-ACTION_CROP_QUALITY="Tayo"
PLG_MEDIA-ACTION_CROP_XML_DESCRIPTION="Waxay ku dartaa shaqada goynta sawirada."

