; Joomla! Project
; (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_TASK_UPDATENOTIFICATION="Hawl - Ogeysiiska Cusbooneysiinta Joomla!"
PLG_TASK_UPDATENOTIFICATION_XML_DESCRIPTION="Hawshani waxay si joogto ah u hubisaa helitaanka noocyada cusub ee Joomla! Marka mid la helo waxay kuu soo diri doontaa emayl, iyadoo ku xasuusineysa inaad cusbooneysiiso. Waxaad habeyn kartaa emaylka: Nidaamka &rarr; Hab Maamulida Boostada."

