; Joomla! Project
; (C) 2024 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SCHEMAORG_ARTICLE="Schema.org - Maqaallo"  
PLG_SCHEMAORG_ARTICLE_DESCRIPTION_LABEL="Macluumaad dheeraad ah oo ku saabsan Nooca Maqaallo Schema.org waxaa laga heli karaa <a href=\"https://schema.org/Article\" target=\"_blank\" rel=\"noopener noreferrer\">https://schema.org/Article</a>"
PLG_SCHEMAORG_ARTICLE_FIELD_ADDRESS_LABEL="Cinwaan"
PLG_SCHEMAORG_ARTICLE_FIELD_AUTHOR_LABEL="Qoraaga"
PLG_SCHEMAORG_ARTICLE_FIELD_DATE_MODIFIED_LABEL="Taariikhda La Bedelay"
PLG_SCHEMAORG_ARTICLE_FIELD_DATE_PUBLISHED_LABEL="Taariikhda La Daabacay"
PLG_SCHEMAORG_ARTICLE_FIELD_DESCRIPTION_LABEL="Sharaxaad"
PLG_SCHEMAORG_ARTICLE_FIELD_EMAIL_LABEL="Emayl"
PLG_SCHEMAORG_ARTICLE_FIELD_GENERIC_FIELD_LABEL="Beer Guud"
PLG_SCHEMAORG_ARTICLE_FIELD_GENERIC_TITLE_LABEL="Cinwaan"
PLG_SCHEMAORG_ARTICLE_FIELD_GENERIC_VALUE_LABEL="Qiime"
PLG_SCHEMAORG_ARTICLE_FIELD_HEADLINE_LABEL="Cinwaan"
PLG_SCHEMAORG_ARTICLE_FIELD_IMAGE_LABEL="Sawirka"
PLG_SCHEMAORG_ARTICLE_FIELD_LOCALITY_LABEL="Goobta"
PLG_SCHEMAORG_ARTICLE_FIELD_LOGO_LABEL="Hal-ku-dheg"
PLG_SCHEMAORG_ARTICLE_FIELD_NAME_LABEL="Magaca"
PLG_SCHEMAORG_ARTICLE_FIELD_ORGANIZATION_LABEL="Urur"
PLG_SCHEMAORG_ARTICLE_FIELD_PERSON_LABEL="Qof"
PLG_SCHEMAORG_ARTICLE_FIELD_POSTAL_CODE_LABEL="Lambarka Boostada"
PLG_SCHEMAORG_ARTICLE_FIELD_STREET_ADDRESS_LABEL="Cinwaanka Wadada"
PLG_SCHEMAORG_ARTICLE_FIELD_TYPE_LABEL="Nooc"
PLG_SCHEMAORG_ARTICLE_FIELD_URL_LABEL="Url"
PLG_SCHEMAORG_ARTICLE_XML_DESCRIPTION="Waxay ku dareysaa Maqaallo noocyo kala duwan oo ku jira shemka hadda jira."

