; Joomla! Project
; (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SCHEMAORG_BOOK="Schema.org - Buug"
PLG_SCHEMAORG_BOOK_DESCRIPTION_LABEL="Macluumaad dheeraad ah oo ku saabsan Nooca Buugga ee Schema.org waxaa laga heli karaa <a href=\"https://schema.org/Book\" target=\"_blank\" rel=\"noopener noreferrer\">https://schema.org/Book</a>"
PLG_SCHEMAORG_BOOK_FIELD_ABRIDGED_LABEL="Kooban"
PLG_SCHEMAORG_BOOK_FIELD_ADDRESS_LABEL="Cinwaanka"
PLG_SCHEMAORG_BOOK_FIELD_AUDIOBOOK_LABEL="Buug Dhageysi"
PLG_SCHEMAORG_BOOK_FIELD_AUTHOR_LABEL="Qoraa"
PLG_SCHEMAORG_BOOK_FIELD_BOOK_EDITION_LABEL="Daabacaadda Buugga"
PLG_SCHEMAORG_BOOK_FIELD_BOOK_FORMAT_LABEL="Qaabka Buugga"
PLG_SCHEMAORG_BOOK_FIELD_DATE_PUBLISHED_LABEL="Taariikhda La Daabacay"
PLG_SCHEMAORG_BOOK_FIELD_EMAIL_LABEL="Iimayl"
PLG_SCHEMAORG_BOOK_FIELD_E_BOOK_LABEL="E-buug"
PLG_SCHEMAORG_BOOK_FIELD_GENERIC_FIELD_LABEL="Goob Guud"
PLG_SCHEMAORG_BOOK_FIELD_GENERIC_TITLE_LABEL="Cinwaan"
PLG_SCHEMAORG_BOOK_FIELD_GENERIC_VALUE_LABEL="Qiime"
PLG_SCHEMAORG_BOOK_FIELD_GRAPHIC_NOVEL="Sheeko Sawir"
PLG_SCHEMAORG_BOOK_FIELD_HARDCOVER_LABEL="Sharax Adag"
PLG_SCHEMAORG_BOOK_FIELD_ILLUSTRATOR_LABEL="Faahfaahin"
PLG_SCHEMAORG_BOOK_FIELD_ILLUSTRATOR_NAME_LABEL="Magaca"
PLG_SCHEMAORG_BOOK_FIELD_ISBN_LABEL="ISBN"
PLG_SCHEMAORG_BOOK_FIELD_LOCALITY_LABEL="Deegaanka"
PLG_SCHEMAORG_BOOK_FIELD_NAME_LABEL="Cinwaan"
PLG_SCHEMAORG_BOOK_FIELD_NUMBER_OF_PAGES_LABEL="Tirada Bogagga"
PLG_SCHEMAORG_BOOK_FIELD_PAPERBACK_LABEL="Daabacda Jilicsan"
PLG_SCHEMAORG_BOOK_FIELD_POSTAL_CODE_LABEL="Koodhka Boostada"
PLG_SCHEMAORG_BOOK_FIELD_STREET_ADDRESS_LABEL="Cinwaanka Wadada"
PLG_SCHEMAORG_BOOK_FIELD_URL_LABEL="Url"
PLG_SCHEMAORG_BOOK_XML_DESCRIPTION="Waxay ku daraysaa Buug sida nooc jaantus cusub ah oo ku jira jaantusyada jira."

