; Joomla! Project
; (C) 2018 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_PRIVACYCONSENT="Nidaam - Ogolaanshaha Asturnaanta"
PLG_SYSTEM_PRIVACYCONSENT_XML_DESCRIPTION="Plugin aasaasi ah oo ku waydiinaya ogolaanshaha asturnaanta bogga isticmaalaha. Isticmaalayaasha jira ee aan weli ogolaan doonin waxay dib loogu hagaajin doonaa markii ay soo galaan si ay u cusboonaysiiyaan xogtooda."

