; Joomla! Project
; (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_SCHEMAORG="Nidaam - Schema.org"
PLG_SYSTEM_SCHEMAORG_BASETYPE_DESCRIPTION="Dooro haddii boggaaga internetka uu matalo urur ama qof keliya."
PLG_SYSTEM_SCHEMAORG_BASETYPE_LABEL="Nooca Asaasiga ah"
PLG_SYSTEM_SCHEMAORG_BASETYPE_OPTION_ORGANIZATION="Urur"
PLG_SYSTEM_SCHEMAORG_BASETYPE_OPTION_PERSON="Qof"
PLG_SYSTEM_SCHEMAORG_FIELD_SCHEMA_DESCRIPTION="Xogta loo qaybiyey waa qaab habaysan oo loogu talagalay abaabulka iyo matalaadda macluumaadka ku saabsan shabakadda. Waxay bixisaa qaab lagu tilmaamo waxa ku jira iyo macnaha macluumaadka si habaysan, taasoo ka dhigaysa mid sahlan in matoorada raadinta iyo barnaamijyada kale ay fahmaan oo ay macluumaadka u habayn karaan. <a href=\"https://schema.org\" target=\"_blank\" rel=\"noopener noreferrer\">Macluumaad dheeri ah oo ku saabsan schema.org</a>."
; The following two strings are deprecated and will be removed with 6.0
PLG_SYSTEM_SCHEMAORG_FIELD_SCHEMA_DESCRIPTION_NOT_CONFIGURATED="Si aad u isticmaasho howlaha schema.org, waa inaad marka hore habeysaa plugin-ka. Fadlan la xidhiidh maamulka bogga si loo habeeyo."
PLG_SYSTEM_SCHEMAORG_FIELD_SCHEMA_DESCRIPTION_NOT_CONFIGURATED_ADMIN="Si aad u isticmaasho howlaha schema.org, waa inaad marka hore habeysaa plugin-ka. Fadlan dooro <a href=\"index.php?option=com_plugins&amp;task=plugin.edit&amp;extension_id=%s\" target=\"_blank\">isku xirkaan si aad u furto plugin-ka</a>, habee oo kaydi."
PLG_SYSTEM_SCHEMAORG_FIELD_SCHEMA_DESCRIPTION_NOT_CONFIGURED="Si aad u isticmaasho howlaha schema.org, waa inaad marka hore habeysaa plugin-ka. Fadlan la xidhiidh maamulka bogga si loo habeeyo."
PLG_SYSTEM_SCHEMAORG_FIELD_SCHEMA_DESCRIPTION_NOT_CONFIGURED_ADMIN="Si aad u isticmaasho howlaha schema.org, waa inaad marka hore habeysaa plugin-ka. Fadlan dooro <a href=\"index.php?option=com_plugins&amp;task=plugin.edit&amp;extension_id=%s\" target=\"_blank\">isku xirkaan si aad u furto plugin-ka</a>, habee oo kaydi."
PLG_SYSTEM_SCHEMAORG_FIELD_SCHEMA_EXTEND_JED_DESC="<strong>Miyaad u baahan tahay noocyo kale oo Schema ah?</strong> Kordhi iyadoo la isticmaalayo <a href=\"https://extensions.joomla.org/category/core-enhancements/schema-plugins\" target=\"_blank\" rel=\"noopener noreferrer\">Schema Plugins ee Joomla! Diiwaanka Kordhinta</a>."
PLG_SYSTEM_SCHEMAORG_FIELD_SCHEMA_LABEL="Schema"
PLG_SYSTEM_SCHEMAORG_FIELD_SCHEMA_TYPE_LABEL="Nooca Schema"
PLG_SYSTEM_SCHEMAORG_IMAGE_LABEL="Sawir"
PLG_SYSTEM_SCHEMAORG_NAME_LABEL="Magaca"
PLG_SYSTEM_SCHEMAORG_SOCIALMEDIA_LABEL="Akoontooyinka Warbaahinta Bulshada"
PLG_SYSTEM_SCHEMAORG_SOCIALMEDIA_URL_LABEL="URL"
PLG_SYSTEM_SCHEMAORG_USER_LABEL="Dooro Isticmaalaha"
PLG_SYSTEM_SCHEMAORG_XML_DESCRIPTION="Waxay ku dareysaa goobta foomka qaaska ah ee aragtida maqaalka ka dibna waxay ku durtaa xogtaas qaabka JSON+LD ee sumadda labaad ee maqaalkaas gaarka ah."

