; Joomla! Project
; (C) 2020 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_WORKFLOW_FEATURING="Habka-Shaqada - In la soo bandhigo"
PLG_WORKFLOW_FEATURING_CHANGE_STATE_NOT_ALLOWED="Lama ogola inaad bedesho xaaladda la soo bandhigay ee shaygan. Fadlan u isticmaal isbeddelka hab-socodka."
PLG_WORKFLOW_FEATURING_FEATURED="Lagu Soo Bandhigay: %s"
PLG_WORKFLOW_FEATURING_TRANSITION_ACTIONS_FEATURING_DESC="Qeex xaaladda lagu soo bandhigayo ee shayga waa in la dejiyo marka la fulinayo isbeddelkan."
PLG_WORKFLOW_FEATURING_TRANSITION_ACTIONS_FEATURING_LABEL="Xaaladda Soo Bandhigida"
PLG_WORKFLOW_FEATURING_XML_DESCRIPTION="Ku dar ficilada soo bandhigida isbeddelada hab-socodka ee waxyaabahaaga."

