; Joomla! Project
; (C) 2020 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_USER_TOKEN="Isticmaale - Joomla Token API"
PLG_USER_TOKEN_COPY="Koobi"
PLG_USER_TOKEN_COPY_DESC="Koobi tokenka si aad ugu dhajiso meesha xusuusqorka"
PLG_USER_TOKEN_COPY_FAIL="Ku guuldareysatay koobinta tokenka."
PLG_USER_TOKEN_COPY_SUCCESS="Tokenka waa la koobiyey."
PLG_USER_TOKEN_ENABLED_DESC="U qabo Maya si aad si ku meel gaar ah uga hortagto helitaanka goobtaada adoo isticmaalaya tokenkan."
PLG_USER_TOKEN_ENABLED_LABEL="Firfircoon"
PLG_USER_TOKEN_GROUP_DESC="Maamul tokenska amniga ee loo isticmaalo xaqiijinta codsiga Joomla API (gelitaanka fog ee goobtaada). Haddii aadan hubin waxa ay sameyso, waxaa laga yaabaa inaadan u baahnayn oo si badbaado leh ugu tagi karto dejinta hawlahaan."
PLG_USER_TOKEN_GROUP_LABEL="Joomla Token API"
PLG_USER_TOKEN_NOTOKENFOROTHERPEOPLE_DESC="Ma arki kartid tokenka isticmaalayaasha kale ee aan haga saaxiib. Weli waad kari kartaa inaad firfircooni, demi ama aad dib u dhisto tokenkooda tusaale marka laga shakiyo in tokenkoodu ku galay dadka aan oggolayn."
PLG_USER_TOKEN_RESET_DESC="U qabo Haa oo kaydi kuwayga isticmaalaha si aad u abuurto token cusub, oo beddelaya kii hore."
PLG_USER_TOKEN_RESET_LABEL="Dib-u-dejinta"
PLG_USER_TOKEN_SAVEME_DESC="Ma haysto token weli. Fadlan badbaadi kuwayga isticmaale si aad u soo saarto token. Ku noqo boggan si aad u aragto oo aad u maamusho tokenkaaga."
PLG_USER_TOKEN_SAVEMEFOROTHERPEOPLE_DESC="Isticmaalahani weli ma hayo token. Haddii aad kaydiso waaxyadooda waa la soo saari doonaa token cusub laakin ma awoodi doontid in aad aragto sababo amni. Weli waad kari kartaan inaad firfircooni, demi ama aad dib u dhisto tokenkooda."
PLG_USER_TOKEN_TOKEN_DESC="Kani waa token-kaaga. U isticmaal codsiyada dhinacyada saddexaad ee u baahan gelitaanka fog ee goobtaada adoo isticmaalaya codsiga Joomla API."
PLG_USER_TOKEN_TOKEN_LABEL="Token"
PLG_USER_TOKEN_XML_DESCRIPTION="Waxay u ogolaaneysaa maaraynta tokenska amniga ee loo isticmaalo xaqiijinta codsiga Joomla API (gelitaanka fog ee goobtaada). Tokenskan waa kuwo khaas ah. Waxaad arki kartaa tokenkaaga laakiin waxaad kaliya demi kartaa ama dib u dejin kartaa tokenka dadka kale."

