; Joomla! Project
; (C) 2018 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_USER_TERMS="Isticmaal - Shuruudaha iyo Shuruudaha"
PLG_USER_TERMS_FIELD_ARTICLE_DESC="Xulo maqaalka liiska ama samee mid cusub."
PLG_USER_TERMS_FIELD_ARTICLE_LABEL="Maqaalka Shuruudaha & Xeerarka"
PLG_USER_TERMS_FIELD_ERROR="Ogolaanshaha Shuruudaha & Shuruudaha mareegta waa lama huraan."
PLG_USER_TERMS_FIELD_LABEL="Shuruudaha & Shuruudaha"
PLG_USER_TERMS_LABEL="Shuruudaha & Shuruudaha"
PLG_USER_TERMS_LOGGING_CONSENT_TO_TERMS="Isticmaalaha <a href='{accountlink}'>{username}</a> ayaa ogolaaday shuruudaha iyo xeerarka intii lagu jiray diwaangelinta."
PLG_USER_TERMS_NOTE_FIELD_DEFAULT="Adiga oo iska diiwaangali mareegtan waxaad aqbashay Shuruudaha & Shuruudaha."
PLG_USER_TERMS_NOTE_FIELD_DESC="Kooban shuruudaha & shuruudaha mareegta. Hadii la dhaafo waxay qaadan doontaa fariinta aasaaska ah."
PLG_USER_TERMS_NOTE_FIELD_LABEL="Shuruudo Gaaban & Shuruudaha"
PLG_USER_TERMS_OPTION_AGREE="Waan ogolaaday"
PLG_USER_TERMS_OPTION_DO_NOT_AGREE="Ma ogoli"
PLG_USER_TERMS_SUBJECT="Siyaasadda Qarsoonnimada"
PLG_USER_TERMS_XML_DESCRIPTION="Farsamada muhiimka ah ee weydiisashada ogolaanshaha isticmaaleha ee shuruudaha iyo shuruudaha mareegta."

