; Joomla! Project
; (C) 2018 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_PRIVACYCONSENT="Nidaamka - Ogolaanshaha Qarsoodiga"
PLG_SYSTEM_PRIVACYCONSENT_BODY="<p>Isticmaaluhu wuu ogolaaday in lagu kaydiyo macluumaadkooda isticmaalka cinwaanka IP-ga <strong>%s</strong></p><p>Silsiladda wakiilka isticmaalaha ee browser-ka isticmaalaha waxay ahayd:<br>%s</p><p>Macluumaadkan waxaa si otomaatig ah loo diiwanaan geliyay markii isticmaalehu uu soo gudbiyay faahfaahintiisa goobta oo uu saxay sanduuqa xaqiijinta.</p>"
PLG_SYSTEM_PRIVACYCONSENT_CONSENT="Isticmaalaha <a href='{accountlink}'>{username}</a> waxa uu aqbalay siyaasadda asturnaanta."
PLG_SYSTEM_PRIVACYCONSENT_FIELD_ARTICLE_DESC="Ka dooro maqaalka liiska ama samee mid cusub."
PLG_SYSTEM_PRIVACYCONSENT_FIELD_ARTICLE_LABEL="Qoraalka Asturnaanta"
PLG_SYSTEM_PRIVACYCONSENT_FIELD_ERROR="Waa lagama maarmaan inaad ogolaato Siyaasadda Asturnaanta ee goobta."
PLG_SYSTEM_PRIVACYCONSENT_FIELD_LABEL="Siyaasadda Asturnaanta"
PLG_SYSTEM_PRIVACYCONSENT_FIELD_MENU_ITEM_LABEL="Qodobka Menu-ka ee Asturnaanta"
PLG_SYSTEM_PRIVACYCONSENT_FIELD_TYPE_ARTICLE="Qoraal"
PLG_SYSTEM_PRIVACYCONSENT_FIELD_TYPE_LABEL="Nooca Asturnaanta"
PLG_SYSTEM_PRIVACYCONSENT_FIELD_TYPE_MENU_ITEM="Menu Item"
PLG_SYSTEM_PRIVACYCONSENT_LABEL="Asturnaanta Goobta"
PLG_SYSTEM_PRIVACYCONSENT_NOTE_FIELD_DEFAULT="Adigoo isku diwaangeliya goobtan oo aqbalaya Siyaasadda Asturnaanta waxaad ogolaanaysaa in goobtani ay kaydiso macluumaadkaaga."
PLG_SYSTEM_PRIVACYCONSENT_NOTE_FIELD_DESC="War kooban oo ku saabsan siyaasadda asturnaanta ee goobta. Haddii lagu daayo bannaan waxaa la adeegsan doonaa farriinta caadiga ah."
PLG_SYSTEM_PRIVACYCONSENT_NOTE_FIELD_LABEL="Siyaasadda Asturnaanta ee Gaaban"
PLG_SYSTEM_PRIVACYCONSENT_OPTION_AGREE="Waan oggolahay"
PLG_SYSTEM_PRIVACYCONSENT_OPTION_DO_NOT_AGREE="Ma ogolin"
PLG_SYSTEM_PRIVACYCONSENT_REDIRECT_MESSAGE_DEFAULT="Fadlan xaqiiji inaad ku consent ogoshahay goobtani inay kaydiso macluumaadkaaga adigoo oggolaanaya siyaasadda asturnaanta."
PLG_SYSTEM_PRIVACYCONSENT_REDIRECT_MESSAGE_DESC="Fariin khaas ah in lasoo bandhigo marka loo leexinayo. Haddii lagu daayo bannaan waxaa la adeegsan doonaa farriinta caadiga ah."
PLG_SYSTEM_PRIVACYCONSENT_REDIRECT_MESSAGE_LABEL="Fariin Leexin"
PLG_SYSTEM_PRIVACYCONSENT_SUBJECT="Siyaasadda Asturnaanta"
PLG_SYSTEM_PRIVACYCONSENT_XML_DESCRIPTION="Plugin-ka aasaasiga ah ee codsada ogolaanshaha isticmaalaha ee siyaasadda asturnaanta ee goobta. Isticmaalayaasha jira ee aan weli ogolaan ayaa lagu leexin doonaa marka ay galaan inay cusboonaysiiyaan astaantooda."

; All the following strings are deprecated and will be removed with 6.0
PLG_SYSTEM_PRIVACYCONSENT_CACHETIMEOUT_DESC="Immisa jeer ayaa hubinta la sameeyaa."
PLG_SYSTEM_PRIVACYCONSENT_CACHETIMEOUT_LABEL="Hubinta joogtada ah (maalmo)"
PLG_SYSTEM_PRIVACYCONSENT_CONSENTEXPIRATION_DESC="Tirada maalmaha ka dib marka ogolaanshaha gaar ahaaneed uu dhacay."
PLG_SYSTEM_PRIVACYCONSENT_CONSENTEXPIRATION_LABEL="Dhacitaanka"
PLG_SYSTEM_PRIVACYCONSENT_EMAIL_REMIND_BODY="Oggolaanshaha Asturnaanta ee aad ku bixisay {URL} wuxuu dhacayaa maalmo kooban gudaheed, waxaad dib u cusboonaysiin kartaa oggolaanshaha asturnaanta mareegtan.\n\nSi aad tan u samayso, waxaad dhamaystiri kartaa mid ka mid ah hawlaha soo socda:\n\n1. Booqo URL-kan soo socda: {TOKENURL}\n\n2. Ka koobi token-ka emailkan, booqo URL-ka lagu tilmaamay, oo ku dhaji token-kaaga foomka.\nURL: {FORMURL}\nToken: {TOKEN}\n\nFadlan ogow in token-kan uu ansax yahay oo kaliya xisaabtan."
PLG_SYSTEM_PRIVACYCONSENT_EMAIL_REMIND_SUBJECT="Oggolaanshaha Asturnaanta ee {SITENAME}"
PLG_SYSTEM_PRIVACYCONSENT_EXPIRATION_FIELDSET_LABEL="Dhacitaanka"
PLG_SYSTEM_PRIVACYCONSENT_FIELD_ENABLED_DESC="Markuu firfircoon yahay waxa uu hubinayaa dhacitaanka oggolaanshaha."
PLG_SYSTEM_PRIVACYCONSENT_FIELD_ENABLED_LABEL="Hawlgal"
PLG_SYSTEM_PRIVACYCONSENT_MAIL_REQUEST_REMINDER_DESC="Xusuusin dib u cusboonaysiinta oggolaanshaha asturnaanta mareegtan."
PLG_SYSTEM_PRIVACYCONSENT_MAIL_REQUEST_REMINDER_TITLE="Nidaamka - Oggolaanshaha Asturnaanta: Cusboonaysii Oggolaanshaha"
PLG_SYSTEM_PRIVACYCONSENT_NOTIFICATION_USER_PRIVACY_EXPIRED_MESSAGE="Oggolaanshaha asturnaanta ayaa dhacay %1$s."
PLG_SYSTEM_PRIVACYCONSENT_NOTIFICATION_USER_PRIVACY_EXPIRED_SUBJECT="Oggolaanshaha Asturnaanta ee Dhacay"
PLG_SYSTEM_PRIVACYCONSENT_REMINDBEFORE_DESC="Tirada maalmood ee la diro xusuusin ka hor dhacitaanka oggolaanshaha asturnaanta."
PLG_SYSTEM_PRIVACYCONSENT_REMINDBEFORE_LABEL="Xusuusi"

