; Joomla! Project
; (C) 2009 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_CONTENT_SELECT_AN_ARTICLE="Dooro Maqaal"
PLG_USER_PROFILE="Isticmaalaha - Astaanta"
PLG_USER_PROFILE_ERROR_INVALID_DOB="Taariikhda dhalashada aad soo gelisay waa khalad. Fadlan geli taariikh sax ah."
PLG_USER_PROFILE_ERROR_INVALID_DOB_FUTURE_DATE="Taariikhda dhalashada ee aad soo gelisay waxay ku taal mustaqbalka."
PLG_USER_PROFILE_FIELD_ABOUT_ME_LABEL="Iga Waran"
PLG_USER_PROFILE_FIELD_ADDRESS1_LABEL="Cinwaanka 1"
PLG_USER_PROFILE_FIELD_ADDRESS2_LABEL="Cinwaanka 2"
PLG_USER_PROFILE_FIELD_CITY_LABEL="Magaalada"
PLG_USER_PROFILE_FIELD_COUNTRY_LABEL="Waddanka"
PLG_USER_PROFILE_FIELD_DOB_DESCRIPTION="Sannad-Bisha-Maalinta, tusaale 2019-01-27."
PLG_USER_PROFILE_FIELD_DOB_HINT="YYYY-MM-DD"
PLG_USER_PROFILE_FIELD_DOB_LABEL="Taariikhda Dhalashada"
PLG_USER_PROFILE_FIELD_FAVORITE_BOOK_LABEL="Buugga Aan Jeclahay"
PLG_USER_PROFILE_FIELD_NAME_PROFILE_REQUIRE_USER="Goobo isticmaalaha ee foomka tifaftirka astaanta"
PLG_USER_PROFILE_FIELD_NAME_REGISTER_REQUIRE_USER="Goobo isticmaalaha ee isdiiwaangalinta iyo isticmaalaha maamulaha"
PLG_USER_PROFILE_FIELD_PHONE_LABEL="Telefoon"
PLG_USER_PROFILE_FIELD_POSTAL_CODE_LABEL="Koodhka Boostada/ZIP"
PLG_USER_PROFILE_FIELD_REGION_LABEL="Gobolka"
PLG_USER_PROFILE_FIELD_TOS_ARTICLE_LABEL="Dooro Maqaalka TOS"
PLG_USER_PROFILE_FIELD_TOS_DESC_SITE="Fadlan aqbal Shuruudaha Adeegga. Ma awoodo inaad isdiiwaangeliso haddii aad ku raacsan tahay."
PLG_USER_PROFILE_FIELD_TOS_LABEL="Shuruudaha Adeegga"
PLG_USER_PROFILE_FIELD_WEB_SITE_LABEL="Bogga Internetka"
PLG_USER_PROFILE_FILL_FIELD_DESC_SITE="Haddii loo baahan yahay, fadlan buuxi goobtan."
PLG_USER_PROFILE_OPTION_AGREE="Heshiis"
PLG_USER_PROFILE_OPTION_DO_NOT_AGREE="Ma ogi"
PLG_USER_PROFILE_SLIDER_LABEL="Qaabka Adeegsadaha"
PLG_USER_PROFILE_XML_DESCRIPTION="Kudar Dheereedka Qaabka Adeegsadaha"

