; Joomla! Project
; (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_MULTIFACTORAUTH_TOTP="Badbaado Fududeyn Noocyo Badan - Koodh Xaqiijin"
PLG_MULTIFACTORAUTH_TOTP_CAPTIVE_PROMPT="Fadlan furnaanta barnaamijkaaga xoojiye ama maareeye erayga sirta ah kuna koobbo lixda lambar ee goobtan sanduuqa qoraalka hoose, ka dibna guji badhanka Xaqiiji. Haddii koodhkan si otomaatig ah laguugu geliyay kaliya guji badhanka Xaqiiji."
PLG_MULTIFACTORAUTH_TOTP_ERR_VALIDATIONFAILED="Maadan gelin koodhka xaqiijinta ansax ah. Fadlan hubi dejinta barnaamijkaaga xoojiye, oo hubi in wakhtiga iyo aagga wakhtiga ee qalabkaaga si sax ah loo dejiyay."
PLG_MULTIFACTORAUTH_TOTP_LBL_LABEL="Ku qor lixda lambar ee koodhka xaqiijinta"
PLG_MULTIFACTORAUTH_TOTP_LBL_SETUP_INSTRUCTIONS="Deji koodhkaaga xaqiijinta (oo sidoo kale loo yaqaan \"koodh xoojiye\") adigoo isticmaalaya macluumaadka hoose. Waxaad u isticmaali kartaa barnaamij xoojiye (sida Google Authenticator, Authy, LastPass Authenticator, iwm), maareeyaha erayga sirta ah ee aad jeceshahay (1Password, BitWarden, Keeper, KeePassXC, Strongbox, iwm) ama, qaarkood, biraawsarkaaga."
PLG_MULTIFACTORAUTH_TOTP_LBL_SETUP_PLACEHOLDER="Lix Lambar Koodh"
PLG_MULTIFACTORAUTH_TOTP_LBL_SETUP_TABLE_HEADING="Dejinta barnaamijka xoojiye"
PLG_MULTIFACTORAUTH_TOTP_LBL_SETUP_TABLE_KEY="Geli furehan"
PLG_MULTIFACTORAUTH_TOTP_LBL_SETUP_TABLE_LINK="Guji isku xirkaan"
PLG_MULTIFACTORAUTH_TOTP_LBL_SETUP_TABLE_LINK_NOTE="<small>Kaliya waxay ka shaqaysaa biraawsarrada la taageero, tusaale ahaan Safari.</small>"
PLG_MULTIFACTORAUTH_TOTP_LBL_SETUP_TABLE_LINK_TEXT="<a href=\"%s\">Deji koodhkaaga xaqiijinta</a>"
PLG_MULTIFACTORAUTH_TOTP_LBL_SETUP_TABLE_QR="Sawir ama midig-guji / yara taabo koodhkan QR"
PLG_MULTIFACTORAUTH_TOTP_LBL_SETUP_TABLE_SUBHEAD="Isticmaal <em>hal</em> hab kale oo ka mid ah hababka soo socdo si aad u dejiso koodhka xaqiijinta ee barnaamijkaaga xoojiye, maareeyaha erayga sirta ah ama biraawsarkaaga."
PLG_MULTIFACTORAUTH_TOTP_METHOD_TITLE="Koodh Xaqiijin"
PLG_MULTIFACTORAUTH_TOTP_SHORTINFO="Isticmaal koodhadh 6-lambar ah oo uu abuuro app 30 ilbiriqsi kasta."
PLG_MULTIFACTORAUTH_TOTP_XML_DESCRIPTION="Badbaado Fududeyn Noocyo Badan ee isticmaalayaasha boggaaga adoo isticmaalaya koodhadh lix lambar ah oo uu abuuro barnaamij xoojiye (Google Authenticator, Authy, LastPass Authenticator, iwm), maareeyaha erayga sirta ah (1Password, BitWarden, Keeper, KeePassXC, Strongbox, iwm) ama, qaarkood, biraawsarkooda."

