; Joomla! Project
; (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FIELDS_IMAGELIST="Goobaha - Liiska Sawirrada"
PLG_FIELDS_IMAGELIST_XML_DESCRIPTION="Qalabkan waxa uu kuu ogolaanayaa inaad abuurto goobo cusub oo nooca 'liiska sawirrada' ah ee waxyaabaha dheeri loo sameeyey halkaas oo meelaha la adeegsan karo ee la habeeyey taageero leh."

