; Joomla! Project
; (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FIELDS_USERGROUPLIST="Goobaha - Liiska Kooxda Isticmaalayaasha"
PLG_FIELDS_USERGROUPLIST_XML_DESCRIPTION="Kani plugin wuxuu kuu ogolaanayaa inaad abuurto goobo cusub oo nooca 'liiska kooxaha isticmaalayaasha' ah meel kasta oo fidinno ah halkaasoo laga taageero goobo khaas ah."

