; Joomla! Project
; (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SAMPLEDATA_BLOG="Xog Tusaale - Bog"
PLG_SAMPLEDATA_BLOG_XML_DESCRIPTION="Waxay bixisaa xog tusaale bog oo loogu talagalay Cassiopeia. Waxaa lagu rakibi karaa isticmaalka module tusaale xogta."

