; Joomla! Project
; (C) 2011 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FINDER_CONTACTS="Raadinta Casriga ah - Xiriirrada"
PLG_FINDER_CONTACTS_FIELD_SEARCH_ARCHIVED_DESC="Markaad bedesho dejintan, waa inaad orodsiisaa amarka tusaha ee Raadinta Casriga ah ka hor intii aysan tan dhaqan gelin."
PLG_FINDER_CONTACTS_FIELD_SEARCH_ARCHIVED_LABEL="Raadi Mawduucyada La Keydiyay"
PLG_FINDER_CONTACTS_TAXONOMIES_CATEGORY="Qeybta"
PLG_FINDER_CONTACTS_TAXONOMIES_COUNTRY="Wadanka"
PLG_FINDER_CONTACTS_TAXONOMIES_LABEL="Canshuuraha in la Tuse"
PLG_FINDER_CONTACTS_TAXONOMIES_LANGUAGE="Luuqada"
PLG_FINDER_CONTACTS_TAXONOMIES_REGION="Gobalka"
PLG_FINDER_CONTACTS_TAXONOMIES_TYPE="Nooca"
PLG_FINDER_CONTACTS_XML_DESCRIPTION="Kudarahan wuxuu tusayaa xiriirada Joomla!"
PLG_FINDER_QUERY_FILTER_BRANCH_P_CONTACT="Xiriirrada"
PLG_FINDER_QUERY_FILTER_BRANCH_P_COUNTRY="Wadamadda"
PLG_FINDER_QUERY_FILTER_BRANCH_P_REGION="Gobollada"
PLG_FINDER_QUERY_FILTER_BRANCH_S_CONTACT="Xiriir"
PLG_FINDER_QUERY_FILTER_BRANCH_S_COUNTRY="Dalka"
PLG_FINDER_QUERY_FILTER_BRANCH_S_REGION="Gobolka"

