; Joomla! Project
; (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_TASK_GLOBALCHECKIN="Hawl - Is-diiwaangelinta Guud"
PLG_TASK_GLOBALCHECKIN_DELAY_LABEL="Muddada Ugu Yar Ka Hor Inta Aan La Diiwaangeliyay (saacado)"
PLG_TASK_GLOBALCHECKIN_DESC="Is-diiwaangeli alaabada hubinta ah."
PLG_TASK_GLOBALCHECKIN_TITLE="Is-diiwaangelinta Guud"
PLG_TASK_GLOBALCHECKIN_XML_DESCRIPTION="Kordhinta si loo is-diiwaangeliyo alaabada hubinta ah."

