; Joomla! Project
; (C) 2020 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_WEBAUTHN="Nidaam - Gelida (Laan-kelme) Aan Furaha La'aanta ah"
PLG_SYSTEM_WEBAUTHN_DESCRIPTION="Waxay awood u siineysaa aqoonsiga aan furaha lahayn iyadoo la adeegsanayo laan-kelmeyaal. Fadlan ogsoonow in tabka laan-kelmeyaalka ee tifaftiraha astaanta isticmaale iyo badhamada soo gelida laan-kelmeyaalka keliya leeyihiin muuqan doonaan haddii isticmaaleha uu ku soo galayo bogga iyada oo loo marayo HTTPS. Diiwaangelinta laan-kelmeyaalka iyo isticmaalka iyaga si loo galo boggaaga waxay shaqeynayaan oo keliya marka boggaaga isticmaalo shahaado sax ah, oo lagu saxeexay Awood Bixiye Shahaadada kuwaasoo daalacashada isticmaaleha aamini kara."

