; Joomla! Project
; (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_MULTIFACTORAUTH_WEBAUTHN="Oggolaansho badan - Furayaasha"
PLG_MULTIFACTORAUTH_WEBAUTHN_XML_DESCRIPTION="Adeegso furayaasha shabakadda sida hab-ogolaansho badan. Dhammaan daalacayaasha casriga ahi waxa ay taageeraan. Daalacayaasha badidoodu waxay bixiyaan aqoonsi gaar ah oo qalabku leeyahay oo lagu ilaaliyo lambarka sirta ah iyo/ama biometric (qalab suulka lagu aqoonsado, wajiga la sawiro &hellip;)."

