; Joomla! Project
; (C) 2007 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SEF_DOMAIN_DESCRIPTION="Haddii goobtaada lagu heli karo in ka badan hal nidaam, geli halkan goobta la doorbidayo (mararka qaar waxaa loola jeedaa sida caadiga ah). <br><strong>Ogsoonow:</strong> https://example.com iyo https://www.example.com waa nidaamyo kala duwan."
PLG_SEF_DOMAIN_LABEL="Goobta Domain-ka"
PLG_SEF_ENFORCESUFFIX_DESCRIPTION="Marka la joojiyo oo \"Kudar Suffix-ka URL-ka\" sidoo kale la joojiyo, URL-yada aan lahayn suffix waxaa loo wareejin doonaa midka saxda ah. Laga bilaabo nuqulka 6.0 wixii ka dambeeya, tani waxay noqon doontaa dabeecad caadi ah oo aan mar dambe ahayn ikhtiyaar."
PLG_SEF_ENFORCESUFFIX_LABEL="Ku adkee suffix-ka by redirect"
PLG_SEF_INDEXPHP_DESCRIPTION="Xulashadani waxay awoodsiinaysaa maareyn adag ee 'index.php' gudaha URL-yada marka 'Isticmaal URL Dib-u-qorid' laga joojiyo Qaabeynta Guud. Waxay ka saari doontaa 'index.php' haddii URL-ku weli ku jiro waxaana u weecin doona codsiyada soo galaya leh 'index.php' iyadoo la'aanteed 'index.php'."
PLG_SEF_INDEXPHP_LABEL="Maareeynta adag ee index.php"
PLG_SEF_STRICTROUTING_DESCRIPTION="Ka hortag router-ka inay aqbasho URL-yada badan oo loo arko iyadoo la'een ogol yahay oo si toos ah loogu wareejin doono URL-ka saxda ah leh 301."
PLG_SEF_STRICTROUTING_LABEL="Routing adag"
PLG_SEF_TRAILINGSLASH_DESCRIPTION="Khasab Joomla inay isticmaasho URL-yada leh ama aan lahayn dashka dambeynta. Marka la dejiyo, waxay ku khasabi doontaa URL-ka saxda ah oo leh redirections waxaana la isticmaali doonaa marka 'Kudar suffix-ka URL-ka' la joojiyo."
PLG_SEF_TRAILINGSLASH_LABEL="Dashka dambeynta ee URL-yada"
PLG_SEF_TRAILINGSLASH_OPTION_NONE="Isbedel la'aan"
PLG_SEF_TRAILINGSLASH_OPTION_NO_SLASH="Ku adkee URL-yada aan lahayn dashka dambeynta"
PLG_SEF_TRAILINGSLASH_OPTION_SLASH="Ku adkee URL-yada leh dashka dambeynta"
PLG_SEF_XML_DESCRIPTION="Waxay ku darsataa taageero SEF ku jira isku xirka dukumintigga. Waxay si toos ah ugu shaqeysaa HTML mana u baahna calaamad gaar ah."
PLG_SYSTEM_SEF="Nidaamka - SEF"

