; Joomla! Project
; (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_SHORTCUT="Nidaamka - Fureyaal Fureyn"
PLG_SYSTEM_SHORTCUT_OVERVIEW_DESC="Riix <kbd>J</kbd> si aad u gasho habka fureye kadibna fureen."
PLG_SYSTEM_SHORTCUT_OVERVIEW_HINT="<span class=\"icon-keyboard fa-keyboard me-2\" aria-hidden=\"true\"></span> <kbd>J</kbd> <small>ka dibna</small> <kbd>X</kbd> <small>Fureyaal Fureenka</small>"
PLG_SYSTEM_SHORTCUT_OVERVIEW_TITLE="Fureyaal Fureeyn Joomla"
PLG_SYSTEM_SHORTCUT_THEN="ka dibna"
PLG_SYSTEM_SHORTCUT_TIMEOUT_DESC="Waqtiga ugu badan ee fure la riixi karo ka dib marka la riixo <kbd>J</kbd>."
PLG_SYSTEM_SHORTCUT_TIMEOUT_LABEL="Waqti xadidid (miliseken)"
PLG_SYSTEM_SHORTCUT_XML_DESCRIPTION="<p>Waxay suurtogelinaysaa fureyaal fureeynta bogga maamuleyaasha, kuwaas oo ay keeni karaan dheeri, oo si toos ah u soo daraya liiska hoos ku qoran ee fureynta:</p><ul class=\"list-unstyled\"><li><kbd>J</kbd> <small>ka dibna</small> <kbd>A</kbd> Badbaadi</li><li><kbd>J</kbd> <small>ka dibna</small> <kbd>S</kbd> Badbaadi & Xir</li><li><kbd>J</kbd> <small>ka dibna</small> <kbd>Q</kbd> Jooji</li><li><kbd>J</kbd> <small>ka dibna</small> <kbd>N</kbd> Cusub</li><li><kbd>J</kbd> <small>ka dibna</small> <kbd>F</kbd> Raadi</li><li><kbd>J</kbd> <small>ka dibna</small> <kbd>O</kbd> Ikhtiyaaraad</li><li><kbd>J</kbd> <small>ka dibna</small> <kbd>H</kbd> Caawimo</li><li><kbd>J</kbd> <small>ka dibna</small> <kbd>M</kbd> Beddel Liiska</li><li><kbd>J</kbd> <small>ka dibna</small> <kbd>X</kbd> Guudmar</li><li><kbd>J</kbd> <small>ka dibna</small> <kbd>D</kbd> Guddi Guriga</li></ul>"

