; Joomla! Project
; (C) 2018 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_EXTENSION_NAMESPACEMAP="Kordhinta - Cusbooneysiiyaha Namespace"
PLG_EXTENSION_NAMESPACEMAP_XML_DESCRIPTION="<p>Si toos ah ayuu u dhisaa oo u cusboonaysiiyaa faylka <strong>administrator/cache/autoload_psr4.php</strong> ee loo isticmaalo in lagu soogaliyo kordhinta.</p><p><strong>Digniin! Fadlan waa in lagu shido plugin-kan</strong> iyadoo uu ordo marka la rakibo, la cusboonaysiiyo ama la tirtiro kordhinta.</p>"

