; Joomla! Project
; (C) 2011 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_CONTENT_FINDER="Waxyaabaha - Raadinta Caqliga"
PLG_CONTENT_FINDER_XML_DESCRIPTION="Isbedelada ku yimaada waxyaabaha ma cusbooneysiin doonaan tusmada Raadinta Caqliga haddii aanad furin waxyaabahan."
PLG_FINDER_QUERY_FILTER_BRANCH_P__="Dhammaan"
PLG_FINDER_QUERY_FILTER_BRANCH_P_CATEGORY="Qaybaha"
PLG_FINDER_QUERY_FILTER_BRANCH_P_LANGUAGE="Luqadaha"
PLG_FINDER_QUERY_FILTER_BRANCH_P_TYPE="Noocyada"
PLG_FINDER_QUERY_FILTER_BRANCH_S_CATEGORY="Qayb"
PLG_FINDER_QUERY_FILTER_BRANCH_S_LANGUAGE="Luqad"
PLG_FINDER_QUERY_FILTER_BRANCH_S_TYPE="Nooc"

