; Joomla! Project
; (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SCHEMAORG_RECIPE="Schema.org - Cunto karis"
PLG_SCHEMAORG_RECIPE_DESCRIPTION_LABEL="Macluumaad dheeraad ah oo ku saabsan Nooca Cunto Karin Schema.org waxaa laga heli karaa <a href=\"https://schema.org/Recipe\" target=\"_blank\" rel=\"noopener noreferrer\">https://schema.org/Recipe</a>"
PLG_SCHEMAORG_RECIPE_FIELD_AUTHOR_LABEL="Qoraa"
PLG_SCHEMAORG_RECIPE_FIELD_CALORIES_LABEL="Kalooriyo"
PLG_SCHEMAORG_RECIPE_FIELD_CARBOHYDRATE_LABEL="Karbohaydrate"
PLG_SCHEMAORG_RECIPE_FIELD_CATEGORY_LABEL="Qayb"
PLG_SCHEMAORG_RECIPE_FIELD_CHOLESTEROL_CONTENT_LABEL="Kolestarool"
PLG_SCHEMAORG_RECIPE_FIELD_COOKING_METHOD_LABEL="Habka Karinta"
PLG_SCHEMAORG_RECIPE_FIELD_COOK_TIME_LABEL="Waqtiga Karinta"
PLG_SCHEMAORG_RECIPE_FIELD_CUISINE_LABEL="Cunto"
PLG_SCHEMAORG_RECIPE_FIELD_DATE_PUBLISHED_LABEL="Taariikhda La Daabacay"
PLG_SCHEMAORG_RECIPE_FIELD_DESCRIPTION_LABEL="Sharaxaad"
PLG_SCHEMAORG_RECIPE_FIELD_FAT_LABEL="Dufan"
PLG_SCHEMAORG_RECIPE_FIELD_FIBER_LABEL="Fiber"
PLG_SCHEMAORG_RECIPE_FIELD_GENERIC_FIELD_LABEL="Goob Guud"
PLG_SCHEMAORG_RECIPE_FIELD_GENERIC_TITLE_LABEL="Cinwaan"
PLG_SCHEMAORG_RECIPE_FIELD_GENERIC_VALUE_LABEL="Qiime"
PLG_SCHEMAORG_RECIPE_FIELD_HOUR_LABEL="Saacado"
PLG_SCHEMAORG_RECIPE_FIELD_IMAGE_LABEL="Sawir"
PLG_SCHEMAORG_RECIPE_FIELD_INGREDIENTS_LABEL="Waxyaabaha ay ka kooban tahay"
PLG_SCHEMAORG_RECIPE_FIELD_INSTRUCTIONS_LABEL="Tilmaamaha"
PLG_SCHEMAORG_RECIPE_FIELD_MINUTE_LABEL="Daqiiqado"
PLG_SCHEMAORG_RECIPE_FIELD_NAME_LABEL="Cinwaan"
PLG_SCHEMAORG_RECIPE_FIELD_NUTRITION_LABEL="Naqshadeyn"
PLG_SCHEMAORG_RECIPE_FIELD_PREPARATION_TIME_LABEL="Waqtiga Diyaarinta"
PLG_SCHEMAORG_RECIPE_FIELD_PROTEIN_LABEL="Borotiin"
PLG_SCHEMAORG_RECIPE_FIELD_SATURATED_FAT_LABEL="Dufan Dhagaxsan"
PLG_SCHEMAORG_RECIPE_FIELD_SERVING_SIZE_LABEL="Cabbirka Adeegga"
PLG_SCHEMAORG_RECIPE_FIELD_SODIUM_LABEL="Sodiyam"
PLG_SCHEMAORG_RECIPE_FIELD_SUGAR_LABEL="Sonkor"
PLG_SCHEMAORG_RECIPE_FIELD_SUITABLE_FOR_DIET_LABEL="Ku Habboon Cuntada"
PLG_SCHEMAORG_RECIPE_FIELD_TRANS_FAT_LABEL="Dufan Isdhaafay"
PLG_SCHEMAORG_RECIPE_FIELD_UNSATURATED_FAT_LABEL="Dufan Aan Dhagaxsanayn"
PLG_SCHEMAORG_RECIPE_FIELD_YIELD_LABEL="Soo Saarka"
PLG_SCHEMAORG_RECIPE_XML_DESCRIPTION="Waxay ku dareysaa Cunto karsiga nooc cusub oo tilmaame ku jira tilmaamayaasha jira."

