; Joomla! Project
; (C) 2018 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_EXTENSION_NAMESPACEMAP="Kordhin - Cusbooneysiinta Namespace"  
PLG_EXTENSION_NAMESPACEMAP_XML_DESCRIPTION="<p>Si toos ah ayuu u dhisaa oo cusbooneysiiyaa faylka <strong>administrator/cache/autoload_psr4.php</strong> kaas oo loo adeegsado in lagu soo raro kordhinta.</p><p><strong>Digniin! Plugin-kan waa in la hawlgaliyaa</strong> maadaama uu ordo marka la rakibayo, la cusbooneysiinayo ama la saaray kordhinta.</p>"

