; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_EDITORS-XTD_IMAGE="Badhanka - Warbaahinta"
PLG_IMAGE_BUTTON_IMAGE="Warbaahinta"
PLG_IMAGE_BUTTON_INSERT="Ku dheji Warbaahinta"
PLG_IMAGE_XML_DESCRIPTION="Waxay soo bandhigaysaa badhanka si loogu dhajiyo warbaahinta meel ka mid ah tifaftiraha. Waxay soo bandhigaysaa popup kuu ogolaanaya inaad habayso sifooyinka warbaahinta iyo inaad soo geliso feylasha cusub ee warbaahinta."

