; Joomla! Project
; (C) 2018 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_CONTENT_CONFIRMCONSENT="Waxyaabaha - Xaqiiji Ogolaanshaha"
PLG_CONTENT_CONFIRMCONSENT_CONSENTBOX_LABEL="Qoraal Qarsoodi"
PLG_CONTENT_CONFIRMCONSENT_FIELD_ARTICLE_DESC="Dooro maqaalka liiska ama samee mid cusub."
PLG_CONTENT_CONFIRMCONSENT_FIELD_ARTICLE_LABEL="Maqaal Qarsoodi"
PLG_CONTENT_CONFIRMCONSENT_FIELD_MENU_ITEM_LABEL="Shayga Liiska Qarsoodinimada"
PLG_CONTENT_CONFIRMCONSENT_FIELD_NOTE_DEFAULT="Markaad soo gudbiso foomkan waxaad ogolaataa Siyaasadda Qarsoodinimada ee boggan iyo kaydinta macluumaadka la gudbiyey."
PLG_CONTENT_CONFIRMCONSENT_FIELD_NOTE_DESC="Kooban oo ka mid ah siyaasadda qarsoodinimada bogga. Haddii la dhaafo markaa farriinta asalka ah ayaa la isticmaali doonaa."
PLG_CONTENT_CONFIRMCONSENT_FIELD_NOTE_LABEL="Siyaasadda Qarsoodinimada Gaaban"
PLG_CONTENT_CONFIRMCONSENT_FIELD_TYPE_ARTICLE="Maqaal"
PLG_CONTENT_CONFIRMCONSENT_FIELD_TYPE_LABEL="Nooca Qarsoodi"
PLG_CONTENT_CONFIRMCONSENT_FIELD_TYPE_MENU_ITEM="Shayga Liiska"
PLG_CONTENT_CONFIRMCONSENT_XML_DESCRIPTION="Plugin-kan wuxuu ku darayaa sanduuqa ogolaanshaha ee loo baahan yahay oo ku yaal foomka tusaale ahaan qaybta xiriirka asaasiga ah."

