; Joomla! Project
; (C) 2020 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_ACCESSIBILITY="Habka - Astaamo Dheeraad ah oo Laheli Karo"
PLG_SYSTEM_ACCESSIBILITY_CLOSE="Xir"
PLG_SYSTEM_ACCESSIBILITY_CURSOR="Calaamad Weyn"
PLG_SYSTEM_ACCESSIBILITY_DECREASE_SPACING="Yaree Fogaanta Qoraalka"
PLG_SYSTEM_ACCESSIBILITY_DECREASE_TEXT="Yaree Cabbirka Qoraalka"
PLG_SYSTEM_ACCESSIBILITY_EMOJIS="Astaamo"
PLG_SYSTEM_ACCESSIBILITY_EMOJIS_FALSE="Isticmaal Google Material Font"
PLG_SYSTEM_ACCESSIBILITY_EMOJIS_TRUE="Isticmaal Emojis"
PLG_SYSTEM_ACCESSIBILITY_GREY="Midabyo Cawl ah"
PLG_SYSTEM_ACCESSIBILITY_INCREASE_SPACING="Kordhi Fogaanta Qoraalka"
PLG_SYSTEM_ACCESSIBILITY_INCREASE_TEXT="Kordhi Cabbirka Qoraalka"
PLG_SYSTEM_ACCESSIBILITY_INVERT_COLORS="Soo rogo Midabada"
PLG_SYSTEM_ACCESSIBILITY_MENU_TITLE="Xulashooyinka Laheli Karo"
PLG_SYSTEM_ACCESSIBILITY_READING="Tilmaame Akhris"
PLG_SYSTEM_ACCESSIBILITY_RESET="Dib Udej"
PLG_SYSTEM_ACCESSIBILITY_SECTION="Qaybta Goobta"
PLG_SYSTEM_ACCESSIBILITY_SECTION_ADMIN="Maamulaha (Backend)"
PLG_SYSTEM_ACCESSIBILITY_SECTION_BOTH="Labada"
PLG_SYSTEM_ACCESSIBILITY_SECTION_SITE="Goobta (Frontend)"
PLG_SYSTEM_ACCESSIBILITY_STT="Khudbad ilaa Qoraal"
PLG_SYSTEM_ACCESSIBILITY_TTS="Qoraal ilaa Cod"
PLG_SYSTEM_ACCESSIBILITY_UNDERLINE="Hoos U Xarriiq Xiriirada"
PLG_SYSTEM_ACCESSIBILITY_XML_DESCRIPTION="Plugin-kani wuxuu ku darayaa qalabka toolbar-kaaga goobtaada si leh xulashooyin dheeraad ah oo laheli karo. Markii la hawlgaliyo, toolbar-ka waxaa lagala furi karaa jiirka ama isticmaalka furaha <strong>CTRL + ALT + A</strong>, ama <strong>CTRL + OPTION + A</strong> ku MacOS."

