; Joomla! Project
; (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_EDITORS-XTD_FIELDS="Badhan - Goob"
PLG_EDITORS-XTD_FIELDS_XML_DESCRIPTION="<p>Wuxuu soo bandhigayaa badhan lagu geliyo goob cayiman meel tafatireed. Wuxuu soo bandhigayaa popup kuu ogolaanaya inaad doorato goobta.</p><p><strong>Digniin!</strong>: meesha la sameeyay looma gudbin doono haddii <a href=\"index.php?option=com_plugins&view=plugins&filter[folder]=content\">Plugin-ka Macluumaadka - Goobaha</a> aysan furin.</p>"

