; Joomla! Project
; (C) 2013 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FINDER_QUERY_FILTER_BRANCH_P_TAG="Calaamadaha"
PLG_FINDER_QUERY_FILTER_BRANCH_S_TAG="Calaamad"
PLG_FINDER_TAGS="Raadiyaha Casriga ah - Calaamadaha"
PLG_FINDER_TAGS_FIELD_SEARCH_ARCHIVED_DESC="Marka aad badalato dejintan, waa inaad ku ordoo amarka tixaabinta ee Raadiyaha Casriga ah si tan ay u dhaqangasho."
PLG_FINDER_TAGS_FIELD_SEARCH_ARCHIVED_LABEL="Raadiyo Mawduucyada La Kaydiyay"
PLG_FINDER_TAGS_TAXONOMIES_AUTHOR="Qoraaga"
PLG_FINDER_TAGS_TAXONOMIES_LABEL="Kala soocida la Tixaabayo"
PLG_FINDER_TAGS_TAXONOMIES_LANGUAGE="Luuqadda"
PLG_FINDER_TAGS_TAXONOMIES_TYPE="Nooca"
PLG_FINDER_TAGS_XML_DESCRIPTION="Ku dhejiinkan wuxuu tixraacayaa calaamadaha Joomla!."

