; Joomla! Project
; (C) 2011 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FINDER_NEWSFEEDS="Raadin Caqliga leh - Feejintii Wararka"
PLG_FINDER_NEWSFEEDS_FIELD_SEARCH_ARCHIVED_DESC="Markaad badaleyso dejiintan, waxaad u baahan tahay inaad ku socodsiiso amarka tusaha Raadiinta Caqliga leh ka hor inta aanay tani saamayn ka yeelan."
PLG_FINDER_NEWSFEEDS_FIELD_SEARCH_ARCHIVED_LABEL="Raadi Mawduuca La keydiyay"
PLG_FINDER_NEWSFEEDS_TAXONOMIES_CATEGORY="Nooca"
PLG_FINDER_NEWSFEEDS_TAXONOMIES_LABEL="Canshuuraha in la Tusi"
PLG_FINDER_NEWSFEEDS_TAXONOMIES_LANGUAGE="Afka"
PLG_FINDER_NEWSFEEDS_TAXONOMIES_TYPE="Nooca"
PLG_FINDER_NEWSFEEDS_XML_DESCRIPTION="Kubbakaragan wuxuu tusmada Joomla! Feejintii Wararka."
PLG_FINDER_QUERY_FILTER_BRANCH_P_NEWS_FEED="Feejintii Wararka"
PLG_FINDER_QUERY_FILTER_BRANCH_S_NEWS_FEED="Feejinta Wararka"

