; Joomla! Project
; (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_TASK_NOTIFICATION="Nidaamka - Ogeysiiska Shaqada"
PLG_SYSTEM_TASK_NOTIFICATION_FAILURE_MAIL_BODY="Salaan,\n\n\nFulintii lagu qorsheeyay Shaqada Hawlaha Jadwalka#{TASK_ID}, {TASK_TITLE}, waxay ku guuldareysatay koodhka ka bixidda {EXIT_CODE} marka la gaaro {EXEC_DATE_TIME}.\n\nFadlan booqo backend-ka Joomla! wixii macluumaad dheeraad ah.\n\n{TASK_OUTPUT}"
PLG_SYSTEM_TASK_NOTIFICATION_FAILURE_MAIL_SUBJECT="Guuldarada Shaqada"
PLG_SYSTEM_TASK_NOTIFICATION_FAILURE_USERGROUP_LABEL="Kooxaha Isticmaalka ee La Ogeysiinayo"
PLG_SYSTEM_TASK_NOTIFICATION_FATAL_MAIL_BODY="Salaan,\n\nFulinta Shaqada Jadwalka#{TASK_ID}, {TASK_TITLE}, waxay kasoo kabsatay guuldaro halis ah.\n\nTani waxay macnaheedu noqon kartaa in fulinta hawsha ay daalisay ilaha nidaamka ama xaddidaadda INI ee PHP.\n\nFadlan booqo backend-ka Joomla! wixii macluumaad dheeraad ah."
PLG_SYSTEM_TASK_NOTIFICATION_FATAL_MAIL_SUBJECT="Hawl Kasoo Badbaadday Guuldaro Halis ah"
PLG_SYSTEM_TASK_NOTIFICATION_FATAL_USERGROUP_LABEL="Kooxaha Isticmaalka ee La Ogeysiinayo"
PLG_SYSTEM_TASK_NOTIFICATION_LABEL_FAILURE_MAIL_TOGGLE="Guuldarada Shaqada"
PLG_SYSTEM_TASK_NOTIFICATION_LABEL_FATAL_FAILURE_MAIL_TOGGLE="Guuldarrooyin/Crashyo Halista ah (Lagu Taliyay)"
PLG_SYSTEM_TASK_NOTIFICATION_LABEL_ORPHANED_TASK_MAIL_TOGGLE="Shaqooyinka Yaryar (Lagu Taliyay)"
PLG_SYSTEM_TASK_NOTIFICATION_LABEL_SUCCESS_MAIL_TOGGLE="Guusha Shaqada"
PLG_SYSTEM_TASK_NOTIFICATION_NO_MAIL_SENT="Uma suurtagelin inay soo dirto ogeysiiska shaqada isticmaalaha kasta. Tani waxay ka dhigan tahay in mailer-ka si habboon loo dhigin ama ma jiro isticmaalaha leh emayllada nidaamka oo karti u leh, com_scheduler `core.manage` jago jiro."
PLG_SYSTEM_TASK_NOTIFICATION_ORPHAN_MAIL_BODY="Salaan,\n\nShaqadii Jadwalka#{TASK_ID}, {TASK_TITLE}, waxaa la siiyay si xor ah. Tani waxay u badan tahay in plugin-ka bixiyaha laga saaray ama laga joojiyay Joomla!-kaaga.\n\nFadlan booqo backend-ka Joomla! si aad u baarto."
PLG_SYSTEM_TASK_NOTIFICATION_ORPHAN_MAIL_SUBJECT="Shaqo Cusub oo Yaraatay"
PLG_SYSTEM_TASK_NOTIFICATION_ORPHAN_USERGROUP_LABEL="Kooxaha Isticmaalka ee La Ogeysiinayo"
PLG_SYSTEM_TASK_NOTIFICATION_SUCCESS_MAIL_BODY="Salaan,\n\nShaqada Jadwalka#{TASK_ID}, {TASK_TITLE}, si guul leh ayaa loo fuliyay marka {EXEC_DATE_TIME}.\n\n{TASK_OUTPUT}"
PLG_SYSTEM_TASK_NOTIFICATION_SUCCESS_MAIL_SUBJECT="Shaqo Guul Leh"
PLG_SYSTEM_TASK_NOTIFICATION_SUCCESS_USERGROUP_LABEL="Kooxaha Isticmaalka ee La Ogeysiinayo"
PLG_SYSTEM_TASK_NOTIFICATION_USER_FETCH_FAIL="Ku guuldareystay inuu soo helo isticmaalayaasha si loogu diro ogeysiisyada."
PLG_SYSTEM_TASK_NOTIFICATION_XML_DESCRIPTION="Mas'uul ka ah ogeysiisyada emayl ee fulinta hawlaha la qorsheeyay."

