; Joomla! Project
; (C) 2009 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_REDIRECT="Nidaamka - Dib u Toosinta"
PLG_SYSTEM_REDIRECT_ERROR_UPDATING_DATABASE="Khalad ayaa dhacay intuu dib u cusbooneysiinayey xogta."
PLG_SYSTEM_REDIRECT_FIELD_COLLECT_URLS_LABEL="Ururi URLs"
PLG_SYSTEM_REDIRECT_FIELD_EXCLUDE_URLS_DESC="Ku qeex tijaabooyin joogto ah ama shuruudo aan la heli doonin badbaadinta."
PLG_SYSTEM_REDIRECT_FIELD_EXCLUDE_URLS_LABEL="Ka Saar URLs"
PLG_SYSTEM_REDIRECT_FIELD_EXCLUDE_URLS_REGEXP_LABEL="Tijaabada Joogtada ah"
PLG_SYSTEM_REDIRECT_FIELD_EXCLUDE_URLS_TERM_DESC="Tijaabo joogto ah ama erey aan la helin."
PLG_SYSTEM_REDIRECT_FIELD_EXCLUDE_URLS_TERM_LABEL="Erey"
PLG_SYSTEM_REDIRECT_FIELD_STORE_FULL_URL_DESC="Badbaadi URL ka dhacay sida mid buuxda (oo ay ku jiraan domain) ama qaraabo (aan ku jirin domain)."
PLG_SYSTEM_REDIRECT_FIELD_STORE_FULL_URL_LABEL="Ku dar Magaca Domain-ka ee URL dhacay"
PLG_SYSTEM_REDIRECT_XML_DESCRIPTION="Nidaamka plugin-ka dib u toosinta wuxuu awood u siinayaa habka Dib u Toosinta Joomla si uu u qabto boggaga maqan oo u soo jeediyo isticmaalayaasha."

