; Joomla! Project
; (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_JOOA11Y="Nidaam - Hubiyaha Helitaanka Joomla"
PLG_SYSTEM_JOOA11Y_XML_DESCRIPTION="Hubiyaha Helitaanka Joomla wuxuu muuqaal ahaan iftiimiyaa dhibaatooyinka helitaanka iyo ku-isticmaalka guud. Waxaa loogu talagalay qorayaasha nuxurka, plugin-ku wuxuu aqoonsadaa khaladaadka ama digniinaha waxaana uu bixiyaa hagitaan ku saabsan sida loo saxo. Fadlan la soco in plugin-kan aanu bixin falanqayn dhamaystiran oo ku saabsan boggaaga, mana hubiyo si otomaatig ah helitaanka boggaaga. Waxaa muhiim ah in la doorto template sida asal ahaan u heli karta si loo hubiyo in boggaagu la kulmo heerarka helitaanka."

