; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_AUTHENTICATION_JOOMLA="Soo galid - Joomla"
PLG_AUTHENTICATION_JOOMLA_XML_DESCRIPTION="<p>Waxay maamushaa aqoonsiga isticmaalaha ee caadiga ah ee Joomla.</p><p><strong>Digniin! Waa inaad leedahay ugu yaraan hal fiilada aqoonsiga oo karti leh ama waxaad waayi doontaa marin u helka boggaaga.</strong></p>"

