; Joomla! Project
; (C) 2019 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_SKIPTO="Nidaamka - U-skoobi-si-to-Afhayn"
PLG_SYSTEM_SKIPTO_XML_DESCRIPTION="Plugin-ka wuxuu abuuraa menu hoos u dhaca oo ka kooban isku xirka meelaha muhiimka ah ee bogga la siiyay. Tani waxay u sahlaysaa dadka isticmaala kumbuyuutarka iyo akhristayaasha shaashad in deg deg loogu boodo meesha la doonayo iyaga oo ka dooranaya liiska fursadaha."

