; Joomla! Project
; (C) 2015 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_STATS="Nidaam - Tirakoobka Joomla!"
PLG_SYSTEM_STATS_XML_DESCRIPTION="Plugin-ka Nidaamka kaas oo u dira tirakoobka deegaanka server uu maamulo mashruuca Joomla! si loo sameeyo falanqeyn tirakoob ah. Tirakoobka la soo diray waxaa ka mid ah nooca PHP, nooca CMS, nooca Database, nooca Database iyo nooca Server-ka."

