; Joomla! Project
; (C) 2016 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_EDITORS-XTD_CONTACT="Badhamada - La xiriir"
PLG_EDITORS-XTD_CONTACT_BUTTON_CONTACT="La xiriir"
PLG_EDITORS-XTD_CONTACT_XML_DESCRIPTION="Waxay soo bandhigtaa badhamo si loo geliyo isku xirnaanta Xiriiriyaha aagga tifaftiraha. Waxay soo bandhigtaa guddi hufan oo kuu ogolaanaya inaad doorato xiriirka."

