; Joomla! Project
; (C) 2007 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_DEBUG_FIELD_ALLOWED_GROUPS_LABEL="Kooxaha La Ogol yahay"
PLG_DEBUG_FIELD_LANGUAGE_ERRORFILES_LABEL="Khaladaadka Markay Akhriyayso Faalada Luqadda"
PLG_DEBUG_FIELD_LANGUAGE_FILES_LABEL="Faalada Luqadda"
PLG_DEBUG_FIELD_LANGUAGE_STRING_LABEL="Tixda Luqadda"
PLG_DEBUG_FIELD_LOG_DEPRECATED_CORE_LABEL="Kala Qeybi API-ha Asalka Ah Ee Xumaaday"
PLG_DEBUG_FIELD_LOGS_LABEL="Diiwaannada Galitaanka"
PLG_DEBUG_FIELD_MEMORY_LABEL="Isticmaalka Xusuusta"
PLG_DEBUG_FIELD_PROFILING_LABEL="Astaynta"
PLG_DEBUG_FIELD_QUERIES_LABEL="Weydiiya"
PLG_DEBUG_FIELD_QUERY_EXPLAINS_LABEL="Sharaxa Weydiinta"
PLG_DEBUG_FIELD_QUERY_PROFILES_LABEL="Astaamaha Weydiinta"
PLG_DEBUG_FIELD_QUERY_TRACES_LABEL="Raadiyeyaasha Weydiinta"
PLG_DEBUG_FIELD_REFRESH_ASSETS_DESC="Haddii la ansixiyo, bog kasta dib markuu load gareeyo, waxa lagu dari doonaa hash kala duwan fayl kasta oo script/stylesheet oo leh nooc toos ah si aanay u isticmaalin kaydka browser-ka marna."
PLG_DEBUG_FIELD_REFRESH_ASSETS_LABEL="Cusboonaysii Hantida"
PLG_DEBUG_FIELD_REQUEST_LABEL="Codsi"
PLG_DEBUG_FIELD_SESSION_LABEL="Xogta Kalfadhi" 
PLG_DEBUG_FIELD_STRIP_FIRST_LABEL="Ka Saar Ereydka Koowaad"
PLG_DEBUG_FIELD_STRIP_PREFIX_DESC="Ka saar ereyo bilowga tixda. Ereyo badan waxa loo isticmaali karaa qaabka: (eray1|eray2)."
PLG_DEBUG_FIELD_STRIP_PREFIX_LABEL="Ka Saar Bilowga"
PLG_DEBUG_FIELD_STRIP_SUFFIX_DESC="Ka saar ereyo dhammaadka tixda. Ereyo badan waxa loo isticmaali karaa qaabka: (eray1|eray2)."
PLG_DEBUG_FIELD_STRIP_SUFFIX_LABEL="Ka Saar Dhammaadka"
PLG_DEBUG_FIELD_TRACK_REQUEST_HISTORY_LABEL="Raac Taariikhda Codsiga"
PLG_DEBUG_FIELD_TRACK_REQUEST_HISTORY_DESC="Markii la ansixiyo waxa ay xogta taariikhda codsiga ku kaydisaa nidaamka kaydinta si loogu falanqeeyo mustaqbalka. Xogtan waxay ka koobnaan kartaa furayaasha sirta iyo token-nada qarsoon. Waxa si kooban oo kaliya lagu ansixiyaa in feylka akhriskari karo qofkasta oo leh akhris u helidda faylka cache. Markii go'aankan la joojiyo waajib ayey ku tahay inaad si adag soo nadiifiso Site Cache!"
PLG_DEBUG_LANGUAGE_FIELDSET_LABEL="Luqadda"
PLG_DEBUG_LOGGING_FIELDSET_LABEL="Diiwaangelinta"
PLG_DEBUG_XML_DESCRIPTION="Plugin-kan wuxuu bixiyaa macluumaad kala duwan oo nidaamka ah iyo sidoo kale kaalmo loogu talagalay abuurista faylalka tarjumaadda."
PLG_SYSTEM_DEBUG="Nidaamka - Dhib-u-saar"

