; Joomla! Project
; (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FIELDS_CALENDAR="Goobo - Kalandarada"
PLG_FIELDS_CALENDAR_DEFAULT_VALUE_DESC="Tani waa taariikhda caadiga ah. Qiimaha wuxuu noqon karaa qaabka ISO 8601 (YYYY-MM-DD HH:MM:SS) ama HADA, taas oo muujineysa taariikhda dhabta ah."
PLG_FIELDS_CALENDAR_DEFAULT_VALUE_LABEL="Taariikhda Caadiga ah"
PLG_FIELDS_CALENDAR_LABEL="Kalandarada (%s)"
PLG_FIELDS_CALENDAR_PARAMS_SHOWTIME_DESC="Haddii la awoodiyo, goobta kalandaradu waxay filaysaa taariikh iyo waqti waxayna sidoo kale muujinaysaa wakhtiga. Qaababka waxaa adeegsada xadhkaha luqadda ee caadiga ah."
PLG_FIELDS_CALENDAR_PARAMS_SHOWTIME_LABEL="Muuji Waqtiga"
PLG_FIELDS_CALENDAR_XML_DESCRIPTION="Qalabkan wuxuu kuu oggolaanayaa inaad abuurto goobo cusub oo nooca 'kalandarada' ah meel kasta oo lagu taageerayo goobo gaar ah."

