; Joomla! Project
; (C) 2010 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_CONTENT_LOADMODULE="Mawduuc - Xamuul Module-ka"
PLG_LOADMODULE_XML_DESCRIPTION="Gudaha waxyaabaha ku jira, plugin-kan wuxuu ku shubaa Module-ka aqoonsi ID ah, Habka: {loadmoduleid 1} ama Module-ka booska uu ku jiro, Habka: {loadposition user1} ama Module-ka magaca, Habka: {loadmodule mod_login}. Ikhtiyaar ahaan waxaad sheegi kartaa qaabka moduleka iyo xamuulka moduleka gaarka ah cinwaanka, Habka: {loadmodule mod_login,module title,style}."

