; Joomla! Project
; (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_TASK_PRIVACYCONSENT="Hawl - Ogolaanshaha Sirta"
PLG_TASK_PRIVACYCONSENT_CONSENTEXPIRATIONDAYS_DESC="Tirada maalmaha tan iyo markii ay ogolaanshaha sirta dhacayaan."
PLG_TASK_PRIVACYCONSENT_CONSENTEXPIRATIONDAYS_LABEL="Dhacitaan"
PLG_TASK_PRIVACYCONSENT_INVALIDATE_TITLE="Dhacitaanka ogolaanshaha sirta"
PLG_TASK_PRIVACYCONSENT_INVALIDATE_DESC="Maamul dhacitaanka ogolaanshaha sirta"
PLG_TASK_PRIVACYCONSENT_EMAIL_REMIND_BODY="Ogolaanshahaaga Sirta ee aad ku bixisay {URL} waxaa dhici doona maalmo yar gudahood, waxaad cusbooneysiin kartaa ogolaanshaha sirta ee boggan.\n\nSi aad sidaas u sameyso, mid ka mid ah howlahaan hoose qabo:\n\n1. Booqo URL-kan: {TOKENURL}\n\n2. Koobi garaaftaada emailkaan, booqo URL-ka lagu xusay, oo ku koolkoolo garaaftaada foomka.\nURL: {FORMURL}\nGaraafta: {TOKEN}\n\nFadlan ogow in garaafta tani ay ansaxsantahay kaliya xisaabtan."
PLG_TASK_PRIVACYCONSENT_EMAIL_REMIND_SUBJECT="Ogolaanshaha Sirta ee {SITENAME}"
PLG_TASK_PRIVACYCONSENT_MAIL_REQUEST_REMINDER_DESC="Xusuusin in la cusbooneysiiyo ogolaanshaha sirta boggan."
PLG_TASK_PRIVACYCONSENT_MAIL_REQUEST_REMINDER_TITLE="Hawl - Ogolaanshaha Sirta: Cusbooneysii Ogolaanshaha"
PLG_TASK_PRIVACYCONSENT_NOTIFICATION_USER_PRIVACY_EXPIRED_MESSAGE="Ogolaanshaha sirta ayaa dhacay %1$s."
PLG_TASK_PRIVACYCONSENT_NOTIFICATION_USER_PRIVACY_EXPIRED_SUBJECT="Ogolaanshaha Sirta ayaa Dhacay"
PLG_TASK_PRIVACYCONSENT_REMINDBEFORE_DESC="Tirada maalmaha lagu soo diri doono xusuusinta ka hor intaanay ogolaanshaha sirta dhicin."
PLG_TASK_PRIVACYCONSENT_REMINDBEFORE_LABEL="Xusuuso"
PLG_TASK_PRIVACYCONSENT_XML_DESCRIPTION="Hawl lagu xusuusiyo ogolaanshaha dhacay iyo in la tirtiro ogolaanshaha dhacay"

