; Joomla! Project
; (C) 2010 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_EDITORS-XTD_READMORE="Badhan - Akhri badan"
PLG_READMORE_XML_DESCRIPTION="Waxay awood u siisaa badhan kaas oo kuu ogolaanaya inaad geliso xiriirka <em>Akhri badan &hellip;</em> maqaal gudaheeda."

