; Joomla! Project
; (C) 2010 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_LOGOUT="Nidaamka - Ka-bax"
PLG_SYSTEM_LOGOUT_REDIRECT="Waxaad loo wareejiyay bogga guriga kadib markaad ka baxdo."
PLG_SYSTEM_LOGOUT_XML_DESCRIPTION="Qalabka nidaamka ka-baxa ayaa u oggolaanaya Joomla inuu isticmaale ku wareejiyo bogga guriga haddii ay doortaan inay ka baxaan halka ay ku jiraan bog leh marin xaddidan."

