; Joomla! Project
; (C) 2015 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_EDITORS-XTD_MODULE="Badhanka - Module"
PLG_MODULE_BUTTON_MODULE="Module"
PLG_MODULE_XML_DESCRIPTION="Waxay soo bandhigtaa badhan si ay ugu dhigto module meel wax lagu qoro. Waxay soo bandhigtaa daaqad yar oo kuu ogolaanaysa inaad doorato module-ka."

