; Joomla! Project
; (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FIELDS_SQL="Goobo - SQL"
PLG_FIELDS_SQL_CREATE_NOT_POSSIBLE="Kaliya isticmaale Super ayaa abuuri kara ama wax ka beddeli kara goobta SQL!"
PLG_FIELDS_SQL_LABEL="SQL (%s)"
; The following string is deprecated and will be removed with 6.0
PLG_FIELDS_SQL_PARAMS_FORM_LAYOUT_FANCY_SELECT="Xul fududeyn"
PLG_FIELDS_SQL_PARAMS_HEADER_DESC="Kudar xarig aan lahayn qiimo oo ku yaal dusha sare liiska hoos udhaca tusaale ahaan ' - Xulo maqaal - '."
PLG_FIELDS_SQL_PARAMS_HEADER_LABEL="Cinwaan"
PLG_FIELDS_SQL_PARAMS_MULTIPLE_LABEL="Badadan"
PLG_FIELDS_SQL_PARAMS_QUERY_DESC="Weeydii SQL-ka oo keeni doonta xogta liiska hoos udhaca. Weydiinta waa inay soo celisaa laba saf; mid lagu magacaabo 'qiimo' oo xajisan doona qiimaha qodobbada liiska; midka kalena waxaa loo yaqaan 'qoraal' oo leh qoraalka ku jira liiska hoos udhaca."
PLG_FIELDS_SQL_PARAMS_QUERY_LABEL="Weeydiin"
PLG_FIELDS_SQL_XML_DESCRIPTION="Kani waa plugin kuu ogolaanaya inaad abuurto goobaha cusub ee nooca 'sql' gudaha dheereynta kasta oo ay taageeraan goobaha gaarka ah."

