; Joomla! Project
; (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_MULTIFACTORAUTH_FIXED="Oggolaanshaha-kaananyahay oo lama beddeli karo - Koodka Joogtada ah"
PLG_MULTIFACTORAUTH_FIXED_ERR_EMPTYCODE="Koodkaaga joogtada ah kuma jiri karo waxba."
PLG_MULTIFACTORAUTH_FIXED_LBL_DEFAULTTITLE="Kood Joogtada ah"
PLG_MULTIFACTORAUTH_FIXED_LBL_DISPLAYEDAS="Kood Joogtada ah"
PLG_MULTIFACTORAUTH_FIXED_LBL_LABEL="Kood Joogtada ah"
PLG_MULTIFACTORAUTH_FIXED_LBL_PLACEHOLDER="Geli Koodkaaga Joogtada ah"
PLG_MULTIFACTORAUTH_FIXED_LBL_POSTMESSAGE="<p class=\"alert alert-info\">Farriimaha ka muuqda kor iyo hoos meelaha koodhka waa la habayn karaa adiga oo ka beddelaya xarigaha luqadda <code>PLG_MULTIFACTORAUTH_FIXED_LBL_PREMESSAGE</code> iyo <code>PLG_MULTIFACTORAUTH_FIXED_LBL_POSTMESSAGE</code>.</p>"
PLG_MULTIFACTORAUTH_FIXED_LBL_PREMESSAGE="<p>Tani waa tusmo ku saabsan Oggolaanshiyaha-kaananyahay ee Joomla. Waa inaad gashaa koodka joogtada ah ee aad habeysay markaad fureysid Oggolaanshiyaha-kaananyahay ee isticmaalehan. Waxay si habboon u shaqaysaa sida eray sir second ah.</p>"
PLG_MULTIFACTORAUTH_FIXED_LBL_SETUP_POSTMESSAGE="<p class=\"alert alert-info\">Farriimaha ka muuqda kor iyo hoos meelaha dejinta waa la habayn karaa adiga oo ka beddelaya xarigaha luqadda <code>PLG_MULTIFACTORAUTH_FIXED_LBL_SETUP_PREMESSAGE</code> iyo <code>PLG_MULTIFACTORAUTH_FIXED_LBL_SETUP_POSTMESSAGE</code></p>"
PLG_MULTIFACTORAUTH_FIXED_LBL_SETUP_PREMESSAGE="<p>Ku shub Kood Joogto ah hoosta. Koodkan Joogtada ah waa in la geliyo ka dib markaad gasho ka hor inta aanad isticmaalin shabakadda.</p>"
PLG_MULTIFACTORAUTH_FIXED_LBL_SHORTINFO="Xulo koodhkaaga ay kuu dajisan tahay. <strong>Kaliya loogu talagalay ujeedooyinka tusidda</strong>."
PLG_MULTIFACTORAUTH_FIXED_XML_DESCRIPTION="Tusmo ku saabsan Oggolaanshiyaha-kaananyahay oo isticmaalaya kood joogta ah (waxa loo yaqaano &ldquo;eray sir second&rdquo;). <strong>Ha isticmaalin bogagga nool, ma aha mid ammaan ah.</strong> Plugin-kani wuxuu u talagalay in loogu isticmaalo tusaale ahaan horumariyeyaasha danaynaya abuurista pluginskooda gaarka ah."

