; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_CONTENT_PAGENAVIGATION="Mawduuc - Hagista Bogga"
PLG_PAGENAVIGATION_ARIA_LABEL="Hagista Bogga"
PLG_PAGENAVIGATION_FIELD_DISPLAY_LABEL="Tekstiga Linkiga"
PLG_PAGENAVIGATION_FIELD_POSITION_LABEL="Meel"
PLG_PAGENAVIGATION_FIELD_RELATIVE_LABEL="Ku Saabsan"
PLG_PAGENAVIGATION_FIELD_VALUE_ABOVE="Kor"
PLG_PAGENAVIGATION_FIELD_VALUE_ARTICLE="Qormo Buuxa"
PLG_PAGENAVIGATION_FIELD_VALUE_BELOW="Hoos"
PLG_PAGENAVIGATION_FIELD_VALUE_NEXTPREV="Xiga/Hore (tekst joogto ah)"
PLG_PAGENAVIGATION_FIELD_VALUE_TEXT="Tekst"
PLG_PAGENAVIGATION_FIELD_VALUE_TITLE="Cinwaanka Qormada"
PLG_PAGENAVIGATION_XML_DESCRIPTION="Waxa ay kuu ogolaanaysaa inaad ku darto xiriirada <em>Xiga &amp; Hore</em> qormo."

