; Joomla! Project
; (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FIELDS_IMAGELIST="Goobo - Liiska sawirrada"
PLG_FIELDS_IMAGELIST_LABEL="Liiska Sawirada (%s)"
PLG_FIELDS_IMAGELIST_PARAMS_DIRECTORY_DESC="Galkaan wuxuu la xiriiraa galka \"sawirrada\" ee ku jira xididka Joomla!."
PLG_FIELDS_IMAGELIST_PARAMS_DIRECTORY_LABEL="Gal"
PLG_FIELDS_IMAGELIST_PARAMS_IMAGE_CLASS_LABEL="Fasalka Sawirka"
PLG_FIELDS_IMAGELIST_PARAMS_MULTIPLE_LABEL="Dhowr"
PLG_FIELDS_IMAGELIST_XML_DESCRIPTION="Ku daris kani wuxuu kuu ogolaanayaa inaad abuurto goobo cusub oo nooca 'liiska sawirrada' ah meel kasta oo goobaha la kobciyo lagu taageerayo."

