; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_EDITORS-XTD_PAGEBREAK="Badhanka - Jebinta Bogga"
PLG_EDITORSXTD_PAGEBREAK_BUTTON_PAGEBREAK="Jebinta Bogga"
PLG_EDITORSXTD_PAGEBREAK_XML_DESCRIPTION="Waxay siisaa badhan oo kuu ogolaanaya inaad ku darto jebinta bogga maqaal. Daaqad pop-up ah ayaa kuu ogolaanaysa inaad dhigayso habka loo isticmaalo."

