; Joomla! Project
; (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FIELDS_COLOR="Goobaha - Midabka"
PLG_FIELDS_COLOR_LABEL="Midabka (%s)"
PLG_FIELDS_COLOR_XML_DESCRIPTION="Kani plugin wuxuu kuu ogolaanayaa inaad abuurto goobo cusub oo nooca 'midab' ah oo ku jira kordhin kasta oo taageeraya goobo gaar ah."

