; Joomla! Project
; (C) 2018 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_QUICKICON_PRIVACYCHECK="Asta Degdeg ah - Ogeysiiska Codsiyada Waa-In La Fashiliyo ee Joomla!"
PLG_QUICKICON_PRIVACYCHECK_CHECKING="Baadhista codsiyada &hellip;"
PLG_QUICKICON_PRIVACYCHECK_ERROR="Codsiyo aan la aqoon &hellip;"
PLG_QUICKICON_PRIVACYCHECK_GROUP_DESC="Kooxda cinwaankan (qiimahaan waxaa loo barbardhigaa qiimaha kooxda ee loo adeegsado qaybah <strong>Asta Degdeg ah</strong> si ay u farsameeyaan astaamo)."
PLG_QUICKICON_PRIVACYCHECK_GROUP_LABEL="Koox"
PLG_QUICKICON_PRIVACYCHECK_NOREQUEST="Wax codsiyo ah oo degdeg ah oo waafaqsan xeerka gaarka ah ma jiro."
PLG_QUICKICON_PRIVACYCHECK_REQUESTFOUND="Codsiyo gaar ah oo degdeg ah ayaa la helay!"
PLG_QUICKICON_PRIVACYCHECK_REQUESTFOUND_BUTTON="Eeg Codsiyada"
PLG_QUICKICON_PRIVACYCHECK_REQUESTFOUND_MESSAGE="%s Codsiyada Xuquuqda Gaarka ah ee Degdega ah si loo maamulo."
PLG_QUICKICON_PRIVACYCHECK_XML_DESCRIPTION="Waxay hubisaa codsiyada gaarka ah ee u baahan in la maareeyo waxayna kugu ogeysiineysaa markaad booqato Gudiga Guriga."

