; Joomla! Project
; (C) 2013 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_INSTALLER_WEBINSTALLER="Rakibiyaha - Ku rakib Shabakada"
PLG_INSTALLER_WEBINSTALLER_CANNOT_INSTALL_EXTENSION_IN_PLUGIN="Kordhintaan laguma rakibi karo nidaamka rakibidda shabakada. Fadlan booqo goobta shabakadda ee horumariyaha si aad u iibsato/soodajiso."
PLG_INSTALLER_WEBINSTALLER_INSTALL_WEB_CONFIRM="Fadlan xaqiiji rakibida adigoo dooranaya badhanka Rakib"
PLG_INSTALLER_WEBINSTALLER_INSTALL_WEB_CONFIRM_NAME="Magaca Kordhinta"
PLG_INSTALLER_WEBINSTALLER_INSTALL_WEB_CONFIRM_URL="Ku rakib shabakada"
PLG_INSTALLER_WEBINSTALLER_INSTALL_WEB_LOADING="Soo gelinayaa &hellip;"
PLG_INSTALLER_WEBINSTALLER_INSTALL_WEB_LOADING_ERROR="Lama xidhiidhi karo adeegaha Joomla! Fadlan isku day mar kale goor dambe."
PLG_INSTALLER_WEBINSTALLER_REDIRECT_TO_EXTERNAL_SITE_TO_INSTALL="Waxaad lagu gudbin doonaa xidhiidhka soo socda si aad u dhammaystirto diiwaangelinta/iibsashada: [SITEURL]"
PLG_INSTALLER_WEBINSTALLER_TAB_LABEL="Ku rakib shabakada"
PLG_INSTALLER_WEBINSTALLER_XML_DESCRIPTION="Qalabkani wuxuu kuu oggolaanayaa inaad si toos ah uga rakibto Buugga Kordhinta Joomla!"

