; Joomla! Project
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_QUICKICON_AUTOUPDATE="Astaanta Deg-degga ah - Ogeysiiska Xaaladda Soo Cusboonaysiinta Tooska ah ee Joomla!"
PLG_QUICKICON_AUTOUPDATE_XML_DESCRIPTION="Kormeera xaaladda cusboonaysiinta otomaatiga ah oo ku soo ogeysiiya markaad booqato bogga Dashboard-ka Guriga."

