; Joomla! Project
; (C) 2013 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_AUTHENTICATION_COOKIE="Cadaynta - Kukkiga"
PLG_AUTHENTICATION_COOKIE_ERROR_LOG_LOGIN_FAILED="Kukki gelitaanku wuu fashilmay isticmaalaha %u."
PLG_AUTHENTICATION_COOKIE_FIELD_COOKIE_LIFETIME_LABEL="Muddada Nololeed ee Kukki (maalmo)"
PLG_AUTHENTICATION_COOKIE_FIELD_KEY_LENGTH_LABEL="Dhererka Furaha"
PLG_AUTHENTICATION_COOKIE_PRIVACY_CAPABILITY_COOKIE="Iyadoo lagu weheliyo plugin-ka taageera muuqaalka \"I Xasuuso\", sida plugin-ka \"Nidaamka - I Xasuuso\", plugin-kani wuxuu abuurayaa kukkii isticmaaleha biraawsarka haddii \"I Xasuuso\" sanduuqa la xusho marka la gelayo bogga. Kukikaan waxaa lagu aqoonsan karaa horu dhaca `joomla_remember_me` waxaana loo isticmaalaa in si otomaatig ah loogu xiro isticmaalayaasha bogga marka ay booqdaan oo aysan horey u gelin."
PLG_AUTHENTICATION_COOKIE_XML_DESCRIPTION="<p>Maareeyaha shaabada adeegsiga Kukkiyaasha Joomla.</p><p><strong>Digniin! Waa inaad haysataa ugu yaraan hal plugin oo kale oo aqoonsi gudaha leh oo karti leh.</strong><br>Waxaad kaloo u baahan doontaa plugin sida plugin-ka Nidaamka - I Xasuuso si aad u fuliso gelitaanka kukki.</p>"

