; Joomla! Project
; (C) 2020 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_WORKFLOW_BASIC_STAGE="Marxalad Aasaasi ah"
COM_WORKFLOW_NOTIFICATION_FIELDSET_LABEL="Ogeysiis"
PLG_WORKFLOW_NOTIFICATION="Hawlgalka - Ogeysiis"
PLG_WORKFLOW_NOTIFICATION_ADDTEXT="Marxaladda waa la beddelay"
PLG_WORKFLOW_NOTIFICATION_ADDTEXT_DESC="Qoraalkan waa la diri doonaa: Cinwaanka [title], waxa beddelay [user], xaalad cusub: [state]. Waxaad ku dari kartaa qoraalkaaga farriintan waxaadna isticmaali kartaa furaha luqadda si aad u sameysato tafaasiil luqadeed."
PLG_WORKFLOW_NOTIFICATION_ADDTEXT_LABEL="Fariin Dheeraad ah"
PLG_WORKFLOW_NOTIFICATION_ON_TRANSITION_MSG="Cinwaanka: %1$s. Kala guurka \"%2$s\" waxa uu fuliyay %3$s. Xaalad cusub: %4$s."
PLG_WORKFLOW_NOTIFICATION_ON_TRANSITION_SUBJECT="Xaaladda \"%s\" waa la beddelay"
PLG_WORKFLOW_NOTIFICATION_NO_RECEIVER="Ogeysiis ma jirto oo la diray maadaama aysan jirin isticmaale loo diro farriintan."
PLG_WORKFLOW_NOTIFICATION_NO_TITLE="Cinwaan aan la aqoon"
PLG_WORKFLOW_NOTIFICATION_RECEIVERS_LABEL="Isticmaalayaasha"
PLG_WORKFLOW_NOTIFICATION_SENDMAIL_LABEL="Soo dir Ogeysiis"
PLG_WORKFLOW_NOTIFICATION_SENT="Ogeysiisyo la diray"
PLG_WORKFLOW_NOTIFICATION_USERGROUP_DESC="Isticmaalayaasha kooxda isticmaalka waxa ay helaan ogeysiis haddii kala guurkani uu dhacay."
PLG_WORKFLOW_NOTIFICATION_USERGROUP_LABEL="Kooxaha Isticmaalaha"
PLG_WORKFLOW_NOTIFICATION_XML_DESCRIPTION="Dir ogeysiis haddii kala-gudub la fuliyey hawlgal."

