; Joomla! Project
; (C) 2020 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_USER_TOKEN="Isticmaale - Joomla API Token"
PLG_USER_TOKEN_ALLOWEDUSERGROUPS_DESC="Kooxaha Isticmaalaha Joomla ee la oggol yahay inay isticmaalaan Joomla Tokens si ay uga galaan codsiga Joomla API. Sidoo kale waxay xakameysaa kooxaha isticmaala ee arka isdhexgalka maareynta Joomla Token ee profile-kooda isticmaale. Default: Kooxda Isticmaalayaasha Gudaha ee Joomla (User Group ID 8)."
PLG_USER_TOKEN_ALLOWEDUSERGROUPS_LABEL="Kooxaha Isticmaalaha La Ogol yahay"
PLG_USER_TOKEN_XML_DESCRIPTION="Waxay ogolaaneysaa maareynta calaamadaha amniga ee loo isticmaalo xaqiijinta codsiga Joomla API (gelitaanka fog ee boggaaga). Calaamadahan waa kuwo si addin ah u gaar ah. Waxaad arki kartaa calaamaddaada laakiin waxaad kaliya joojin kartaa ama dib u dejiyaa calaamadaha isticmaaleyaasha kale."

