; Joomla! Project
; (C) 2007 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_CACHE_FIELD_BROWSERCACHE_LABEL="Isticmaal Caching Browser"
PLG_CACHE_FIELD_EXCLUDE_DESC="Cadee URL-yada aad rabto in laga dhaafo caching, mid kasta oo saf gaar ah. Waxyaabaha caadiga ah waa la taageerayaa, tusaale ahaan, <br><strong>about\-[a-z]+</strong> - waxay ka dhaafi doontaa dhammaan URL-yada leh 'about-', tusaale ahaan 'about-us', 'about-me', 'about-joomla' iwm.<br><strong>/component/users/</strong> - waxay ka dhaafi doontaa dhammaan URL-yada leh /component/users/.<br><strong>com_users</strong> - waxay ka dhaafi doontaa dhammaan bogagga qaybta Users."
PLG_CACHE_FIELD_EXCLUDE_LABEL="Ka dhaaf URL-yada"
PLG_CACHE_FIELD_EXCLUDE_MENU_ITEMS_LABEL="Ka dhaaf Shayga Menu-ga"
PLG_CACHE_XML_DESCRIPTION="Waxay bixisaa bog caching. Tani waxay ku haboon tahay goobaha leh mowduuc joogto ah ama mawduuc aan si joogto ah isbeddelin."
PLG_SYSTEM_CACHE="Nidaam - Bog Caching"

