; Joomla! Project
; (C) 2015 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_STATS="Nidaamka - Tirakoobyada Joomla!"
PLG_SYSTEM_STATS_BTN_NEVER_SEND="Maya"
PLG_SYSTEM_STATS_BTN_SEND_ALWAYS="Haa, waxaan caawin doonaa Joomla!"
PLG_SYSTEM_STATS_BTN_SEND_NOW="Hal mar"
PLG_SYSTEM_STATS_INTERVAL_LABEL="Kala-duwanaansho (saacado)"
PLG_SYSTEM_STATS_LABEL_CMS_VERSION="Nooca CMS"
PLG_SYSTEM_STATS_LABEL_DB_TYPE="Nooca DB"
PLG_SYSTEM_STATS_LABEL_DB_VERSION="Nooca DB"
PLG_SYSTEM_STATS_LABEL_MESSAGE_TITLE="Naga caawi inaan Joomla! ka fiican!"
PLG_SYSTEM_STATS_LABEL_PHP_VERSION="Nooca PHP"
PLG_SYSTEM_STATS_LABEL_SERVER_OS="OS Server"
PLG_SYSTEM_STATS_LABEL_UNIQUE_ID="Aqoonsi Gaar ah"
PLG_SYSTEM_STATS_MODE_LABEL="Hab"
PLG_SYSTEM_STATS_MODE_OPTION_ALWAYS_SEND="Mar walba dir"
PLG_SYSTEM_STATS_MODE_OPTION_NEVER_SEND="Ha waligaa dirin"
PLG_SYSTEM_STATS_MODE_OPTION_ON_DEMAND="Kala hadal mar kale"
PLG_SYSTEM_STATS_MSG_ALLOW_SENDING_DATA="Fur Tirakoobka Joomla?"
PLG_SYSTEM_STATS_MSG_JOOMLA_WANTS_TO_SEND_DATA="Waxaan dooneynaa inaan kordhinno iswaafajinta software-ka Joomla! ee la isticmaalayaasha goos goosha server-ka, sidaas darteed waxaan u baahanahay xog aan la aqoon oo ka socota degelkaaga si aan u fahanno si fiican saldhigga rakibida iyo bey'adaha isticmaale ee ugu dambeeya. Dhammaan xog waa la qarsoonaa oo keliya waxaa loo dirsadaa server dhexe oo ay kantaroolaan Joomla! Waad beddeli kartaa dejimahaaga dambe markaad ku jirto Plugins &rarr; Nidaam - Tirakoobyada Joomla!"
PLG_SYSTEM_STATS_MSG_WHAT_DATA_WILL_BE_SENT="Waa la qariyay dhammaan xogta mana la aqoonsan karo. Halkan dooro si aad u eegto."
PLG_SYSTEM_STATS_RESET_UNIQUE_ID="Dib u deji Aqoonsiga Gaar ah"
PLG_SYSTEM_STATS_SETTING="Dejin"
PLG_SYSTEM_STATS_STATISTICS="Tirakoob"
PLG_SYSTEM_STATS_UNIQUE_ID_LABEL="Aqoonsi Gaar ah"
PLG_SYSTEM_STATS_VALUE="Qiime"
PLG_SYSTEM_STATS_XML_DESCRIPTION="Plugin Nidaam oo diriya tirakoobka deegaanka server la kantaroolo mashaariicda Joomla! si loogu falanqeeyo tirakoob. Tirakoobyada la diray waxaa ka mid ah nooca PHP, nooca CMS, Nooca Database, Nooca Database iyo Nooca Server."

