; Joomla! Project
; (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FIELDS_RADIO="Goobaha - Raadio"
PLG_FIELDS_RADIO_LABEL="Raadio (%s)"
PLG_FIELDS_RADIO_PARAMS_FORM_LAYOUT_BUTTONS="Badhamada"
PLG_FIELDS_RADIO_PARAMS_FORM_LAYOUT_SWITCHER="Beddelaha"
PLG_FIELDS_RADIO_PARAMS_OPTIONS_LABEL="Qiimaha Raadiyaha"
PLG_FIELDS_RADIO_PARAMS_OPTIONS_NAME_LABEL="Qoraal"
PLG_FIELDS_RADIO_PARAMS_OPTIONS_VALUE_LABEL="Qiimaha"
PLG_FIELDS_RADIO_XML_DESCRIPTION="Plugin-kan wuxuu kuu ogolaanayaa inaad abuurto meelaha cusub ee nooca 'raadiyaha' ku jira wax kasta oo kordhin ah halkaas oo goobaha gaarka ah la taageerayo."

