; Joomla! Project
; (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FIELDS_TEXTAREA="Goobaha - Aagga Qoraalka"
PLG_FIELDS_TEXTAREA_XML_DESCRIPTION="Qoraalkan wuxuu kuu ogolaanayaa inaad abuurto goobo cusub oo nooca 'aagga qoraalka' meel kasta oo dheeri ah oo goobaha la beddeli karo lagu taageero."

