; Joomla! Project
; (C) 2007 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_AUTHENTICATION_JOOMLA="Ansaxin - Joomla"
PLG_AUTHENTICATION_JOOMLA_XML_DESCRIPTION="<p>Waxay maamushaa ansaxinta isticmaale ee caadiga ah ee Joomla.</p><p><strong>Digniin! Waa inaad awood siisaa ugu yaraan mid ka mid ah hab-socodsiinta ansaxinta ama waxaad waayi doontaa dhammaan helitaanka goobtaada.</strong></p>"

