; Joomla! Project
; (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FIELDS_MEDIA="Goobaha - Warbaahinta"
PLG_FIELDS_MEDIA_LABEL="Warbaahinta (%s)"
PLG_FIELDS_MEDIA_PARAMS_DIRECTORY_LABEL="Gal"
PLG_FIELDS_MEDIA_PARAMS_IMAGE_CLASS_LABEL="Fasalka Sawirka"
PLG_FIELDS_MEDIA_PARAMS_PREVIEW_INLINE="Khadka"
PLG_FIELDS_MEDIA_PARAMS_PREVIEW_LABEL="Hordhac"
PLG_FIELDS_MEDIA_XML_DESCRIPTION="Kordhiyayahaan waxa uu kuu ogolaanayaa inaad abuurtid meel cusub oo nooca 'warbaahinta' ah, meel walba oo lagu taageero goobaha loo adeegsado."

