; Joomla! Project
; (C) 2019 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_SKIPTO="Nidaam - Ka booday Navigation"
PLG_SYSTEM_SKIPTO_ACCESS_KEY="Furaha gelitaanka waa $key"
PLG_SYSTEM_SKIPTO_HEADING="Guudmar Bogga"
PLG_SYSTEM_SKIPTO_HEADING_LEVEL="Heerka cinwaanka"
PLG_SYSTEM_SKIPTO_HEADING_MOFN=" ($m ee $n)"
PLG_SYSTEM_SKIPTO_HEADING_NONE="Ma jiraan cinwaano loo boodo"
PLG_SYSTEM_SKIPTO_LANDMARK_ASIDE="Dhinac"
PLG_SYSTEM_SKIPTO_LANDMARK_FOOTER="Gunaanad"
PLG_SYSTEM_SKIPTO_LANDMARK_FORM="Foom"
PLG_SYSTEM_SKIPTO_LANDMARK_HEADER="Ciwaan"
PLG_SYSTEM_SKIPTO_LANDMARK="Astaamo"
PLG_SYSTEM_SKIPTO_LANDMARK_MAIN="Muuqaalka ugu muhiimsan"
PLG_SYSTEM_SKIPTO_LANDMARK_NAV="Hagaaji"
PLG_SYSTEM_SKIPTO_LANDMARK_NONE="Ma jiraan astaamo loo boodo"
PLG_SYSTEM_SKIPTO_LANDMARK_REGION="Gobol"
PLG_SYSTEM_SKIPTO_LANDMARK_SEARCH="Raadi"
PLG_SYSTEM_SKIPTO_MENU="Astaamada iyo Guudmar Bogga"
PLG_SYSTEM_SKIPTO_SECTION="Qaybta Goobta"
PLG_SYSTEM_SKIPTO_SECTION_ADMIN="Maamulka (Dhabarka)"
PLG_SYSTEM_SKIPTO_SECTION_BOTH="Labada"
PLG_SYSTEM_SKIPTO_SECTION_SITE="Goobta (Hore)"
PLG_SYSTEM_SKIPTO_TITLE="Navigation Keyboard"
PLG_SYSTEM_SKIPTO_XML_DESCRIPTION="Plugin-ku waxa uu abuurayaa menu hoos u dhac ah oo ka kooban xidhiidhada meelaha muhiimka ah ee bogga Internetka la siiyay. Tani waxay fududaynaysaa isticmaalayaasha keyboard-ka iyo akhristaha shaashaddu inay si degdeg ah ugu boodaan goobta la rabo iyaga oo dooranaya liiska doorashooyinka."

