; Joomla! Project
; (C) 2010 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_CONTENT_JOOMLA="Mawduuc - Joomla"  
PLG_CONTENT_JOOMLA_XML_DESCRIPTION="Plugin-kani waxa uu maareeyaa categoriyaasha kordhinta aasaasiga ah; waxayna dirtaa email marka maqaal cusub lagu soo gudbiyo shaashadda hore."

