; Joomla! Project
; (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_GUIDEDTOURS="Nidaamka - Plugin-ka Dalxiisyada Hagaya"
PLG_SYSTEM_GUIDEDTOURS_BACK="Dib"
PLG_SYSTEM_GUIDEDTOURS_COMPLETE="Dhameystiran"
PLG_SYSTEM_GUIDEDTOURS_COULD_NOT_LOAD_THE_TOUR="Ma bilaabi karin dalxiiska. Aqoonsiga saxda ah lama bixin."
PLG_SYSTEM_GUIDEDTOURS_DESCRIPTION="Plugin-ka Dalxiiska Hagaya ee Nidaamka"
PLG_SYSTEM_GUIDEDTOURS_HIDE_FOREVER="Qari Mar Walba"
PLG_SYSTEM_GUIDEDTOURS_NEXT="Soo Socod"
PLG_SYSTEM_GUIDEDTOURS_START="Bilow"
PLG_SYSTEM_GUIDEDTOURS_STEP_NUMBER_OF="Tallaabo {number} ka mid ah {total}"
PLG_SYSTEM_GUIDEDTOURS_TOUR_ERROR="Hooy maya! Waxay u egtahay in dalxiiskiinna uu raadka ka lumay. Dalxiisku wuu baxay mana sii socon karo."
PLG_SYSTEM_GUIDEDTOURS_TOUR_ERROR_RESPONSE="Wax khalad ah ayaa dhacay markii lala kaydinayey macluumaadka xaaladda dalxiiska! Khaladka jawaabta."
PLG_SYSTEM_GUIDEDTOURS_TOUR_INVALID_RESPONSE="Wax khalad ah ayaa dhacay markii lala kaydinayey macluumaadka xaaladda dalxiiska! Jawaabtu waa khaldan tahay."

