; Joomla! Project
; (C) 2010 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_CONTACTCREATOR_ERR_FAILED_CREATING_CONTACT="Abuuritaanka isgaarsiinta otomaatigga ah waa ku guuldareysatay. Fadlan la xidhiidh maamulaha goobta."
PLG_CONTACTCREATOR_ERR_NO_CATEGORY="Abuuritaanka otomaatigga ah ee xidhiidhka ayaa fashilmay sababtoo ah qaybta xiriirka lama dejin!"
PLG_CONTACTCREATOR_FIELD_AUTOMATIC_WEBPAGE_DESC="Qaabaysan oo si otomaatig ah loogu abuuro bogga internet-ka ee xidhiidhka. [name] waxaa lagu bedelay magaca, [username] waxaa lagu bedelay magaca isticmaale, [userid] waxaa lagu bedelay aqoonsiga isticmaale, iyo [email] waxaa lagu bedelay email-ka."
PLG_CONTACTCREATOR_FIELD_AUTOMATIC_WEBPAGE_LABEL="Bogga Otomaatigga ah"
PLG_CONTACTCREATOR_FIELD_AUTOPUBLISH_LABEL="Si otomaatig ah u Daabac Xidhiidhka"
PLG_CONTACTCREATOR_XML_DESCRIPTION="Plugin-ka si otomaatig ah u abuuro xogta xiriirka isticmaalayaasha cusub."
PLG_USER_CONTACTCREATOR="Isticmaale - Abuuraha Xidhiidhka"

