; Joomla! Project
; (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_MEDIA-ACTION_ROTATE="Fal Media - Rog"
PLG_MEDIA-ACTION_ROTATE_LABEL="Rog"
PLG_MEDIA-ACTION_ROTATE_PARAM_ANGLE="Xagal"
PLG_MEDIA-ACTION_ROTATE_PARAM_BUTTONS="Badhamada Xagasha"
PLG_MEDIA-ACTION_ROTATE_QUALITY="Tayada"
PLG_MEDIA-ACTION_ROTATE_XML_DESCRIPTION="Waxay ku dareysaa shaqeynta rogida sawirada."

