; Joomla! Project
; (C) 2018 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_ACTIONLOGS="Nidaamka - Diiwaangelinta Ficillada Isticmaalaha"
PLG_SYSTEM_ACTIONLOGS_EXTENSIONS_NOTIFICATIONS="Dhacdooyinka Emailka"
PLG_SYSTEM_ACTIONLOGS_INFO_DESC="Kaabidda Diiwaanka Ficillada - Joomla waa naafo"
PLG_SYSTEM_ACTIONLOGS_INFO_LABEL="Macluumaadka"
PLG_SYSTEM_ACTIONLOGS_JOOMLA_ACTIONLOG_DISABLED="Diiwaanka Ficillada - Joomla"
PLG_SYSTEM_ACTIONLOGS_JOOMLA_ACTIONLOG_DISABLED_REDIRECT="Kaabidda %s waa naafo."
PLG_SYSTEM_ACTIONLOGS_NOTIFICATIONS="Ogeysiisyada Emailka"
PLG_SYSTEM_ACTIONLOGS_OPTIONS="Ikhtiyaarrada Diiwaangelinta Ficillada Isticmaalaha"
PLG_SYSTEM_ACTIONLOGS_XML_DESCRIPTION="Waxay duubtaa ficillada isticmaalayaasha ee goobta si ay dib loogu eego haddii loo baahdo."
; Common content type log messages
PLG_SYSTEM_ACTIONLOGS_CONTENT_ADDED="Isticmaale <a href=\"{accountlink}\">{username}</a> ayaa ku daray {type} cusub <a href=\"{itemlink}\">{title}</a>"
PLG_SYSTEM_ACTIONLOGS_CONTENT_ARCHIVED="Isticmaale <a href=\"{accountlink}\">{username}</a> ayaa kaydiyay {type} <a href=\"{itemlink}\">{title}</a>"
PLG_SYSTEM_ACTIONLOGS_CONTENT_DELETED="Isticmaale <a href=\"{accountlink}\">{username}</a> ayaa tirtiray {type} {title}"
PLG_SYSTEM_ACTIONLOGS_CONTENT_PUBLISHED="Isticmaale <a href=\"{accountlink}\">{username}</a> ayaa daabacay {type} <a href=\"{itemlink}\">{title}</a>"
PLG_SYSTEM_ACTIONLOGS_CONTENT_TRASHED="Isticmaale <a href=\"{accountlink}\">{username}</a> ayaa qashinka ku riday {type} <a href=\"{itemlink}\">{title}</a>"
PLG_SYSTEM_ACTIONLOGS_CONTENT_UNPUBLISHED="Isticmaale <a href=\"{accountlink}\">{username}</a> ayaa daabacaadda ka saaray {type} <a href=\"{itemlink}\">{title}</a>"
PLG_SYSTEM_ACTIONLOGS_CONTENT_UPDATED="Isticmaale <a href=\"{accountlink}\">{username}</a> ayaa cusbooneysiiyay {type} <a href=\"{itemlink}\">{title}</a>"

; All the following strings are deprecated and will be removed with 6.0
PLG_SYSTEM_ACTIONLOGS_LOG_DELETE_PERIOD="Maalmood si loo tirtiro diiwaanka kadib"
PLG_SYSTEM_ACTIONLOGS_LOG_DELETE_PERIOD_DESC="Geli 0 haddii aadan rabin inaad tirtirto diiwaanka."

