; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_CONTENT_LOADMODULE="Mawduuca - Soo dejiso Modules"
PLG_LOADMODULE_FIELD_STYLE_LABEL="Qaabka"
PLG_LOADMODULE_FIELD_VALUE_DIVS="Kushubeysan Divs"
PLG_LOADMODULE_FIELD_VALUE_RAW="Ma jiro kushubin (soosaar aan caddayn)"
PLG_LOADMODULE_FIELD_VALUE_TABLE="Kushubeysan jadwal (saf)"
PLG_LOADMODULE_XML_DESCRIPTION="Dhex dhexaadka ku jira, plugin-kan wuxuu ku rari karaa Module ID-ga, Qoritaanka: {loadmoduleid 1} ama Module boos, Qoritaanka: {loadposition user1} ama Module magaca, Qoritaanka: {loadmodule mod_login}. Ikhtiyaar ahaan waxaa lagu xusin karaa qaabka module iyo in loadmodule module –ka gaarka ah lagu magacaabo by ciwaan, Qoritaanka: {loadmodule mod_login,titleka module,qaabka}."
; Deprecated, will be removed with 6.0
PLG_LOADMODULE_FIELD_VALUE_HORIZONTAL="Ku duuban jadwal (horizontal)"
PLG_LOADMODULE_FIELD_VALUE_MULTIPLEDIVS="Ku duuban Divs badan"

