; Joomla! Project
; (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_TASK_REQUESTS="Hawl - Codsiyada"
PLG_TASK_REQUESTS_BEARER="Wakiil"
PLG_TASK_REQUESTS_JOOMLA_TOKEN="X-Joomla-Token"
PLG_TASK_REQUESTS_LABEL_AUTH="Oggolaansho"
PLG_TASK_REQUESTS_LABEL_AUTH_HEADER="Cinwanka Oggolaanshaha"
PLG_TASK_REQUESTS_LABEL_AUTH_KEY="Keyga Oggolaanshaha"
PLG_TASK_REQUESTS_LABEL_REQUEST_TIMEOUT="Waqtiga Codsiga Dhamaaday"
PLG_TASK_REQUESTS_LABEL_REQUEST_URL="Codsiga URL"
PLG_TASK_REQUESTS_TASK_GET_REQUEST_DESC="Samee codsiyo GET ah server-ka. Waxay taageertaa waqtiga la habeeyay iyo cinwaanada oggolaanshaha."
PLG_TASK_REQUESTS_TASK_GET_REQUEST_LOG_RESPONSE="Koodhka jawaabta codsiga wuxuu ahaa: %1$d"
PLG_TASK_REQUESTS_TASK_GET_REQUEST_LOG_TIMEOUT="Codsiga GET wuu fashilmay ama wuu waqtiga dhashay."
PLG_TASK_REQUESTS_TASK_GET_REQUEST_LOG_UNWRITEABLE_OUTPUT="Lama qori karo faylka waxsoosaarka!"
PLG_TASK_REQUESTS_TASK_GET_REQUEST_ROUTINE_END_LOG_MESSAGE="Koodhka soo noqoshada GET waa: %1$d. Waqtiga Habaynta: %2$.2f ilbiriqsi"
PLG_TASK_REQUESTS_TASK_GET_REQUEST_TITLE="Codsiga GET"
PLG_TASK_REQUESTS_XML_DESCRIPTION="Barnaamijka shaqada si loo sameeyo codsiyada GET ee server-ka."

