; Joomla! Project
; (C) 2005 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_EDITORS_TINYMCE="Tafatiraha - TinyMCE"
PLG_TINY_BUILDER="Abuuraha Qaabka TinyMCE"
PLG_TINY_BUTTON_TOGGLE_EDITOR="Toggle Tafatiraha"
PLG_TINY_CONFIG_TEXTFILTER_ACL_LABEL="Isticmaalaha Joomla Filitarka Qoraalka"
PLG_TINY_CORE_BUTTONS="CMS Mawduucyada"
PLG_TINY_DND_ADDITIONALDATA="Xog Dheeraad ah"
PLG_TINY_DND_ALTTEXT="Sharaxa Sawirka (Qoraalka Alt)"
PLG_TINY_DND_EMPTY_ALT="Ma jiro Sharaxaad"
PLG_TINY_DND_FILE_EXISTS_ERROR="Faylka \"%s\" horey ayuu u jiray."
PLG_TINY_DND_LAZYLOADED="Sawirka waxaa loo rogi doonaa kuwa gaabin ah"
PLG_TINY_ERR_CUSTOMCSSFILENOTPRESENT="Magaca faylka %s waxaa lagu geliyay fieldka TinyMCE Custom CSS. Faylkan lama heli karo galka habka caadiga ah. Wax styles lama heli karo."
PLG_TINY_ERR_EDITORCSSFILENOTPRESENT="Lama heli karo faylka 'editor.css' ee habka ama templates/system folder. Wax styles ah lama heli karo."
PLG_TINY_ERR_UNSUPPORTEDBROWSER="Jiido oo dhig sawirka la geliyo ma aha mid la heli karo biraawkarrkaaga. Fadlan ka fikir isticmaale biraawkarka si buuxda HTML5 is waafaqsan."
PLG_TINY_FIELD_ADVIMAGE_LABEL="Sawirka Horumarsan"
PLG_TINY_FIELD_ADVLIST_LABEL="Liiska Horumarsan"
PLG_TINY_FIELD_CONTENTCODE_LABEL="Lambarka Luqadda"
PLG_TINY_FIELD_CONTENTLANGS_DESC="Luqadda qeybaha waxay kuu ogolaaneysaa inaad calaamadaysid erey ama jumlad luuqad kala duwan ah. Si aad ugu abuurto liiska luuqadaha waa inaad galisaa magaca luuqadda iyo lambarka luuqadda. Koodhkani wuxuu u dhaqmi karaa luqad keliya tusaale: de ama wuxuu ku jiri karaa degaan tusaale de-AT."
PLG_TINY_FIELD_CONTENTLANGS_LABEL="Luqadda Qeybaha"
PLG_TINY_FIELD_CONTENTLANGUAGE_LABEL="Magaca Luqadda"
PLG_TINY_FIELD_CONTEXTMENU_LABEL="Menu-ka Macnaha"
PLG_TINY_FIELD_CSS_DESC="Marka la eego caadiga Plugin wuxuu raadiyaa faylka editor.css. Haddii aysan helin mid ku yaal habka default CSS gal, waxay soo rogtaa faylka editor.css ee habka nidaamka."
PLG_TINY_FIELD_CSS_LABEL="Noocyada Template-ka ee CSS"
PLG_TINY_FIELD_CUSTOMBUTTON_LABEL="Badhamada La Xakameeyey"
PLG_TINY_FIELD_CUSTOMPLUGIN_LABEL="Plugin-ka La Xakameeyey"
PLG_TINY_FIELD_CUSTOM_CONTENT_TEMPLATE_PATH_DESC="Gal lagu magacaabo \"tinymce\" ee habka qaabeysan ee boggaaga."
PLG_TINY_FIELD_CUSTOM_CONTENT_TEMPLATE_PATH_LABEL="Jid Tusaale Nuxur"
PLG_TINY_FIELD_CUSTOM_CSS_DESC="Faylka CSS optional oo beddelaya faylka editor.css ee caadiga ah. Geli magaca faylka si loo tilmaamo fayl ku jira galka CSS ee template-ka caadiga ah (tusaale ahaan, media/templates/site/cassiopeia/css/). Ama geli bakhaar URL buuxa ee faylka CSS gaar ah. Haddii aad geliso qiime qaybtaan, faylkaan ayaa la isticmaali doonaa halkii faylka editor.css."
PLG_TINY_FIELD_CUSTOM_CSS_LABEL="Fasallada CSS Gaar ah"
PLG_TINY_FIELD_CUSTOM_PATH_LABEL="Jidka Sawirrada"
PLG_TINY_FIELD_DIRECTION_LABEL="Jihada Qoraalka"
PLG_TINY_FIELD_DRAG_DROP_LABEL="Jiido oo Ka Daadi Sawirada"
PLG_TINY_FIELD_ELEMENTS_LABEL="Uncho Uqalma oo Kordhay"
PLG_TINY_FIELD_ENCODING_LABEL="Koodhka Untiy"
PLG_TINY_FIELD_EXTERNALPLUGINS_DESC="Siin lammaane ka kooban Magaca Plugin iyo jidka ilaha failka JavaScript ee Plugin. Jidka waa inuu ku xirnaado xididka goobta, ama URL sax ah."
PLG_TINY_FIELD_EXTERNALPLUGINS_LABEL="URL-yada Plugin-ka Dibadda"
PLG_TINY_FIELD_EXTERNALPLUGINS_NAME_LABEL="Magaca Plugin"
PLG_TINY_FIELD_EXTERNALPLUGINS_PATH_LABEL="Jid"
PLG_TINY_FIELD_HTMLHEIGHT_LABEL="Dhererka HTML"
PLG_TINY_FIELD_HTMLWIDTH_LABEL="Ballaca HTML"
PLG_TINY_FIELD_LABEL_ADVANCEDPARAMS="Horumarsan"
PLG_TINY_FIELD_LANGCODE_LABEL="Koodhka Luuqadda"
PLG_TINY_FIELD_LANGSELECT_LABEL="Xulashada Luuqada Tooska ah"
PLG_TINY_FIELD_LINK_CLASSES_LIST_DESC="Ku dar fasallo caadi ah liiska dhanka fasalka ee gudaha wadahadalka xiriirka abuuritaanka."
PLG_TINY_FIELD_LINK_CLASSES_LIST_LABEL="Liiska Fasallada Xiriirka"
PLG_TINY_FIELD_LINK_CLASS_LIST_LABEL="Liiska Fasalka"
PLG_TINY_FIELD_LINK_CLASS_NAME_LABEL="Magaca"
PLG_TINY_FIELD_LINK_CLASS_NONE="Midna"
PLG_TINY_FIELD_NEWLINES_LABEL="Khadooyin Cusub"
PLG_TINY_FIELD_NUMBER_OF_SETS_LABEL="Tirooyinka Setyada"
PLG_TINY_FIELD_PASTE_AS_TEXT_LABEL="Ku Dhaji Sida Qoraal"
PLG_TINY_FIELD_PATH_LABEL="Jidka Qalabka"
PLG_TINY_FIELD_PROHIBITED_LABEL="Qalab Diiddan"
PLG_TINY_FIELD_RESIZE_HORIZONTAL_LABEL="Balaadhinta Jiifta"
PLG_TINY_FIELD_RESIZING_LABEL="Balaadhinta"
PLG_TINY_FIELD_SANDBOX_IFRAMES_DESC="Tani waa qaab amni kaas oo xaddidaya waxa iframe sameyn karo iyadoo loo adeegsanayo sanduuq kaas oo aan xannaanadayn karno qaab ah oo mid walba ah iframe. Waxaa lagula talinayaa in la hawlgeliyo qaabkan sababo la xiriira arrimaha ammaanka. Kaliya dami haddii iframe aan la xajin karin oo aad kapsan tahay in waxyaabaha ku jira iframed ammaan yihiin."
PLG_TINY_FIELD_SANDBOX_IFRAMES_LABEL="Sanduuqyada Iframes"
PLG_TINY_FIELD_SETACCESS_LABEL="U Qoondee Qabkan"
PLG_TINY_FIELD_SKIN_ADMIN_DARK_LABEL="Maamule Maqaarka (Hab Madow)"
PLG_TINY_FIELD_SKIN_ADMIN_LABEL="Maamule Maqaarka"
PLG_TINY_FIELD_SKIN_DARK_LABEL="Bog Maqaarka (Hab Madow)"
PLG_TINY_FIELD_SKIN_INFO_DESC="Nuqul ku rid maqaarkaaga cusub: /media/vendor/tinymce/skins/ui."
PLG_TINY_FIELD_SKIN_INFO_LABEL="Maqaarka la habeeyay tag: <a href=\"https://skin.tiny.cloud/t5/\" target=\"_blank\" rel=\"noopener noreferrer\">Abuuraha Maqaarka</a>"
PLG_TINY_FIELD_SKIN_LABEL="Bog Maqaarka"
PLG_TINY_FIELD_SOURCECODE_LABEL="Muujinta Koodhka Isugeynta"
PLG_TINY_FIELD_TEXTPATTERN_DESC="Adeegso hab qoraal si u habeyso nuxurka isku xirka, liisaska, iyo habab kale."
PLG_TINY_FIELD_TEXTPATTERN_LABEL="Hab qoraal"
PLG_TINY_FIELD_TOOLBAR_MODE_LABEL="Habka Toolbar"
PLG_TINY_FIELD_URLS_LABEL="URL-yada"
PLG_TINY_FIELD_VALIDELEMENTS_DESC="Waxay qeexdaa qaar ka mid ah waxyaabaha ku jiri doona qoraalka la saxayo marka tifaftire kaydso (xejinta xeerka caadiga ah ee dookhan waa isku dhafka buuxa ee qeexitaannada HTML5 iyo HTML4)."
PLG_TINY_FIELD_VALIDELEMENTS_LABEL="Qalab Saxan"
PLG_TINY_FIELD_VALUE_ABSOLUTE="Dhab Ah"
PLG_TINY_FIELD_VALUE_ADVANCED="Sare"
PLG_TINY_FIELD_VALUE_BR="Qalabyada BR"
PLG_TINY_FIELD_VALUE_EXTENDED="Ballaadhsan"
PLG_TINY_FIELD_VALUE_FLOATING="Si Uur Ka Joogan"


PLG_TINY_FIELD_VALUE_LTR="Bidix ilaa midig"
PLG_TINY_FIELD_VALUE_NAMED="loo magacaabay"
PLG_TINY_FIELD_VALUE_NUMERIC="lambar"
PLG_TINY_FIELD_VALUE_P="Qodobbada P"
PLG_TINY_FIELD_VALUE_RAW="saafi"
PLG_TINY_FIELD_VALUE_RELATIVE="Deris"
PLG_TINY_FIELD_VALUE_RTL="Midig ilaa bidix"
PLG_TINY_FIELD_VALUE_SCROLLING="Is rogrogid"
PLG_TINY_FIELD_VALUE_SIMPLE="Sahlan"
PLG_TINY_FIELD_VALUE_SLIDING="Dumaas"
PLG_TINY_FIELD_VALUE_WRAP="Duub"
PLG_TINY_FIELD_WORDCOUNT_LABEL="Tirada Ereyada"
PLG_TINY_LEGACY_WARNING="<p><a href=\"%s\">TinyMCE Editor Plugin</a> waa la cusboonaysiiyay. Hadda waxay isticmaashaa qaabeyntaadii hore. Markaad sixido, si aad u cusbooneysiiso waxaad ku magacaabi kartaa oo aad habayn kartaa qaababka kala duwan ee kooxaha isticmaala gaar ah.</p><p>Digniin: markaad tafatirishay plugin-ka, waxaad lumin doontaa dhammaan qaabeyntaadii hore!</p>"
PLG_TINY_MENU_CONTAINER="Weel"
PLG_TINY_SET_PRESET_BUTTON_ADVANCED="Isticmaal preeset-ka sarreeya"
PLG_TINY_SET_PRESET_BUTTON_MEDIUM="Isticmaal preeset dhexdhexaad ah"
PLG_TINY_SET_PRESET_BUTTON_SIMPLE="Isticmaal preeset sahlan"
PLG_TINY_SET_SOURCE_PANEL_DESCRIPTION="<strong>Dhammaan menus-yada iyo badhamada la heli karo.</strong>"
PLG_TINY_SET_TARGET_PANEL_DESCRIPTION="Isticmaal guddiga hoose si aad u habayso (jiido oo dhig) TinyMCE mid kasta oo ka mid ah dhammaan."
PLG_TINY_SET_TARGET_PANEL_TITLE="Dhammaan TinyMCE"
PLG_TINY_SET_TITLE="Go'aan %d"
PLG_TINY_TOOLBAR_BUTTON_FONTSELECT="Xulashada Font"
PLG_TINY_TOOLBAR_BUTTON_FONTSIZESELECT="Xulashada Xajmiga Font"
PLG_TINY_TOOLBAR_BUTTON_FORMATSELECT="Xulashada Qaabka"
PLG_TINY_TOOLBAR_BUTTON_SEPARATOR="Alaad"
PLG_TINY_TOOLBAR_BUTTON_STYLESELECT="Xullo Qaabka"
PLG_TINY_XML_DESCRIPTION="TinyMCE waa tifatiraha webka ee madaxbannaan ee JavaScript HTML ee WYSIWYG. Isticmaalka <strong>dhigyada</strong> waxaad u habeyn kartaa una habeyn kartaa tifaftiraha koox kasta oo isticmaale."

