; Joomla! Project
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_QUICKICON_AUTOUPDATE="Asta Degdegga ah - Joomla! Ogeysiiska Xaaladda Cusbooneysiinta Toos ah"
PLG_QUICKICON_AUTOUPDATE_CHECKING="Hubinta Cusbooneysiinta Tooska ah &hellip;"
PLG_QUICKICON_AUTOUPDATE_DISABLED="Cusbooneysiinta Tooska ah waa daman tahay."
PLG_QUICKICON_AUTOUPDATE_ERROR="Xaaladda Cusbooneysiinta Tooska ah lama yaqaan &hellip;"
PLG_QUICKICON_AUTOUPDATE_GROUP_DESC="Kooxda jaangooyaha (qiimahan waxaa lala barbardhigaa qiimaha kooxa ee lagu isticmaalo moogdulska <strong>Asta Degdegga</strong> si loo durayo astaamaha)."
PLG_QUICKICON_AUTOUPDATE_GROUP_LABEL="Kooxda"
PLG_QUICKICON_AUTOUPDATE_OK="Cusbooneysiinta Tooska ah waa la karbiyay."
PLG_QUICKICON_AUTOUPDATE_OUTDATED="Xiriirka Cusbooneysiinta Tooska ah ayaa jabay."
PLG_QUICKICON_AUTOUPDATE_UNAVAILABLE="Cusbooneysiinta Tooska ah lama heli karo."
PLG_QUICKICON_AUTOUPDATE_XML_DESCRIPTION="Kormeerka xaaladda cusbooneysiinta tooska ah iyo waxa ku ogeysiinaya marka aad booqato bogga Dashboard-ka Guriga."

