; Joomla! Project
; (C) 2019 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_QUICKICON_DOWNLOADKEY="Asta dhakhso - Ogeysiis Qeybta Soo Dejinta Maqan"
PLG_QUICKICON_DOWNLOADKEY_GROUP_DESC="Kooxda plugin-kan (qiimaha tani waxaa lagu barbardhigaa qiimaha kooxda ee loo adeegsaday module-yada <strong>Asta dhakhso</strong> si loo geliyo astaamaha)."
PLG_QUICKICON_DOWNLOADKEY_GROUP_LABEL="Koox"
PLG_QUICKICON_DOWNLOADKEY_N_MISSING="%d Furayaasha Soo Dejinta ayaa maqan!"
PLG_QUICKICON_DOWNLOADKEY_N_MISSING_1="Waxaa maqan Furaha Soo Dejinta!"
PLG_QUICKICON_DOWNLOADKEY_OK="Furayaasha Soo Dejinta si sax ah ayaa loo geliyey"
PLG_QUICKICON_DOWNLOADKEY_XML_DESCRIPTION="Waxay hubisaa goobaha cusbooneysiinta ee kordhinta (soo degis lacag leh) ee aan laga helin macluumaadka Furaha Soo Dejinta khusaysan waxayna ku ogeysiineysaa markaad booqato bogga Dashboard-ka Guriga."

