; Joomla! Project
; (C) 2014 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_CONTENT_CONTACT="Mawduuc - Xiriir"
PLG_CONTENT_CONTACT_PARAM_ALIAS_DESCRIPTION="Ku xidh xogta dhabta ah ee isticmaale xitaa haddii magac been abuur ah lagu dejiyay xulashooyinka maqaalka."
PLG_CONTENT_CONTACT_PARAM_ALIAS_LABEL="Sidoo kale isku xidh magac been abuur ah"
PLG_CONTENT_CONTACT_PARAM_URL_DESCRIPTION="Waxaad ku xiriirin kartaa magaca qoraaga:<ul><li>Bogga xiriirka ee la xidhiidha.<li>Degel web oo lagu tilmaamay astaanta xiriirka la xidhiidha.<li>Email lagu tilmaamay astaanta xiriirka la xidhiidha.</ul>"
PLG_CONTENT_CONTACT_PARAM_URL_EMAIL="Email ka socda xiriirka"
PLG_CONTENT_CONTACT_PARAM_URL_LABEL="Dalbashada"
PLG_CONTENT_CONTACT_PARAM_URL_URL="Bogga gudaha ee xiriirka"
PLG_CONTENT_CONTACT_PARAM_URL_WEBPAGE="Degel web oo ka socda xiriirka"
PLG_CONTENT_CONTACT_XML_DESCRIPTION="Waxay bixisaa xiriir u dhexeeya qoraaga maadada iyo shayga xiriirka oo loo isticmaali karo Astaanta Qoraaga."

