; Joomla! Project
; (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FIELDS_USERGROUPLIST="Goobo - Liiska Kooxaha Isticmaalaha"
PLG_FIELDS_USERGROUPLIST_DEFAULT_VALUE_DESC="Liiska kooxaha isticmaalaha oo isticmaalaya farta koma."
PLG_FIELDS_USERGROUPLIST_DEFAULT_VALUE_LABEL="Kooxaha Isticmaalaha ee Damaanadqaadka"
PLG_FIELDS_USERGROUPLIST_LABEL="Kooxaha Isticmaalaha (%s)"
PLG_FIELDS_USERGROUPLIST_PARAMS_MULTIPLE_LABEL="Mid ka badan"
PLG_FIELDS_USERGROUPLIST_XML_DESCRIPTION="Fiiriwadani waxay kuu ogolaaneysaa inaad abuurto goobo cusub oo ah nooca 'liiska kooxaha isticmaalaha' meel walba oo maktabaddo gaar ahi ay taageersan yihiin."

