; Joomla! Project
; (C) 2018 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_ACTIONLOG_JOOMLA="Diiwaanka Ficilka - Joomla"
PLG_ACTIONLOG_JOOMLA_API="Isticmaale <a href='{accountlink}'>{username}</a> sameeyey {verb} ku saabsan {url}"
PLG_ACTIONLOG_JOOMLA_APPLICATION_ADMINISTRATOR="maamul"
PLG_ACTIONLOG_JOOMLA_APPLICATION_API="api"
PLG_ACTIONLOG_JOOMLA_APPLICATION_CLI="cli"
PLG_ACTIONLOG_JOOMLA_APPLICATION_SITE="bogga"
PLG_ACTIONLOG_JOOMLA_XML_DESCRIPTION="Diiwaangeli ficillada isticmaalayaasha ee bogga loogu talagalay dheeraadyada asalka ah ee Joomla si loo eego haddii loo baahdo."
; Content types title
PLG_ACTIONLOG_JOOMLA_TYPE_ACCESS_LEVEL="heerka gelitaanka"
PLG_ACTIONLOG_JOOMLA_TYPE_APPLICATION_CONFIG="Qaabeynta Guud"
PLG_ACTIONLOG_JOOMLA_TYPE_ARTICLE="maqaal"
PLG_ACTIONLOG_JOOMLA_TYPE_BANNER="calanka"
PLG_ACTIONLOG_JOOMLA_TYPE_BANNER_CLIENT="macaamiilka calanka"
PLG_ACTIONLOG_JOOMLA_TYPE_CATEGORY="qeybta"
PLG_ACTIONLOG_JOOMLA_TYPE_COMPONENT="qayb"
PLG_ACTIONLOG_JOOMLA_TYPE_COMPONENT_CONFIG="Qaabaynta Qayb"
PLG_ACTIONLOG_JOOMLA_TYPE_CONTACT="xiriir"
PLG_ACTIONLOG_JOOMLA_TYPE_FIELD="beer"
PLG_ACTIONLOG_JOOMLA_TYPE_FILE="file"
PLG_ACTIONLOG_JOOMLA_TYPE_LANGUAGE="luqadda"
PLG_ACTIONLOG_JOOMLA_TYPE_LIBRARY="maktabadda"
PLG_ACTIONLOG_JOOMLA_TYPE_LINK="isku xirta"
PLG_ACTIONLOG_JOOMLA_TYPE_LINK_REDIRECT="isku xirta dib u leexinta"
PLG_ACTIONLOG_JOOMLA_TYPE_MEDIA="warbaahinta"
PLG_ACTIONLOG_JOOMLA_TYPE_MENU="menu"
PLG_ACTIONLOG_JOOMLA_TYPE_MENU_ITEM="shayga menu"
PLG_ACTIONLOG_JOOMLA_TYPE_MODULE="module"
PLG_ACTIONLOG_JOOMLA_TYPE_NEWSFEED="quudinta wararka"
PLG_ACTIONLOG_JOOMLA_TYPE_PACKAGE="xirmo"
PLG_ACTIONLOG_JOOMLA_TYPE_PLUGIN="ku-dar"
PLG_ACTIONLOG_JOOMLA_TYPE_STYLE="qaabka maabka"
PLG_ACTIONLOG_JOOMLA_TYPE_TAG="sumad"
PLG_ACTIONLOG_JOOMLA_TYPE_TASK="Hawsha"
PLG_ACTIONLOG_JOOMLA_TYPE_TEMPLATE="gabar"
PLG_ACTIONLOG_JOOMLA_TYPE_USER="isticmaale"
PLG_ACTIONLOG_JOOMLA_TYPE_USER_GROUP="kooxda isticmaalaha"
PLG_ACTIONLOG_JOOMLA_TYPE_USER_NOTE="xusuus qor isticmaale"
; User actions
PLG_ACTIONLOG_JOOMLA_USER_BLOCK="Isticmaale <a href='{accountlink}'>{username}</a> wuxuu xannibay isticmaale <a href='{itemlink}'>{title}</a>"
PLG_ACTIONLOG_JOOMLA_USER_CACHE="Isticmaale <a href='{accountlink}'>{username}</a> ayaa tirtiray koox cache ah {group}"
PLG_ACTIONLOG_JOOMLA_USER_CHECKIN="Isticmaale <a href='{accountlink}'>{username}</a> ayaa sameeyay hubin bishii {table}"
PLG_ACTIONLOG_JOOMLA_USER_LOG="Isticmaale <a href='{accountlink}'>{username}</a> wuxuu ka saaray saf ama in ka badan xisaab xisaabeedka"
PLG_ACTIONLOG_JOOMLA_USER_LOGEXPORT="Isticmaale <a href='{accountlink}'>{username}</a> wuxuu dhoofiyey saf ama in ka badan xisaab xisaabeedka"
PLG_ACTIONLOG_JOOMLA_USER_LOGGED_IN="Isticmaale <a href='{accountlink}'>{username}</a> ayaa soo galay {app}"
PLG_ACTIONLOG_JOOMLA_USER_LOGGED_OUT="Isticmaale <a href='{accountlink}'>{username}</a> ayaa ka baxay {app}"
PLG_ACTIONLOG_JOOMLA_USER_LOGIN_FAILED="Isku day guuldarreystay ayaa lagu sameeyay in lagu soo galo sida <a href='{accountlink}'>{username}</a> {app}"
PLG_ACTIONLOG_JOOMLA_USER_REGISTERED="Isticmaale <a href='{accountlink}'>{username}</a> ayaa isdiiwaangeliyey xisaab"
PLG_ACTIONLOG_JOOMLA_USER_REGISTRATION_ACTIVATE="Isticmaale <a href='{accountlink}'>{username}</a> wuxuu howlgeliyey xisaabta"
PLG_ACTIONLOG_JOOMLA_USER_REMIND="Isticmaale <a href='{accountlink}'>{username}</a> ayaa codsaday xusuusin magiciisa isticmaale ee xisaabtooda"
PLG_ACTIONLOG_JOOMLA_USER_RESET_COMPLETE="Isticmaale <a href='{accountlink}'>{username}</a> wuxuu dhammaystiray dib u dejinta erayga sirta ee xisaabtooda"
PLG_ACTIONLOG_JOOMLA_USER_RESET_REQUEST="Isticmaale <a href='{accountlink}'>{username}</a> ayaa codsaday dib u dejinta erayga sirta ee xisaabtooda"
PLG_ACTIONLOG_JOOMLA_USER_UNBLOCK="Isticmaale <a href='{accountlink}'>{username}</a> wuxuu xannibaadda ka qaaday isticmaale <a href='{itemlink}'>{title}</a>"
PLG_ACTIONLOG_JOOMLA_USER_UPDATE="Isticmaale <a href='{accountlink}'>{username}</a> ayaa cusbooneysiiyay Joomla laga bilaabo {oldversion} illaa {version}"
; Automatic updates
PLG_ACTIONLOG_JOOMLA_SYSTEM_UPDATE="Habaynta si toos ah ayaa cusboonaysiisay Joomla nooca {oldversion} ilaa {version}"
; Config
PLG_ACTIONLOG_JOOMLA_APPLICATION_CONFIG_UPDATED="Isticmaalaha <a href='{accountlink}'>{username}</a> ayaa bedelay dejinta habaynta arjiga"
PLG_ACTIONLOG_JOOMLA_COMPONENT_CONFIG_UPDATED="Isticmaalaha <a href='{accountlink}'>{username}</a> ayaa bedelay dejinta qaybta {extension_name}"
; Extensions
PLG_ACTIONLOG_JOOMLA_EXTENSION_INSTALLED="Isticmaalaha <a href='{accountlink}'>{username}</a> ayaa rakibay {type} {extension_name}"
PLG_ACTIONLOG_JOOMLA_EXTENSION_UNINSTALLED="Isticmaalaha <a href='{accountlink}'>{username}</a> ayaa ka saaray {type} {extension_name}"
PLG_ACTIONLOG_JOOMLA_EXTENSION_UPDATED="Isticmaalaha <a href='{accountlink}'>{username}</a> ayaa cusbooneysiiyay {type} {extension_name}"
PLG_ACTIONLOG_JOOMLA_PLUGIN_INSTALLED="Isticmaalaha <a href='{accountlink}'>{username}</a> ayaa rakibay plugin <a href='index.php?option=com_plugins&task=plugin.edit&extension_id={id}'>{extension_name}</a>"
; Guided Tours
PLG_ACTIONLOG_JOOMLA_GUIDEDTOURS_TOURCOMPLETED="Isticmaale <a href='{accountlink}'>{username}</a> ayaa dhammaystiray booqashada '{title}'"
PLG_ACTIONLOG_JOOMLA_GUIDEDTOURS_TOURDELAYED="Isticmaale <a href='{accountlink}'>{username}</a> ayaa dib u dhigay booqashada '{title}'"
PLG_ACTIONLOG_JOOMLA_GUIDEDTOURS_TOURSKIPPED="Isticmaale <a href='{accountlink}'>{username}</a> ayaa ka booday booqashada '{title}'"

