; Joomla! Project
; (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_SCHEDULERUNNER="Nidaamka - Joojinta Jadwalka"
PLG_SYSTEM_SCHEDULERUNNER_XML_DESCRIPTION="Plugin-kan ayaa mas'uul ka ah jadwalkayga caajiska, webcron iyo hawlaha riix si ay u socdaan ee com_scheduler. Marka laga soo tago taas, sidoo kale waxa ay hirgalisaa kobcinta/jihaynta foomka ee qoryaha com_scheduler."

