; Joomla! Project
; (C) 2006 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_USER_JOOMLA="Isticmaale - Joomla!"
PLG_USER_JOOMLA_FIELD_AUTOREGISTER_LABEL="Si toos ah u abuur Isticmaale"
PLG_USER_JOOMLA_FIELD_FORCELOGOUT_LABEL="Ku qas ka bixista dhamaan Kalfadhiyada?"
PLG_USER_JOOMLA_FIELD_MAILTOUSER_LABEL="Ogeysiis E-mayl ah oo loogu talagalay Isticmaale"
PLG_USER_JOOMLA_MAIL_MAIL_DESC="Waxay u dirtaa isticmaalaha cusub marka lagu abuuro dacallada dambe."
PLG_USER_JOOMLA_MAIL_MAIL_TITLE="Isticmaaleyaasha: Isticmaale Cusub"
PLG_USER_JOOMLA_NEW_USER_EMAIL_BODY="Salaan {NAME},\n\n\nWaxaa lagugu daray isticmaale ahaan {SITENAME} ee maamulaha.\n\nE-maylkani wuxuu leeyahay magacaaga isticmaalaha iyo sirta si aad uga gasho {URL}\n\nMagaca Isticmaalaha: {USERNAME}\nPassword: {PASSWORD}\n\n\nFadlan ha ka jawaabin fariintan maadaama ay si toos ah u dhalatay oo ay tahay oo keliya ujeeddo macluumaad."
PLG_USER_JOOMLA_NEW_USER_EMAIL_SUBJECT="Faahfaahinta Isticmaale Cusub"
PLG_USER_JOOMLA_XML_DESCRIPTION="<p>Waxay gacanta ku haydaa iswaafajin Isticmaalaha Joomla sida caadiga ah.</p><p><strong>Digniin! Waa inaad dhaqaajisaa ugu yaraan mid ka mid ah nidaamyada xakameynta kalfadhiga isticmaalaha ama waxaad waayi doontaa dhammaan gelitaanka goobtaada.</strong></p>"

