; Joomla! Project
; (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FIELDS_EDITOR="Goobo - Tafatire"
PLG_FIELDS_EDITOR_LABEL="Tafatire (%s)"
PLG_FIELDS_EDITOR_PARAMS_BUTTONS_HIDE_LABEL="Qari Badhamada"
PLG_FIELDS_EDITOR_PARAMS_FILTER_LABEL="Shaandhee"
PLG_FIELDS_EDITOR_PARAMS_HEIGHT_LABEL="Dherer"
PLG_FIELDS_EDITOR_PARAMS_SHOW_BUTTONS_LABEL="Badhamada"
PLG_FIELDS_EDITOR_PARAMS_WIDTH_LABEL="Ballac"
PLG_FIELDS_EDITOR_XML_DESCRIPTION="Fidintani waxay kuu ogolaanaysaa inaad sameyso goobo cusub oo nooca 'tafatiro' ah meel kasta oo kordhin loogu talagalay halkaas oo goobo la beddeli karo la taageero."

