; Joomla! Project
; (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_MULTIFACTORAUTH_EMAIL="Aqoonsiga badan - Koodhka Aqoonsiga ee Iimaylka"
PLG_MULTIFACTORAUTH_EMAIL_XML_DESCRIPTION="Adeegso koodhyada amniga lix lambar ah oo xaddidan wakhtiga oo laguugu soo diro iimayl."

