; Joomla! Project
; (C) 2020 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_WORKFLOW_PUBLISHING="Workflow - Daabacaadda"
PLG_WORKFLOW_PUBLISHING_CHANGE_STATE_NOT_ALLOWED="Looma ogola in aad beddesho xaaladda daabacaadda ee shaygan. Fadlan isticmaal kala guurka workflow."
PLG_WORKFLOW_PUBLISHING_PUBLISHED="Xaalad: %s"
PLG_WORKFLOW_PUBLISHING_TRANSITION_ACTIONS_PUBLISHING_DESC="Cadee xaaladda lagu dejin doono shayga, marka la fulinayo hayaanka."
PLG_WORKFLOW_PUBLISHING_TRANSITION_ACTIONS_PUBLISHING_DO_NO_CHANGE="- Ha bedelin -"
PLG_WORKFLOW_PUBLISHING_TRANSITION_ACTIONS_PUBLISHING_LABEL="Xaaladda Daabacaadda"
PLG_WORKFLOW_PUBLISHING_XML_DESCRIPTION="Ku dar ficilada daabacaadda kala guurada workflow ee walxahaaga."

