; Joomla! Project
; (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_TASK_CHECK_FILES="Hawl - Hubi Faylasha"
PLG_TASK_CHECK_FILES_LABEL_DIMENSION_LIMIT="Xadka (px)"
PLG_TASK_CHECK_FILES_LABEL_MAXIMAGES="Sawirada Ugu Badan"
PLG_TASK_CHECK_FILES_LABEL_MAXIMAGES_DESC="Tirada ugu badan ee sawirada lagu farsameyn karo hal socod. Dejinta tiradan aad u saraysa waxay sababi kartaa in hawshu waqtiga ka dhamaato."
PLG_TASK_CHECK_FILES_LABEL_DIRECTORY="Galinta"
PLG_TASK_CHECK_FILES_LABEL_IMAGE_DIMENSION="Cabbirka"
PLG_TASK_CHECK_FILES_LOG_IMAGE_PATH_NA="Jidka sawirka ma jiro!"
PLG_TASK_CHECK_FILES_LOG_IMAGE_SAVE_FAIL="Ku guul daraystay in la keydiyo faylka sawirka"
PLG_TASK_CHECK_FILES_LOG_RESIZE_FAIL="Ku guul daraystay in la yareeyo sawirka sabab la xiriirta khalad ku jira logic plugin..."
PLG_TASK_CHECK_FILES_LOG_RESIZING_IMAGE="Waxaa la helay sawir cabbirkiisu yahay %1$sx%2$s px; waxaa la yareynayaa ilaa %3$sx%4$s px. Faylka: %5$s"
PLG_TASK_CHECK_FILES_TASK_IMAGE_SIZE_DESC="Hubi sawirada, yaree haddii ay ka weyn yihiin inta la ogolyahay. Feejignow: Faylkii asalka ahaa waa la qori doonaa!"
PLG_TASK_CHECK_FILES_TASK_IMAGE_SIZE_TITLE="Hubinta Cabbirka Sawirka"
PLG_TASK_CHECK_FILES_XML_DESCRIPTION="Waxay bixisaa hawlo joogto ah oo loogu talagalay hubinta faylasha waaweyn, iyo ficillada la xiriira haddii ay suurogal tahay."

