; Joomla! Project
; (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_SCHEDULERUNNER="Nidaamka - Wakhtiga Joojinta"
PLG_SYSTEM_SCHEDULERUNNER_XML_DESCRIPTION="Qalabkan waa masuulka jadwalka xiimaynta, webcron iyo riix si loogu shaqeeyo hawlaha com_scheduler. Ka sokow, tan sidoo kale waxay hirgelisaa qaababka kor u qaada/dabooli-shaqooyinka qaabaynta qaybtan com_scheduler."

