; Joomla! Project
; (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_MULTIFACTORAUTH_TOTP="Xaqiijinta Farta Badan - Koodhka Xaqiijinta"
PLG_MULTIFACTORAUTH_TOTP_XML_DESCRIPTION="Xaqiijinta Farta Badan ee isticmaalayaasha boggaaga oo adeegsanaya koodhadhka xaqiijinta lix lambar ah oo ay soo saarto app xaqiijinta (Google Authenticator, Authy, LastPass Authenticator, iwm), maareeyaha erayga sirta ah (1Password, BitWarden, Keeper, KeePassXC, Strongbox, iwm) ama, mararka qaarkood, biraawsarka."

