; Joomla! Project
; (C) 2011 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_LANGUAGECODE="Nidaamka - Koodhka Luqadda"
PLG_SYSTEM_LANGUAGECODE_FIELD_DESC="Wax ka beddel koodhka luqadda loo isticmaalo luqadda <em>%s</em>."
PLG_SYSTEM_LANGUAGECODE_FIELDSET_DESC="Wax ka beddel koodhka luqadda ee dokumentiga HTML ee la abuuray. Tusaale adeegsi: Waxaad rakibtay xirmada luqadda fr-FR waxaadna rabtaa in Mashiinnada Raadiyaha ay bogga u aqoonsadaan inuu ku wajahan yahay dad ku hadla French-Kanadiyaan ah. Ku dar sumadda 'fr-CA' beerta u dhigma ee 'fr-FR' si aad tan u xalliso."
PLG_SYSTEM_LANGUAGECODE_FIELDSET_LABEL="Koodhyada Luqadda"
PLG_SYSTEM_LANGUAGECODE_XML_DESCRIPTION="Bixiye awoodda lagu beddelo koodhka luqadda ee dokumentiga HTML ee la abuuray si loo hagaajiyo SEO.<br>Goobaha waxay soo muuqan doonaan marka plugin-ka la dajiyo oo la badbaadiyo."

