; Joomla! Project
; (C) 2010 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SEF_XML_DESCRIPTION="Waxay ku darsataa taageero SEF xiriirrada ku jira dukumintiga. Waxay toos u shaqeysaa HTML-ka mana u baahna calaamad gaar ah." 
PLG_SYSTEM_SEF="Nidaamka - SEF"

