; Joomla! Project
; (C) 2016 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

ATUM="Template-ka Maamulaha Atum"  
TPL_ATUM_BACK_TO_CONTROL_PANEL="Ku Noqo Dashboard-ka"  
TPL_ATUM_BACKEND_LOGIN="Joomla Maamulaha Soo Gelida"  
TPL_ATUM_COLORSCHEME_LABEL="Habka Madaw"  
TPL_ATUM_COLORSCHEME_OPTION_DARK="Adeegso nidaamka midabka madaw"  
TPL_ATUM_COLORSCHEME_OPTION_FOLLOW_OS="Raac dejimaha OS-ka"  
TPL_ATUM_COLORSCHEME_OPTION_LIGHT="Adeegso nidaamka midabka iftiin ah"  
TPL_ATUM_COLORS_HUE="Dooro qiimaha hue-ga midabka madaw"  
TPL_ATUM_COLORS_SETTINGS_BG_LIGHT_LABEL="Asalka Iftiin"  
TPL_ATUM_COLORS_SETTINGS_LABEL="Dejinta Midabka"  
TPL_ATUM_COLORS_SETTINGS_LINK_COLOR_DARK_LABEL="Midabka Link-ga (Habka Madaw)"  
TPL_ATUM_COLORS_SETTINGS_LINK_COLOR_LABEL="Midabka Link-ga"  
TPL_ATUM_COLORS_SETTINGS_MONOCHROME_LABEL="Deji Midabka Monochrome"  
TPL_ATUM_COLORS_SETTINGS_SPECIAL_COLOR_LABEL="Midab Gaar ah"  
TPL_ATUM_COLORS_SETTINGS_TEXT_DARK_LABEL="Qoraal Madaw"  
TPL_ATUM_COLORS_SETTINGS_TEXT_LIGHT_LABEL="Qoraal Iftiin"  
TPL_ATUM_IMAGE_LABEL="Sawir"  
TPL_ATUM_IMAGE_SETTINGS_LABEL="Dejinta Sawirka"  
TPL_ATUM_LOGIN_LOGO_LABEL="Logo-ga Soo Gelida"  
TPL_ATUM_LOGIN_SIDEBAR_VIEW_WEBSITE="Daawo website-ka"  
TPL_ATUM_LOGO_ALT_EMPTY_DESC="Sawir Qurxoon - faahfaahin looma baahna"  
TPL_ATUM_LOGO_ALT_EMPTY_LABEL="Faahfaahin La’aan"  
TPL_ATUM_LOGO_ALT_LABEL="Faahfaahinta Sawirka (Qoraalka Alt)"  
TPL_ATUM_MORE_ELEMENTS="Qaybo Kale"  
TPL_ATUM_SITE_LOGO_LABEL="Astaanta Weyn"  
TPL_ATUM_SITE_LOGO_SMALL_LABEL="Calaamadda Yaryar"
TPL_ATUM_TOOLBAR="Toolbar"
TPL_ATUM_XML_DESCRIPTION="Isagoo sii wata mawduuca ilaaha/ilmaha ilaha Masaarida (Khepri laga bilaabo 1.5, Hathor laga bilaabo 1.6, Isis laga bilaabo 3.0), Atum waa magaca qaabka maamulka ee Joomla 4 iyo Joomla 5."

