; Joomla! Project
; (C) 2016 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

ATUM="Atum Template-ka Maamulka"
TPL_ATUM_POSITION_BOTTOM="Hoose"
TPL_ATUM_POSITION_CPANEL="Cpanel"
TPL_ATUM_POSITION_CUSTOMTOP="Sare Kartoon"
TPL_ATUM_POSITION_DEBUG="Tijaabo"
TPL_ATUM_POSITION_ICON="Astaamo Dhaqso"
TPL_ATUM_POSITION_LOGIN="Gal"
TPL_ATUM_POSITION_MENU="Menu"
TPL_ATUM_POSITION_SIDEBAR="Bar-Soca"
TPL_ATUM_POSITION_STATUS="Xaalad"
TPL_ATUM_POSITION_TITLE="Cinwaan"
TPL_ATUM_POSITION_TOOLBAR="Qalabka"
TPL_ATUM_POSITION_TOP="Sare"
TPL_ATUM_XML_DESCRIPTION="Iyadoo laga codsanayo mowduuca ilaahyada/ilaahyadii masar ee hore (Khepri laga bilaabo 1.5, Hathor laga bilaabo 1.6, Isis laga bilaabo 3.0), Atum waa magaca Template-ka Maamulaha ee Joomla 4 iyo Joomla 5."

