; Joomla! Project
; (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

WEBSERVICE_COM_MEDIA="Adeegga warbaahinta ee webka"
WEBSERVICE_COM_MEDIA_MISSING_REQUIRED_PARAMETERS="Wax ka maqan ayaad u baahan tahay parameter(s): %s"
WEBSERVICE_COM_MEDIA_FILE_NOT_FOUND="Fayl lama helin: %s"
WEBSERVICE_COM_MEDIA_FILE_EXISTS="Faylka wuu jiraa oo dib looguma dalban cusboonaysiin: %s"
WEBSERVICE_COM_MEDIA_BAD_FILE_TYPE="Jid aan ansax ahayn ama nooca faylka oo aan la ogoleyn: %s"
WEBSERVICE_COM_MEDIA_UNSUPPORTED_PARAMETER_COMBINATION="Isku darka weydiinta wax lala yaabo ama aan taageersaneyn"

